### ISSUE TITLE
Show Image DA: Follow FTN.08

### ISSUE THREAD

**Issue by inexorabletash** [a2stuff/a2d#107]
http://www.1000bit.it/support/manuali/apple/technotes/ftyp/ftn.08.0000.html

* [x] Aux type should indicate whether or not the image is compressed
* [ ] Bits in the file should indicate display mode (resolution, B&W or color)

... not that there are likely to be files around that use these.

Implementing UnpackBytes support would be interesting. Unfortunate that it's not a decode-in-place friendly format.

**Comment by inexorabletash** [comment]
Good description of the PackBytes format at: https://www.fadden.com/apple2/hdc/lesson02.html

**Comment by inexorabletash** [comment]
See also: http://wsxyz.net/tohgr.html

**Comment by inexorabletash** [comment]
668864aed174b44f7c95e5e33e8ca33724a2de3f adds support for packed files. Bailing on the bits until someone complains.

**Comment by c0mmander8** [comment]
Please reopen this issue and, as mentioned above, support bits in the file that should indicate display mode (resolution, B&W or color).

**Comment by inexorabletash** [comment]
I suppose that should be trivial. Do you have any sample files?

**Comment by c0mmander8** [comment]
Sorry, I do not have any sample files.

**Comment by inexorabletash** [comment]
Ah, here's the reason I didn't pursue the mode bytes:

> can determine the mode of the file by examining byte +120 (+$78). The value of this byte, which ranges from zero to seven, is interpreted as follows:
```
               Mode                         Page 1    Page 2
               280 x 192 Black & White        0         4
               280 x 192 Limited Color        1         5
               560 x 192 Black & White        2         6
               140 x 192 Full Color           3         7
```

Not that most people used FOT as a file type, but having one of the screen hole bytes be zero will be extremely common, which would force the display to B&W per the above table. 

Unless we find a corpus of files and/or tools that generate files according to the above, I'd prefer to leave things alone.

**Comment by inexorabletash** [comment]
Well... there isn't really a corpus of FOT files of any sort. So waffling back the other way.
