### ISSUE TITLE
Show menu separators with lines

### ISSUE THREAD

**Issue by inexorabletash** [a2stuff/a2d#135]
Consider matching early macOS (System 7-) and showing menu filler/separator items as an edge-to-edge horizontal line rather than just a blank space. 

Code would be in `draw_menu`

**Comment by inexorabletash** [comment]
Screenshot from GUIdebook:
![](https://guidebookgallery.org/pics/gui/system/managers/applicationmanager/macos11.png)

**Comment by inexorabletash** [comment]
Meh, not really worth it for the number of bytes it'd take. (Would need to use a pattern, too)

![image](https://user-images.githubusercontent.com/771547/53539607-182cc180-3ac7-11e9-9956-10a0c80f41df.png)

**Comment by c0mmander8** [comment]
Please, as referenced in issue #226, reopen this issue and adopt the menu line separators.

**Comment by inexorabletash** [comment]
Yeah, I'd still like this too.

**Comment by inexorabletash** [comment]
Wasn't so bad:

![image](https://user-images.githubusercontent.com/771547/100268262-95d66900-2f09-11eb-9232-25be70bf738b.png)

**Comment by I3arana** [comment]
Flash as mate!
Glad you doubled back and did this.
