### ISSUE TITLE
Case-correct AWP/ASP/ADB files

### ISSUE THREAD

**Issue by inexorabletash** [a2stuff/a2d#179]
AppleWorks files encode case using the file auxtype, eg see http://www.1000bit.it/support/manuali/apple/technotes/ftyp/ftn.1a.xxxx.html - we could use that scheme to decode the user-intended case rather than the heuristic. 

This is almost certainly not important enough to justify the code space impact, but filing the idea for posterity.

**Comment by c0mmander8** [comment]
What about AppleWorks spaces?

**Comment by c0mmander8** [comment]
What about AppleWorks spaces?

**Comment by inexorabletash** [comment]
ProDOS is case insensitive, but does not automatically translate spaces to periods. Showing periods as spaces could be done -- perhaps everywhere, not just for AW files -- but (1) that would take the UI further away from being a representation of the ProDOS file system and (2) every internal call site that deals with ProDOS calls would need to translate the names back and forth, which would be substantial increase in code size and complexity.
