### ISSUE TITLE
Rename should reset (or update?) case bits

### ISSUE THREAD

**Issue by inexorabletash** [a2stuff/a2d#187]
Repro:

1. In ProDOS 2.5 create a file named e.g. "AaBbCcDd"
2. Boot ProDOS 2.4
3. In DeskTop, rename it to "WWXXYYZZ"

Expect:

File shows as either "WWXXYYZZ" (maintaining case) or "Wwxxyyzz" (normal case adjustment)

Actual:

File shows as "WwXxYyZz", since the case bits are untouched by 2.4

This should be done for AppleWorks (AWP/ASP/ADB) files as well, which encode the case bits in the aux type instead (byte-swapped)

**Comment by inexorabletash** [comment]
Ugh, this will require mucking with directory entries - the version bits aren't available in GET/SET_INFO calls.

**Comment by inexorabletash** [comment]
Resetting case bits for AppleWorks files is easier, as it can be done via SET_FILE_INFO

**Comment by c0mmander8** [comment]
Maybe issue #352 should be reopened and this issue should be merged into issue #352 instead of closing issue #352? Issue #352 covers all the aspects of this issue, but issue #352 is more expansive and comprehensive in scope.

**Comment by inexorabletash** [comment]
On further reflection, merging into #352
