### ISSUE TITLE
"Cancel" in Delete an Entry... should be "Close"

### ISSUE THREAD

**Issue by inexorabletash** [a2stuff/a2d#190]
Repro:

1. Start DeskTop
1. Selector > Delete an Entry ...
1. Select an entry
1. Click OK

Expected: Window closes, or there's an option to close.

Actual: Options remain OK / Cancel. You can delete another option using OK, but to close you have to Cancel, but this doesn't cancel the previous delete. 

This would make sense if the dialog was "Delete Entries ..." but the current naming makes it weird.

**Comment by c0mmander8** [comment]
Please reopen this issue, revert commit 44a88ba and implement the alternative fix mentioned there instead because I think it is very convenient to be able to delete multiple entries from the Selector at the same time.
