### ISSUE TITLE
[feature request] Expand text Preview to Text Editor

### ISSUE THREAD

**Issue by ZoriaRPG** [a2stuff/a2d#201]
It would be nice to have a fully-fledged text editor for A2D; perhaps something that can output .bas files.

**Comment by inexorabletash** [comment]
Duplicate of https://github.com/a2stuff/a2d/issues/12

There's not really enough room for a text editor DA - scrapbook maybe, but not files.

But a standalone MGTK-based app is doable.

**Comment by ZoriaRPG** [comment]
Standalone programme is what I had in mind, not a DA.

**Comment by inexorabletash** [comment]
Yep, so nothing stopping that, it's just a different project using MGTK.
