### ISSUE TITLE
[feature request] [development] A2D SDK

### ISSUE THREAD

**Issue by ZoriaRPG** [a2stuff/a2d#202]
It would be nice to have a toolset to write applications to run inside of A2D. GEOS had this, and as far as I am aware, nothing similar ever existed for A2D.

For that matter, is there a way to execute a programme return from ProDOS BASIC 1.7, back to A2D? If not, it's be lovely to see a BASIC.SYSTEM 1.8 that has an instruction to return to it if BASIC.SYSTEM was loaded from A2D.

**Comment by inexorabletash** [comment]
The MouseGraphics ToolKit which is the basis for full applications is documented here: 
https://github.com/a2stuff/a2d/blob/master/mgtk/MGTK.md
Somewhat like the original Mac (System 1 and so on), applications are really separate ProDOS programs that take over all of RAM but use the ToolKit to follow the same UI conventions. Those are totally doable using MGTK.

Desk Accessories (a subset that run within DeskTop and also use MGTK, under significant memory constraints) are documented here: https://github.com/a2stuff/a2d/blob/master/desk.acc/API.md

To return from BASIC launched from DeskTop, just type `BYE`; DeskTop replaces the current ProDOS selector when it is running so exiting a shell or app returns you to DeskTop. The original selector is restored when you File > Quit from DeskTop back to ProDOS.

**Comment by inexorabletash** [comment]
FWIW, you can think of Selector, DeskTop, and Disk Copy as three separate MGTK-based applications, although they are linked together (e.g. DiskCopy relies on DeskTop having loaded MGTK and probed the drives already; Selector and DeskTop are both launched by Desktop.system  rather than as standalone system files)

**Comment by inexorabletash** [comment]
(and if you're interested in writing MGTK-based apps or DeskTop DAs, let me know!)
