### ISSUE TITLE
New DA: Find File

### ISSUE THREAD

**Issue by inexorabletash** [a2stuff/a2d#21]
See https://mirrors.apple2.org.za/ground.icaen.uiowa.edu/MiscInfo/Misc/mousedesk.info

> 5.  Add "FIND FILE" ability  Sorely missed, this ability is best substituted by its equivalent in AppleWorks' T.O. DirecTree.  There is a stand alone program from April 1989's Nibble Magazine called "Where.Is"  that does search out and find files, but on hard drives, it's slower than molasses.

**Comment by inexorabletash** [comment]
We can prototype this as a DA. It's really three parts:

* [ ] UI for entering the search term.
* [ ] Code to traverse the directories and find matches.
* [ ] UI to display the results. 

We may want to require that a window is open and scope searches relative to that path.

**Comment by inexorabletash** [comment]
Any volunteers to take on the actual search code?

**Comment by inexorabletash** [comment]
Started in `find` branch

**Comment by mgcaret** [comment]
I’m not volunteering, but recursive catalog code in ProDOS TN#17 is probably worth a starting look. 

The biggest issue is going to be RAM... there will definitely be some tradeoff between speed and space for the search, and space to store any matches. 


--MG

**Comment by inexorabletash** [comment]
Thanks @mgcaret - added temporarily:

https://github.com/inexorabletash/a2d/blob/find/desk.acc/tn17.s

Also, the `find` branch has a WIP file that demonstrates how to create an input field and buttons. It's manual, but straightforward. The UI needs a nested winfo to implement the scrolling region, but you can type (with arrow keys, delete, blinking IP) and click the buttons (including dragging in/out):

![image](https://user-images.githubusercontent.com/771547/39906768-9b0142da-5499-11e8-9f82-0630d99eb43a.png)

My plan is to adapt the TN17 code, and move it to the start of the DA; it'll run through about $E00, and be followed by the GUI code. $1C00-$1FFF will be the I/O buffer. $1A00-$1BFF can be the block buffer. The search code will run in Main and can overwrite the GUI code - so $E00-$1A00 can be a buffer for result paths - about 45 of them. After the search is done, control will pass back to the GUI code and it can AUXMOVE the results in one at a time as the UI is drawn.

**Comment by inexorabletash** [comment]
Scrollable results

![image](https://user-images.githubusercontent.com/771547/40100908-8a43d336-589a-11e8-98ab-665d5f37e5f3.png)

Results are faked at the moment.

**Comment by inexorabletash** [comment]
A few more TODO items:

* [ ] make an Escape keypress terminate an in-progress search
* [ ] display results progressively, rather than waiting for the traversal to be complete

**Comment by inexorabletash** [comment]
Pattern matching with wildcards: http://6502.org/source/strings/patmatch.htm
