### ISSUE TITLE
FDHD ProDOS Volumes, Wrong Size

### ISSUE THREAD

**Issue by ZoriaRPG** [a2stuff/a2d#215]
A2D sees 1440K (FDHD 3.5 Drive on 3.5 Drive controller) volumes as if they are 800K diskettes.
The space free reported is incorrect, and I have not determined if file access beyond 800K is invalid. 

This seems to affect volumes formatted by ProDOS 8, such as Copy IIPlus 9.1, but not when they were formatted with GS/OS.

I will need to check to see if I somehow formatted the disks improperly, but I would expect the drive to refuse to format a 2MB diskette as a 1MB diskette unless the HD window is covered.

**Comment by inexorabletash** [comment]
There is no logic specific to that drive type; what do other ProDOS 8 tools report as the disk size?

This sounds more like a bug in the ProDOS 8 tools used to format the disks.

**Comment by inexorabletash** [comment]
Also, what does CATALOG report from BASIC.SYSTEM for free/used/total blocks?

**Comment by inexorabletash** [comment]
http://wiki.apple2.org/index.php?title=3.5_Drive_Compatibility indicates the drive behaves like an 800k drive in certain circumstances. 

Anyway, if you can verify whether DeskTop sees the disks the same way as ProDOS 8 (eg via BASIC.SYSTEM) that would help. I don't have one of these devices to test with.

**Comment by inexorabletash** [comment]
This old thread from 1998 is interesting. Does seem like some ProDOS 8 apps may not be correctly querying the disk size when formatting. 

https://groups.google.com/forum/m/#!topic/comp.sys.apple2/2RLal6eZvgI

**Comment by inexorabletash** [comment]
No feedback, closing.
