### ISSUE TITLE
Add a "Duplicate File" command

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#228]
Add a "Duplicate" command with an Apple-D keypress shortcut to the File menu.

**Comment by c0mmander8** [comment]
Also, dragging item(s) within the same window while holding Apple key down should make a duplicate of it or them.

**Comment by c0mmander8** [comment]
Also, dragging item(s) within the same window while holding down the Apple key should make a duplicate of it or them.

**Comment by c0mmander8** [comment]
Also, dragging item(s) within the same window while holding the Apple key down should make a duplicate of it or them.

**Comment by inexorabletash** [comment]
*Good First Bug* notes:

Start off by repurposing the logic used for Rename and New Folder, adding another variant to prompt for the name. Then invoke the copy logic which is already set up to be called with a source and destination path.

**Comment by ph0enix-c0der** [comment]
"Also, dragging item(s) within the same window while holding the Apple key down should make a duplicate of it or them." is now issue #837.
