### ISSUE TITLE
Restore the window selection mode that was removed in issue #154, commit 3926014, with a different keypress shortcut to activate it

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#229]
Please restore the window selection mode that was removed in issue #154, commit 3926014, with a different keypress shortcut to activate it, now that many of the unusual keypress shortcuts have been removed from the menus and there are plenty to choose from.

**Comment by inexorabletash** [comment]
Why is that better than Apple-Tab ?

**Comment by c0mmander8** [comment]
It is just simply an extra option in addition to Apple-Tab, not a replacement for it.

**Comment by inexorabletash** [comment]
I don't consider it worth the code space and maintenance cost. The discoverability of the non-menu shortcuts is low.
