### ISSUE TITLE
BIN should be $06 instead of $08 in the release notes located at https://www.a2desktop.com/release-notes and at https://github.com/a2stuff/a2d/blob/main/RELEASE-NOTES.md

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#235]
BIN should be $06 instead of $08 in the release notes located at https://www.a2desktop.com/release-notes and at https://github.com/a2stuff/a2d/blob/main/RELEASE-NOTES.md. For example:

Graphics files must be type FOT ($08), or BIN ($06) with specific aux type:

    BIN ($08) files:
        Aux type $2000 or $4000 and 17 blocks are hi-res images.
        Aux type $2000 or $4000 and 33 blocks are double hi-res images.
        Aux type $5800 and 3 blocks are Minipix (Print Shop) images.
    FOT ($08) files:
        Aux type $4000 or $4001 are packed hi-res/double-hires images. (#107)
        17 block files are hi-res images.
        33 block files are double-hires images.

**Comment by inexorabletash** [comment]
Good catch. I'm going to recruit you as a regression tester. :)
