### ISSUE TITLE
There is still a mismatch between the release notes

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#239]
As referenced in issue #234, there is still a mismatch between the release notes at https://www.a2desktop.com/release-notes and the release notes at https://github.com/a2stuff/a2d/blob/main/RELEASE-NOTES.md. The release notes at https://www.a2desktop.com/release-notes say "Font files must be type FNT ($07) and must be MGTK font resources. (This file type is officially reserved for Apple /// SOS font files, but unlikely to be confused.)" while the release notes at https://github.com/a2stuff/a2d/blob/main/RELEASE-NOTES.md just only say "Font files must be type FNT ($07) and must be MGTK font resources." by itself.

**Comment by inexorabletash** [comment]
This is intentional.

**Comment by c0mmander8** [comment]
Why?

**Comment by inexorabletash** [comment]
The release notes in the repo are intended to be a concise summary. The site expands in more detail, and aren't really intended for broad consumption anyway - that's what the documentation is for.

I appreciate your attention to detail here. There may be higher impact ways to assist the project than release note nitpicks, though!
