### ISSUE TITLE
Update documentation to provide when either Apple key can be used for keyboard control instead of Open-Apple alone

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#241]
Update documentation located at https://www.a2desktop.com/docs#h.p_fthAmDxtEOQ9 to provide when either Apple key can be used for keyboard control instead of Open-Apple alone.

**Comment by inexorabletash** [comment]
Thanks, done.

Not every place in the docs gives the ▲ variant, e.g. for shortcuts, but that's noted at the end. There's a trade off where being more precise decreases readability.
