### ISSUE TITLE
If not already done, make sure that all 65C02 code is removed from the complete package of Apple II DeskTop, Disk Copy, Selector and all desk accessories, both new and original, for compatiblity with unenhanced Apple IIe and and unenhanced Apple IIe clones

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#243]
If not already done, make sure that all 65C02 code is removed from the complete package of Apple II DeskTop, Disk Copy, Selector and all desk accessories, both new and original, for compatiblity with unenhanced Apple IIe and and unenhanced Apple IIe clones.

**Comment by inexorabletash** [comment]
That's already done, you can look for `.cpu` directives in the code
