### ISSUE TITLE
In the release notes located at https://www.a2desktop.com/release-notes, "Holding Apple while double-clicking or using File>Open closes parent folder. (#9)" should be "Holding Apple while double-clicking or using File > Open closes parent folder. (#9)"

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#244]
As referenced in issue #242, commit 2e05dd6, in the release notes located at https://www.a2desktop.com/release-notes, "Holding Apple while double-clicking or using File>Open closes parent folder. (#9)" should be "Holding Apple while double-clicking or using File > Open closes parent folder. (#9)". As referenced in issue #242, commit 2e05dd6, the release notes located at https://github.com/a2stuff/a2d/blob/main/RELEASE-NOTES.md were updated to state exactly that but not the release notes located at https://www.a2desktop.com/release-notes.

**Comment by inexorabletash** [comment]
Once again, I appreciate your attention to detail, this level of nitpicking is not an effective use of time.

**Comment by inexorabletash** [comment]
fixed
