### ISSUE TITLE
In the release notes located at https://www.a2desktop.com/release-notes, "Apple-` or Apple-Tab cycles through open windows; Apple-~ cycles in reverse. (#143, #230)" is missing the hyperlink for issue #230

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#245]
In the release notes located at https://www.a2desktop.com/release-notes, "Apple-` or Apple-Tab cycles through open windows; Apple-~ cycles in reverse. (#143, #230)" is missing the hyperlink for issue #230.

**Comment by inexorabletash** [comment]
Fixed

**Comment by c0mmander8** [comment]
I see that this issue was fixed.
