### ISSUE TITLE
Please revert this. The backticks render text in `code style`, preferred for filenames.

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#247]
Please revert this. The backticks render text in `code style`, preferred for filenames.

_Originally posted by @inexorabletash in https://github.com/a2stuff/a2d/pull/246#discussion_r460413781_

**Comment by c0mmander8** [comment]
The release notes located at https://www.a2desktop.com/release-notes have heavy formatting throughout, including other instances of filenames, while the release notes located at https://github.com/a2stuff/a2d/blob/main/RELEASE-NOTES.md are otherwise plain text.

**Comment by inexorabletash** [comment]
This is not an appropriate use of the issue tracker. Comments can be made on pull requests.

The issue tracker is not a discussion forum.
