### ISSUE TITLE
Please revert, leave the document structure alone.

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#248]
Please revert, leave the document structure alone.

_Originally posted by @inexorabletash in https://github.com/a2stuff/a2d/pull/246#discussion_r460413808_

**Comment by c0mmander8** [comment]
I increased the size of 1.2 to match the larger size 1.1 is already at.

**Comment by inexorabletash** [comment]
This is not an appropriate use of the issue tracker. Comments can be made on pull requests.
