### ISSUE TITLE
Please revert, no need to capitalize.

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#249]
Please revert, no need to capitalize.

_Originally posted by @inexorabletash in https://github.com/a2stuff/a2d/pull/246#discussion_r460414112_

**Comment by c0mmander8** [comment]
Other mentions of "Slot" in the release notes are already capitalized.

**Comment by inexorabletash** [comment]
This is not an appropriate use of the issue tracker. Comments can be made on pull requests.
