### ISSUE TITLE
Put a second, bold, outer circle around the default choice in a dialog box

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#252]
Put a second, bold, outer circle around the default choice in a dialog box, just like the later Mac and the IIGS.

**Comment by inexorabletash** [comment]
I think that would degrade the visual appearance. It's particularly bad on the IIgs given the lack of vertical resolution.

Showing the shortcuts (i.e. ↵) on the key serves that purpose. If there are buttons where that isn't shown, we should fix.

**Comment by c0mmander8** [comment]
Please reopen this issue. I still think that this issue is an important issue to be implemented because this would greatly increase the usability of Apple II DeskTop.
