### ISSUE TITLE
The IIGS cursor does not move while running Apple II DeskTop inside Bernie ][ The Rescue 3.0 Preview inside SheepShaver

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#253]
The emulated IIGS cursor does not move while running Apple II DeskTop on an emulated IIGS inside Bernie ][ The Rescue 3.0 Preview (the latest version of the program despite the name) running on an emulated Mac running Mac OS 9.0.4 inside SheepShaver while any version of the IIGS Finder works perfectly.

**Comment by inexorabletash** [comment]
It works fine in GSPlus (KEGS based), Sweet 16, and a real GS, so sounds like an emulator bug. 

How do other 8-bit mouse apps behave?

**Comment by inexorabletash** [comment]
No feedback, closing.
