### ISSUE TITLE
Make Apple-Arrow keypresses do something

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#254]
Make Apple-Arrow Keypresses do something. Some ideas:

Apple-Left Arrow: Cycle windows backwards. Same as Shift-Apple-\`.
Apple-Right Arrow: Cycle windows forwards. Same as Apple-\` or Apple-Tab.
Apple-Down Arrow: Open selected icon(s). Same as Apple-O.
Apple-Up Arrow: Open enclosing folder or, if none, enclosing volume of the current window. If there is no enclosing folder or enclosing volume, select the desktop instead. Also, select the folder icon or volume icon of the directory from which the keypresses were invoked.

**Comment by inexorabletash** [comment]
<kbd>🍏</kbd>+<kbd>↑</kbd> and <kbd>🍏</kbd>+<kbd>↓</kbd> make sense - I use those in macOS a lot.

Not sure about <kbd>🍏</kbd>+<kbd>←</kbd> and <kbd>🍏</kbd>+<kbd>→</kbd> since there's already a key and no precedent for those operations. Might be better to reserve those for future use.

**Comment by inexorabletash** [comment]
Added up/down. I want to reserve left/right for the future.

**Comment by c0mmander8** [comment]
What about selecting the folder icon or volume icon of the directory from which Apple-Up Arrow was invoked?

**Comment by c0mmander8** [comment]
As referenced in issue #314, what about selecting the folder icon or volume icon of the directory from which Apple-Up Arrow was invoked?

**Comment by c0mmander8** [comment]
As referenced in issue #314, what about selecting the folder icon or volume icon of the directory from which Apple-Up Arrow was invoked, just like the later Mac and the later IIGS?
