### ISSUE TITLE
Some Find Files improvements

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#255]
Here are some Find Files improvements:

* ~Launch Find Files by pressing Apple-F.~ DAs don't get shortcuts.
* ~Search only the selected window and its child folders.~ Already the case.
* [x]  If no windows are selected, search all volumes and all their child folders.
* [ ] Search for files, folders and volumes.
* [x] As referenced in issue #21, display results progressively rather than waiting for the traversal to be complete.
* ~Show the volume name in the path in the search results.~ Already the case.
* [ ] Add a horizontal scroll bar for long paths and long filenames, folder names and volume names.
* [x] When a result is double-clicked, open a window of the enclosing folder or, if none, the enclosing volume of the result being double-clicked. If there is no enclosing folder or enclosing volume, select the desktop instead. Also, select the file icon, folder icon or volume icon of the result being double-clicked.
* [x] Allow clicking between letters with the insertion point in order to edit the middle of a search term.
* [x] Implement keyboard navigation of the existing vertical scrollbar. I would recommend Down Arrow to scroll down a result, Up Arrow to scroll up a result, Apple-Down Arrow for Page Down and Apple-Up Arrow for Page Up.
* ~Increase maximum number of shown results from 54 to unlimited.~ Infeasible - 54 is the maximum number of paths that can fit in available memory.

**Comment by inexorabletash** [comment]
> Show the volume name in the path in the search results.

This is already present. If not, please file an issue with repro steps.

**Comment by inexorabletash** [comment]
I'm calling this complete. The two outstanding feature requests are not worth pursuing:

* The DA now uses a List Box control, which doesn't support horizontal scroll. Now that you can double-click a result to show the file, the name being truncated is less important.
* Volume names aren't searched. The DA is "Find Files" so it's right there in the name, and supporting this edge case would be a lot of code for little benefit.
