### ISSUE TITLE
New keyboard shortcuts

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#256]
As referenced in issue #254 and issue #255, here are some new keyboard shortcuts adapted from https://support.apple.com/en-us/HT201236 and some that I have adapted myself:

Space bar: Preview files using preview handlers. Same as proposed Apple-Y.
Apple-Space bar: Launch Find Files. Same as proposed Apple-F.
Control-Apple-Space bar: Launch Key Caps. Same as proposed Shift-Apple-Space bar.
Shift-Apple-Space bar: Launch Key Caps. Same as proposed Control-Apple-Space bar.
Shift-Apple-3: Launch Screen Dump. Same as proposed Apple-P.
Apple-F: Launch Find Files. Same as proposed Apple-Space bar.
Shift-Apple-N: Create new folder. Same as Apple-N.
Shift-Apple-O: Open selected icon(s) while closing the parent folder. Same as proposed Shift-Apple-Down Arrow.
Apple-P: Launch Screen Dump. Same as proposed proposed Shift-Apple-3.
Shift-Apple-W: Close all windows.
Apple-Y: Preview files using preview handlers. Same as proposed Space bar.
Apple-Left Arrow: Cycle windows backwards. Same as Shift-Apple-\`.
Apple-Right Arrow: Cycle windows forwards. Same as Apple-\` or Apple-Tab.
Apple-Down Arrow: Open selected icon(s). Same as Apple-O.
Shift-Apple-Down Arrow: Open selected icon(s) while closing the parent folder or parent volume. Same as proposed Shift-Apple-O.
Apple-Up Arrow: Open enclosing folder or, if none, enclosing volume of the current window. If there is no enclosing folder or enclosing volume, select the desktop instead. Also, select the folder icon or volume icon of the directory from which the keypress was invoked.
Shift-Apple-Up Arrow: Open enclosing folder or, if none, enclosing volume of the current window while closing the child folder or child volume. If there is no enclosing folder or enclosing volume, select the desktop instead. Also, select the folder icon or volume icon of the directory from which the keypress was invoked.
Apple-Arrow keypresses can be used with or without the Control key being pressed down at the same time.

**Comment by c0mmander8** [comment]
Here is another one:

Holding Apple key down while dragging item(s) to another volume: Move the dragged item(s) to the other volume instead of copying it or them.

**Comment by c0mmander8** [comment]
Here is another one:

Holding Apple key down while dragging item(s) to another volume: Move the dragged item(s) to the other volume instead of copying it or them.

**Comment by c0mmander8** [comment]
Here is another one:

Holding Apple key down while dragging item(s) to another volume: Move the dragged item(s) to the other volume instead of copying it or them.

**Comment by c0mmander8** [comment]
Here is another one:

Holding Apple key down while dragging item(s) to another volume: Move the dragged item(s) to the other volume instead of copying it or them.

**Comment by inexorabletash** [comment]
Please don't duplicate suggestions; much of this duplicates #254, and loses my comments.
You can use backslash \ before \` to prevent the formatting; I edited your comment to fix it.

Regarding the suggestions:

* You can't detect Shift separately from Caps Lock for alphabetic keys, so those shouldn't be used.
* You can't detect Control in 
* Duplicate shortcuts - unless there is strong precedent e.g. from existing OSes - just make for confusing documentation in the short term, and prevents the shortcuts from being used for other functionality in the future. 
* Shortcuts for desk accessories are not supported.

**Comment by c0mmander8** [comment]
You can't detect Control in what?

**Comment by inexorabletash** [comment]
> You can't detect Control in what?

Whoops, I was going to type that you can't detect the control key being down, but different codes are generated. I was going to check if <kbd>Control</kbd>+<kbd>Space</kbd> Generated a unique code... then forgot to finish what I was typing. 

BTW you can do fancy formatting here to improve readability with: `<kbd>Control</kbd>`

**Comment by inexorabletash** [comment]
Nope, <kbd>Control</kbd>+ <kbd>Space</kbd> and <kbd>Space</kbd> can't be distinguished - both generate code 32.

**Comment by c0mmander8** [comment]
Why are shortcuts for desk accessories not supported? Apple-F and its Command equivalent are used to launch Find File on the IIGS and the later Mac even though it is a desk accessory on both.

**Comment by c0mmander8** [comment]
Why are shortcuts for desk accessories not supported? Apple-F and its Command equivalent are used to launch Find File on the IIGS and the later Mac even though it is a desk accessory on both.

**Comment by inexorabletash** [comment]
> Why are shortcuts for desk accessories not supported? 

There's no dynamic registration for shortcuts, so they can't show in the menu which means they're undiscoverable. They could be hardcoded to always try to run the DA (and fail if not installed) but I don't think that's ideal.

**Comment by c0mmander8** [comment]
As referenced in issue #255, here is my revised list of keyboard shortcuts adapted from https://support.apple.com/en-us/HT201236:

Space bar: Preview files using preview handlers. Same as proposed Apple-Y.
Apple-Space bar: Launch Find Files. Same as proposed Apple-F.
Shift-Apple-3: Launch Screen Dump. Same as proposed Apple-P.
Apple-F: Launch Find Files. Same as proposed Apple-Space bar.
Apple-P: Launch Screen Dump. Same as proposed proposed Shift-Apple-3.
Apple-Y: Preview files using preview handlers. Same as proposed Space bar.
Holding Apple key down while dragging item(s) to another volume: Move the dragged item(s) to the other volume instead of copying the dragged item(s) to the other volume.

**Comment by inexorabletash** [comment]
* There are already multiple shortcuts to preview files (<kbd>Apple</kbd>+<kbd>O</kbd> or <kbd>Apple</kbd>+<kbd>↓</kbd>)
* I'm not a fan of shortcuts for the desk accessories, and the discoverability will be low. Users can use the Selector to make custom shortcuts (<kbd>Apple</kbd>+<kbd>1</kbd> ... <kbd>Apple</kbd>+<kbd>8</kbd>) to desk accessories if they need a shortcut

**Comment by ph0enix-c0der** [comment]
This issue should be added to the Apple II DeskTop 1.2 milestone.
