### ISSUE TITLE
Apple-clicking a window's title bar should open a pop-up menu containing the current window, the window's enclosing folder(s) and the window's enclosing volume

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#262]
Apple-clicking a window's title bar should open a pop-up menu containing the window's enclosing folder(s), with an open folder icon on the left side of each folder name, and enclosing volume, with a miniaturized version of the volume's desktop icon on the left side of the volume name, just like the later Mac and the later IIGS. Selecting a folder or the volume from the pop-up menu should open the respective folder or volume selected. Selecting a folder or the volume from the pop-up menu while holding the Apple key down should open the respective folder or volume selected while closing the current window.

**Comment by c0mmander8** [comment]
Apple-clicking a window's title bar should open a pop-up menu containing the current window, with the window's respective folder or volume icon on the left side of the window's name, the window's enclosing folder(s), if any, with an open folder icon on the left side of each folder name, and the window's enclosing volume, if any, with a miniaturized version of the volume's desktop icon on the left side of the volume name, just like the later Mac and the later IIGS. Selecting a folder or the volume from the pop-up menu should open the respective folder or volume selected. Selecting a folder or the volume from the pop-up menu while holding the Apple key down should open the respective folder or volume selected while closing the current window.

**Comment by c0mmander8** [comment]
Apple-clicking a window's title bar should open a pop-up menu containing the current window, with the window's respective folder or volume icon, as described below, on the left side of the window's name, the window's enclosing folder(s), if any, with an empty folder icon on the left side of each folder name, and the window's enclosing volume, if any, with a miniaturized version of the volume's desktop icon on the left side of the volume name, just like the later Mac and the later IIGS. Selecting a folder or the volume from the pop-up menu should open the respective folder or volume selected. Selecting a folder or the volume from the pop-up menu while holding the Apple key down should open the respective folder or volume selected while closing the current window.

**Comment by c0mmander8** [comment]
Apple-clicking a window's title bar should open a pop-up menu containing the current window, with the window's respective folder or volume icon, as described below, on the left side of the window's name, the window's enclosing folder(s), if any, with an empty, physically open folder icon on the left side of each folder name, and the window's enclosing volume, if any, with a miniaturized version of the volume's desktop icon on the left side of the volume name, just like the later Mac and the later IIGS. Selecting a folder or the volume from the pop-up menu should open the respective folder or volume selected. Selecting a folder or the volume from the pop-up menu while holding the Apple key down should open the respective folder or volume selected while closing the current window.

**Comment by c0mmander8** [comment]
Apple-clicking a window's title bar should open a pop-up menu containing the current window, with the window's respective folder or volume icon, as described below, on the left side of the window's name, the window's enclosing folder(s), if any, with an empty, physically open folder icon on the left side of each folder name, and the window's enclosing volume, if any, with a miniaturized version of the volume's desktop icon on the left side of the volume name, just like the later Mac and the later IIGS. Selecting a folder or the volume from the pop-up menu should open the respective folder or volume selected. Selecting a folder or the volume from the pop-up menu while holding the Apple key down should open the respective folder or volume selected while closing the current window.

**Comment by inexorabletash** [comment]
Editing message titles generates spam (I get an email for every edit you make) - please stop. 

I'm leaving this open, but noting that MGTK has no support for popup menus, so this would be a substantial undertaking with significant code-size impact.

**Comment by c0mmander8** [comment]
Please let me continue editing comments, including message titles, so that I can continue to make corrections to my posts as needed. Thank you for your cooperation.

**Comment by inexorabletash** [comment]
Not interested.
