### ISSUE TITLE
Add gesture to close all windows except active window

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#263]
As referenced by Jay Edwards below, make selecting File > Close All while holding down the Apple key close all windows except the currently active one.

4.  Add "Close All Windows BUT Front One" and "Close All Windows AND Open 
This Folder" commands.  All versions of MouseDesk and Apple DeskTop II have a 
"Close All (Windows)" command to make cleaning up the desktop quick and easy.  
The added benefit of these two commands would both clean up the desktop and 
remove unnecessary icons from the desktop.  The "Close All Windows AND Open
This 
Folder" option would be especially useful if the 110 item limit can not be 
increased.

**Comment by c0mmander8** [comment]
As referenced by Jay Edwards below, make selecting File > Close Window or File > Close All while holding the Apple key down close all windows except the currently active one.

4.  Add "Close All Windows BUT Front One" and "Close All Windows AND Open 
This Folder" commands.  All versions of MouseDesk and Apple DeskTop II have a 
"Close All (Windows)" command to make cleaning up the desktop quick and easy.  
The added benefit of these two commands would both clean up the desktop and 
remove unnecessary icons from the desktop.  The "Close All Windows AND Open
This 
Folder" option would be especially useful if the 110 item limit can not be 
increased.

**Comment by c0mmander8** [comment]
As referenced by Jay Edwards below, make selecting File > Close Window or File > Close All while holding the Apple key down close all windows except the currently active one.

4.  Add "Close All Windows BUT Front One" and "Close All Windows AND Open 
This Folder" commands.  All versions of MouseDesk and Apple DeskTop II have a 
"Close All (Windows)" command to make cleaning up the desktop quick and easy.  
The added benefit of these two commands would both clean up the desktop and 
remove unnecessary icons from the desktop.  The "Close All Windows AND Open
This 
Folder" option would be especially useful if the 110 item limit can not be 
increased.

**Comment by c0mmander8** [comment]
As referenced by Jay Edwards below, make selecting File > Close Window or File > Close All while holding the Apple key down close all windows except the currently active one.

4.  Add "Close All Windows BUT Front One" and "Close All Windows AND Open 
This Folder" commands.  All versions of MouseDesk and Apple DeskTop II have a 
"Close All (Windows)" command to make cleaning up the desktop quick and easy.  
The added benefit of these two commands would both clean up the desktop and 
remove unnecessary icons from the desktop.  The "Close All Windows AND Open
This 
Folder" option would be especially useful if the 110 item limit can not be 
increased.

**Comment by inexorabletash** [comment]
Benefits of this seem low, not interested.

**Comment by c0mmander8** [comment]
Reopen this issue, because I think it is genuinely useful to users with lots of files.

**Comment by c0mmander8** [comment]
Reopen this issue, because I think this issue is genuinely useful to users with lots of files.

**Comment by c0mmander8** [comment]
Reopen this issue, because I think this issue is genuinely useful to users with lots of files and / or open windows.

**Comment by c0mmander8** [comment]
Reopen this issue, because I think this issue is genuinely useful to users with lots of files / folders and / or open windows.

**Comment by c0mmander8** [comment]
Reopen this issue, because I think this issue is genuinely useful to users with lots of files and / or folders and / or open windows.

**Comment by c0mmander8** [comment]
Reopen this issue, because I think this issue is genuinely useful to users with lots of files / folders / open windows.

**Comment by c0mmander8** [comment]
As referenced in issue #289, reopen this issue, because I think this issue is genuinely useful to users with lots of files / folders / open windows.
