### ISSUE TITLE
Add a Window(s) menu, with all open windows listed, an option to make the desktop active and, if possible, an option to stack the windows

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#264]
As referenced by Jay Edwards below, add a Window or Windows menu, whichever you prefer to call it, with all open windows listed, an option to make the desktop active and, if possible, an option to stack the windows, just like the later IIGS and the later Mac. If you select a window from the menu, bring it to the front. If you select a window from the menu while holding the Apple key down, close that window instead of bringing it to the front.

2a.  Add "Window" option on pull down menu bar to move to front windows open 
on the desktop, but buried under other open windows.

2b.  An alternative to "1a" (or addition to) would be the ability to collapse 
windows to their top bar, just as can be done on the IIgs and Macs.

**Comment by inexorabletash** [comment]
Early versions of MouseDesk had this, and there is actually some plumbing remaining for it. I think it would add more clutter to the UI than it's worth, though.

**Comment by inexorabletash** [comment]
Not interested.
