### ISSUE TITLE
Make double-clicking on a window's title bar collapse it, double-clicking on a collapsed window's title bar restore it back to normal and, if possible, add a WindowShade box to the right corner of the title bar of every window

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#265]
As referenced by Jay Edwards below, make double-clicking on a window's title bar collapse it, double-clicking on a collapsed window's title bar restore it back to normal and, if possible, add a WindowShade box in the upper-right corner of every window, just like the later Mac.

2a.  Add "Window" option on pull down menu bar to move to front windows open 
on the desktop, but buried under other open windows.

2b.  An alternative to "1a" (or addition to) would be the ability to collapse 
windows to their top bar, just as can be done on the IIgs and Macs.

**Comment by c0mmander8** [comment]
Make double-clicking on a window's title bar while holding the Apple key down collapse all the windows and double clicking on a collapsed window's title bar while holding the Apple key down restore all the windows back to normal. Make clicking on the WindowShade box collapse the window or restore the window back to normal based on the situation. Make clicking on the WindowShade box while holding the Apple key down collapse all the windows or restore all the windows back to normal based on the situation.

**Comment by inexorabletash** [comment]
Not supported by MGTK and I never liked this feature. It never caught on
