### ISSUE TITLE
Add gesture to close all windows

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#266]
Make selecting File > Close while holding the Apple key down close all windows and make clicking on the close box while holding the Apple key down close all windows, just like the Mac and the IIGS.

**Comment by c0mmander8** [comment]
Make clicking on the close box while holding the Apple key down close all windows, just like the Mac and the IIGS.

**Comment by c0mmander8** [comment]
Make clicking on the close box while holding the Apple key down close all windows, just like the Mac and the IIGS.

**Comment by c0mmander8** [comment]
Make clicking on the close box while holding the Apple key down close all windows, just like the Mac and the IIGS.

**Comment by c0mmander8** [comment]
Make clicking on the close box while holding the Apple key down close all windows, just like the later Mac and the later IIGS.

**Comment by inexorabletash** [comment]
Added the gesture. Since menu items can't change dynamically and there's already **File > Close All**, did not modify the menu command behavior.
