### ISSUE TITLE
Add a zoom box to the right corner of the title bar of every window

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#267]
Add a zoom box to the right corner of the title bar of every window, just like the later Mac and the IIGS. When clicked, it expands the window size just enough to display all the icons or list of items, but no more than that. When clicked while holding the Apple key down, it expands the window to maximum size.

**Comment by inexorabletash** [comment]
Not supported by MGTK.

**Comment by inexorabletash** [comment]
Not interested.
