### ISSUE TITLE
Make Apple-dragging a window's title bar move the window without making the window active

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#268]
Make Apple-dragging a window's title bar move the window without making the window active, just like the Mac and the IIGS.

**Comment by inexorabletash** [comment]
Not supported by MGTK so this would be extremely difficult.

**Comment by inexorabletash** [comment]
Never going to do this.

**Comment by c0mmander8** [comment]
Please reopen this issue. I still think that this issue is an important issue to be implemented because this would greatly increase the usability of Apple II DeskTop.
