### ISSUE TITLE
Use K instead of KB in File > Get Info, list views and everywhere else KB is currently used or, conversely, use KB instead of K in volume info header and everywhere else K is currently used

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#269]
Use K instead of KB in File > Get Info, list views and everywhere else KB is currently used, just like the Mac and the IIGS. Conversely, if you do not agree, use KB instead of K in disk info header and everywhere else K is currently used.

**Comment by inexorabletash** [comment]
Thank you for the suggestion. 

Please restrict issue titles to 10 words at most per GitHub social conventions, like book titles or email subjects, and refrain from editing them unless they are egregiously incorrect. Look at how other people post issues for guidance. You can provide more details in issue contents. Repeated failure to respect this request will result in being blocked from participating.

**Comment by inexorabletash** [comment]
DeskTop was copying the original MacOS Finder, which was inconsistent. But I agree, consistency is probably better.

![image](https://user-images.githubusercontent.com/771547/92310527-3ac55380-ef64-11ea-8991-0853fb184e45.png)

**Comment by c0mmander8** [comment]
Why did you choose to use KB instead of K?
