### ISSUE TITLE
Use a comma when file, folder or volume sizes are 4 or 5 digits long in K or KB in File > Get Info, list views, volume info header and everywhere else K or KB is currently used

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#270]
Use a comma when file, folder or volume sizes are 4 or 5 digits long in K or KB in File > Get Info, list views, disk info header and everywhere else K or KB is currently used, just like the later Mac and the later IIGS.

**Comment by inexorabletash** [comment]
Thank you for the suggestion. 

Please restrict issue titles to 10 words at most per GitHub social conventions, like book titles or email subjects, and refrain from editing them unless they are egregiously incorrect. Look at how other people post issues for guidance. You can provide more details in issue contents. Repeated failure to respect this request will result in being blocked from participating.
