### ISSUE TITLE
Add Restart and Shut Down commands to the Special menu or the Startup menu

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#271]
Add Restart and Shut Down commands to the Special Menu, just like the later Mac and the later IIGS.

**Comment by c0mmander8** [comment]
Add Restart and Shut Down commands to the Special menu or the Startup menu, just like the later Mac and the later IIGS.

**Comment by c0mmander8** [comment]
Add Restart and Shut Down commands to the Special menu or to the Startup menu, just like the later Mac and the later IIGS.

**Comment by c0mmander8** [comment]
Add Restart and Shut Down commands to the Special menu or the Startup menu, just like the later Mac and the later IIGS.

**Comment by inexorabletash** [comment]
Not interested. Quit back to ProDOS is sufficient.
