### ISSUE TITLE
Make pressing the Reset key or the Power key bring up a dialog box

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#272]
Make pressing the Reset key or the Power key bring up a dialog box, giving the user the following choices to click or the following keys to press, from the right side of the dialog box to the left, just like the later Mac:

Shut Down-Return or S
Restart-R
Quit (to launching application)-Q
Cancel-Escape or C

**Comment by inexorabletash** [comment]
Not interested.
