### ISSUE TITLE
Add alphanumeric keyboard navigation and the following related keyboard features

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#275]
Add alphanumeric keyboard navigation and the following related keyboard features, just like the later Mac and the later IIGS:

~~\`: Selects the first item whose name starts with \`. If none, selects the next item in alphabetical, numerical or symbolic order.~~
~~Arrow key: Selects the next item in the respective direction.~~
~~Enter: Once issue #203 is implemented, selects the filename for editing.~~
Letter key: Selects the first item whose name starts with that letter or group of characters. If none, selects the first item whose name starts with the next available letter or group of characters in alphabetical order.
~~Number key: Selects the first item whose name starts with that number or group of characters. If none, selects the first item whose name starts with the next available number or group of characters in numerical order.~~
Return: Once issue #203 is implemented, selects the filename for editing.
~~Shift-` (\~): Selects the first item whose name starts with \~. If none, selects the previous item in alphabetical, numerical or symbolic order.~~
Shift-Apple-Up Arrow: Makes the current window inactive and the desktop active.
~~Shift-Tab: Selects the previous item in alphabetical, numerical or symbolic order.~~
~~Symbol key: Selects the first item whose name starts with that symbol or group of characters. If none, selects the first item whose name starts with the next available symbol or group of characters in symbolic order.~~
Tab: Selects the next item in alphabetical, numerical or symbolic order.

**Comment by inexorabletash** [comment]
A few notes:

* The Arrow suggestion is redundant with #274; please don't file duplicate bugs.
* In ProDOS, files can't start with `~`, numbers, or other symbols, so those suggestions are nonsensical.
* On the Apple II, the <kbd>Return</kbd> and <kbd>Enter</kbd> keys are identical, so that's redundant.
* On the Apple II, <kbd>Shift</kbd>+<kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Up</kbd> can't be detected.

**Comment by I3arana** [comment]
Great solution. modeless would be hair pulling at 1mhz

**Comment by c0mmander8** [comment]
Please implement the details of issue #609 and issue #610 when implementing the window keyboard navigation in the Apple II DeskTop app in this feature request.

**Comment by inexorabletash** [comment]
Type-down selection isn't a bad idea. 

The challenge is that, unlike the file picker (see #610), the list of icons in a window the desktop don't have names in sorted order anywhere. So either a sorting pass needs to be done when typing starts, or a sorted list needs to be maintained. The former is probably easier, and the list would be invalidated if typing is reset so it won't take up persistent memory.

**Comment by inexorabletash** [comment]
I've implemented support for type-down selection. 

Leaving this open, since <kbd>Tab</kdb> support is a reasonable idea to add; it's effectively a merge of the sorting behavior for type-down plus the arrow keys to move to the next/prev item.

**Comment by inexorabletash** [comment]
<kbd>Tab</kbd> / <kbd>Shift</kbd>+<kbd>Tab</kbd> support added. I think that's all that's plausible to do here.
