### ISSUE TITLE
Alphabetize the items in the Apple menu

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#276]
Alphabetize the items in the Apple menu, just like the Mac and the IIGS.

**Comment by inexorabletash** [comment]
No, they're intentionally in directory order so users can arrange them as they wish.

**Comment by c0mmander8** [comment]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that I have to manually arrange the sort order of the Desk.Acc folder in order to alphabetize the items in the Apple menu.

**Describe the solution you'd like**
Please reopen this issue and add an option / a setting in the Control Panel to override the sort order of the Desk.Acc folder and to automatically alphabetize the items in the Apple menu, just like the later IIGS.

**Describe alternatives you've considered**
Keep on manually arranging the sort order of the Desk.Acc folder in order to alphabetize the items in the Apple menu.

**Additional context**
There is no other context or screenshots about this feature request here.

**Comment by inexorabletash** [comment]
This was effectively fixed in 92b43036 if you don't reorder the items later.
