### ISSUE TITLE
Put a space between the size number and KB

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#277]
Put a space between the size number and KB in the volume info header and everywhere else a space is missing between the size number and KB, just like the space between the size number and MB in the later Mac and the later IIGS. Fix changes in commit 9920e2f where there is no space between the size number or its sample representation and KB.

**Comment by inexorabletash** [comment]
Thanks for pointing out the inconsistency. I'm still not sure about **123K** vs. **123 KB** but I agree consistency is better if we stick with KB.
