### ISSUE TITLE
Make selection work in list views

### ISSUE THREAD

**Issue by inexorabletash** [a2stuff/a2d#28]

**Comment by ZoriaRPG** [comment]
Ah, sorry. Why is this categorised 'unrealistic'?

**Comment by inexorabletash** [comment]
I'm using that tag to set expectations for anything that would require substantial rewrite/rearchitecture, i.e. many tens of hours. Which is unlikely to get done without other contributors taking the lead.

**Comment by inexorabletash** [comment]
Removing BCR-low just because this is one of the top requests. It's a huge amount of work and I'm unlikely to tackle it, but it might be worth it for someone to take it on.
