### ISSUE TITLE
Problem with writing directly to slot-3 Le Chat Mauve Eve I/O registers

### ISSUE THREAD

**Issue by tomcw** [a2stuff/a2d#280]
This issue is about the code that writes to Le Chat Mauve (LCM) I/O registers in slot-3 DEVICE SELECT I/O space, here:
https://github.com/a2stuff/a2d/blob/4567248953fc9b097647f2f23912abf825c18b5e/desktop/desktop_main.s#L10340

These I/O writes will collide with any card that's in slot-3 (in addition to the 80 Col/RGB card that's in the AUX slot). A typical card to put in slot-3 is one without any ROM/firmware, that only has I/O mapped at $C0Bx, eg. Uthernet and Uthernet II cards.

LCM "Eve" has 16 registers mapped at: $C0B0..$C0BF
Uthernet has 16 registers mapped at: $C0B0..$C0BF
Uthernet II has 4 registers mapped at: $C0B4..$C0B7

Obviously no one will have a LCM + Uthernet installed at the same time.
But they may have an AppleColor (RGB) card + Uthernet, and the LCM I/O-writes that A2D does may interfere with the Uthernet card (depending on what "random" values are written to HR2_OFF and HR3_OFF).

I don't know if there's a way to detect if you have an LCM in the AUX slot.
There is a way to probe for the Uthernet II card, see the manual, [here](http://dserver.macgui.com/Uthernet%20II%20manual%20draft.pdf).

I don't have a good solution for this though.
(Maybe tailor the values written to HR2_OFF and HR3_OFF to be harmless for both Uthernet cards?)

**Comment by inexorabletash** [comment]
The "Eve" card is presumably pretty rare. I could introduce another control panel DA for advanced options, and just have a checkbox for Eve support.

It'd be a good first bug for someone to take on.

**Comment by tomcw** [comment]
Yeah, it's a pretty rare case I'm talking about here.
I don't think it's something you really need to worry about, but worth documenting at least.

**Comment by inexorabletash** [comment]
A2osX has detection code for the Eve, not sure if it's Uthernet-safe, though. 

https://github.com/A2osX/A2osX/blob/f862d6303b99c1342b0b7b1091589e84fc724780/DRV/DHGR.DRV.S.txt#L56

**Comment by tomcw** [comment]
re. A2osX's EVE detection

A quick look, and it appears to be good.
It only writes to TXT16.OFF ($C0B8) and TXT16.ON ($C0B9), which doesn't clash with the Uthernet II registers.
