### ISSUE TITLE
This Apple: Detect Uthernet II

### ISSUE THREAD

**Issue by inexorabletash** [a2stuff/a2d#281]
Add logic for detecting Uthernet II during slot scan, as is done for Mockingboard.

http://dserver.macgui.com/Uthernet%20II%20manual%2017%20Nov%2018.pdf

**Comment by inexorabletash** [comment]
@tomcw - perhaps you can review the change and/or give it a whirl?

**Comment by apple2geek** [comment]
I have an Uthernet-II in my system (in slot 3), and it doesn't seem to be identified by This Apple.
Should this detection work for slot 3?  Is this maybe a case of it just not being displayed because Slot 3 is identified as 80-column?  Can the DA output show both, if present?

**Comment by inexorabletash** [comment]
@apple2geek Does it report empty or unknown?

The current logic uses ProDOS's bitmask of whether a card is in the slot or not, which may not be trustworthy in this case.

**Comment by inexorabletash** [comment]
Oh, you note it's detecting the 80 col card there. Hmm, I'll think about checking slot 3 for firmware-less cards.

**Comment by apple2geek** [comment]
Additional observation - the Uthernet-II is not detected when relocated to Slot 1 or 2 either.  Both show up as (empty), so this may be the same situation as the Mockingboard, which is not being detected and is showing up as (empty) as well.
