### ISSUE TITLE
Prodos bell G pitch slider

### ISSUE THREAD

**Issue by I3arana** [a2stuff/a2d#283]
Request addition to your fine feature of the prodos bell G noise. In general control panel , add a slider that controls the pitch of the bell,(and possibly duration or sustain) handy and nice, especially with accelleration. As in beaglewrite's DeskTop based Desk Acc (check it out)

**Comment by inexorabletash** [comment]
Out of curiosity, do you frequently do things that invoke the bell? 

I almost never run into it when I'm using DeskTop.

**Comment by I3arana** [comment]
Yes from time to time, deleting locked files, fiddling with gsos files etc

**Comment by inexorabletash** [comment]
> As in beaglewrite's DeskTop based Desk Acc (check it out)

FWIW, BeagleWrite has no relation to DeskTop, and doesn't use MouseGraphics ToolKit - it's got its own graphics library implementation.

Are you referring to the Control Panel accessory? It always seems to crash for me (beeps and exits) when I install it into BeagleWrite and launch it. The other BW DAs seem to run fine - Puzzle, Clock, Calendar, etc. Any ideas?

**Comment by inexorabletash** [comment]
FWIW, I got the BeagleWrite Control Panel DA working. Looks like it's just a pitch slider. 

I'm thinking of something like this:

![image](https://user-images.githubusercontent.com/771547/156113513-f4a23999-107e-4be7-a29c-a4ca46c4748d.png)

**Comment by I3arana** [comment]
Thanks for your brilliant work and continued contributions on this.By the lions mane!

**Comment by ph0enix-c0der** [comment]
This issue should be added to the Apple II DeskTop 1.2 milestone.
