### ISSUE TITLE
make selectable the code that forces DeskTop into B&w mode

### ISSUE THREAD

**Issue by I3arana** [a2stuff/a2d#284]
The code inside DeskTop that switches the display into b&w is keeping us from seeing the colour desktop patterns from the new Desk Accessory on Platinum IIe, GS, applewin and Gerard puter's emulator. could we please have a switch to turn it off even tho it means colour fringing? 
Love the colour patterns.Thx.

**Comment by inexorabletash** [comment]
Good suggestion. I'll think about where to add it. It could also help with #281

**Comment by inexorabletash** [comment]
I was thinking a checkbox under the Desktop Pattern item in the Control Panel:

☒ RGB Color

That wouldn't help with #281 though. In theory we want a tri-state:

* non-RGB and/or don't poke color switches
* force RGB mono
* force RGB color

... but that's getting very complicated.

**Comment by inexorabletash** [comment]
I went with the simple checkbox. Tested it in IIgs emulator, seems to behave as expected.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/98489524-2cedb200-21e3-11eb-90e1-e40f098855e4.png)

**Comment by I3arana** [comment]
Well done! Thx! although, I found most IIGS emulators wouldnt allow it to switch back for some reason. Real rom 1/3 would. It also tookup to 30secs for the switch. Ps sent you an email.

**Comment by inexorabletash** [comment]
And I was using GSplus (a fork of GSport which is a fork of KEGSs)

**Comment by I3arana** [comment]
The gmail acc. subject Liine DeskTop. will resend
