### ISSUE TITLE
Forked files (Big challenge)

### ISSUE THREAD

**Issue by I3arana** [a2stuff/a2d#288]
What would be a handy feature is for DT to see and manipulate forked files properly. GSOS, classic mac and osx files
 if thats not possible, a workaround *could be* that the DT finder  'sees' forked files as AppleDouble.. which is a filetype on GSOS and OSX

**Comment by inexorabletash** [comment]
This seems somewhat out of scope to me. I guess I consider the project to be aimed at creating a great app for ProDOS 8 and 8-bit Apples... if you need IIgs-specific behavior, use GS/OS?

**Comment by I3arana** [comment]
Fair enough. Ill drop it.
    It as aimed at interoperability as a user and coder with gsos and macos files. theres a few fellas that have said to me yesterday and over the years this would be helpful.
 ps. the two 8 bit packages that can read hfs disks are hfslink and a2fx. in response to an earlier enquiry.
 Additionally, check  out IIGS system disk 2.0(its DeskTop) the appletalk subsystem is implemented in p8 apps. ofcourse the drivers are for a gs...but that i have no reservations that it will be a help to one with your skills  none the less.

**Comment by inexorabletash** [comment]
Closing this out as I don't see it ever happening.
