### ISSUE TITLE
Reopen issue #263 - Add gesture to close all windows except active window

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#289]
As referenced in issue #263, reopen issue #263 - Add gesture to close all windows except active window, because I think that issue is genuinely useful to users with lots of files.

**Comment by c0mmander8** [comment]
As referenced in issue #263, reopen issue #263 - Add gesture to close all windows except active window, because I think that issue is genuinely useful to users with lots of files and / or open windows.

**Comment by c0mmander8** [comment]
As referenced in issue #263, reopen issue #263 - Add gesture to close all windows except active window, because I think that issue is genuinely useful to users with lots of files / folders and / or open windows.

**Comment by c0mmander8** [comment]
As referenced in issue #263, reopen issue #263 - Add gesture to close all windows except active window, because I think that issue is genuinely useful to users with lots of files and / or folders and / or open windows.

**Comment by c0mmander8** [comment]
As referenced in issue #263, reopen issue #263 - Add gesture to close all windows except active window, because I think that issue is genuinely useful to users with lots of files / folders / open windows.

**Comment by inexorabletash** [comment]
This is not an appropriate use of the issue tracker. Please stop.
