### ISSUE TITLE
Reopen and merge pull request #279 - Pull request-9/28/2020

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#290]
As referenced in pull request #279, reopen and merge pull request #279 - Pull request-9/28/2020, because I need that pull request merged before I can delete my existing fork of this repository and clone a new fork of this repository with all the changes you have made since my existing fork was branched off.

**Comment by inexorabletash** [comment]
This is not an appropriate use of the issue tracker. Please stop.
