### ISSUE TITLE
Add support for all other file types in the Apple menu

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#293]
Add support for all other file types in the Apple menu, just like the later Mac.

**Comment by c0mmander8** [comment]
This issue should also be made compatible with issue #102.

**Comment by inexorabletash** [comment]
At first I thought this was silly and redundant with the Selector... then I thought it might just be a harmless one line change. It turned up some pre-existing logic flaws but was overall pretty easy.

Note that previews don't work (you can't put an image file or a text file), only executables.

**Comment by c0mmander8** [comment]
Can you get previews to work?
