### ISSUE TITLE
Make the Apple menu hierarchical

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#294]
Make the Apple menu hierarchical, just like the later Mac. Use the folder glyphs introduced in issue #292 to delineate folders in the hierarchical submenus, just like in the parent Apple menu.

**Comment by inexorabletash** [comment]
MGTK doesn't support hierarchical menus, and it would likely not be plausible with the current savearea mechanism. Given the extreme cost and low benefit, closing this out.

**Comment by c0mmander8** [comment]
This issue should also be made compatible with issue #102.
