### ISSUE TITLE
Add support for a 9th Selector menu run list entry

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#299]
Add support for a 9th Selector menu run list entry with an Apple-9 keyboard shortcut so the Apple-9 keyboard shortcut can be used. Add support for a 17th and an 18th Selector other run list entries making a total of 27 Selector menu run list entries and Selector other run list entries combined. This balances the Selector dialog box from the adding of a 9th Selector menu run list entry.

**Comment by inexorabletash** [comment]
This would significantly complicate the code in many places (which are predicated on multiplying by 8) for little benefit. I suspect this request is only being made to try and utilize every available key sequence, not out of actual user need.
