### ISSUE TITLE
Make Down Arrow / Up Arrow keypresses cycle vertically

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#300]
As referenced in issue #274 and issue #275, make Down Arrow / Up Arrow keypresses cycle vertically first and only then horizontally, the reverse of the current behavior with the Left / Right Arrows.

**Comment by c0mmander8** [comment]
As referenced in issue #274 and issue #275, make Down Arrow / Up Arrow keypresses cycle icons vertically first and only then horizontally, the reverse of the current behavior with the Left / Right Arrows.

**Comment by inexorabletash** [comment]
Cycling occurs in icon index order. I'm not interested in implementing spatial navigation.

**Comment by xandark** [comment]
> If spatially-aware cursor selection is too much to implement, then maybe a short-term solution would be to only allow left/right presses for the icon/small icon view modes, and only the up/down presses for the list view mode.
