### ISSUE TITLE
Show the return glyph next to "Rename..." in the File menu

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#302]
Show the return glyph next to "Rename..." in the File menu as a keyboard shortcut for that item.

**Comment by c0mmander8** [comment]
Show the return symbol next to "Rename..." in the File menu as a keyboard shortcut for that item.

**Comment by inexorabletash** [comment]
Please don't leave redundant comments (e.g. just changing "glyph" to "symbol"); this makes the issue harder to read and takes time away from more impactful work.

I investigated this briefly. There's some MGTK weirdness to reason through.
* MGTK doesn't show glyphs for keys if the menu item isn't defined to use open or solid apple; it actually tries to prefix the glyph with a control key glyph, but then ignores that.
* MGTK will dispatch without modifiers... if it's a control key (ASCII $00-$1F). 

A non-hacky change would be to make MGTK show the control key prefix correctly, and use `^` as a prefix character, resulting in **^M** showing for return, thus supporting future control characters. But the ⏎ symbol would be a far better user experience. MGTK itself doesn't have knowledge of the font glyphs for control characters, though.

I'll ponder how to do this in a reasonable way.
