### ISSUE TITLE
Menu item string changes

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#303]
The following menu item string changes are proposed because an ellipsis (...) signifies that additional action is required before the requested operation can be performed:

"About Apple II DeskTop..." should be "About Apple II DeskTop" without the ellipsis because there is no further action to perform, just like the later Mac.
"Lock" should be "Lock..." with the ellipsis because you have to confirm whether you want to go forward with the requested operation at the prompt, just like the dialog box header string.
"Unlock" should be "Unlock..." with the ellipsis because you have to confirm whether you want to go forward with the requested operation at the prompt, just like the dialog box header string.

**Comment by inexorabletash** [comment]
Thanks - I appreciate the attention to detail.
