### ISSUE TITLE
Dialog box header string changes

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#304]
The following dialog box header string changes are proposed because an ellipsis (...) signifies that additional action is required before the requested operation can be performed:

"Get Info..." should be "Get Info" without the ellipsis because there is no further action to perform, just like the menu item string.
"Get Size..." should be "Get Size" without the ellipsis because there is no further action to perform, just like the menu item string.

**Comment by inexorabletash** [comment]
Thanks - I appreciate the attention to detail.
