### ISSUE TITLE
Should the "Disk Copy..." menu item string be "Disk Copy" without the ellipsis (...)?

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#307]
Should the "Disk Copy..." menu item string be "Disk Copy" without the ellipsis (...) because there is no further action to perform to launch Disk Copy although additional action is required to get anything done with Disk Copy?

**Comment by inexorabletash** [comment]
I was wondering that as well. Disk Copy is weird for a whole bunch of reasons. Maybe it should even be "Copy a Disk..." to match the other actions, but it doesn't behave the same way.

I think I'll leave them for now (and close this) but we can revisit.

**Comment by ph0enix-c0der** [comment]
This issue should be removed from the Apple II DeskTop 1.2 milestone.
