### ISSUE TITLE
GSplus freezes when formatting a disk using Format a Disk...

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#309]
GSplus v0.14 (the latest version of the program) freezes when formatting a disk (not the startup disk) using Format a Disk... in Apple II DeskTop 1.2 (Pre-)Alpha 22 (the latest version of the program) on Windows.

**Comment by c0mmander8** [comment]
This issue is not related to issue #310. This is a totally unrelated issue.

**Comment by inexorabletash** [comment]
I can repro this with a remapped drive, so it's similar to #306 (but at least not crashing the emulator?)

Can you share your gsplus drive config and verify that you were reformatting a remapped drive? (i.e. not one of the first two disks in a slot)

I was not able to repro with disks in slot 5 or 6, just in slot 7 disk 3 or greater.

**Comment by c0mmander8** [comment]
My GSplus drive configuration is using s7d1 and s7d2, not s7d3 or greater and therefore I was not reformatting a remapped drive.

**Comment by inexorabletash** [comment]
Thanks, that helps. Please try to provide that information with bug reports in the future.

I'm able to repro, and on the GSplus console I see:

```Unknown prodos_unit: 251```

251 is $FB which is the unit number for Slot 7 Drive 2 which is what I was trying to format. The lower nibble is supposed to be 0, though.... I'm able to format a Smartport device in S7D2 in Virtual II, so this is indeed something specific to GSplus; it may adhere more closely to the standard.

**Comment by inexorabletash** [comment]
Fortunately, that one was easy once I knew where to look!
