### ISSUE TITLE
Run Basic Here does not open when run from the Apple menu

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#312]
As referenced in issue #310, Run Basic Here does not open when run from the Apple menu. It works perfectly fine though when double-clicked on in the Desk.Acc folder.

**Comment by c0mmander8** [comment]
As referenced in issue #310, but totally unrelated to that issue, Run Basic Here does not open when run from the Apple menu. It works perfectly fine though when double-clicked on in the Desk.Acc folder.

**Comment by inexorabletash** [comment]
My guess is that you don't have a window open. It needs a window open to define the path for the window. 

If that's not the case, please comment with full repro steps.

**Comment by c0mmander8** [comment]
I take my last comment back. I think this issue and issue #311 are in fact related to issue #310.

**Comment by c0mmander8** [comment]
I take all my comments back. You were right about this issue and issue #311. I did not have a window open in each case. Thank you.
