### ISSUE TITLE
Always shade an open window's respective folder icon or volume icon in its parent window or, in the case of a volume, the desktop

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#313]
Always shade an open window's respective folder icon or volume icon in its parent window or, in the case of a volume, the desktop. Right now this does not happen if you close the parent window and then reopen it or if you quit Apple II DeskTop and then relaunch it.

**Comment by c0mmander8** [comment]
Always shade an open window's respective folder icon or volume icon in its parent window or, in the case of a volume, the desktop, just like the Mac and the IIGS. Right now this does not happen if you close the parent window and then reopen it or if you quit Apple II DeskTop and then relaunch it.

**Comment by c0mmander8** [comment]
Always shade an open window's respective folder icon or volume icon in its parent window or, in the case of a volume, on the desktop, just like the Mac and the IIGS. Right now this does not happen if you close the parent window and then reopen it or if you quit Apple II DeskTop and then relaunch it.

**Comment by c0mmander8** [comment]
Always shade an open folder's respective folder icon in its parent window and always shade an open volume's respective volume icon on the desktop, just like the Mac and the IIGS. Right now this does not happen if you close an open folder's parent window and then reopen it or if you quit Apple II DeskTop and then relaunch it.

**Comment by c0mmander8** [comment]
Always shade an open folder's respective folder icon in its parent window and always shade an open volume's respective volume icon on the desktop, just like the Mac and the IIGS. Right now this does not happen if you close a parent window and then reopen it or if you quit Apple II DeskTop and then relaunch it.

**Comment by c0mmander8** [comment]
Always shade an open folder's respective folder icon in its parent window and always shade an open volume's respective volume icon on the desktop, just like the Mac and the IIGS. Right now this does not happen if you close an open folder's parent window and then reopen it or if you quit Apple II DeskTop and then relaunch it.

**Comment by inexorabletash** [comment]
You repeated the same thing 7 times. Please stop doing this. 

Also, please use the issue templates, which will guide you into filing useful issues, e.g. providing repro steps. 

On this specific issue: the cost/benefit is too low to try and maintain this at all times.

**Comment by I3arana** [comment]
"You repeated the same thing 7 times. Please stop doing this."
Yes, youre clogging up my email inbox.
