### ISSUE TITLE
Make Find Files search all mounted volumes if no window is open

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#315]
Make Find Files work properly and search all mounted volumes for results if no window is open, just like the later Mac.

**Comment by c0mmander8** [comment]
As referenced in issue #310 and issue #311, make Find Files work properly and search all mounted volumes for results if no window is open, just like the later Mac.

**Comment by inexorabletash** [comment]
Please don't repeat yourself. 

Not interested.
