### ISSUE TITLE
Eliminate, or at least raise, the 8-windows-at-once limit for displaying files and folders

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#319]
Eliminate the 8-windows-at-once limit for displaying files and folders, just like the later Mac and the later IIGS. If for some reason this is not feasible or realistic, raise the 8-windows-at-once limit for displaying files and folders to the maximum number of windows possible.

**Comment by inexorabletash** [comment]
16 is possible - 4 bits are reserved per icon for window id. 

However, the storage overhead - a statically allocated icon table (128 bytes) winfo (56 bytes) and path (65 bytes) plus a handful of table entries for each - seems to make this impractical without strongly compelling use cases that would be needed by most users.

**Comment by c0mmander8** [comment]
Please reopen this issue. I still think that this issue is an important issue to be implemented because this would greatly increase the usability of Apple II DeskTop.

**Comment by inexorabletash** [comment]
This is now trivially possible following the changes in fffa03e59aac07b824b79c4ccddf59df3383b0b7 but each window has a significant huge memory hit. Changing it from 8 (current) to 15 (max) consumes 532 more bytes in Main (mostly path buffers for the windows) and 560 bytes in LC (mostly the winfo objects/title buffers).  Also, given the limit of 127 icons, it's hard to get 15 windows open.

Adding one or two more windows would be possible, but it's unclear there's really a significant use case for this.
