### ISSUE TITLE
Widen Name column and shrink Size column in list views

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#321]
Widen Name column and shrink Size column in list views in order to make better use of screen space.

**Comment by c0mmander8** [comment]
Widen Name column and shrink Size column in list views in order to fit long filenames after implementing issue #318, leave long filenames with more breathing space and make better use of screen space.

**Comment by inexorabletash** [comment]
Please stop repeating comments. You can make edits if needed. 

Also, please follow issue templates. I've limited access to the repository for a while due to your over-posting.

**Comment by inexorabletash** [comment]
As this is predicated on another suggestion, having a separate issue is unnecessary. Closing out.

**Comment by c0mmander8** [comment]
This issue is actually not predicated on issue #318. It stands alone on its own merits.

**Comment by c0mmander8** [comment]
The Size column in list views is actually too wide because its width still reflects the time when the Size column said "Blocks" instead of "K". Reopen this issue, and as mentioned above, widen the Name column and shrink the Size column in list views in order to leave long filenames with more breathing space and make better use of screen space, just like the Mac and the IIGS.

**Comment by inexorabletash** [comment]
Thanks for clarifying. In the future, please use the bug template structure. It makes it easier to read issues.

**Comment by inexorabletash** [comment]
Minor adjustment. Before:
![image](https://user-images.githubusercontent.com/771547/102303073-3fa88480-3f0f-11eb-80a1-b42c88296634.png)

After:
![image](https://user-images.githubusercontent.com/771547/102303110-5353eb00-3f0f-11eb-8590-597723ff8586.png)

**Comment by inexorabletash** [comment]
Also, please watch your tone in comments. _"Reopen this issue, and as mentioned above, "_ is a forceful imperative, and contributes to a negative impression of your contributions. Please try and phrase suggestions less forcefully.

**Comment by I3arana** [comment]
+1
