### ISSUE TITLE
Widen Selector menu

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#323]
Widen Selector menu in order to fit 15-character Selector menu run list entry names after implementing issue #322 and leave long Selector menu run list entry names with more breathing space.

**Comment by inexorabletash** [comment]
This is a completely unnecessary issue. Menus are dynamically sized based on content. 

@c0mmander8 - your frequent repetition, inability to respect feedback, and lack of adherence to behavioral norms for contributors is becoming tiresome. I greatly appreciate your politeness, attention to detail and prowess at testing, but you need to learn to contribute productively. 

I am limiting contributions to the repository for a while.
