### ISSUE TITLE
Fix Left Arrow / Right Arrow keypresses in Special > Format a Disk... and in Special > Erase a Disk...

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#328]
Make Left Arrow / Right Arrow keypresses correctly select the next item in the respective direction and cycle horizontally in Special > Format a Disk... and in Special > Erase a Disk....

**Comment by inexorabletash** [comment]
Please use the template structure when filing bugs, and respect the requested word limits for issue titles.

**Comment by inexorabletash** [comment]
Hah, good catch.

**Comment by c0mmander8** [comment]
I actually also mean cycle horizontally, not just only correctly select the next item in the respective direction.

**Comment by c0mmander8** [comment]
I changed my mind. Actually, please reopen this issue and also make Left Arrow / Right Arrow keypresses cycle horizontally first and only then vertically in Special > Format a Disk... and in Special > Erase a Disk..., the reverse of the current behavior with the Down / Up Arrows and what actually happens when cycling icons.

**Comment by c0mmander8** [comment]
I see that this issue was fixed in commit 385d374.
