### ISSUE TITLE
Solid-Apple should also work with the Selector keyboard shortcuts in addition to Open-Apple

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#329]
Solid-Apple should also work with the Open-Apple-0 to Open-Apple-8 keyboard shortcuts in the Selector menu and the Open-Apple-1 to Open-Apple-5 keyboard shortcuts in Selector > Add an Entry... and in Selector > Edit an Entry... in addition to Open-Apple.

**Comment by I3arana** [comment]
No,  solidapple has always had a different function. In later key boards it was relpaced by option.

**Comment by inexorabletash** [comment]
Please use the template structure when filing bugs, and respect the requested word limits for issue titles.

DeskTop usually treats both open and solid apple the same for shortcuts. I personally find this handy when using Virtual ][ so the command key can be used for controlling the emulator.

**Comment by inexorabletash** [comment]
> Solid-Apple should also work with the Open-Apple-0 to Open-Apple-8 keyboard shortcuts in the Selector menu

This seems to already be the case.

**Comment by inexorabletash** [comment]
> Open-Apple-1 to Open-Apple-5 keyboard shortcuts in Selector > Add an Entry... and in Selector > Edit an Entry... 

This also is already the case. Either modifier works. Closing, pending further feedback.
