### ISSUE TITLE
Add a progress bar while Selector launches

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#330]
Add a progress bar while Selector launches, just like Apple II Desktop.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/103145492-accacf80-46f0-11eb-9f75-8149e80158d2.png)

Selector loads much less than DeskTop so the bar is much less necessary. But it was a tiny copy/paste of code and there's plenty of room in the loading code, so sure.
