### ISSUE TITLE
Prefix folders in the Selector with the folder glyphs

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#331]
As referenced in issue #323 and issue #324, prefix folders in the Selector menu and folders in the Selector dialog box in Selector > Edit an Entry..., in Selector > Delete an Entry..., in Selector > Run an Entry... and when booting up the Selector directly with the folder glyphs, just like folders in the Apple menu, and widen the Selector menu and the Selector dialog box to compensate for the space the folder glyphs take up.

**Comment by inexorabletash** [comment]
This is not worth pursuing.
