### ISSUE TITLE
Make Left Arrow / Right Arrow keypresses cycle horizontally in the Selector dialog box when booting up the Selector directly

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#332]
Make Left Arrow / Right Arrow keypresses cycle horizontally in the Selector dialog box when booting up the Selector directly, just like Left Arrow / Right Arrow keypresses already do in the Selector dialog box in Selector > Edit an Entry..., in Selector > Delete an Entry... and in Selector > Run an Entry....

**Comment by inexorabletash** [comment]
Please use the template structure when filing bugs, and respect the requested word limits for issue titles.

**Comment by inexorabletash** [comment]
This appears to already be the case. Closing, pending further feedback.

**Comment by c0mmander8** [comment]
I actually mean cycle horizontally, not just only correctly select the next item in the respective direction.

**Comment by c0mmander8** [comment]
I changed my mind. Actually, please reopen this issue and make Left Arrow / Right Arrow keypresses cycle horizontally first and only then vertically in the Selector dialog box in Selector > Edit an Entry..., in Selector > Delete an Entry..., in Selector > Run an Entry... and when booting up the Selector directly at startup, the reverse of the current behavior with the Down / Up Arrows and what actually happens when cycling icons.

**Comment by c0mmander8** [comment]
I see that this issue was fixed in commit cabf2c3.
