### ISSUE TITLE
Suggest to change A2DeskTop.po file extension to hdv

### ISSUE THREAD

**Issue by wyatt-wong** [a2stuff/a2d#334]
Currently, the compiled a2d have extension of .po but it is a hard disk image. I suggest to change the file extension to .hdv to differentiate it from normal .po file. Furthermore, it is easy to identify it is a hard disk image when using Virtual ][ to mount it for boot up.

**Comment by inexorabletash** [comment]
Hmmm... it's intended to be an 800k image. The challenge is that image types are all over the map, with nearly every file type usable for every size. 

[Floppy Emu](https://www.bigmessowires.com/femu-instructions.pdf): 
* 5.25 inch Apple II floppy disk images in .DSK, .DO, .PO, .NIB, .WOZ, or .2MG formats
* 3.5 inch Apple II floppy disk images in .DSK, .DO, .PO, or .2MG formats
* Smartport disk images in .PO, .HDV, or .2MG formats"

[Virtual \]\[](https://www.virtualii.com/VirtualIIHelp/virtual_II_help.html#DiskImages) 
* 5.25" diskette - . dsk, .do, .po, .woz, .nib
* 3.5" diskette - .po, .2mg
* Hard disk or 3.5" diskette - .2mg, .hdv

[BOOTI](https://ct6502.org/wp-content/uploads/2019/11/BOOTI-USER-MANUAL.pdf) - .po/.dsk/.2mg/.iso/.hdv/.do (but note that .dsk and .do must be in ProDOS order, and BOOTI is not a floppy emulator)

AppleWin supports:
* Floppy:  .do, .dsk, .nib, .po, .woz, .2mg
* Hard disk: hdv, .po, .2mg
(I think. The docs are weird. I think 800k floppies are treated as hard disks as well.)

... and so on. 

Anyway, the point is that for an 800k image, HDV is wrong. 2MG might be better, but isn't clearly more suited for 800k floppy vs. hard disk.

**Comment by I3arana** [comment]
Agreed. Its no difficulty to boot the 3.5 image , and copy its contents across to a 32mb hdv.
________________________________

**Comment by wyatt-wong** [comment]
Changing the extension to .2mg and Virtual ][ was unable to recognize it. Changing the extension to .hdv can be successfully recognized by Virtual ][.

**Comment by inexorabletash** [comment]
Were you changing the file name or the file format? You can't just rename a file and expect it to work in most cases. Renaming your cat "Fido" doesn't make it a dog.

**Comment by wyatt-wong** [comment]
A simple filename rename works for me. You can test it in Virtual ][

**Comment by wyatt-wong** [comment]
wyattwong@MacBookPro Downloads % cd a2d
wyattwong@MacBookPro a2d % make clean
cleaning desktop
make[1]: Entering directory '/Users/wyattwong/Downloads/a2d/desktop'
rm -f out/*.o
rm -f out/*.list
rm -f out/desktop.built
make[1]: Leaving directory '/Users/wyattwong/Downloads/a2d/desktop'
cleaning desktop.system
make[1]: Entering directory '/Users/wyattwong/Downloads/a2d/desktop.system'
rm -f out/*.o
rm -f out/*.list
rm -f out/desktop.system.SYS
make[1]: Leaving directory '/Users/wyattwong/Downloads/a2d/desktop.system'
cleaning desk.acc
make[1]: Entering directory '/Users/wyattwong/Downloads/a2d/desk.acc'
rm -f out/*.o
rm -f out/*.list
rm -f out/calculator.da out/date.da out/puzzle.da out/sort.directory.da out/this.apple.da out/eyes.da out/screen.dump.da out/run.basic.here.da out/key.caps.da out/find.files.da out/flying.toasters.da out/control.panel.da out/joystick.da out/melt.da out/invert.da out/system.speed.da out/show.text.file.da out/show.image.file.da out/show.font.file.da
make[1]: Leaving directory '/Users/wyattwong/Downloads/a2d/desk.acc'
cleaning selector
make[1]: Entering directory '/Users/wyattwong/Downloads/a2d/selector'
rm -f out/*.o
rm -f out/*.list
rm -f out/selector.built
make[1]: Leaving directory '/Users/wyattwong/Downloads/a2d/selector'
wyattwong@MacBookPro a2d % make
Building: desktop
make[1]: Entering directory '/Users/wyattwong/Downloads/a2d/desktop'
ca65 --target apple2enh --list-bytes 0 --listing out/desktop.list -o out/desktop.o desktop.s
ld65 --config ../res/asm.cfg -o 'out/desktop.built' out/desktop.o
make[1]: Leaving directory '/Users/wyattwong/Downloads/a2d/desktop'
make desktop good
Building: desktop.system
make[1]: Entering directory '/Users/wyattwong/Downloads/a2d/desktop.system'
ca65 --target apple2enh --list-bytes 0 --listing out/desktop.system.list -o out/desktop.system.o desktop.system.s
ld65 --config ../res/asm.cfg -o 'out/desktop.system.SYS' out/desktop.system.o
xattr -wx prodos.AuxType '00 20' out/desktop.system.SYS
rm out/desktop.system.o
make[1]: Leaving directory '/Users/wyattwong/Downloads/a2d/desktop.system'
make desktop.system good
Building: desk.acc
make[1]: Entering directory '/Users/wyattwong/Downloads/a2d/desk.acc'
ca65 --target apple2enh --list-bytes 0 --listing out/calculator.list -o out/calculator.o calculator.s
ld65 --config ../res/asm.cfg -o 'out/calculator.da' out/calculator.o
ca65 --target apple2enh --list-bytes 0 --listing out/date.list -o out/date.o date.s
ld65 --config ../res/asm.cfg -o 'out/date.da' out/date.o
ca65 --target apple2enh --list-bytes 0 --listing out/puzzle.list -o out/puzzle.o puzzle.s
ld65 --config ../res/asm.cfg -o 'out/puzzle.da' out/puzzle.o
ca65 --target apple2enh --list-bytes 0 --listing out/sort.directory.list -o out/sort.directory.o sort.directory.s
ld65 --config ../res/asm.cfg -o 'out/sort.directory.da' out/sort.directory.o
ca65 --target apple2enh --list-bytes 0 --listing out/this.apple.list -o out/this.apple.o this.apple.s
ld65 --config ../res/asm.cfg -o 'out/this.apple.da' out/this.apple.o
ca65 --target apple2enh --list-bytes 0 --listing out/eyes.list -o out/eyes.o eyes.s
ld65 --config ../res/asm.cfg -o 'out/eyes.da' out/eyes.o
ca65 --target apple2enh --list-bytes 0 --listing out/screen.dump.list -o out/screen.dump.o screen.dump.s
ld65 --config ../res/asm.cfg -o 'out/screen.dump.da' out/screen.dump.o
ca65 --target apple2enh --list-bytes 0 --listing out/run.basic.here.list -o out/run.basic.here.o run.basic.here.s
ld65 --config ../res/asm.cfg -o 'out/run.basic.here.da' out/run.basic.here.o
ca65 --target apple2enh --list-bytes 0 --listing out/key.caps.list -o out/key.caps.o key.caps.s
ld65 --config ../res/asm.cfg -o 'out/key.caps.da' out/key.caps.o
ca65 --target apple2enh --list-bytes 0 --listing out/find.files.list -o out/find.files.o find.files.s
ld65 --config ../res/asm.cfg -o 'out/find.files.da' out/find.files.o
ca65 --target apple2enh --list-bytes 0 --listing out/flying.toasters.list -o out/flying.toasters.o flying.toasters.s
ld65 --config ../res/asm.cfg -o 'out/flying.toasters.da' out/flying.toasters.o
ca65 --target apple2enh --list-bytes 0 --listing out/control.panel.list -o out/control.panel.o control.panel.s
ld65 --config ../res/asm.cfg -o 'out/control.panel.da' out/control.panel.o
ca65 --target apple2enh --list-bytes 0 --listing out/joystick.list -o out/joystick.o joystick.s
ld65 --config ../res/asm.cfg -o 'out/joystick.da' out/joystick.o
ca65 --target apple2enh --list-bytes 0 --listing out/melt.list -o out/melt.o melt.s
ld65 --config ../res/asm.cfg -o 'out/melt.da' out/melt.o
ca65 --target apple2enh --list-bytes 0 --listing out/invert.list -o out/invert.o invert.s
ld65 --config ../res/asm.cfg -o 'out/invert.da' out/invert.o
ca65 --target apple2enh --list-bytes 0 --listing out/system.speed.list -o out/system.speed.o system.speed.s
ld65 --config ../res/asm.cfg -o 'out/system.speed.da' out/system.speed.o
ca65 --target apple2enh --list-bytes 0 --listing out/show.text.file.list -o out/show.text.file.o show.text.file.s
ld65 --config ../res/asm.cfg -o 'out/show.text.file.da' out/show.text.file.o
ca65 --target apple2enh --list-bytes 0 --listing out/show.image.file.list -o out/show.image.file.o show.image.file.s
ld65 --config ../res/asm.cfg -o 'out/show.image.file.da' out/show.image.file.o
ca65 --target apple2enh --list-bytes 0 --listing out/show.font.file.list -o out/show.font.file.o show.font.file.s
ld65 --config ../res/asm.cfg -o 'out/show.font.file.da' out/show.font.file.o
rm out/joystick.o out/calculator.o out/find.files.o out/show.text.file.o out/show.image.file.o out/run.basic.here.o out/puzzle.o out/system.speed.o out/sort.directory.o out/date.o out/melt.o out/show.font.file.o out/this.apple.o out/invert.o out/control.panel.o out/screen.dump.o out/key.caps.o out/eyes.o out/flying.toasters.o
make[1]: Leaving directory '/Users/wyattwong/Downloads/a2d/desk.acc'
make desk.acc good
Building: selector
make[1]: Entering directory '/Users/wyattwong/Downloads/a2d/selector'
ca65 --target apple2enh --list-bytes 0 --listing out/selector.list -o out/selector.o selector.s
ld65 --config ../res/asm.cfg -o 'out/selector.built' out/selector.o
make[1]: Leaving directory '/Users/wyattwong/Downloads/a2d/selector'
make selector good
wyattwong@MacBookPro a2d %

**Comment by wyatt-wong** [comment]
wyattwong@MacBookPro a2d % make package
bin/package.sh
Building disk images
Catalog of 800k disk:
cadius v 1.4.5 (c) Brutal Deluxe 2011-2013.
  Name                  Type   Aux      Size     Data     Res  Data   Res  Sparse Index  Struct  Access    Creation Date     Modification Date
/A2.DESKTOP/
  BASIC.SYSTEM          SYS   $2000    10240    10240       0    20    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
  DESKTOP.SYSTEM        SYS   $0000     8192     8192       0    12    0      4     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
  DESKTOP2              $F1   $0000   114400   114400       0   216    0      8     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
  PRODOS                SYS   $0000    17128    17128       0    33    0      1     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
  READ.ME               TXT   $0000      156      156       0     1    0      0     0     Seed   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
  /DESK.ACC/
    CALCULATOR          $F1   $0640     3000     3000       0     6    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    EYES                $F1   $0640     1961     1961       0     4    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    FIND.FILES          $F1   $0640     3141     3141       0     7    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    KEY.CAPS            $F1   $0640     2490     2490       0     5    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    PUZZLE              $F1   $0640     2680     2680       0     6    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    RUN.BASIC.HERE      $F1   $0640      465      465       0     1    0      0     0     Seed   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    SCREEN.DUMP         $F1   $0640      345      345       0     1    0      0     0     Seed   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    SORT.DIRECTORY      $F1   $0640     1157     1157       0     3    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    THIS.APPLE          $F1   $0640     4356     4356       0     9    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    /CONTROL.PANELS/
      CONTROL.PANEL     $F1   $0640     4799     4799       0    10    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
      DATE              $F1   $0640     1863     1863       0     4    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
      JOYSTICK          $F1   $0640     1113     1113       0     3    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
      SYSTEM.SPEED      $F1   $0640     1076     1076       0     3    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    /SCREEN.SAVERS/
      FLYING.TOASTERS   $F1   $0640     1569     1569       0     4    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
      INVERT            $F1   $0640      176      176       0     1    0      0     0     Seed   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
      MELT              $F1   $0640      705      705       0     2    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
  /OPTIONAL/
    SELECTOR            $F1   $0000    39776    39776       0    77    0      1     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
  /PREVIEW/
    SHOW.FONT.FILE      $F1   $0640      975      975       0     2    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    SHOW.IMAGE.FILE     $F1   $0640     2256     2256       0     5    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    SHOW.TEXT.FILE      $F1   $0640     2288     2288       0     5    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
              Block : 1600     Free : 1127     File : 25     Directory : 5
Catalog of 140k disk 1:
cadius v 1.4.5 (c) Brutal Deluxe 2011-2013.
  Name                Type   Aux      Size     Data     Res  Data   Res  Sparse Index  Struct  Access    Creation Date     Modification Date
/A2.DESKTOP.1/
  DESKTOP.SYSTEM      SYS   $0000     8192     8192       0    12    0      4     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
  DESKTOP2            $F1   $0000   114400   114400       0   216    0      8     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
  READ.ME             TXT   $0000      156      156       0     1    0      0     0     Seed   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
            Block : 280     Free : 42     File : 3     Directory : 0
Catalog of 140k disk 2:
cadius v 1.4.5 (c) Brutal Deluxe 2011-2013.
  Name                  Type   Aux      Size     Data     Res  Data   Res  Sparse Index  Struct  Access    Creation Date     Modification Date
/A2.DESKTOP.2/
  /DESK.ACC/
    CALCULATOR          $F1   $0640     3000     3000       0     6    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    EYES                $F1   $0640     1961     1961       0     4    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    FIND.FILES          $F1   $0640     3141     3141       0     7    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    KEY.CAPS            $F1   $0640     2490     2490       0     5    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    PUZZLE              $F1   $0640     2680     2680       0     6    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    RUN.BASIC.HERE      $F1   $0640      465      465       0     1    0      0     0     Seed   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    SCREEN.DUMP         $F1   $0640      345      345       0     1    0      0     0     Seed   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    SORT.DIRECTORY      $F1   $0640     1157     1157       0     3    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    THIS.APPLE          $F1   $0640     4356     4356       0     9    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    /CONTROL.PANELS/
      CONTROL.PANEL     $F1   $0640     4799     4799       0    10    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
      DATE              $F1   $0640     1863     1863       0     4    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
      JOYSTICK          $F1   $0640     1113     1113       0     3    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
      SYSTEM.SPEED      $F1   $0640     1076     1076       0     3    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    /SCREEN.SAVERS/
      FLYING.TOASTERS   $F1   $0640     1569     1569       0     4    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
      INVERT            $F1   $0640      176      176       0     1    0      0     0     Seed   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
      MELT              $F1   $0640      705      705       0     2    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
  /OPTIONAL/
    SELECTOR            $F1   $0000    39776    39776       0    77    0      1     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
  /PREVIEW/
    SHOW.FONT.FILE      $F1   $0640      975      975       0     2    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    SHOW.IMAGE.FILE     $F1   $0640     2256     2256       0     5    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
    SHOW.TEXT.FILE      $F1   $0640     2288     2288       0     5    0      0     1     Sapl   RWBND    18-Dec-2020 22:10   18-Dec-2020 22:10  
              Block : 280     Free : 93     File : 20     Directory : 5
wyattwong@MacBookPro a2d %

**Comment by wyatt-wong** [comment]
After rename A2DeskTop.po to A2DeskTop.2mg and started Virtual ][![image](https://user-images.githubusercontent.com/10095648/102636169-46452f00-418f-11eb-9e80-fd25dbcd0061.png)

**Comment by wyatt-wong** [comment]
After rename A2DeskTop.2mg to A2DeskTop.hdv and start in Virtual ][
![image](https://user-images.githubusercontent.com/10095648/102636489-ac31b680-418f-11eb-8758-9aac9e2715b8.png)

**Comment by inexorabletash** [comment]
Please don't post giant logs that don't provide useful information.

**Comment by inexorabletash** [comment]
A little research would tell you that 2MG files are not just dumps of sectors like .PO and .HDV so a rename wouldn't work. (See cat/dog comment above)

If you were to modify the packaging script to specify 2MG, Cadius would create the file in the appropriate format.

I agree the various .po files are potentially confusing, for users who don't look at the file sizes or read the documentation. Maybe rename the 140k floppy files to .dsk and generate the 800k floppy as 2mg ? Are there compatibility problems with any emulators/devices?
