### ISSUE TITLE
Make Left Arrow / Right Arrow keypresses cycle items horizontally first and only then vertically in the format / erase dialog box

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#336]
As referenced in issue #328, make Left Arrow / Right Arrow keypresses cycle items horizontally first and only then vertically in the format / erase dialog box in Special > Format a Disk... and in Special > Erase a Disk..., the reverse of the current behavior with the Down / Up Arrows and what actually happens when cycling icons.

**Comment by c0mmander8** [comment]
That is, make Left Arrow keypresses go to the end of the previous row when reaching the beginning of the row and make Right Arrow keypresses go to the beginning of the next row when reaching the end of the row.

**Comment by c0mmander8** [comment]
That is, make Left Arrow keypresses go to the end of the previous row when reaching the beginning of the row you are currently on and make Right Arrow keypresses go to the beginning of the next row when reaching the end of the row you are currently on.

**Comment by inexorabletash** [comment]
This proposal doesn't appear to be solving a problem or usability issue. There is no user need being expressed here.

**Comment by c0mmander8** [comment]
This proposal and issue #337 are for greater user interface consistency.

**Comment by c0mmander8** [comment]
This issue and issue #337 are for greater user interface consistency throughout Apple II DeskTop. So, please reopen this issue and, as referenced above and in issue #328, make Left Arrow / Right Arrow keypresses cycle items horizontally first and only then vertically in the format / erase dialog box in Special > Format a Disk... and in Special > Erase a Disk..., the reverse of the current behavior with the Down / Up Arrows and what actually happens when cycling icons. That is, make Left Arrow keypresses go to the end of the previous row when reaching the beginning of the row that you are currently on and make Right Arrow keypresses go to the beginning of the next row when reaching the end of the row that you are currently on. This issue and issue #337 are for greater user interface consistency throughout Apple II DeskTop.

**Comment by c0mmander8** [comment]
This issue and issue #337 are for greater user interface consistency and uniformity throughout Apple II DeskTop. So, please reopen this issue and, as referenced above and in issue #328, make Left Arrow / Right Arrow keypresses cycle items horizontally first and only then vertically in the format / erase dialog box in Special > Format a Disk... and in Special > Erase a Disk..., the reverse of the current behavior with the Down / Up Arrows and what actually happens when cycling icons. That is, make Left Arrow keypresses go to the end of the previous row when reaching the beginning of the row that you are currently on and make Right Arrow keypresses go to the beginning of the next row when reaching the end of the row that you are currently on. This issue and issue #337 are for greater user interface consistency and uniformity throughout Apple II DeskTop.

**Comment by I3arana** [comment]
Why are you always repeating yourself? Are you an adult, or a child who wants to get his own way? poor form.
 Suggest you do the work yourself and submit apull request. Instead of harassing the lead on this. Yes Harassing.

**Comment by c0mmander8** [comment]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that the user interface is not consistent and uniform between what Left Arrow / Right Arrow keypresses do and what Down Arrow / Up Arrow keypresses do.

**Describe the solution you'd like**
Please reopen this issue and, as referenced above and in issue #328, make Left Arrow / Right Arrow keypresses cycle items horizontally first and only then vertically in the format / erase dialog box in Special > Format a Disk... and in Special > Erase a Disk..., the reverse of the current behavior with Down Arrow / Up Arrow keypresses and what actually happens when cycling icons. That is, make Left Arrow keypresses go to the end of the previous row when reaching the beginning of the row that you are currently on and make Right Arrow keypresses go to the beginning of the next row when reaching the end of the row that you are currently on.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
This issue and issue #337 are for greater user interface consistency and uniformity throughout Apple II DeskTop.

**Comment by c0mmander8** [comment]
Please reopen this issue as well, just like you did with issue #337.

**Comment by c0mmander8** [comment]
I see that this issue was fixed in commit 385d374.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/108013411-83c40e00-6fc0-11eb-9c1e-6e745a26c245.png)

Please stop spamming the issue tracker with redundant information.
