### ISSUE TITLE
Make Left Arrow / Right Arrow keypresses cycle items horizontally first and only then vertically in the Selector dialog box

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#337]
As referenced in issue #332, make Left Arrow / Right Arrow keypresses cycle items horizontally first and only then vertically in the Selector dialog box in Selector > Edit an Entry..., in Selector > Delete an Entry..., in Selector > Run an Entry... and when booting up the Selector directly at startup, the reverse of the current behavior with the Down / Up Arrows and what actually happens when cycling icons.

**Comment by c0mmander8** [comment]
That is, make Left Arrow keypresses go to the end of the previous row when reaching the beginning of the row and make Right Arrow keypresses go to the beginning of the next row when reaching the end of the row.

**Comment by c0mmander8** [comment]
That is, make Left Arrow keypresses go to the end of the previous row when reaching the beginning of the row you are currently on and make Right Arrow keypresses go to the beginning of the next row when reaching the end of the row you are currently on.

**Comment by inexorabletash** [comment]
This proposal doesn't appear to be solving a problem or usability issue. There is no user need being expressed here.

**Comment by c0mmander8** [comment]
This proposal and issue #336 are for greater user interface consistency.

**Comment by c0mmander8** [comment]
This issue and issue #336 are for greater user interface consistency throughout Apple II DeskTop. So, please reopen this issue and, as referenced above and in issue #332, make Left Arrow / Right Arrow keypresses cycle items horizontally first and only then vertically in the Selector dialog box in Selector > Edit an Entry..., in Selector > Delete an Entry..., in Selector > Run an Entry... and when booting up the Selector directly at startup, the reverse of the current behavior with the Down / Up Arrows and what actually happens when cycling icons. That is, make Left Arrow keypresses go to the end of the previous row when reaching the beginning of the row that you are currently on and make Right Arrow keypresses go to the beginning of the next row when reaching the end of the row that you are currently on. This issue and issue #336 are for greater user interface consistency throughout Apple II DeskTop.

**Comment by c0mmander8** [comment]
This issue and issue #336 are for greater user interface consistency and uniformity throughout Apple II DeskTop. So, please reopen this issue and, as referenced above and in issue #332, make Left Arrow / Right Arrow keypresses cycle items horizontally first and only then vertically in the Selector dialog box in Selector > Edit an Entry..., in Selector > Delete an Entry..., in Selector > Run an Entry... and when booting up the Selector directly at startup, the reverse of the current behavior with the Down / Up Arrows and what actually happens when cycling icons. That is, make Left Arrow keypresses go to the end of the previous row when reaching the beginning of the row that you are currently on and make Right Arrow keypresses go to the beginning of the next row when reaching the end of the row that you are currently on. This issue and issue #336 are for greater user interface consistency and uniformity throughout Apple II DeskTop.

**Comment by c0mmander8** [comment]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that the user interface is not consistent and uniform between what Left Arrow / Right Arrow keypresses do and what Down Arrow / Up Arrow keypresses do.

**Describe the solution you'd like**
Please reopen this issue and, as referenced above and in issue #332, make Left Arrow / Right Arrow keypresses cycle items horizontally first and only then vertically in the Selector dialog box in Selector > Edit an Entry..., in Selector > Delete an Entry..., in Selector > Run an Entry... and when booting up the Selector directly at startup, the reverse of the current behavior with Down Arrow / Up Arrow keypresses and what actually happens when cycling icons. That is, make Left Arrow keypresses go to the end of the previous row when reaching the beginning of the row that you are currently on and make Right Arrow keypresses go to the beginning of the next row when reaching the end of the row that you are currently on.
**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
This issue and issue #336 are for greater user interface consistency and uniformity throughout Apple II DeskTop.

**Comment by inexorabletash** [comment]
FWIW, here's a better way to describe the request:

**Steps to reproduce**
1. Start Desktop, populate Selector with multiple items in both run lists (first 8 and next 16)
2. Launch Selector > Edit an Entry... (or Delete an Entry... or Run an Entry...)
3. Press right arrow. Item in first row, first column is selected.
4. Press right arrow. Item in first row, second column is selected.
5. Press right arrow. Item in first row, third column is selected.
6. Press right arrow one more time.

**Expected behavior**
Selection wraps to first column in the _second_ row, much as vertical arrows wrap to the prev/next column.

**Actual behavior**
Selection wraps to first column in the _first_ row.

Keep sentences short. Give step-by-step instructions on how to reproduce the issue. Describe the expected and actual behavior to make

**Comment by c0mmander8** [comment]
What else were you going to say when you were cutoff?

**Comment by c0mmander8** [comment]
What else were you going to say when you were cut off?

**Comment by c0mmander8** [comment]
As referenced in issue #328 and issue #336, do not forget to change the Left Arrow / Right Arrow keypress behavior in the format / erase dialog box in Special > Format a Disk... and in Special > Erase a Disk..., too.

**Comment by inexorabletash** [comment]
Yep, just ran out of time.

**Comment by inexorabletash** [comment]
> What else were you going to say when you were cutoff?

> What else were you going to say when you were cut off?

Comments can be edited. Please do not repeat comments, either to get more attention on them, or in lieu of edits. This is your final warning on this behavior. Failure to comply will result in a 30 day ban.

**Comment by c0mmander8** [comment]
As referenced in issue #291, I have been unable to edit the titles of my issues, edit my issues and edit / delete my comments since November. That is why I have been duplicating / repeating my comments since then instead of editing / deleting them, as I did repeatedly during July, August and September. I am sorry for the visual pollution duplicating / repeating my comments causes, as well as the spam email this creates, just as the excessive editing of the titles of my issues, editing of my issues and editing / deleting of my comments caused over this past summer.
I will be more respectful and I will no longer duplicate / repeat my comments for corrections of typographical and / or grammatical errors, such as the example you cited above. But, I sometimes forget some information that is important to an issue or a comment, and that added information sometimes cannot simply be issued as a comment all by itself without the added information lacking important context clues about where it belongs in the parent issue or comment. In this scenario, I am forced to reissue the entire issue or comment as a new comment with the added information included in its proper spot. Please do not ban me for the continued use of this kind of duplicate / repeat comments.

**Comment by inexorabletash** [comment]
Re: " I have been unable to edit the titles of my issues" - you should attempt to understand why. Make sure you are using an up-to-date browser.

**Comment by c0mmander8** [comment]
I see that this issue was fixed in commit cabf2c3.
