### ISSUE TITLE
The return symbol in File > Rename... should be directly below the "I" in File > Get Info

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#343]
The return symbol in File > Rename... should be directly below the "I" in File > Get Info instead of directly below the Open-Apple symbol in File > Get Info because the return key is not a modifier key and is equivalent to a letter key and also because keyboard shortcuts in menus should be flush right.

**Comment by I3arana** [comment]
Fork mate, when were you diagnosed OCD?

**Comment by inexorabletash** [comment]
I appreciate the attention to detail.

MGTK has the accelerators left-aligned within a column, which explains the current appearance. Adjusting this would add more code than is justified.
