### ISSUE TITLE
After attempting to format/erase a drive without a disk, file dialog boxes are blank

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#345]
After attempting to format or erase a phantom drive at s5d1, s5d2, s6d1 or s6d2 that does not exist in Special > Format a Disk... or in Special > Erase a Disk... in Apple II Desktop 1.2 (Pre-)Alpha 23 (the latest version of the program) on GSplus 0.14 (the latest version of the program), the file dialog boxes in File > Copy a File..., in File > Delete a File..., in Selector > Add an Entry... and in Selector > Edit an Entry... are blank until I reboot.

**Comment by inexorabletash** [comment]
This reproduces in Virtual II as well. I'll simplify the bug title.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/103142203-37d9a480-46b4-11eb-91d3-b49ca0022984.png)

Great find on this bug!
