### ISSUE TITLE
The vertical scrollbar appears where it did not exist before after a window refreshes

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#347]
The vertical scrollbar with its scrollbar thumb appears where it did not exist before after a window refreshes after doing one of the following: creating a new folder, renaming an icon or deleting an icon or a group of icons. Clicking on the vertical scrollbar makes the vertical scrollbar with its scrollbar thumb disappear. The vertical scrollbar with its scrollbar thumb should not appear at all in this scenario.

**Comment by inexorabletash** [comment]
Same root cause as #348
