### ISSUE TITLE
Vertical scrollbar appears unnecessarily when window is shown/refreshed

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#348]
The vertical scrollbar with its scrollbar thumb appears when there is between 11 to 15 icons in a window and there is nothing hidden to scroll for in the window. Clicking on the vertical scrollbar or moving its scrollbar thumb down / up all the way only moves the window down / up a few millimeters in total and only shows extra white space. The vertical scrollbar with its scrollbar thumb should not appear at all in this scenario.

**Comment by c0mmander8** [comment]
The vertical scrollbar with its scrollbar thumb appears when a window is its default size, there is between 11 to 15 icons in the window and there is nothing hidden to scroll for in the window. Clicking on the vertical scrollbar or moving its scrollbar thumb down / up all the way only moves the window down / up a few millimeters in total and only shows extra white space. The vertical scrollbar with its scrollbar thumb should not appear at all in this scenario.

**Comment by inexorabletash** [comment]
Please use the issue template for filing issues, and follow the template structure for reporting repro steps and expected/actual behavior.

This behavior (the scrollbar appearing active even if unnecessary) was around in 1.1. I always found it irritating, so thank you for filing a bug to track it.

**Comment by inexorabletash** [comment]
The behavior in 1.1 was somewhat different; the change in 1.2 is that icons are not all the same height which affects the bbox calculation. But the same unnecessary scrollbar appearance problem occurred.

**Comment by inexorabletash** [comment]
Another scroll weirdness:

1. Set up a window like this: 
![image](https://user-images.githubusercontent.com/771547/103729757-f8edfd80-4f95-11eb-8b38-d6ec2ed392d2.png)

2. Drag the icon to the left: 
![image](https://user-images.githubusercontent.com/771547/103729774-05725600-4f96-11eb-9078-40d22182f177.png)
(note: text vanishes!) 

3. Click in the scrollbar track:
![image](https://user-images.githubusercontent.com/771547/103729847-2c308c80-4f96-11eb-9e7f-d59da0d08eb2.png)
(note: icon vanishes completely!)

**Comment by c0mmander8** [comment]
Please reopen this issue. This issue still occurs when you open a new window and immediately afterward you create a new folder in Apple II DeskTop 1.2 Alpha 26.
