### ISSUE TITLE
Allow instantly moving files and folders without copying them first

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#350]
Allow instantly moving files and folders directly from their origin to their destination without copying them first, just like the Mac and the IIGS.

**Comment by c0mmander8** [comment]
Why not?

**Comment by c0mmander8** [comment]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when it takes so long for Apple II DeskTop to move files and folders from their origin to their destination.

**Describe the solution you'd like**
Please reopen this issue and, as referenced above, allow instantly moving files and folders directly from their origin to their destination without copying them first, just like the Mac and the IIGS.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
There is no other context or screenshots about this feature request here.

**Comment by inexorabletash** [comment]
The reason behind the current behavior is that ProDOS doesn't support a "move" operation, where a file is relocated without being rewritten. It could be done by altering the file entries in the containing directories, but this be a lot more code and would not be supported on network devices. (Admittedly that's a rare case.)

**Comment by c0mmander8** [comment]
I think that altering the file entries in the containing directories should be done because moving files and folders are essential tasks of a file manager such as Apple II DeskTop.

**Comment by c0mmander8** [comment]
Please reopen this issue as well, just like you did with issue #351.

**Comment by c0mmander8** [comment]
I think that altering the file entries in the containing directories should be done because moving files and folders are essential tasks of a file manager such as Apple II DeskTop. But keep the current behavior for network devices though. I do not want you to take away any existing features.

**Comment by c0mmander8** [comment]
Please reopen this issue as well, just like you did with issue #351.

**Comment by I3arana** [comment]
This is the straw that brake the camels back. I wont be seeing this behaviour clogging my inbox anymore.

**Comment by c0mmander8** [comment]
Please reopen this issue. I still think that this issue is an important issue to be implemented because this would greatly increase the usability of Apple II DeskTop.
