### ISSUE TITLE
Support writable GS/OS and AppleWorks filename casing

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#352]
**Is your feature request related to a problem? Please describe.**
The following functionality is affected:

* File > Rename
* Copying and Moving files (either via dialog or drag/drop)

**Sample Repro**
1. In ProDOS 2.5 create a file named e.g. "AaBbCcDd"
2. Boot ProDOS 2.4
3. In DeskTop, rename it to "WWXXYYZZ"

Expect: File shows as either "WWXXYYZZ" (maintaining case) or "Wwxxyyzz" (normal case adjustment)

Actual: File shows as "WwXxYyZz", since the case bits are untouched by 2.4

This should be done for AppleWorks (AWP/ASP/ADB) files as well, which encode the case bits in the aux type instead (byte-swapped)

**Describe the solution you'd like**
As referenced in issue #187, support writable GS/OS (ProDOS 2.5.x) filename casing and, where applicable, support writable AppleWorks filename casing when renaming and copying files, when renaming and copying files, when creating, renaming and copying folders and when formatting, erasing and renaming volumes, both on ProDOS 2.5.x and on ProDOS 2.4.x and earlier, just like the later IIGS and the later Mac.

**Cases**

* [x] AppleWorks file rename
* [x] AppleWorks file duplicate
* [ ] GS/OS file rename
* [ ] GS/OS file duplicate
* [ ] GS/OS file copy/move
* [ ] GS/OS volume rename

Other:

* AppleWorks file copy is already supported, since the case bits are in the AuxType which is copied.
* Arguably, GS/OS file duplicate and copy do not need handling; the case bits are in the Version, which is zeroed.

**Comment by inexorabletash** [comment]
AppleWorks is more doable than GS/OS, since AppleWorks name bits are in the AuxType field and can be set with a SET_FILE_INFO call. GS/OS naming lives in the version/minversion entries which requires modifying the directory entries.

**Comment by inexorabletash** [comment]
Merging into #187

**Comment by c0mmander8** [comment]
Maybe this issue should be reopened and issue #187 should be merged into this issue instead of closing this issue? This issue covers all the aspects of issue #187, but this issue is more expansive and comprehensive in scope.

**Comment by inexorabletash** [comment]
AppleWorks files should copy/move and preserve case bits, since those are stored in AuxType field which is copied.

So the distinct cases that aren't handled are at least:

* GS/OS file copy/move
* GS/OS volume rename
* GS/OS file rename
* AppleWorks file rename

I'm not sure if the code paths for dragging a volume onto another volume/info a folder are distinct.

Of these, AppleWorks file rename should be straightforward, as that can be done with `SET_FILE_INFO` call.

The GS/OS cases would require scanning directory blocks and manipulating the respective FileEntry structure. This will be significant work, so I don't expect to get to it any decade soon. Alternately, just run DeskTop under ProDOS 2.5, which should preserve case in such operations.

**Comment by inexorabletash** [comment]
Additional cases: 

* [ ] Duplicating GS/OS files
* [ ] Duplicating AppleWorks files

**Comment by c0mmander8** [comment]
"AppleWorks duplicate" should be edited to instead be "AppleWorks file duplicate", both in my first comment posted on December 30, 2020 opening this issue (the first comment in this issue overall), which was later edited by you, which is located at the top of this issue and also in your fourth comment in this issue (the sixth comment in this issue overall), which was just posted on March 29, 2022, which is located just one comment above this comment in this issue, for greater clarity in this issue and in order to match the other, both already existing and proposed new, "AppleWorks file" and "GS/OS file" entries in this issue.

Further additional cases to be added to my first comment posted on December 30, 2020 opening this issue (the first comment in this issue overall), which was later edited by you, which is located at the top of this issue:

* AppleWorks file copy via the File > Copy a File... dialog box
* AppleWorks file copy or move via drag and drop

Cases to replace "GS/OS file copy/move", both in my first comment posted on December 30, 2020 opening this issue (the first comment in this issue overall), which was later edited by you, which is located at the top of this issue and also in your third comment in this issue (the fifth comment in this issue overall), which was posted on January 22, 2021, which is located two comments above this comment in this issue, for greater clarity in this issue and in order to match the proposed new, "AppleWorks file copy" entries in this issue.

* GS/OS file copy via the File > Copy a File... dialog box
* GS/OS file copy or move via drag and drop

**Comment by inexorabletash** [comment]
The new `GetFileEntryBlock` proc in desktop/main.s is a building block that can be used for this.

**Comment by inexorabletash** [comment]
I'm going to call this "done", although it's not following the behavior that the issue summary suggests.

AppleWorks files: 
* File rename or duplicate - the new case bits are applied. You can't have an AppleWorks file without case bits (from the perspective of AppleWorks) so this is necessary to avoid surprises.
* File moves or copies - the old case bits are retained.

Other files and volumes:
* File rename, duplicate, or copy - the case bits are cleared. From a GS/OS perspective this means the file will be all uppercase. DeskTop will apply case heuristics.
* File move - if on the same volume the case bits are retained. If on a different volume this is effectively a copy/delete, and the case bits are cleared.
* Volume rename - the case bits are cleared. From a GS/OS perspective this means the file will be all uppercase. DeskTop will apply case heuristics.

The reason GS/OS case bits are not applied is that I believe that most of the time A2D users are thinking like IIe/IIc ProDOS-8 users and keep Caps Lock down 99% of the time. When entering a filename they type in uppercase and rely on A2D's recasing heuristics to make the name more attractive. If we always applied case bits, then any file you renamed would end up in ALL.CAPS which is ugly.

**Comment by inexorabletash** [comment]
Although I believe the current state is acceptable, some things which could be revisited in the future:

* When copying files (or moving across volumes), there isn't an obvious downside to applying the case bits to the destination. In the copy code, `TryCreateDst` could do this, given a convenient `GetFileInfoEx` / `SetFileInfoEx` impl.
* Applying case bits on rename (file or volume) or duplicate (file) could be made an option.

**Comment by inexorabletash** [comment]
Update:

* When copying files, case bits are now preserved.
* There's a new setting in the Options control panel to allow preserving case when naming a file or disk (File > New Folder, File > Rename, File > Duplicate, Special > Format Disk, Special > Erase Disk)
