### ISSUE TITLE
Allow moving or copying a file or a folder from an underlying inactive window to the active window

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#353]
**Describe the bug**
When I have overlapping windows open, I am unable to move or copy a file or a folder from an underlying inactive window to the active window, just like the early Mac and the early IIGS. 

**To Reproduce**
1. Start Apple II DeskTop.
2. Open overlapping windows.
3. Choose a window to be the active window.
4. Try to move or copy a file or a folder from an underlying inactive window to the active window.
5. The respective underlying inactive window instantly becomes the active window and covers up the formerly active window preventing me from moving or copying the respective file or the respective folder to the formerly active window.

**Expected behavior**
When I have overlapping windows open, I should be able to move or copy a file or a folder from an underlying inactive window to the active window, just like the later Mac and the later IIGS.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem. 

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 (Pre-)Alpha 23 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
It is a serious user impediment to not be able to move a file or a folder from one window to another window in certain overlapping window scenarios.

**Comment by inexorabletash** [comment]
This would require significant rewrites to MGTK to support interaction with inactive windows, including both hit testing and rendering into background windows. As such, I consider it out of scope for this project. 

I agree it's frustrating, but it's not going to happen without a complete rewrite.

**Comment by c0mmander8** [comment]
What does "hit testing and rendering into background windows" mean? Please reopen this issue. I still think that this issue is an important issue to be implemented because this would greatly increase the usability of Apple II DeskTop. Even if you decide not to reopen this issue, please answer my question at the beginning of this comment.

**Comment by inexorabletash** [comment]
I value your attention to detail and passion for this project. 

However, mass updating bugs with "Please reopen this issue...." (I count 10 today) is not going to be tolerated.

"hit testing" = determining what was clicked on
"rendering" = drawing
"background window" = not the topmost/active window

**Comment by ph0enix-c0der** [comment]
Now that you are allowed to move or copy a file or a folder from an active window to a folder located inside an inactive window as a result of issue #418 being fixed, please reopen this issue and please fix this issue. I thank you in advance.
