### ISSUE TITLE
Freeze on keypress on Apple IIc+ under MAME 0.227

### ISSUE THREAD

**Issue by inexorabletash** [a2stuff/a2d#358]
**Describe the bug**
Pressing any key seems to beep, and freeze the system on an emulated IIc Plus.

**To Reproduce**
1. Start DeskTop
2. Press any key (e.g. Escape)

**System Details (please complete the following information):**
 - Apple IIc Plus
 - MAME (via Ample) 0.227

It's possible that this is an emulation issue; should verify on real hardware.

**Comment by inexorabletash** [comment]
Does not reproduce on real hardware.

**Comment by inexorabletash** [comment]
It's crashing to the monitor. Switching to text mode, it's crashing here:
```
EBBD- M=BA A=2D X=C5 Y=89 P=F5 S=82
```
FWIW, $5FA (TYPHED) is 0 so it's not typeahead buffer...

**Comment by inexorabletash** [comment]
Hey @mgcaret - any guesses?

**Comment by mgcaret** [comment]
It’s probably an emulation issue.  MAME’s IIc code could use some work.  Things like a soft switch is being hit on a read when it’s supposed to only be affected by a write.  I’d be willing to bet it’s something like that.

**Comment by inexorabletash** [comment]
@rb6502 - I think you've been working on the apple2cp implementation? What's the best way to report or track this?

**Comment by rb6502** [comment]
Hi!  Please open an issue under mamedev/mame, and feel free to link this one.

**Comment by rb6502** [comment]
@mgcaret Can you point out which soft switches are write-only that aren't in MAME?  I'd appreciate it.

**Comment by mgcaret** [comment]
@rb6502 I just did a cursory look and it seems that the code has been reorganized and unified with the IIe code since I last looked.  So maybe I am off-base with this.   I’ll take a look tonight and see if I can spot anything.  I’ll also build myself a fresh copy and confirm the crash.

**Comment by rb6502** [comment]
I've confirmed the crash.  Interestingly it happens on the 32K ROM IIc versions, but not the original 16K ROM.  Unfortunately poking around the $C028 ROMSWITCH hasn't helped.

**Comment by mgcaret** [comment]
Okay, that eliminates IIc+-specific behavior, which is good because we don't have firmware source for that.

**Comment by mgcaret** [comment]
Soft switches in the current MAME code appear to be fine.

I have source code that can build all four non-Plus IIc ROMs (via conditionals, so I have .if ROM_VER > 2 for instance).  I've looked at all the sections that are different and nothing jumps out at me there.

**Comment by inexorabletash** [comment]
Fixed in MAME. Thanks, @rb6502 !

**Comment by mgcaret** [comment]
Hah, I just rebuilt MAME a few minutes before the fix was committed.  If I'd updated my local copy a few minutes later I'd have been very confused at not replicating the crash...
