### ISSUE TITLE
Apple-clicking on an already selected icon does not unselect the icon

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#359]
**Describe the bug**
Apple-clicking on an already selected icon does not unselect the icon.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open a window.
3. Select multiple icons.
4. Apple-click on an already selected icon.
5. The icon should be unselected, but the icon is still selected.

**Expected behavior**
Apple-clicking on an already selected icon should unselect the icon, just like Shift-clicking on an already selected icon does on the Mac and the IIGS.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem. 

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 (Pre-)Alpha 23 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
I

**Comment by c0mmander8** [comment]
As referenced in issue #340 and issue #373, also apply this issue to Shift-clicking.

**Comment by c0mmander8** [comment]
I see that this issue was fixed in commit a46f46a.
