### ISSUE TITLE
The file selection of multiple icons is garbled after switching into and out of list view

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#360]
**Describe the bug**
The file selection of multiple icons is garbled after switching into and out of list view.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open a window.
3. Go to and select File > Select All.
4. Switch into list view.
5. Switch back into icon view.
6. The file selection of all icons is garbled.

**Expected behavior**
The file selection of multiple icons is restored back to the same state it was in before entering list view.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 (Pre-)Alpha 23 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Thank you for the bug report with clear repro steps. (We need to figure out how to get screenshots working for you - every OS supports grabbing part of the screen to the clipboard and you can just paste into the edit box)

I can reproduce, but I'm using real hardware at the moment so screenshots are harder. :) The selection is apparently preserved across view changes, visible if you use File > Get Info when in the list view or garbled icon state. It *should* be cleared when the view is changed.

**Comment by c0mmander8** [comment]
I think that the file selection should be preserved when the view is changed into list view and back again into icon view, but that the file selection should be preserved properly in this scenario. This is useful for quick glimpses into list view for more information about something without having to reselect the file selection all over again.

**Comment by inexorabletash** [comment]
Without #28 being implemented, that would mean selection would cease to be visible which would be bad.

**Comment by c0mmander8** [comment]
What do you mean?

**Comment by inexorabletash** [comment]
If selection was maintained while in list view, operations would have unpredictable results. If you're suggesting that the set of selected icons be preserved but not actionable until view was switched back... that's significant work for a rare case and just supporting selection in list view is a better use of space/time.
