### ISSUE TITLE
All folders selected should open when one folder is double-clicked on

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#363]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I select multiple folders and only the folder I double-click on opens all by itself, just like the early Mac.

**Describe the solution you'd like**
All folders selected should open when one folder is double-clicked on, just like the later Mac and the IIGS. This should happen in the following order:

If you firstly select folder A, then, secondly select folder B and finally, thirdly select folder C: firstly folder A opens, then, secondly folder B opens and finally, thirdly folder C opens, and folder C finally becomes the active window.
If you firstly select folder A, then, secondly select folder C and finally, thirdly select folder B: firstly folder A opens, then, secondly folder C opens and finally, thirdly folder B opens, and folder B finally becomes the active window.
If you firstly select folder B, then, secondly select folder C and finally, thirdly select folder A: firstly folder B opens, then, secondly folder C opens and finally, thirdly folder A opens, and folder A finally becomes the active window.
If you firstly select folder B, then, secondly select folder A and finally, thirdly select folder C: firstly folder B opens, then, secondly folder A opens and finally, thirdly folder C opens, and folder C finally becomes the active window.
If you firstly select folder C, then, secondly select folder A and finally, thirdly select folder B: firstly folder C opens, then, secondly folder A opens and finally, thirdly folder B opens, and folder B finally becomes the active window.
If you firstly select folder C, then, secondly select folder B and finally, thirdly select folder A: firstly folder C opens, then, secondly folder B opens and finally, thirdly folder A opens, and folder A finally becomes the active window.
**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
There is no other context or screenshots about this feature request here.

**Comment by inexorabletash** [comment]
> There are no alternative solutions or features that I can think of for this scenario.

There's clearly an alternative: open each folder one by one

This is a rare enough scenario and the complexity doesn't justify the effort.

**Comment by c0mmander8** [comment]
Multiple folders can be opened at the same time in Apple II DeskTop by selecting multiple folders and then using the File > Open command or using the Apple-O or the Apple-Down Arrow keypress shortcuts.

**Comment by c0mmander8** [comment]
Please reopen this issue. I still think that this issue is an important issue to be implemented because this would greatly increase the usability of Apple II DeskTop.

**Comment by c0mmander8** [comment]
Please remove the "Won't Fix" label from this issue as I see that this issue was fixed in commit 75c1e57.

**Comment by inexorabletash** [comment]
Good catch.
