### ISSUE TITLE
Autoscroll windows when dragging icons

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#370]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that when I am dragging a rectangle to select an icon or multiple icons or when I am dragging an already selected icon or multiple icons, I am unable to select a location or a destination that is in an area of a window hidden by a scrollbar, whether it is in the same window or another window.

**Describe the solution you'd like**
When dragging a rectangle to select an icon or multiple icons or when dragging an already selected icon or multiple icons to an area of a window hidden by a scrollbar, whether it is in the same window or another window, the respective window should automatically scroll by itself in order to make the selection or the move / copy of the icon or multiple icons possible, just like the later Mac.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
This issue is extremely handy in scenarios where there are lots of icons in a window or in two windows.

**Comment by inexorabletash** [comment]
After pondering this for a long time, it really doesn't seem feasible. The experience would be terrible under ~4MHz, and the timing would be extremely sensitive. So closing, but "without prejudice" meaning if someone wants to tackle it and can deliver a reasonable implementation we'd definitely consider it.
