### ISSUE TITLE
Support having open multiple desk accessories at the same time

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#372]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that I have to close a desk accessory before I can open another desk accessory.

**Describe the solution you'd like**
Support having open multiple desk accessories at the same time, just like the Mac and the later IIGS.

**Describe alternatives you've considered**
Keep on closing a desk accessory before opening another desk accessory, just I have always done.

**Additional context**
There is no other context or screenshots about this feature request here.

**Comment by inexorabletash** [comment]
Would require a complete rewrite.
