### ISSUE TITLE
Make Shift-Apple-Tab keypress cycle backwards through open windows and allow Shift-clicking to select multiple contiguous and / or noncontiguous icons

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#373]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am using Apple II DeskTop on an Apple IIGS or on a Platinum Apple IIe and familiar keyboard shortcuts and actions from other platforms involving the Shift key do not work.

**Describe the solution you'd like**
As referenced in issue #230 and issue #340, as an extra bonus for those users of Apple II DeskTop using an Apple IIGS, a Platinum Apple IIe or any other model that can detect the Shift key being pressed, make Shift-Apple-Tab keypress cycle backwards through open windows in addition to the already existing Shift-Apple-` (Apple-~) keypress and allow Shift-clicking to select multiple contiguous and / or noncontiguous icons in addition to the already existing Apple-clicking, just like the Mac and the IIGS.

**Describe alternatives you've considered**
Keep on using Shift-Apple-` (Apple-~) keypress to cycle backwards through open windows and keep on Apple-clicking to select multiple contiguous and / or noncontiguous icons, just as I have always done.

**Additional context**
Despite the added inconsistent documentation, this issue is extremely handy for when I am using Apple II DeskTop on an Apple IIGS or on a Platinum Apple IIe and will be able to use the Shift-Apple-Tab keypress to cycle backwards through open windows without thinking about which keypress combination I have to use and will be able to Shift-click to select multiple contiguous and / or noncontiguous icons without thinking about which key I have to hold down, just like I do on other platforms.

**Comment by inexorabletash** [comment]
Filing a duplicate issue because you disagree with the previous resolution is unacceptable. Do not do so again or you will be banned.

**Comment by c0mmander8** [comment]
I see that the allow Shift-clicking to select multiple contiguous and / or noncontiguous icons in addition to the already existing Apple-clicking part of this issue was fixed in commit 68835d6.
