### ISSUE TITLE
A folder gives the wrong volume info header size information when launched from the Apple menu, the Selector menu or Selector > Run an Entry...

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#374]
**Describe the bug**
A folder gives the wrong volume info header size information when launched from the Apple menu, the Selector menu or Selector > Run an Entry....
**To Reproduce**
1. Start Apple II DeskTop.
2. Go to the Apple menu and select a folder.
3. The volume info header of the folder says "0K in disk" and "0K available".
4. Go to the Apple menu and select a folder located on volume A, which has "1,234K in disk" and "5,678K available".
5. The volume info header of the folder located on volume A says "0K in disk" and "0K available".
6. Double-click and open and then close the volume A icon located on the desktop. 
7. Go to the Apple menu and select a folder located on volume A.
8. The volume info header of the folder located on volume A says "1,234K in disk" and "5,678K available" correctly.
9. Double-click and open and then close the volume B, which has "9,012K in disk" and "3,456K available", icon located on the desktop.
10. Go to the Apple menu and select a folder located on volume A.
11. The volume info header of the folder located on volume A says "9,012K in disk" and "3,456K available".

**Expected behavior**
A folder gives the correct volume info header size information when launched from the Apple menu, the Selector menu or Selector > Run an Entry....
**Screenshots**
I am sorry. I have no screenshots to help explain my problem. 

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 (Pre-)Alpha 23 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment]
This issue might be related to issue #218. I do not know though.

**Comment by c0mmander8** [comment]
What about the volume A window giving the volume B volume info header information?

**Comment by inexorabletash** [comment]
That should be handled too.
