### ISSUE TITLE
The startup disk is not the default volume shown for File > Copy a File..., File > Delete a File... and Selector > Add an Entry... if there are two or more volumes mounted

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#375]
**Describe the bug**
The startup disk is not the default volume shown for File > Copy a File..., File > Delete a File... and Selector > Add an Entry... if there are two or more volumes mounted.

**To Reproduce**
1. Start Apple II DeskTop with only the startup disk mounted at s7d1.
2. Go to the File menu and click on File > Copy a File... or File > Delete a File... or go to the Selector menu and click on Selector > Add an Entry....
3. The startup disk is the default volume shown.
4. Quit Apple II DeskTop.
5. Restart Apple II DeskTop with the startup disk mounted at s7d1 and another volume mounted at s7d2.
6. Go to the File menu and click on File > Copy a File... or File > Delete a File... or go to the Selector menu and click on Selector > Add an Entry....
7. The non-startup volume is the default volume shown.

**Expected behavior**
The startup disk should be the default volume shown for File > Copy a File..., File > Delete a File... and Selector > Add an Entry... if there are two or more volumes mounted.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 (Pre-)Alpha 23 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
Long-time users might expect and prefer the current default volume behavior, so the current default volume behavior should continue to remain, as an option in the Control Panel.

**Comment by inexorabletash** [comment]
Devices are shown in `DEVLST` order. Reverse order might make more sense.

**Comment by inexorabletash** [comment]
This ended up being pretty easy. Thanks for filing this - it bothered me as well!
