### ISSUE TITLE
Use a comma when numbers are 4 or 5 digits long in Disk Copy

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#377]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that a comma is not used when numbers are 4 or 5 digits long in the "Error when reading block", "Blocks to transfer:", "Blocks Read:" and "Blocks Written:" dialog box strings and everywhere else in Facilities > Quick Copy and Facilities > Disk Copy in Disk Copy.

**Describe the solution you'd like**
Use a comma when numbers are 4 or 5 digits long in the "Error when reading block", "Blocks to transfer:", "Blocks Read:" and "Blocks Written:" dialog box strings and everywhere else in Facilities > Quick Copy and Facilities > Disk Copy in Disk Copy.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
There is no other context or screenshots about this feature request here.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/105569358-df6ae680-5cf5-11eb-9744-d0a9ce9f1e3f.png)

The leading padding is yucky, too.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/105608002-31435900-5d56-11eb-998b-00a944bb1a0c.png)

Or with larger numbers to show separator - obviously something is busted here but the numbers are okay!

![image](https://user-images.githubusercontent.com/771547/105608069-a1ea7580-5d56-11eb-946a-5317751aeb02.png)
