### ISSUE TITLE
Preview AppleWorks AWP word processor files and Apple IIGS Teach text editor files with Show Text File

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#382]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that I cannot double-click and preview AppleWorks AWP word processor files and Apple IIGS Teach text editor files with the Show Text File preview handler, preferably with all formatting intact if that is feasible and realistic, or use the Apple menu, the Selector menu or Selector > Run an Entry... to launch them.

**Describe the solution you'd like**
I should be able to double-click and preview AppleWorks AWP word processor files and Apple IIGS Teach text editor files with the Show Text File preview handler, preferably with all formatting intact if that is feasible and realistic, or use the Apple menu, the Selector menu or Selector > Run an Entry... to launch them.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
If this issue is implemented, create a specific icon in Apple II DeskTop for Apple IIGS Teach text editor files based on a black & white version of the existing IIGS Finder icon for Apple IIGS Teach text editor files.

**Comment by inexorabletash** [comment]
Supporting Teach files should be trivial - just add the type to the filter. Icons take up tremendous space though so they can share the normal text file icon:

http://www.1000bit.it/support/manuali/apple/technotes/ftyp/ftn.50.5445.html

For AWP there's a workaround which is to install STF as a normal DA. Claiming the type fully would prevent using BASIS.SYSTEM as a dispatcher for AW files, which is something I'd like to allow.

**Comment by inexorabletash** [comment]
This ended up not working, since ProDOS-8 is unable to interact with the files.

**Comment by c0mmander8** [comment]
Is it possible to claim the type fully for AppleWorks AWP word processor files while still allowing using BASIS.SYSTEM as a dispatcher for AW files?

**Comment by c0mmander8** [comment]
Please reopen this issue so that, as referenced above, I am able to double-click and preview AppleWorks AWP word processor files with the Show Text File preview handler, preferably with all formatting intact if that is feasible and realistic, or use the Apple menu, the Selector menu or Selector > Run an Entry... to launch them while still allowing using BASIS.SYSTEM as a dispatcher for AppleWorks files.
