### ISSUE TITLE
Attempting to preview an Apple IIGS Teach text editor file with the Show Text File preview handler opens a blank Show Text File window and freezes Apple II DeskTop

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#389]
**Describe the bug**
Attempting to preview an Apple IIGS Teach text editor file with the Show Text File preview handler opens a blank Show Text File window and freezes Apple II DeskTop.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open a window.
3. Double-click on an Apple IIGS Teach text editor file to preview it directly or first select an Apple IIGS Teach text editor file and then go to the Apple menu and select the Show Text File preview handler as a regular DA.
4. A blank Show Text File window opens and Apple II DeskTop freezes.

**Expected behavior**
Attempting to preview an Apple IIGS Teach text editor file with the Show Text File preview handler should open a Show Text File window filled with the contents of the Apple IIGS Teach text editor file and should not freeze Apple II DeskTop.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 25 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
This issue also occurred in previous (pre-)alphas of Apple II DeskTop when first selecting an Apple IIGS Teach text editor file and then going to the Apple menu and selecting the Show Text File preview handler as a regular DA.

**Comment by inexorabletash** [comment]
Can you attach a disk image containing a sample file?

**Comment by c0mmander8** [comment]
Sorry, I cannot attach a disk image containing a sample file. But I can explain how to obtain one. Download "Live.Install.po" from ftp://ftp.apple.asimov.net/pub/apple_II/images/gs/os/gsos/Apple_IIGS_System_6.0.4/ and mount the disk image. Open "Live.Install", the Apple IIGS System 6.0.4 Live Install disk, and attempt to preview any of the four included documentation files - whether you choose "Read.Me", "Shortcuts", "Whats.New" or "Reference", it does not matter. Apple II DeskTop will open a blank Show Text File window and freeze. By the way - if you try to copy any, some or all of the four included documentation files from "Live.Install", the Apple IIGS System 6.0.4 Live Install disk, to "A2.Desktop", the Apple II DeskTop 1.2 Alpha 25 disk, Apple II DeskTop will show a "System Error" dialog box and the copy will be cancelled.

**Comment by c0mmander8** [comment]
The "By the way - " part of this issue is similar to issue #390.

**Comment by inexorabletash** [comment]
ProDOS 8 hits an error trying to read the ProDOS 16 / GS/OS files. Maybe due to the fork. Not sure.

Anyway, I've removed the icon association for Teach files so previews won't be attempted.

Workaround: use GS/OS Finder instead
