### ISSUE TITLE
Attempting to manually copy all of the files from the Apple IIGS System 6.0.4 Live Install disk to a blank 32 MB volume is interrupted by a "System Error" dialog box and the copy is cancelled

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#390]
**Describe the bug**
Attempting to manually copy all of the files from the Apple IIGS System 6.0.4 Live Install disk to a blank 32 MB volume is interrupted by a "System Error" dialog box and the copy is cancelled.

**To Reproduce**
1. Download "Live.Install.po" from ftp://ftp.apple.asimov.net/pub/apple_II/images/gs/os/gsos/Apple_IIGS_System_6.0.4/ and mount the disk image.
2. Mount a blank 32 MB volume.
3. Start Apple II DeskTop.
4. Drag the "Live.Install" icon to the blank 32 MB volume icon.
5. The copy is interrupted by a "System Error" dialog box and the copy is cancelled.

**Expected behavior**
Attempting to manually copy all of the files from the Apple IIGS System 6.0.4 Live Install disk to a blank 32 MB volume completes successfully.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 25 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment]
This issue is similar to the "By the way - " part of issue #389.

**Comment by inexorabletash** [comment]
Appears that ProDOS 8 can't copy ProDOS 16/GS/OS files with multiple forks (e.g. the Teach files). Same thing applies to Copy II Plus - it shows an error trying to copy those files.

Workaround: use GS/OS Finder instead

Won't Fix.
