### ISSUE TITLE
Lowercase letters sorted after all uppercase letters in dialogs

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#391]
**Describe the bug**
Files and folders with filenames that contain lowercase letters, whether GS/OS (ProDOS 2.5.x) or AppleWorks, are shown only after all capital letters are shown instead of being shown alphabetically in the file dialog boxes located at File > Run a Program... in the Selector and at File > Copy a File..., File > Delete a File..., Selector > Add an Entry... and Selector > Edit an Entry... in Apple II DeskTop.

**To Reproduce**
1. Start the Selector.
2. Go to the File menu and select File > Run a Program....
3. Files and folders with filenames that contain lowercase letters, whether GS/OS (ProDOS 2.5.x) or AppleWorks, are shown only after all capital letters are shown instead of being shown alphabetically in the file dialog box.
4. Start Apple II DeskTop.
5. Go to the File menu and select File > Copy a File... or File > Delete a File... or go to the Selector menu and select Selector > Add an Entry... or Selector > Edit an Entry....
6. Files and folders with filenames that contain lowercase letters, whether GS/OS (ProDOS 2.5.x) or AppleWorks, are shown only after all capital letters are shown instead of being shown alphabetically in the file dialog box.

**Expected behavior**
Files and folders with filenames that contain lowercase letters, whether GS/OS (ProDOS 2.5.x) or AppleWorks, should be shown alphabetically instead of being shown only after all capital letters are shown in the file dialog boxes located at File > Run a Program... in the Selector and at File > Copy a File..., File > Delete a File..., Selector > Add an Entry... and Selector > Edit an Entry... in Apple II DeskTop.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 25 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Ah, collation issues. This is because in ASCII all the uppercase letters appear before all the lowercase letters, and sorting is done by ASCII code point.

(At least we don't have to worry about non-ASCII characters once localization is in, since those aren't supported in the ProDOS-8 filesystem.)
