### ISSUE TITLE
The volume info header of a folder selected from the Apple menu is garbled after opening a large volume

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#392]
**Describe the bug**
The volume info header of a folder selected from the Apple menu is garbled after opening a large volume.

**To Reproduce**
1. Download "Live.Install.po" from ftp://ftp.apple.asimov.net/pub/apple_II/images/gs/os/gsos/Apple_IIGS_System_6.0.4/ and mount the disk image.
2. Start Apple II DeskTop.
3. Double-click and open "Live.Install".
4. Go to the Apple menu and select "Control Panels".
5. The volume info header of "Control.Panels" is garbled.

**Expected behavior**
The volume info header of a folder selected from the Apple menu should not be garbled after opening a large volume.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 25 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
No repro. A screenshot would really help to show what you might be doing differently.

![image](https://user-images.githubusercontent.com/771547/107134526-add24d80-68a7-11eb-9c42-c4ecff97f2f6.png)

**Comment by c0mmander8** [comment]
The difference in reproducing this bug is that my startup disk is an 800K disk image.

**Comment by inexorabletash** [comment]
Thanks - this is why screenshots are very useful. They include subtle information that isn't captured. If you need assistance learning to make screenshots, I can provide google links to instructions for how to make screenshots on every major operating system. An alternative is taking photos of the screen using a smartphone.

I was able to repro this:
![image](https://user-images.githubusercontent.com/771547/107136073-17a52400-68b5-11eb-8a38-2978c4eb882a.png)

Full screenshot for context:
![image](https://user-images.githubusercontent.com/771547/107136065-0825db00-68b5-11eb-982f-21dfe2dca73c.png)

**Comment by inexorabletash** [comment]
Found the cause and a fix. 
![image](https://user-images.githubusercontent.com/771547/107136539-28579900-68b9-11eb-9f0b-2369515866ce.png)
