### ISSUE TITLE
Moving an icon from a window to a folder or another window causes a scrollbar or both scrollbars to appear unnecessarily

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#394]
**Describe the bug**
Moving an icon from a window to a folder or another window causes a scrollbar or both scrollbars to appear unnecessarily.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open a window or multiple windows.
3. Move an icon from a window to a folder or another window.
4. A scrollbar or both scrollbars appear unnecessarily.

**Expected behavior**
Moving an icon from a window to a folder or another window should not cause a scrollbar or both scrollbars to appear unnecessarily.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 25 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Thanks - this was a subtle one. Remember to keep titles concise.

Again, screenshots would be helpful to ensure I'm testing the same way and fixing the same bug.
