### ISSUE TITLE
Freezes with vertical black stripes copying disk with Disk Copy (not Quick Copy)

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#398]
**Describe the bug**
GSplus freezes with vertical black stripes on the screen when attempting to duplicate a disk using Facilities > Disk Copy in Disk Copy.

**To Reproduce**
1. Download "A2DeskTop_800k.2mg" from https://github.com/a2stuff/a2d/releases and mount the disk image.
2. Start Apple II DeskTop.
3. Go to the Special menu and select Special > Disk Copy....
4. Go to the Facilities menu and select Facilities > Disk Copy.
5. Attempt to duplicate "A2.Desktop" located at s7d1 to a disk located at s7d2.
6. GSplus freezes with vertical black stripes on the screen.

**Expected behavior**
GSplus should not freeze with vertical black lines on the screen when attempting to duplicate a disk using Facilities > Disk Copy in Disk Copy and the duplication of the disk should complete successfully.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 25 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
This issue also occurred in previous (pre-)alphas of Apple II DeskTop without the vertical black stripes on the screen.

**Comment by c0mmander8** [comment]
The vertical black stripes occur when one or both of the disks are 32MB volumes in Apple II DeskTop 1.2 Alpha 25. The vertical black stripes do not occur when both of the disks are 800K disks in Apple II DeskTop 1.2 Alpha 25. The reverse occurs in previous (pre-)alphas of Apple II DeskTop. The vertical black stripes occur in previous (pre-)alphas of Apple II DeskTop when both of the disks are 800K disks. The vertical black stripes do not occur in previous (pre-)alphas of Apple II DeskTop when one or both of the disks are 32MB volumes. GSplus freezes in all of these scenarios, though.

**Comment by inexorabletash** [comment]
Does Quick Copy have the same issue?

**Comment by inexorabletash** [comment]
Reproduces in Virtual ][.

**Comment by c0mmander8** [comment]
Quick Copy does not have the same issue.

**Comment by inexorabletash** [comment]
Thanks for identifying this. As usual, you don't need to write so much, although I appreciate your attention to detail.

Disk Copy still seems to have many, many issues, so further testing will be required.
