### ISSUE TITLE
"ESC" should be "Esc" in Find Files in Spanish in desk.acc/find.files.res.es

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#399]
"ESC" should be "Esc" in Find Files in Spanish in desk.acc/find.files.res.es.

**Comment by inexorabletash** [comment]
The translations are not ready for testing. Please do not file bugs until builds are released.

**Comment by c0mmander8** [comment]
I see that this issue was fixed in commit 50beafc.

**Comment by inexorabletash** [comment]
Yes, I'm doing extensive string cleanup and so filing bugs about strings right now isn't worthwhile. I fixed this before I saw you'd filed the bug. So hold off for now, please.
