### ISSUE TITLE
The space before the ellipsis should be removed from the following Disk Copy strings in all languages

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#400]
The space before the ellipsis should be removed from the following Disk Copy strings in all languages, including the recently posted Italian and Spanish translations:

"Formatting the disk ...." should be "Formatting the disk...."
"Writing .... " should be "Writing.... "
"Reading .... " should be "Reading.... "

**Comment by inexorabletash** [comment]
The translations are not ready for testing. Please do not file bugs until builds are released.

**Comment by c0mmander8** [comment]
This issue especially applies to the English original, not just the translations.

**Comment by c0mmander8** [comment]
I see that this issue was fixed in commit 8bdbffe.
