### ISSUE TITLE
"Escape" should be "Esc" in the following Disk Copy strings in all languages

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#401]
"Escape" should be "Esc" in the following Disk Copy strings in all languages, including the recently posted Italian and Spanish translations:

"Insert source disk or press Escape to cancel." should be "Insert source disk or press Esc to cancel."
"Insert destination disk or press Escape to cancel." should be "Insert destination disk or press Esc to cancel."

**Comment by inexorabletash** [comment]
The translations are not ready for testing. Please do not file bugs until builds are released.

**Comment by c0mmander8** [comment]
This issue especially applies to the English original, not just the translations.

**Comment by c0mmander8** [comment]
I see that this issue was fixed in commit 323f48b.
