### ISSUE TITLE
Update the default date in the Date DA to the build date

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#404]
**Is your feature request related to a problem? Please describe.**
The default date in the Date control panel on systems without a real-time clock is decades out of date.

**Describe the solution you'd like**
Automatically update the default date in the Date control panel on systems without a real-time clock to the current build date of Apple II DeskTop whenever a new build of Apple II DeskTop is released.

**Describe alternatives you've considered**
Keep updating the default date in the Date control panel on systems without a real-time clock decades into the future to the present date.

**Additional context**
This issue will make setting up a brand new installation of Apple II DeskTop on systems without a real-time clock faster and easier.

**Comment by inexorabletash** [comment]
Heh, I think it's kind of cute. This is what's hardcoded in `desk.acc/date.s`

```
day:    .byte   26              ; Feb 26, 1985
month:  .byte   2               ; The date this was written?
year:   .byte   85
```
