### ISSUE TITLE
Esc does not close alert dialog boxes that only have an OK button and error dialog boxes that only have an OK button in Apple II DeskTop, Disk Copy and the Selector

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#406]
Esc does not close alert dialog boxes that only have an OK button and error dialog boxes that only have an OK button in Apple II DeskTop, Disk Copy and the Selector.

**Comment by c0mmander8** [comment]
Esc should also close all other kinds of dialog boxes that only have an OK button in Apple II DeskTop, Disk Copy and the Selector.

**Comment by c0mmander8** [comment]
When I say "dialog boxes that only have an OK button", I mean, more generally, "dialog boxes that do not have a Cancel button".

**Comment by inexorabletash** [comment]
If you can find any more, please file a new bug with repro steps to reach the dialog.
