### ISSUE TITLE
"Remerciements @ : Alexis Gerard, Jim Gerber, Pat Pahl" in the French version of Apple II DeskTop should be "Remerciements @ : A. Gerard, J. Gerber, P. Pahl, J. Bernard"

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#407]
"Remerciements @ : Alexis Gerard, Jim Gerber, Pat Pahl" in the French version of Apple II DeskTop should be "Remerciements @ : A. Gerard, J. Gerber, P. Pahl, J. Bernard", just like all of the other language versions of Apple II DeskTop.

**Comment by inexorabletash** [comment]
Thanks. That came from the earlier MouseDesk strings.
