### ISSUE TITLE
RELEASE-NOTES.md string changes

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#408]
RELEASE-NOTES.md string changes:

"* Progress bar shown while loading, and when copying to RAM disk." should be 
"* Progress bar shown while loading, and when copying to RAM disk. ([#330](https://github.com/a2stuff/a2d/issues/330))".

"* Holding **Apple** while clicking a file deselects. ([#359](https://github.com/a2stuff/a2d/issues/359))" should be 
"* Holding **Apple** while clicking a selected file deselects the file. ([#359](https://github.com/a2stuff/a2d/issues/359))".

"* **Return** is a shortcut for **File > Rename...** ([#273](https://github.com/a2stuff/a2d/issues/273))" should be 
"* **Return** is a shortcut for **File > Rename...**. ([#275](https://github.com/a2stuff/a2d/issues/275))".

"* **File > New Folder** scrolls the new folder icon into view. ([#16](https://github.com/a2stuff/a2d/issues/16))" should be 
"* **File > New Folder...** scrolls the new folder icon into view. ([#16](https://github.com/a2stuff/a2d/issues/16))".

"* **File > Rename** dialog pre-filled with previous name. ([#156](https://github.com/a2stuff/a2d/issues/156))" should be 
"**File > Rename...** dialog pre-filled with previous name. ([#156](https://github.com/a2stuff/a2d/issues/156))".

"* **File > Get Info** and list views show file and volume sizes in KB rather than Blocks." should be 
"* **File > Get Info**, **Special > Get Size**, and list views show file and volume sizes in K rather than blocks. ([#308](https://github.com/a2stuff/a2d/issues/308))".

"* Progress bar shown on splash screen during launch." should be deleted because it is a duplicate of 
"* Progress bar shown while loading, and when copying to RAM disk.".

"* Show Text File DA: Keyboard support. Escape quits, arrows scroll. ([#4](https://github.com/a2stuff/a2d/issues/4))" should be 
"* Show Text File DA: Keyboard support. **Esc** quits, arrows scroll. ([#4](https://github.com/a2stuff/a2d/issues/4))".

"* Other executable files (SYS, BAS, BIN) can be launched from the Apple menu. ([#293](https://github.com/a2stuff/a2d/issues/293))" should be 
"* Other executable files (SYS, S16, BAS, BIN) and previewable files (TXT, FOT, BIN, FNT) can be launched from the Apple menu. ([#293](https://github.com/a2stuff/a2d/issues/293), [#295](https://github.com/a2stuff/a2d/issues/295))".

"* Allows editing the desktop pattern ([#31](https://github.com/a2stuff/a2d/issues/31)), double-click speed ([#2](https://github.com/a2stuff/a2d/issues/2)), mouse tracking speed ([#273](https://github.com/a2stuff/a2d/issues/273)), insertion point blink speed, and clock 12/24hr setting ([#220](https://github.com/a2stuff/a2d/issues/220))." should be 
"* Allows editing the desktop pattern ([#31](https://github.com/a2stuff/a2d/issues/31)), RGB color setting ([#284](https://github.com/a2stuff/a2d/issues/284)), mouse tracking speed ([#273](https://github.com/a2stuff/a2d/issues/273)), double-click speed ([#2](https://github.com/a2stuff/a2d/issues/2)), insertion point blink speed, and clock 12/24hr setting ([#220](https://github.com/a2stuff/a2d/issues/220)).".

"* Scrollbars no longer activate unnecessarily ([#366](https://github.com/a2stuff/a2d/issues/366), [#394](https://github.com/a2stuff/a2d/issues/394))" should be 
"* Scrollbars no longer activate unnecessarily. ([#347](https://github.com/a2stuff/a2d/issues/347), [#348](https://github.com/a2stuff/a2d/issues/348), [#394](https://github.com/a2stuff/a2d/issues/394))" because issue #366 has nothing to do with scrollbars activating unnecessarily.

**Comment by c0mmander8** [comment]
"* Show Text File DA: Keyboard support. Escape quits, arrows scroll. (#4)" should be "* Show Text File DA: Keyboard support. Esc quits, arrow keys scroll. (#4)".

**Comment by c0mmander8** [comment]
"* Show Text File DA: Keyboard support. Escape quits, arrows scroll. ([#4](https://github.com/a2stuff/a2d/issues/4))" should be "* Show Text File DA: Keyboard support. **Esc** quits, arrow keys scroll. ([#4](https://github.com/a2stuff/a2d/issues/4))".

**Comment by c0mmander8** [comment]
Corrections for RELEASE-NOTES.md string changes:

"* **Return** is a shortcut for **File > Rename...** ([#273](https://github.com/a2stuff/a2d/issues/273))" should be "* **Return** is a shortcut for **File > Rename...**. ([#275](https://github.com/a2stuff/a2d/issues/275))" because issue #273 has nothing to do with Return being a shortcut for File > Rename....
"* **File > Rename** dialog pre-filled with previous name. ([#156](https://github.com/a2stuff/a2d/issues/156))" should be "* **File > Rename...** dialog pre-filled with previous name. ([#156](https://github.com/a2stuff/a2d/issues/156))".
"* Show Text File DA: Keyboard support. Escape quits, arrows scroll. ([#4](https://github.com/a2stuff/a2d/issues/4))" should be "* Show Text File DA: Keyboard support. **Esc** quits, arrow keys scroll. ([#4](https://github.com/a2stuff/a2d/issues/4))".

**Comment by inexorabletash** [comment]
I appreciate corrections, e.g. incorrect links.

Grammar and style checks in the release notes are not really worth my time, so please refrain in the future.

**Comment by inexorabletash** [comment]
Also note that there is no desire to make the release notes entirely comprehensive. The github repository allows anyone to revisit the entire change history. Many things of minor importance are left out of the release notes intentionally.
