### ISSUE TITLE
Clicking Change Drive in the Selector > Edit an Entry... file picker dialog box always goes to the second volume the first time you click on it instead of the next volume

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#410]
**Describe the bug**
Clicking Change Drive in the Selector > Edit an Entry... file picker dialog box always goes to the second volume the first time you click on it instead of the next volume.

**To Reproduce**
1. Start Apple II DeskTop with three volumes mounted.
2. Click on the Selector menu and go to Selector > Add an Entry....
3. Add an entry to the Selector from one of the non-startup volumes.
4. Click OK.
5. Click on the Selector menu and go to Selector > Edit an Entry....
6. Click on the Selector entry you have just created.
7. Click OK.
8. Click Change Drive in the Selector > Edit an Entry... file picker dialog box.
9. The Selector > Edit an Entry... file picker dialog box goes to the second volume the first time you click on it instead of the next volume.

**Expected behavior**
Clicking Change Drive in the Selector > Edit an Entry... file picker dialog box should always goes to the next volume the first time you click on it.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 26 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
To do this, the selector-edit-specific instantiation of the dialog would need to grab `DEVNUM` (last active unit number) from ProDOS after the dialog is initialized, search `DEVLST` to find the index, and set the file dialog's `device_num`appropriately.
