### ISSUE TITLE
Dialog boxes should have the OK button in the lower right corner of the dialog box

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#411]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see an alert dialog box, an error dialog box or any other kind of dialog box in Apple II Desktop, Disk Copy, the Selector or desk accessories with the OK button in the lower left corner of the dialog box instead of the OK button in the lower right corner of the dialog box.

**Describe the solution you'd like**
Alert dialog boxes, error dialog boxes or any other kinds of dialog boxes in Apple II DeskTop, Disk Copy, the Selector or desk accessories should have the OK button in the lower right corner of the dialog box instead of having the OK button in the lower left corner of the dialog box, just like the later Mac and the later IIGS.

**Describe alternatives you've considered**
Keep on using Apple II DeskTop the way it currently is.

**Additional context**
There is no other context or screenshots about this feature request here.

**Comment by inexorabletash** [comment]
I prefer the quirky look, before Apple had a well established HIG.

**Comment by c0mmander8** [comment]
But all dialog boxes, including both alert dialog boxes and non-alert dialog boxes, in Disk Copy, the Selector and desk accessories, except Find Files and Run Basic Here, and all non-alert dialog boxes in Apple II DeskTop already have the OK button in the lower right corner of the dialog box. Only Find Files, with its "Search" button OK button equivalent, Run Basic Here and Apple II DeskTop alert dialog boxes have the OK button in the lower left corner of the dialog box. Please reopen this issue and, as referenced above, all dialog boxes, including both alert dialog boxes and non-alert dialog boxes, in Apple II DeskTop, Disk Copy, the Selector and desk accessories should have the OK button or its equivalent button in the lower right corner of the dialog box instead of having the OK button or its equivalent button in the lower left corner of the dialog box, just like the later Mac and the later IIGS. Implementing this issue will lead to greater user interface consistency.
