### ISSUE TITLE
Opening a new window and creating a new folder immediately afterward should not cause the vertical scrollbar with its scrollbar thumb to appear

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#414]
**Describe the bug**
As referenced is issue #348, opening a new window and creating a new folder immediately afterward causes the vertical scrollbar with its scrollbar thumb to appear. Clicking on the vertical scrollbar or moving its scrollbar thumb down / up all the way only moves the window down / up a few millimeters in total and only shows extra white space. The vertical scrollbar with its scrollbar thumb should not appear at all in this scenario.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open a window.
3. Create a new folder immediately afterward.
4. The vertical scrollbar with its scrollbar thumb appears.
5. Clicking on the vertical scrollbar or moving its scrollbar thumb down / up all the way only moves the window down / up a few millimeters in total and only shows extra white space.

**Expected behavior**
Opening a new window and creating a new folder immediately afterward should not cause the vertical scrollbar with its scrollbar thumb to appear.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 26 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
Please update "* Scrollbars no longer activate unnecessarily ([#347](https://github.com/a2stuff/a2d/issues/347), [#348](https://github.com/a2stuff/a2d/issues/348), [#394](https://github.com/a2stuff/a2d/issues/394))" in RELEASE-NOTES.md to say "* Scrollbars no longer activate unnecessarily ([#347](https://github.com/a2stuff/a2d/issues/347), [#348](https://github.com/a2stuff/a2d/issues/348), [#394](https://github.com/a2stuff/a2d/issues/394), [#414](https://github.com/a2stuff/a2d/issues/414))" instead.

**Comment by inexorabletash** [comment]
I'm unable to repro this. Please provide a screenshot so I can diagnose what's different.

**Comment by c0mmander8** [comment]
This issue still reproduces for me in Apple II DeskTop 1.2 Alpha 28. I am unable to provide a screenshot.

**Comment by c0mmander8** [comment]
Please try again using these more detailed steps to reproduce the behavior in this issue:

1. Start Apple II DeskTop while booted from the "A2.Desktop" volume, which is the "A2DeskTop-1.2-alpha28-en_800k.2mg" disk image,
2. Manually open the "A2.Desktop" volume.
3. Create a new folder immediately afterward.
4. The vertical scrollbar with its scrollbar thumb appears.
5. Clicking on the vertical scrollbar or moving its scrollbar thumb down / up all the way only moves the window down / up a few millimeters in total and only shows extra white space.

**Comment by c0mmander8** [comment]
Please try again using these more detailed steps to reproduce the behavior in this issue:

1. Start Apple II DeskTop while booted from the "A2.Desktop" volume, which is the "A2DeskTop-1.2-alpha28-en_800k.2mg" disk image,
2. Manually open the "A2.Desktop" volume, which is the "A2DeskTop-1.2-alpha28-en_800k.2mg" disk image,
3. Create a new folder immediately afterward.
4. The vertical scrollbar with its scrollbar thumb appears in the "A2.Desktop" volume window.
5. Clicking on the vertical scrollbar or moving its scrollbar thumb down / up all the way only moves the the "A2.Desktop" volume window down / up a few millimeters in total and only shows extra white space.

**Comment by c0mmander8** [comment]
Please update "* Scrollbars no longer activate unnecessarily (#347, #348, #394)" in RELEASE-NOTES.md to say "* Scrollbars no longer activate unnecessarily (#347, #348, #394, #414)" instead.

**Comment by inexorabletash** [comment]
Still no repro. 

![image](https://user-images.githubusercontent.com/771547/116769589-19810e00-a9f2-11eb-94c2-d241e3938093.png)

Are you sure you have a fresh download with no modifications?

**Comment by c0mmander8** [comment]
In addition to the files and folders shown in your screenshot, my Apple II DeskTop install also contains a file named "Desktop.File". This makes it so that I have 11 items in my "A2.Desktop" volume window before the new folder is even created. My "A2.Desktop" volume window therefore has 3 rows of icons when it is first opened instead of the 2 rows of icons shown in your "A2.Desktop" volume window in your screenshot.

**Comment by inexorabletash** [comment]
Thanks. As always, screenshots would have helped. I'm not sure why you're unable to make them.

So here's the state when the folder has been added but the "scroll into view" logic hasn't run. The issue is that the folder icon is shorter than most, but the "is the bottom of icon the fully visible?" logic uses the maximum icon height for the calculation, not the actual height.

![image](https://user-images.githubusercontent.com/771547/116790023-00667480-aa67-11eb-93b2-1ac84bb933d8.png)

**Comment by inexorabletash** [comment]
And for reference, this would not appear in release notes because this particular problem was not present in 1.1
