### ISSUE TITLE
"Close Window" is translated as "Close" and "Eject Disk" is translated as "Eject" in the German, French and Italian versions of Apple II DeskTop

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#417]
"Close Window" is translated as "Close" and "Eject Disk" is translated as "Eject" in the German, French and Italian versions of Apple II DeskTop. "Close Window" should be translated as "Close Window" and "Eject Disk" should be translated as "Eject Disk" in the German, French and Italian versions of Apple II DeskTop.

**Comment by inexorabletash** [comment]
That's what the translators preferred. Please do not file further issues of this sort unless the translation is actually incorrect.

**Comment by c0mmander8** [comment]
I thought that this issue was a remnant from before you changed the menu strings from "Close" to "Close Window" and from "Eject" to "Eject Disk" in the English original.

**Comment by c0mmander8** [comment]
I thought that this issue was a remnant from before you changed the menu strings from "Close" to "Close Window" and from "Eject" to "Eject Disk" in the English original instead of the translators' preference.
