### ISSUE TITLE
Allow moving or copying a file or a folder from the active window to a folder located inside an inactive window

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#418]
**Describe the bug**
Whenever I have more than one window open, I am unable to move or copy a file or a folder from the active window to a folder located inside an inactive window.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open two windows containing files, one of which also contains a folder.
3. Choose the window without the folder to be the active window.
4. Try to move or copy a file from the active window to the folder located inside the inactive window.
5. The folder located inside the inactive window fails to highlight so you are unable to move or copy the file from the active window to the folder located inside the inactive window.

**Expected behavior**
Whenever I have more than one window open, I should be able to move or copy a file or a folder from the active window to a folder located inside an inactive window, just like the Mac and the IIGS.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 26 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
It is a serious user impediment to not be able to move a file or a folder from one window to a folder in another window.

**Comment by inexorabletash** [comment]
Too complicated due to limited ability to hit test and clip in inactive windows.

**Comment by c0mmander8** [comment]
What does "hit test and clip" mean? Please reopen this issue. I still think that this issue is an important issue to be implemented because this would greatly increase the usability of Apple II DeskTop. Even if you decide not to reopen this issue, please answer my question at the beginning of this comment.

**Comment by inexorabletash** [comment]
I value your attention to detail and passion for this project.

However, mass updating bugs with "Please reopen this issue...." (I count 10 today) is not going to be tolerated.

"hit test" = determining what was clicked
"clip" = draw into only part of the screen, in this case a non-rectangular area (which MGTK does not support)
