### ISSUE TITLE
"Apple > About Apple II DeskTop..." in a2d/res/notes/menus.txt should be "Apple > About Apple II DeskTop" without the ellipsis

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#421]
"Apple > About Apple II DeskTop..." in a2d/res/notes/menus.txt should be "Apple > About Apple II DeskTop" without the ellipsis.

**Comment by inexorabletash** [comment]
Please don't file bugs like this. They aren't worth anyone's time.

**Comment by c0mmander8** [comment]
As referenced in this issue and commit 1210a60, "Apple > About Apple II DeskTop..." in a2d/res/notes/menus.txt should instead be "Apple > About Apple II DeskTop" without the ellipsis (...) for more accuracy in a2d/res/notes/menus.txt.

**Comment by c0mmander8** [comment]
Why the thumbs down?

**Comment by inexorabletash** [comment]
This is a file of notes for my personal use. Even reading these comments is a waste of my time that I could be using for something else instead.
