### ISSUE TITLE
Show Text File: conditionally activate scrollbar and move it proportionally

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#422]
**Describe the bug**
The vertical scrollbar with its scrollbar thumb appears in Show Text File even where there is nothing to scroll in the text file. The vertical scrollbar's scrollbar thumb barely moves at all while scrolling even if only a little bit of the text file is cut off from view.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open a window.
3. Double-click on a text file.
4. The vertical scrollbar with its scrollbar thumb appears in Show Text File even where there is nothing to scroll in the text file.
5. The vertical scrollbar's scrollbar thumb barely moves at all while scrolling even if only a little bit of the text file is cut off from view.

**Expected behavior**
The vertical scrollbar's scrollbar thumb in Show Text File should appear only when necessary and it should move in proportion to the length of the text file.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 26 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
The entire file is not loaded, so this is likely to be very difficult to get right. At best an approximation could be given based on the length of the file, but that wouldn't correspond to the number of lines.

**Comment by inexorabletash** [comment]
From #696, these should be supported for consistency:

Apple-Up Arrow; Page Up
Apple-Down Arrow: Page Down
Open Apple-Solid Apple-Up Arrow: Home
Open Apple-Solid Apple-Down Arrow: End
