### ISSUE TITLE
Additional Find Files improvements

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#423]
Here are additional Find Files improvements:

Allow clicking between letters with the insertion point in order to edit the middle of a search term.
Implement keyboard navigation of the existing vertical scrollbar. I would recommend Down Arrow for Page Down, Up Arrow for Page Up, Apple-Down Arrow for End and Apple-Up Arrow for Home.
Increase maximum number of shown results from 54 to unlimited.

**Comment by c0mmander8** [comment]
Here are additional Find Files improvements:

Allow clicking between letters with the insertion point in order to edit the middle of a search term.
Implement keyboard navigation of the existing vertical scrollbar. I would recommend Down Arrow to scroll down a line, Up Arrow to scroll up a line, Apple-Down Arrow for Page Down and Apple-Up Arrow for Page Up.
Increase maximum number of shown results from 54 to unlimited.

**Comment by c0mmander8** [comment]
Here are additional Find Files improvements:

Allow clicking between letters with the insertion point in order to edit the middle of a search term.
Implement keyboard navigation of the existing vertical scrollbar. I would recommend Down Arrow to scroll down a result, Up Arrow to scroll up a result, Apple-Down Arrow for Page Down and Apple-Up Arrow for Page Up.
Increase maximum number of shown results from 54 to unlimited.

**Comment by inexorabletash** [comment]
Repeating your comments in lieu of making is not acceptable. It spams the repository with unnecessary updates. It is also nearly impossible to tell what changed between the messages. 

You have been warned repeatedly. Doing so again will result in a permanent ban.

**Comment by inexorabletash** [comment]
Merged into #255
