### ISSUE TITLE
A mysterious glyph, most likely a MouseText character, should not appear at the beginning of the line on the left side of the text field for a second before disappearing when pressing Apple-Left Arrow in Find Files

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#424]
**Describe the bug**
A mysterious glyph, most likely a MouseText character, appears at the beginning of the line on the left side of the text field for a second before disappearing when pressing Apple-Left Arrow in Find Files. It appears if the insertion point is between characters in the middle of the text field or at the end of the line on the right-hand side of the text field. It does not appear if the insertion point is at the beginning of the line on the left-hand side of the text field. The mysterious glyph varies depending on where in the text field the insertion point is located.

**To Reproduce**
1. Start Apple II DeskTop.
2. Click on the Apple menu and select Find Files.
3. Type some characters into the text field.
4. Optionally, Press the Left Arrow once or a few times to go into the middle of the text field from the end of the text field.
5. Do not go to the beginning of the text field.
6. Press Apple-Left Arrow.
7. A mysterious glyph, most likely a MouseText character, appears at the beginning of the line on the left side of the text field for a second before disappearing.

**Expected behavior**
A mysterious glyph, most likely a MouseText character, should not appear at the beginning of the line on the left side of the text field for a second before disappearing when pressing Apple-Left Arrow in Find Files.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 26 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Thanks. Please reduce the length of your message titles. They are titles, not essays.
