### ISSUE TITLE
The build date located in the about box located at Apple > About Apple II DeskTop is stated as "05, 2021" or "05 2021" instead of "March 5, 2021" or its localized equivalent

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#425]
The build date located in the about box located at Apple > About Apple II DeskTop is stated as "05, 2021" or "05 2021" instead of "March 5, 2021" or its localized equivalent, with the word "March" or its localized equivalent missing and there is an extra "0" in all language versions of Apple II DeskTop 1.2 Alpha 27.

**Comment by inexorabletash** [comment]
Thanks. Difference in shell logic since I switched the Travis-CI configuration to use linux instead of macos
