### ISSUE TITLE
GS/OS (ProDOS 2.5.x) filename casing should be applied to the old volume name in Special > Format a Disk... and in Special > Erase a Disk...

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#427]
**Describe the bug**
GS/OS (ProDOS 2.5.x) filename casing is not applied to the old volume name in Special > Format a Disk... and in Special > Erase a Disk....

**To Reproduce**
1. Start Apple II DeskTop with a volume with GS/OS (ProDOS 2.5.x) filename casing applied named "LIve.INstall".
2. Click on the Special menu and go to Special > Format a Disk... or go to Special > Erase a Disk....
3. Select the slot number and the drive number of "LIve.INstall".
4. Enter a volume name for the new volume to be created.
5. A dialog box appears stating "Do you want to format LIVE.INSTALL ?" or "Do you want to erase LIVE.INSTALL ?" with "LIVE.INSTALL" all in capital letters.

**Expected behavior**
GS/OS (ProDOS 2.5.x) filename casing should be applied to the old volume name in Special > Format a Disk... and in Special > Erase a Disk....

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 27 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Not worth it relative to complexity.

**Comment by inexorabletash** [comment]
Moving this from Won't Fix to Archived. Plausible using a call from the format/erase overlay's `GetVol` to `AdjustVolumeNameCase`, but complicated by the fact that the latter uses ~$800 for buffers and $1C00 for an I/O buffer, while the former has code in $800 and the actual string is in $1C00!

**Comment by inexorabletash** [comment]
The $1C00 conflict is no longer a problem.
