### ISSUE TITLE
A folder with a filename that has all capital (uppercase) letters and no lowercase letters created in GS/OS 6.0.1 should appear in Apple II DeskTop as a folder with a filename with all capital (uppercase) letters and no lowercase letters

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#430]
**Describe the bug**
A folder with a filename that has all capital (uppercase) letters and no lowercase letters created in GS/OS 6.0.1, which has lowercase letter filename support and contains ProDOS 2.0.3, appears in Apple II DeskTop as a folder with a filename with Apple II DeskTop case adjusting applied instead of appearing in Apple II DeskTop as a folder with a filename with all capital (uppercase) letters and no lowercase letters.

**To Reproduce**
1. Start GS/OS 6.0.1.
2. Open a window.
3. Create a folder.
4. Rename the folder with a filename that has all capital (uppercase) letters and no lowercase letters.
5. Shut down the computer.
6. Restart the computer.
7. Start Apple II DeskTop.
8. Open the same window you opened in step 2.
9. The folder you created in step 3 and renamed in step 4 appears in Apple II DeskTop as a folder with a filename with Apple II DeskTop case adjusting applied instead of appearing in Apple II DeskTop as a folder with a filename with all capital (uppercase) letters and no lowercase letters.

**Expected behavior**
A folder with a filename that has all capital (uppercase) letters and no lowercase letters created in GS/OS 6.0.1, which has lowercase letter filename support and contains ProDOS 2.0.3, should appear in Apple II DeskTop as a folder with a filename with all capital (uppercase) letters and no lowercase letters.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 27 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
The last screenshot at the bottom of issue #64 and its accompanying information shows how this issue should be implemented. From the existence of the last screenshot at the bottom of issue #64 and its accompanying information, this issue seems feasible and realistic. This issue also and secondly applies to the file picker dialog boxes located at File > Copy a File..., File > Delete a File..., Selector > Add an Entry... and Selector > Edit an Entry... in Apple II DeskTop and located at File > Run a Program... in the Selector. This issue thirdly and finally applies to the Move..., Copy... and Delete... dialog boxes in Apple II DeskTop.

**Comment by inexorabletash** [comment]
This appears to be a bug or intentional design decision in GS/OS (either the OS or the Finder). 

The technical note describing name casing is here: http://www.1000bit.it/support/manuali/apple/technotes/gsos/tn.gsos.08.html

> If version is read as a word value, bit 7 of min_version would be the highest bit (bit 15) of the word. If that bit is set, the remaining 15 bits of the word are interpreted as flags that indicate whether the corresponding character in the filename is uppercase or lowercase...

When a file is named in the IIgs Finder in ALL CAPS, bit 15 of min_version is _not_ set. The IIgs Finder shows files like this (e.g. regular P-8 files) in uppercase, so it's not observed there. That seems like a bug to me, but regardless - it's a problem in the filesystem data that GS/OS or the Finder produces, not A2D.
