### ISSUE TITLE
IIc+ video appears in color rather than grayscale

### ISSUE THREAD

**Issue by bbellina** [a2stuff/a2d#431]
Hello, I have a IIc+ that is connected via its composite out video to a VCR and then from that to a TV. Unfortunately I do not have a IIc color monitor. When I run A2Desktop 1.2 the video shown is in color rather than grayscale, which makes it very difficult to read. On my IIGS this doesn't happen, but the IIGS is using a IIGS RGB monitor.  I don't know if this is something adjustable in the code or maybe with a control panel, or if this is unavoidable due to my use of a non-Apple monitor. But if there is something that can be done, that would be great.  Thanks.

**Comment by inexorabletash** [comment]
The IIgs has a way to disable color output. Without additional hardware, the IIe and IIc do not have this ability. You can use a monitor with the ability to switch to monochrome, or get an adapter cards for the IIe (like the AppleColor Extended 80 Column RGB) or adapter box for the IIc (Video7 made one) but both are extremely rare. 

See the docs: https://a2desktop.com/docs
