### ISSUE TITLE
Clicking inside the Special > Erase a Disk... dialog box at a certain point should not cause Apple II DeskTop to freeze

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#432]
**Describe the bug**
Clicking inside the Special > Erase a Disk... dialog box at a certain point causes Apple II DeskTop to freeze.

**To Reproduce**
1. Start Apple II DeskTop.
2. Click on the Special menu and go to Special > Erase a Disk....
3. Select the slot number and the drive number of any drive; it does not matter whether the selected drive is phantom or real.
4. Enter a volume name for the new volume to be created.
5. A dialog box appears stating "Do you want to erase (the volume name) ?" with the volume name all in capital letters or "Do you want to erase the disk in slot (x) drive (x)?".
6. Click inside the dialog box, but not on any button on the screen, with your mouse.
7. Apple II DeskTop freezes.

**Expected behavior**
Clicking inside the Special > Erase a Disk... dialog box at a certain point should not cause Apple II DeskTop to freeze.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 27 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
This issue does not occur with clicking inside the Special > Format a Disk... dialog box at the same point.

**Comment by inexorabletash** [comment]
Nice find!
