### ISSUE TITLE
The splash screen on the menu bar when launching Disk Copy should say "Disk Copy Version 1.2" instead of saying "Disk copy version 1.2"

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#433]
The splash screen on the menu bar when launching Disk Copy should say "Disk Copy Version 1.2" instead of saying "Disk copy version 1.2".

**Comment by inexorabletash** [comment]
Sure. That splash string is a bit silly but doesn't hurt to fix it.
