### ISSUE TITLE
AppleWin: 800k disk images are shown with the hard disk icon

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#436]
The "A2DeskTop-1.2-alpha27-en_800k.2mg" disk image should appear with a 3.5-inch floppy disk icon instead of a hard drive icon in Apple II DeskTop 1.2 Alpha 27 (the latest version of the program) in an emulated Enhanced Apple IIe in AppleWin 1.29.16.0 (the latest version of the program). This issue does not occur with an emulated ROM 01 Apple IIGS in GSplus 0.14 (the latest version of the program).

**Comment by inexorabletash** [comment]
Please stop overly verbose issue titles. It makes the issues difficult to read. Try to keep issue titles to ten words or less. 

Please stop including unnecessary and repetitive phrasing such as "(the latest version of the program)" which produces long and difficult to read sentences. 

Please use issue templates, which include appropriate issue labels and provide structure such as where to include versions.

**Comment by inexorabletash** [comment]
Root cause: AppleWin's virtual hard disk firmware isn't SmartPort, so DeskTop treats it as "unknown" device type. The _if 800k show as 3.5" floppy_ heuristic is skipped.
