### ISSUE TITLE
GSplus: 140K disk images are shown with the 3.5-inch floppy disk icon

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#437]
**Describe the bug**
A 140K disk image located at s7d1 in GSplus appears with a 3.5-inch floppy disk icon instead of a 5.25-inch floppy disk icon in Apple II DeskTop.

**To Reproduce**
1. Start Apple II DeskTop with "A2DeskTop-1.2-alpha27-en_140k_disk1.po" located at s7d1 in GSplus mounted.
2. "A2DeskTop-1.2-alpha27-en_140k_disk1.po" appears with a 3.5-inch floppy disk icon instead of a 5.25-inch floppy disk icon in Apple II DeskTop.

**Expected behavior**
A 140K disk image located at s7d1 in GSplus should not appear with a 3.5-inch floppy disk icon instead of a 5.25-inch floppy disk icon in Apple II DeskTop.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 27 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
There's no reasonable behavior here. Slot 7 on GSplus is a virtual hard drive controller. A2D is using a 3.5" icon for "small/removable" disks, which is not incorrect here. Using a 5.25" icon would also be wrong as the system is not treating the device as a Disk II.
