### ISSUE TITLE
The Apple IIGS Control Panel RAM5 RAM disk is shown with the hard drive icon

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#438]
**Describe the bug**
The Apple IIGS Control Panel RAM5 RAM disk appears with a hard drive icon instead of a RAMCard RAM disk icon in Apple II DeskTop.

**To Reproduce**
1. Enter the Apple IIGS Control Panel.
2. Create an Apple IIGS Control Panel RAM5 RAM disk.
3. Exit the Apple IIGS Control Panel.
4. Shut down the computer.
5. Restart the computer.
6. Start Apple II DeskTop.
7. The Apple IIGS Control Panel RAM5 RAM disk appears with a hard drive icon instead of a RAMCard RAM disk icon in Apple II DeskTop.

**Expected behavior**
The Apple IIGS Control Panel RAM5 RAM disk should not appear with a hard drive icon instead of a RAMCard RAM disk icon in Apple II DeskTop.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 27 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
$C5FB is $80, but should have the low bit set to signal a ramdisk. But that may be incorrect - it's only true for smartport devices, not generically?
