### ISSUE TITLE
The Apple IIGS Control Panel RAM5 RAM disk should be recognized as a RAMCard for RAMCard features

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#439]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that the Apple IIGS Control Panel RAM5 RAM disk is not recognized as a RAMCard for the "Copying Apple II DeskTop into RAMCard" feature while starting Apple II DeskTop and the "Copy to RAMCard:" feature in Selector > Add an Entry... and in Selector > Edit an Entry... in Apple II DeskTop, both at boot and at first use.

**Describe the solution you'd like**
The Apple IIGS Control Panel RAM5 RAM disk should be recognized as a RAMCard for the "Copying Apple II DeskTop into RAMCard" feature while starting Apple II DeskTop and the "Copy to RAMCard:" feature in Selector > Add an Entry... and in Selector > Edit an Entry... in Apple II DeskTop, both at boot and at first use.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
There is no other context or screenshots about this feature request here.

**Comment by inexorabletash** [comment]
`DESKTOP.SYSTEM` scans slots for ramdisk signatures... but only tries Slot N Drive 1. Trying Drive 2 as well should be easy.

**Comment by inexorabletash** [comment]
Hmm, more subtle than that - $C5FB is $80 - the low bit is expected to be set for a ramdisk.
