### ISSUE TITLE
Entering and then exiting the Apple IIGS Control Panel in Disk Copy, in the Selector or in desk accessories should not cause the Apple IIGS to remain in color mode and mess up its video

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#440]
**Describe the bug**
Entering and then exiting the Apple IIGS Control Panel in Disk Copy, in the Selector or in desk accessories causes the Apple IIGS to remain in color mode and messes up its video.

**To Reproduce**
1. Start Apple II DeskTop or launch the Selector on an Apple IIGS.
2. Launch Disk Copy or open a desk accessory if Apple II DeskTop has been started instead of the Selector being launched.
3. Enter the Apple IIGS Control Panel.
4. Exit the Apple IIGS Control Panel.
5. The Apple IIGS remains in color mode and its video is messed up.

**Expected behavior**
Entering and then exiting the Apple IIGS Control Panel in Disk Copy, in the Selector or in desk accessories should not cause cause the Apple IIGS to remain in color mode and mess up its video.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 27 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
This issue occurs for only about a second or a few seconds before going away automatically when in Apple II DeskTop and not in Disk Copy or a desk accessory.

**Comment by c0mmander8** [comment]
This issue also applies to all dialog boxes in Apple II DeskTop, in Disk Copy, in the Selector or in desk accessories.

**Comment by c0mmander8** [comment]
This issue also applies to all dialog boxes in Apple II DeskTop, in Disk Copy, in the Selector and in desk accessories.

**Comment by inexorabletash** [comment]
Yep. The clock also doesn't update in these cases.

Only the main DeskTop event loop has a counter for resetting the IIgs mode and updating the clock. Nested event loops don't do this.

**Comment by inexorabletash** [comment]
A checklist of places to tackle:

* [ ] Windowed Desk Accessories
* [ ] DeskTop dialogs
* [ ] DeskTop alerts
* [ ] Disk Copy
* [ ] Selector
* [ ] Selector dialogs
* [ ] Selector alerts

Alerts are a separate code path from dialogs, they have single-line messages and no title.

**Comment by inexorabletash** [comment]
Somehow a glitch is introduced where Selector hangs if the video is reset during an alert, after the alert is dismissed. I haven't been able to determine why yet.

**Comment by c0mmander8** [comment]
I see that this issue is referenced in issue #193.

**Comment by c0mmander8** [comment]
Did you also fix updating the clock in these cases?

**Comment by c0mmander8** [comment]
Please update "* IIgs: Mono DHR is re-enabled when returning from system control panel. ([#193](https://github.com/a2stuff/a2d/issues/193))" in RELEASE-NOTES.md to say 
"* IIgs: Mono DHR is re-enabled when returning from system control panel. ([#193](https://github.com/a2stuff/a2d/issues/193), [#440](https://github.com/a2stuff/a2d/issues/440))" instead.

**Comment by c0mmander8** [comment]
Please reopen this issue. There are a few lingering bugs to work out in Apple II DeskTop Alpha 28:

1. Notwithstanding commit fb771c4, entering and then exiting the Apple IIGS Control Panel in the main Selector window in Apple II DeskTop Alpha 28 still causes the Apple IIGS to remain in color mode and still messes up its video. This issue does not occur anymore in Selector regular dialog boxes and this issue does not occur anymore in Selector alert dialog boxes.
2. Entering and then exiting the Apple IIGS Control Panel while having a menu dropped down in Apple II DeskTop, in Disk Copy or in the Selector in Apple II DeskTop Alpha 28 still causes the Apple IIGS to remain in color mode and still messes up its video until the menu is released.
3. Entering and then exiting the Apple IIGS Control Panel while accomplishing a long task, such as copying / moving / deleting many files and folders in Apple II DeskTop or copying disks or volumes in Apple II DeskTop or in Disk Copy, in Apple II DeskTop Alpha 28 still causes the Apple IIGS to remain in color mode and still messes up its video until the task is completed.
4. Please update "* IIgs: Mono DHR is re-enabled when returning from system control panel. ([#193](https://github.com/a2stuff/a2d/issues/193))" in RELEASE-NOTES.md to say 
"* IIgs: Mono DHR is re-enabled when returning from system control panel. ([#193](https://github.com/a2stuff/a2d/issues/193), [#440](https://github.com/a2stuff/a2d/issues/440))" instead.

**Comment by inexorabletash** [comment]
(1) - Fixed; I'd left the change commented out while debugging another issue.

(2), (3) - No. Introducing changes into every nested loops is not worth it. "If it hurts, don't do it".

(4) - Stop asking for additions to the release notes unless there is an actual error. They are intended to be an overview, not a comprehensive change log.

**Comment by c0mmander8** [comment]
Please reopen this issue. This bug still applies to non-windowed desk accessories, such as the Flying Toasters, Melt and Invert screen savers and the Show Image File preview handler. Entering and then exiting the Apple IIGS Control Panel in non-windowed desk accessories still causes the Apple IIGS to remain in color mode and still messes up its video until the respective screen saver is exited, until the Show Image File b&w / color mode switch is toggled or until Show Image File is exited.

**Comment by inexorabletash** [comment]
Given that the negative side effects are minor, this is not worth addressing.
