### ISSUE TITLE
A new disk that is mounted should appear in an already existing empty space between volumes instead of being covered up by an existing volume

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#441]
**Describe the bug**
A new disk that is mounted is covered up by an existing volume instead of appearing in an already existing empty space between volumes.

**To Reproduce**
1. Start Apple II DeskTop with three volumes mounted.
2. Eject the disk that is the middle (second) volume on the desktop.
3. The disk unmounts and a dialog box appears stating "System Error".
4. Click OK.
5. There is now an empty space on the desktop between the top (first) and bottom (third) volumes.
6. Insert a new disk to replace the one that was ejected and unmounted.
7. The new disk is mounted and is covered up by the bottom (third) volume instead of appearing in the empty space between the the top (first) and bottom (third) volumes.

**Expected behavior**
A new disk that is mounted should appear in an already existing empty space between volumes instead of being covered up by an existing volume.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 27 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Thanks for the clear repro steps! I'd seen this happening but hadn't tracked down a reliable repro.
