### ISSUE TITLE
Special > Check All Drives should not close all open windows

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#442]
**Describe the bug**
Special > Check All Drives closes all open windows and then fails to restore them.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open multiple windows.
3. Click on the Special menu and go to Special > Check All Drives.
4. All open windows are closed and then they are not restored.

**Expected behavior**
Special > Check All Drives should not close all open windows.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 27 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
This issue does not occur with Special > Check Drive. Special > Check Drive does not close the windows of the drive you are checking.

**Comment by inexorabletash** [comment]
Special > Check Drive doesn't close windows if the volume no longer exists, so it's more complicated than simply delegating to the `cmd_check_single_drive` logic. That should be fixed too.

**Comment by inexorabletash** [comment]
Heh, actually, Special > Check Drive is supposed to close all windows, it was just broken.

**Comment by inexorabletash** [comment]
I'm going to close this as invalid. Check Drive was just broken.
