### ISSUE TITLE
Show menu bar clock in Disk Copy and in the Selector

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#444]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that the menu bar clock is not shown in Disk Copy itself, in Disk Copy's regular dialog boxes, in Disk Copy's alert dialog boxes, in the Selector itself, in the Selector's regular dialog boxes or in the Selector's alert dialog boxes.

**Describe the solution you'd like**
The menu bar clock should be shown in Disk Copy itself, in Disk Copy's regular dialog boxes, in Disk Copy's alert dialog boxes, in the Selector itself, in the Selector's regular dialog boxes and in the Selector's alert dialog boxes.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
The 12 hour / 24 hour menu bar clock setting from the Control Panel contained in "Desktop.Config" should be respected in Disk Copy and in the Selector, just like it is in Apple II DeskTop.

**Comment by c0mmander8** [comment]
Why is this issue a "Won't Fix"?

**Comment by inexorabletash** [comment]
It might not be that bad. 

Every feature comes with a cost, though.

**Comment by inexorabletash** [comment]
Added to Selector, but not Disk Copy. Showing it in Disk Copy would remove precious buffer space, and the clock wouldn't update regularly during the copy anyway since.
