### ISSUE TITLE
The splash screen strings should be centered

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#445]
The splash screen strings while starting Apple II DeskTop, launching Disk Copy and launching the Selector, if one actually exists for the Selector, should be centered, just like the splash screen string while launching an application on the Mac or the IIGS is centered.

**Comment by c0mmander8** [comment]
Why is this issue a "Won't Fix"?

**Comment by inexorabletash** [comment]
They are implemented by setting a temporary menu title. It's not worth expending any time or code on. 

It's not really worth my time even responding here. Trivial issues like this are an annoyance.
