### ISSUE TITLE
Apple II DeskTop numbered error message dialog box string changes in a2d/desktop/res/aux.res.en and equivalent changes in all translations

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#449]
Apple II DeskTop numbered error message dialog box string changes in a2d/desktop/res/aux.res.en and equivalent changes in all translations:

".define res_string_errmsg_00 "System Error"" should be 
".define res_string_errmsg_00 "System error."" because all of the other Apple II DeskTop numbered error message dialog box strings in a2d/desktop/res/aux.res.en are sentences with words starting with a lowercase letter in the middle of the message and a period at the end of the message. This Apple II DeskTop numbered error message dialog box string change should be made to the English original in a2d/desktop/res/aux.res.en and an equivalent change should be made, where applicable, to all translations, including the recently posted German, Spanish, French and Italian translations.
".define res_string_errmsg_27 "I/O Error."" should be 
".define res_string_errmsg_27 "I/O error."" because all of the other Apple II DeskTop numbered error message dialog box strings in a2d/desktop/res/aux.res.en are sentences with words starting with a lowercase letter in the middle of the message and a period at the end of the message. This Apple II DeskTop numbered error message dialog box string change should be made to the English original in a2d/desktop/res/aux.res.en and an equivalent change should be made, where applicable, to all translations, including the recently posted German, Spanish, French and Italian translations.

**Comment by inexorabletash** [comment]
* File bugs against functionality, not the source.
* Use issue templates
* Keep titles down to 10 words if possible
* Report problems, stop phrasing things as "should" 
* Write shorter text.

I'm happy with the string as-is.

**Comment by c0mmander8** [comment]
Please reconsider your decision and please reopen this issue. As referenced above, the Apple II DeskTop numbered error message dialog box strings in a2d/desktop/res/aux.res.en listed above and relisted below each have a serious capitalization issue and the first one also has a serious punctuation error. These Apple II DeskTop numbered error message dialog box string changes should be made to the English original in a2d/desktop/res/aux.res.en and an equivalent change should be made, where applicable, to all translations:

1. ".define res_string_errmsg_00 "System Error"" really should be 
".define res_string_errmsg_00 "System error."" because this Apple II DeskTop numbered error message dialog box string in a2d/desktop/res/aux.res.en has a serious capitalization issue and also has a serious punctuation error.
2. ".define res_string_errmsg_27 "I/O Error."" really should be
".define res_string_errmsg_27 "I/O error."" because this Apple II DeskTop numbered error message dialog box string in a2d/desktop/res/aux.res.en has a serious capitalization issue.
