### ISSUE TITLE
Selector alert error message dialog box string change in a2d/selector/res/alert_dialog.res.en and an equivalent change in all translations

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#450]
Selector alert error message dialog box string change in a2d/selector/res/alert_dialog.res.en and an equivalent change in all translations:

".define res_string_alert_io_error "I/O Error."" should be 
".define res_string_alert_io_error "I/O error."" because all of the other Selector alert error message dialog box strings in a2d/selector/res/alert_dialog.res.en are sentences with words starting with a lowercase letter in the middle of the message and a period at the end of the message. This Selector alert error message dialog box string change should be made to the English original in a2d/selector/res/alert_dialog.res.en and an equivalent change should be made, where applicable, to all translations, including the recently posted German, Spanish, French and Italian translations.

**Comment by inexorabletash** [comment]
* File bugs against functionality, not the source.
* Use issue templates
* Keep titles down to 10 words if possible
* Report problems, stop phrasing things as "should" 
* Write shorter text.

I'm happy with the string as-is.

**Comment by c0mmander8** [comment]
Please reconsider your decision and please reopen this issue. As referenced above, the Selector alert error message dialog box string in a2d/selector/res/alert_dialog.res.en listed above and relisted below has a serious capitalization issue. This Selector alert error message dialog box string change should be made to the English original in a2d/selector/res/alert_dialog.res.en and an equivalent change should be made, where applicable, to all translations:

1. ".define res_string_alert_io_error "I/O Error."" really should be
".define res_string_alert_io_error "I/O error."" because this Selector alert error message dialog box string in a2d/selector/res/alert_dialog.res.en has a serious capitalization issue.

**Comment by c0mmander8** [comment]
Please reconsider your decision and please reopen this issue and please unlock and reopen issue #449. As referenced above and in issue #449, this issue and issue #449 are for greater user interface consistency.

**Comment by c0mmander8** [comment]
This issue and issue #449 are not "resolved".
