### ISSUE TITLE
Regression: "RGB Color" is disabled in Disk Copy after enabling it in Apple II DeskTop

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#452]
**Describe the bug**
"RGB Color" is disabled in Disk Copy after enabling it in Apple II DeskTop. This is a regression in Apple II DeskTop Alpha 28. This issue did not occur in Apple II DeskTop Alpha 27.

**To Reproduce**
1. Start Apple II DeskTop.
2. Click on the Apple menu and select the Control Panels folder.
3. Double-click and open the Control Panel control panel.
4. Click on and turn on "RGB Color" in the "Desktop Pattern" section.
5. "RGB Color" is now enabled.
6. Launch Disk Copy.
7. "RGB Color" is now disabled.
8. Quit Disk Copy.
9. "RGB Color" is now enabled once again.

**Expected behavior**
"RGB Color" should not be disabled in Disk Copy after enabling it in Apple II DeskTop.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 28 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Disk Copy doesn't load settings, but there's $80 bytes free to do so, so might as well.
