### ISSUE TITLE
The desktop pattern picker arrows in the Control Panel control panel cycle though the desktop patterns relative to the default desktop pattern, rather than the active desktop pattern

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#453]
**Describe the bug**
The desktop pattern picker arrows in the Control Panel control panel cycle though the desktop patterns relative to the default desktop pattern, rather than the active desktop pattern.

**To Reproduce**
1. Start Apple II DeskTop with the default desktop pattern chosen.
2. Click on the Apple menu and select the Control Panels folder.
3. Double-click and open the Control Panel control panel.
4. Click on and turn on "RGB Color" in the "Desktop Pattern" section.
5. "RGB Color" is now enabled.
6. The current desktop pattern is gray.
7. Click on the left arrow in the desktop pattern picker.
8. The shown desktop pattern is light green.
9. Click on the right arrow in the desktop pattern picker.
10. The shown desktop pattern is gray.
11. Click on the right arrow in the desktop pattern picker a second time.
12. The shown desktop pattern is purple.
13. Choose a random desktop pattern to be your desktop pattern.
14. Close the Control Panel control panel.
15. Double-click and reopen the Control Panel control panel.
16. The current desktop pattern is whatever random desktop pattern you just chose to be your desktop pattern.
17. Click on the left arrow in the desktop pattern picker.
18. The shown desktop pattern is still light green.
19. Click on the right arrow in the desktop pattern picker.
20. The shown desktop pattern is still gray.
21. Click on the right arrow in the desktop pattern picker a second time.
22. The shown desktop pattern is still purple.

**Expected behavior**
The desktop pattern picker arrows in the Control Panel control panel should cycle though desktop patterns relative to the active desktop pattern, rather than the default desktop pattern.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 28 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment]
This issue is essentially the desktop pattern version of issue #410.

**Comment by inexorabletash** [comment]
Not important.
