### ISSUE TITLE
GSplus: Bugs with 15 mounted 140K 5.25-inch floppy disk images

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#455]
**Describe the bug**
With 15 140K 5.25-inch floppy disk images mounted at s5d1, s5d2, s6d1, s6d2 and s7d1 to s7d11 in GSplus, the 140K 5.25-inch floppy disk image remapped to s3d1 falsely appears as a RAMCard. Clicking on the Special menu and going to Special > Format a Disk... or going to Special > Erase a Disk... freezes the emulator.

**To Reproduce**
1. Start Apple II DeskTop with 15 140K 5.25-inch floppy disk images mounted at s5d1, s5d2, s6d1, s6d2 and s7d1 to s7d11 in GSplus.
2. The 140K 5.25-inch floppy disk image remapped to s3d1 falsely appears as a RAMCard.
3. Clicking on the Special menu and going to Special > Format a Disk... or going to Special > Erase a Disk... freezes the emulator.

**Expected behavior**
With 15 140K 5.25-inch floppy disk images mounted at s5d1, s5d2, s6d1, s6d2 and s7d1 to s7d11 in GSplus, the 140K 5.25-inch floppy disk image remapped to s3d1 should not falsely appear as a RAMCard. Clicking on the Special menu and going to Special > Format a Disk... or going to Special > Erase a Disk... should not freeze the emulator.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 28 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
ProDOS only supports RAMDisks for Slot 3 and won't remap like that.

**Comment by inexorabletash** [comment]
There are general issues with more than 4 volumes per slot.

**Comment by inexorabletash** [comment]
Fixed the icon issue for drives remapped to S3D1.

ProDOS 8 only allows up to 14 volumes, and S3D2 is reserved for /RAM and since that's forcibly disconnected DeskTop only supports 13.  If you're using a non-standard ProDOS and DEVCNT ($BF31) is greater than $D, you're gonna have a bad time.

**Comment by c0mmander8** [comment]
Please reopen this issue. According to the following comment from David Wilson from https://comp.sys.apple2.narkive.com/kDNpqMP4/question-on-prodos-smartport-drive-remapping, slot 3, drive 1 can be remapped to by ProDOS 2.0.x (2.4.x):


David Wilson
13 years ago
Permalink
On Dec 5, 5:26 pm, ***@actrix.gen.nz (David Empson) wrote:
A great explanation of SmartPort.

> For its SmartPort unit remapping, ProDOS can "reuse" any slot (apart
> from 3) which doesn't contain a storage device. (Slot 3 is out because
> of /RAM.)

Slot 3 Drive 1 will be used by the v2.0.x remapping code.
The order of use is:

4/1 4/2 1/1 1/2 2/1 2/2 5/1 5/2 6/1 6/2 7/1 7/2 3/1

> Assuming you have a 5.25" drive in slot 6, I'm guessing you have another
> storage device in slot 5, which is why it skipped that one when
> allocating slot 4.

As can be seen in the table above, slot 5 is midway down the list
(probably as both IIc and IIgs have disk drives in that slot).

> You probably can't get much more than 8. The absolute maximum limit is
> 14 units, but you could only get that if you took out all disk
> controller and other storage interface cards (apart from the Microdrive
> card), and removed the extended 80-column card.

ProDOS supports up to 14 volumes but reserves 3/2 for /RAM (v2.0.1
forgot to do that and would, if you had enough SmartPort devices, map
a drive to it and then overwrite it with /RAM). I have managed to get
15 drives working under ProDOS by using 0/2 (0/1 aka Unit 00 is
special and cannot be used).

> In principle, someone could write a program which patched the SmartPort
> device mapping table inside ProDOS's language card, and this could allow
> more units to be swapped in under user control, as long as the interface
> card firmware supported more devices.

Would anyone be interested in such a program? I must do some 6502
programming again before I forget how to...

> Standard 5.25" drives have no connection with SmartPort at all (apart
> from sharing the same physical port on a IIgs or IIc).

Unless they are plugged into a Laser UDC card in which case they can
be accessed through the SmartPort firmware interface (which makes them
behave differently under Apple Pascal 1.3 - they get different boot
blocks when formatted to those found on drives connected to a Disk ]
[ controller card [neither Pascal 5.25" disk will boot on the other
controller]).

> You can check wheter a card has a SmartPort interface by examining the
> firmware. No manuals handy, but I remembered this level of detail from
> at least 11 years ago. :-)
>
> The ID bytes for a ProDOS block device are:
>
> Cn01 = 20
> Cn03 = 00
> Cn05 = 03
> CnFF is not FF (13-sector 5.25") or 00 (16-bit 5.25")

16-sector :-)

Pretty darn good memory.

**Comment by c0mmander8** [comment]
I see that this issue was fixed in commit f07e689. What about clicking on the Special menu and going to Special > Format a Disk... or going to Special > Erase a Disk... freezing the emulator in this issue and issue #456?

**Comment by ph0enix-c0der** [comment]
This issue should be added to the Apple II DeskTop 1.2 milestone.
