### ISSUE TITLE
GSplus: Bugs with 15 mounted 800K 3.5-inch floppy disk images

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#456]
**Describe the bug**
With 15 800K 3.5-inch floppy disk images mounted at s5d1, s5d2, s6d1, s6d2 and s7d1 to s7d11 in GSplus, the 800K 3.5-inch floppy disk images mounted at s6d1 and s6d2 falsely appear as 140K 5.25-inch floppy disks and the 800K 3.5-inch floppy disk image remapped to s3d1 falsely appears as a RAMCard. Clicking on the Special menu and going to Special > Format a Disk... or going to Special > Erase a Disk... freezes the emulator.

**To Reproduce**
1. Start Apple II DeskTop with 15 800K 3.5-inch floppy disk images mounted at s5d1, s5d2, s6d1, s6d2 and s7d1 to s7d11 in GSplus.
2. The 800K 3.5-inch floppy disk images mounted at s6d1 and s6d2 falsely appear as 140K 5.25-inch floppy disks.
3. The 800K 3.5-inch floppy disk image remapped to s3d1 falsely appears as a RAMCard.
4. Clicking on the Special menu and going to Special > Format a Disk... or going to Special > Erase a Disk... freezes the emulator.

**Expected behavior**
With 15 800K 3.5-inch floppy disk images mounted at s5d1, s5d2, s6d1, s6d2 and s7d1 to s7d11 in GSplus, the 800K 3.5-inch floppy disk images mounted at s6d1 and s6d2 should not falsely appear as 140K 5.25-inch floppy disks and the 800K 3.5-inch floppy disk image remapped to s3d1 should not falsely appear as a RAMCard. Clicking on the Special menu and going to Special > Format a Disk... or going to Special > Erase a Disk... should not freeze the emulator.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 28 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Emulator bug. It's reporting a Disk II card in Slot 6 but not behaving like that's what it is.

**Comment by inexorabletash** [comment]
More specifically, if you use a disk image with more than 280 blocks, the emulator doesn't complain, and ProDOS is going to be extremely confused as the disk volume table will think there are more than 280 blocks, but attempts to write past that will fail. You'll probably corrupt the disk. Don't do this.

**Comment by c0mmander8** [comment]
What about clicking on the Special menu and going to Special > Format a Disk... or going to Special > Erase a Disk... freezing the emulator in this issue and issue #455?

**Comment by inexorabletash** [comment]
I haven't been able to repro freezing using multiple disk images. I suspect you may have some other variable going on, e.g. you have the same disk image mounted multiple times or something. As always, a screenshot or copy of your config file could help identify what's going on.

**Comment by c0mmander8** [comment]
I am unable to provide a screenshot or a copy of my GSplus configuration file.

**Comment by c0mmander8** [comment]
I did not have the same disk image mounted multiple times. I am unable to provide a screenshot or a copy of my GSplus configuration file.
