### ISSUE TITLE
GSplus: Bugs with 15 mounted 32 MB hard drive images

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#457]
**Describe the bug**
With 15 32 MB hard drive images mounted at s5d1, s5d2, s6d1, s6d2 and s7d1 to s7d11 in GSplus, the 32 MB hard drive images mounted at s6d1 and s6d2 falsely appear as 140K 5.25-inch floppy disks and the 32 MB hard drive image remapped to s3d1 falsely appears as a RAMCard. Clicking on the Special menu and going to Special > Format a Disk... or going to Special > Erase a Disk... does not freeze the emulator in this scenario.

**To Reproduce**
1. Start Apple II DeskTop with 15 32 MB hard drive images mounted at s5d1, s5d2, s6d1, s6d2 and s7d1 to s7d11 in GSplus.
2. The 32 MB hard drive images mounted at s6d1 and s6d2 falsely appear as 140K 5.25-inch floppy disks.
3. The 32 MB hard drive image remapped to s3d1 falsely appears as a RAMCard.
4. Clicking on the Special menu and going to Special > Format a Disk... or going to Special > Erase a Disk... does not freeze the emulator in this scenario.

**Expected behavior**
With 15 32 MB hard drive images mounted at s5d1, s5d2, s6d1, s6d2 and s7d1 to s7d11 in GSplus, the 32 MB hard drive images mounted at s6d1 and s6d2 should not falsely appear as 140K 5.25-inch floppy disks and the 32 MB hard drive image remapped to s3d1 should not falsely appear as a RAMCard.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 28 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Emulator bug. The hardware is claiming to be a Disk II in Slot 6.

**Comment by inexorabletash** [comment]
More specifically, if you use a disk image with more than 280 blocks, the emulator doesn't complain, and ProDOS is going to be extremely confused as the disk volume table will think there are more than 280 blocks, but attempts to write past that will fail. You'll probably corrupt the disk. Don't do this.
