### ISSUE TITLE
The "Warning! Do you want to save the new list on the system disk?" dialog box does not appear after deleting a Selector entry while booted from a RAMCard

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#459]
**Describe the bug**
The "Warning! Do you want to save the new list on the system disk?" dialog box does not appear after deleting a Selector entry by clicking on the Selector menu and going to Selector > Delete an Entry... while booted from a RAMCard.

**To Reproduce**
1. Start Apple II DeskTop while booted from a RAMCard.
2. Click on the Selector menu and go to Selector > Delete an Entry....
3. Select a Selector entry to delete.
4. Click OK.
5. The "Warning! Do you want to save the new list on the system disk?" dialog box does not appear.

**Expected behavior**
The "Warning! Do you want to save the new list on the system disk?" dialog box should appear after deleting a Selector entry by clicking on the Selector menu and going to Selector > Delete an Entry... while booted from a RAMCard.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 28 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
The "Warning! Do you want to save the new list on the system disk?" dialog box appears after adding a Selector entry by clicking on the Selector menu and going to Selector > Add an Entry... while booted from a RAMCard or editing a Selector entry by clicking on the Selector menu and going to Selector > Edit an Entry... while booted from a RAMCard.

**Comment by inexorabletash** [comment]
Nice catch.
