### ISSUE TITLE
Off by one in "Copy to RAMCard..." dialog when target is in volume directory

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#462]
**Describe the bug**
"Files remaining to copy:" in the "Copy to RAMCard..." dialog box briefly says "65,535" after briefly saying "0" when the copy of files and folders is completed.

**To Reproduce**
1. Start Apple II DeskTop while booted from a RAMCard.
2. Click on the Selector menu and go to Selector > Add an Entry....
3. Select a file or a folder to add to the Selector.
4. Under "Add a entry to the:", select "Run list".
5. Under "Copy to RAMCard:", select "at first use".
6. Click OK.
7. Click on the Selector menu and go to the bottom entry of that menu - that is the entry you have just added to the Selector.
8. The "Copy to RAMCard..." dialog box appears and begins copying files and folders to the RAMCard.
9. "Files remaining to copy:" in the "Copy to RAMCard..." dialog box briefly says "65,535" after briefly saying "0" when the copy of files and folders is completed.

**Expected behavior**
"Files remaining to copy:" in the "Copy to RAMCard..." dialog box should not say "65,535" after saying "0" when the copy of files and folders is completed.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 28 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
No repro for me. Can you be more specific about what you are adding to the selector? 

This sort of issue would occur if the count got out of sync, but without a repro it's hard to see why that would happen.

**Comment by c0mmander8** [comment]
I am adding the "Desk.Acc" folder located in the "A2.Desktop" volume, which is the "A2DeskTop-1.2-alpha28-en_800k.2mg" disk image, to the Selector in this issue. The RAMCard in this issue is the Apple IIGS Control Panel RAM5 RAM disk.

**Comment by c0mmander8** [comment]
The "A2.Desktop" volume, which is the "A2DeskTop-1.2-alpha28-en_800k.2mg" disk image, in this issue is located at s7d1.

**Comment by inexorabletash** [comment]
Thanks, that was useful:

![image](https://user-images.githubusercontent.com/771547/116637574-1c5c0000-a919-11eb-8f87-8fedd48eab9b.png)

**Comment by c0mmander8** [comment]
There is a painting error in the border of the "Copy to RAMCard..." dialog box in the screenshot you have just posted.

**Comment by c0mmander8** [comment]
The painting error in the right border of the "Copy to RAMCard..." dialog box in the screenshot you have just posted is now issue #465.

**Comment by inexorabletash** [comment]
Okay, found the minimal repro: it's when the target is in the root of a volume, e.g. `/VOL/ENTRY`. The initial enumeration of files doesn't include the volume dir in the count, but the iteration includes the creation of the folder, so there's the off-by-one.
