### ISSUE TITLE
Target volume in "Copy to RAMCard..." dialog box not case adjusted

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#463]
**Describe the bug**
The Apple IIGS Control Panel RAM5 RAM disk is shown as "RAM5" in the "Copy to RAMCard..." dialog box instead of being shown as "Ram5" like elsewhere in Apple II DeskTop.

**To Reproduce**
1. Start Apple II DeskTop while booted from the Apple IIGS Control Panel RAM5 RAM disk.
2. Click on the Selector menu and go to Selector > Add an Entry....
3. Select a file or a folder to add to the Selector.
4. Under "Add a entry to the:", select "Run list".
5. Under "Copy to RAMCard:", select "at first use".
6. Click OK.
7. Click on the Selector menu and go to the bottom entry of that menu - that is the entry you have just added to the Selector.
8. The "Copy to RAMCard..." dialog box appears and begins copying files and folders to the Apple IIGS Control Panel RAM5 RAM disk.
9. The Apple IIGS Control Panel RAM5 RAM disk is shown as "RAM5" in the "Copy to RAMCard..." dialog box instead of being shown as "Ram5" like elsewhere in Apple II DeskTop.

**Expected behavior**
The Apple IIGS Control Panel RAM5 RAM disk should be shown as "Ram5" in the "Copy to RAMCard..." dialog box like elsewhere in Apple II DeskTop.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 28 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Not just IIgs:

![image](https://user-images.githubusercontent.com/771547/116499303-b57b1000-a860-11eb-9fff-7c8ba7847d48.png)
