### ISSUE TITLE
Long file paths cause painting errors in the right border of the Copy..., Move..., Delete... and Copy to RAMCard... dialog boxes

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#465]
As referenced in the screenshot you have posted in issue #462, long file paths cause painting errors in the right border of the Copy..., Move..., Delete... and Copy to RAMCard... dialog boxes.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/116645332-75805f80-a92a-11eb-80b7-57c5e65533a3.png)
