### ISSUE TITLE
The startup disk is shown all in capital letters in the "New Folder..." dialog box when the "Control.Panels" folder is directly opened from the Apple menu

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#466]
**Describe the bug**
The startup disk is shown all in capital letters in the "New Folder..." dialog box when the "Control.Panels" folder is directly opened from the Apple menu instead of having GS/OS (ProDOS 2.5.x) filename casing applied or Apple II DeskTop case adjusting applied like when the "Control.Panels" folder is manually opened from the "Desk.Acc" folder.

**To Reproduce**
1. Start Apple II DeskTop while booted from "A2.Desktop", which is the "A2DeskTop-1.2-alpha28-en_800k.2mg" disk image,
2. Click on the Apple menu and go to "Control Panels".
3. The "Control.Panels" folder opens.
4. Click on the File menu and go to File > New Folder....
5. The startup disk is shown as "A2.DESKTOP" in the "New Folder..." dialog box instead of being shown as "A2.Desktop" like when the "Control.Panels" folder is manually opened from the "Desk.Acc" folder.

**Expected behavior**
The startup disk should have GS/OS (ProDOS 2.5.x) filename casing applied or Apple II DeskTop case adjusting applied in the "New Folder..." dialog box when the "Control.Panels" folder is directly opened from the Apple menu like when the "Control.Panels" folder is manually opened from the "Desk.Acc" folder.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 28 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
This would likely also apply to folders opened via the Selector menu.

**Comment by inexorabletash** [comment]
Screenshot for reference:

![image](https://user-images.githubusercontent.com/771547/116791320-4bd05100-aa6e-11eb-9c67-5b295f38ea4d.png)

This due to the DeskTop path being composed using the ProDOS PREFIX, which is capitalized. I'm going to mark this as Won't Fix because this would require iterating over all parent directories to find the file entries to extract the capitalization, which would be a significant performance hit during startup for such a minor issue.

**Comment by c0mmander8** [comment]
This issue does not also apply to folders opened via the Selector menu.

**Comment by c0mmander8** [comment]
Why does this bug not occur when folders are opened via the Selector menu?

**Comment by inexorabletash** [comment]
Selector entries are created by the program, and recorded in the SELECTOR.LIST file as mixed-case at the time they are created.
