### ISSUE TITLE
Renaming paths used by DeskTop breaks many things

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#467]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that key functionality in Apple II DeskTop, including links in the Apple menu, ceases to function when the startup disk is renamed while running Apple II DeskTop and that links are broken in the Selector when any file, folder or volume is renamed.

**Describe the solution you'd like**
Key functionality in Apple II DeskTop, including links in the Apple menu, should continue to function when the startup disk is renamed while running Apple II DeskTop and that links should not be broken in the Selector when any file, folder or volume is renamed.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
There is no other context or screenshots about this feature request here.

**Comment by c0mmander8** [comment]
The key functionality in Apple II DeskTop that ceases to function when the startup disk is renamed while running Apple II DeskTop is:

1. Links of files and folders in the Apple menu
2. File > Copy a File...
3. File > Delete a File...
4. File > Quit
5. Special > Format a Disk...
6. Special > Erase a Disk...
7. Special > Disk Copy...
8. Selector > Add an Entry...
9. Selector > Edit an Entry...
10. Selector > Delete an Entry...
11. Selector > Run an Entry...
12. Links of files and folders located on the startup disk in the Selector menu

Links of files and folders are also broken in the Selector when any file, folder or volume in the file path of that file or folder is renamed.

**Comment by inexorabletash** [comment]
You should try formatting the disk, that's fun too.

The alternative is obviously: "Don't Do That"

**Comment by c0mmander8** [comment]
Links of files and folders are also broken in the Apple menu when any file, folder or volume in the file path of that file or folder is renamed.

**Comment by inexorabletash** [comment]
* [ ] Renaming the path to DeskTop (current prefix) breaks things. 
  * This includes the following items, which are loaded using relative paths.
     * Overlays (loading parts of `DESKTOP2`)
     * Loading/saving `SELECTOR.LIST`
     * Loading Apple menu items 
     * Previewing items
     * Writing out updated `DESKTOP.FILE` (window positions) on exit
  * This could be fixed by updating the ProDOS prefix (and `RAMCARD_PREFIX`, if needed) if it is affected by the rename. 
* [ ] When DeskTop has copied itself to a RAMCard, renaming the original path causes actions that write back to the original path to fail. 
  * This includes:
    * Updating `SELECTOR.LIST` (selector entries)
    * Updating `DESKTOP.CONFIG` (control panel settings)
    * Writing out updated `DESKTOP.FILE` (window positions) on exit
  *  This could be fixed by updating the `DESKTOP_ORIG_PREFIX`, if needed.
*  [ ] Renaming paths used by Selector items causes them to fail to load. 
  * This could be fixed by updating any affected `SELECTOR.LIST` entries when affected by the rename.

**Comment by inexorabletash** [comment]
I'm going to close this out. The one remaining thing I'm aware of is that paths in Shortcuts would be broken by a rename.

Fixing this would require loading and potentially saving the `SELECTOR.LIST` file on _every_ rename, which I'm not in favor of. The shortcuts can be fixed by the user.
