### ISSUE TITLE
Should a RAMCard or the Apple IIGS Control Panel RAM5 RAM disk, when one of them is the startup disk, be shown in the upper right corner of the desktop and as the default volume in the Copy a File..., Delete a File... and Add an Entry... dialog boxes?

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#468]
Should a RAMCard or the Apple IIGS Control Panel RAM5 RAM disk, when one of them is the startup disk, be shown in the upper right corner of the desktop and as the default volume in the Copy a File..., Delete a File... and Add an Entry... dialog boxes?

**Comment by inexorabletash** [comment]
No. The order in reverse order of ProDOS DEVLST, which matches the OS's search for volumes during boot. The volume that DeskTop is running from is not a consideration.

**Comment by c0mmander8** [comment]
On the Mac and on the IIGS, the startup disk is shown in the upper right corner of the desktop and on the Mac and on the IIGS, the startup disk is the default volume in the Open..., Save... and Save As... dialog boxes, though.

**Comment by c0mmander8** [comment]
On the Mac and on the IIGS, this applies even if the startup disk is a RAM disk.

**Comment by c0mmander8** [comment]
This issue is updated in issue #658.

**Comment by inexorabletash** [comment]
Please don't leave comments like that. If you are viewing this page in a web browser, you'll see that GitHub automatically creates links between issues when mentioned. If you add them manually, it generates email and notifications, which are annoying.

**Comment by c0mmander8** [comment]
Since issue #658, commit ff2d615 has been implemented, the "1.2" milestone should be removed from this issue and the "Won't Fix" label should be reapplied to this issue.
