### ISSUE TITLE
Hang on File > New Folder after dragging a folder

### ISSUE THREAD

**Issue by inexorabletash** [a2stuff/a2d#471]
**Describe the bug**
File > New Folder hangs after a folder drag.

**To Reproduce**
1. Start DeskTop
2. Open a volume
3. File > New Folder, create "A", OK
4. File > New Folder, create "B", OK
5. Drag B onto A
6. File > New Folder. DeskTop hangs.

**Expected behavior**
No hang.

**Comment by inexorabletash** [comment]
The code for `cmd_new_folder` is getting trashed by `find_windows_for_prefix`, which is getting called with Y=0 from `update_vol_free_used_for_icon`...

**Comment by c0mmander8** [comment]
This issue also applies to folders with 1 character filenames contained in folder windows, not just volume windows. Did you fix those, too?
