### ISSUE TITLE
The heading above the Franklin ACE 2000 icon you added to a2d/res/notes/icons.txt in commit 02cb3d8 should say "Franklin ACE 2000" instead of saying "Franklin Ace 500" a second time and the heading above the Franklin ACE 500 icon in a2d/res/notes/icons.txt should say "Franklin ACE 500" instead of saying "Franklin Ace 500" the first time

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#472]
As referenced in commit 02cb3d8, the heading above the Franklin ACE 2000 icon you added to a2d/res/notes/icons.txt in commit 02cb3d8 should say "Franklin ACE 2000" instead of saying "Franklin Ace 500" a second time. Also, the heading above the Franklin ACE 500 icon in a2d/res/notes/icons.txt should say "Franklin ACE 500" instead of saying "Franklin Ace 500" the first time.

**Comment by inexorabletash** [comment]
Blocking this user for a month, in the hope that they can take the time to learn how to use the issue tracker properly and improve their communication skills.
