### ISSUE TITLE
Case of symbols

### ISSUE THREAD

**Issue by polluks** [a2stuff/a2d#474]
````
Building: desktop
ca65 --target apple2enh --list-bytes 0 --listing out/desktop.list -o out/desktop.o desktop.s
init.s(114): Error: Symbol 'BUTN2' is undefined
main.s(16272): Error: Symbol 'BUTN2' is undefined
make[1]: *** [out/desktop.o] Error 1
make: *** [desktop] Error 1
````

**Comment by inexorabletash** [comment]
BUTN2 is defined in cc65, `asminc/apple2.inc`

20a9c0c336 (Oliver Schmidt 2020-06-06 15:14:56 +0200 75)

Is it possible you have not updated your cc65 since then?

**Comment by inexorabletash** [comment]
Ping @polluks - can you check whether you have an up-to-date cc65?

**Comment by polluks** [comment]
Indeed, I was using V2.18

2021-06-11 3:03 GMT+02:00, Joshua Bell ***@***.***>:
