### ISSUE TITLE
Add "Startup" Control Panel

### ISSUE THREAD

**Issue by inexorabletash** [a2stuff/a2d#476]
Add a "Startup" control panel with options related to launching:

* [ ] Copy to RAMCard on startup #460 
* [ ] Launch Selector if present

These would modify `DESKTOP.SYSTEM` in the `header` area, just like the date/path storage.

**Comment by c0mmander8** [comment]
I am unable to see the complete list of changes in commit 5b848eb in my web browser. Does Apple II DeskTop now copy itself into a RAMCard, if a RAMCard is present, if the Apple key is held down while starting Apple II DeskTop if the "Copy to RAMCard (if present)" checkbox is unchecked in the new Startup control panel? This is an inversion of Apple II DeskTop's previous behavior. If Apple II DeskTop does not do this now, could you please add this feature?
