### ISSUE TITLE
Holding down the space bar while starting Apple II DeskTop should invert the "Run Selector (if present)" setting in the new Startup control panel

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#477]
**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem.

**Describe the solution you'd like**
Holding down the space bar while starting Apple II DeskTop should invert the "Run Selector (if present)" setting in the new Startup control panel. This proposed new feature should work together in conjunction with holding down the Apple key to invert the "Copy to RAMCard (if present)" setting in the new Startup control panel.

**Describe alternatives you've considered**
Just keep on checking and unchecking the "Run Selector (if present)" checkbox in the new Startup control panel.

**Additional context**
This feature request is useful for people who want to constantly switch between starting Apple II DeskTop and starting the Selector.

**Comment by inexorabletash** [comment]
Not interested.

**Comment by inexorabletash** [comment]
Note that if you hold down <key>Q</key> when the Selector is loading, it will launch DeskTop immediately, without fully starting the Selector app.

**Comment by c0mmander8** [comment]
Thank you for that tidbit.

**Comment by c0mmander8** [comment]
The inversion proposed in this feature request is only temporary and only until the next reboot / restart of Apple II DeskTop.
