### ISSUE TITLE
MGTK: how to write a sample app?

### ISSUE THREAD

**Issue by audetto** [a2stuff/a2d#478]
Hi,

I was trying to write an app using the MGTK framework.

I have only seen DeskAccs using this framework. Does it mean that "DA" and "MGTK Apps" are actually synonyms?

And that all it takes for an app to be recognised as MGTK is to have types as https://github.com/a2stuff/a2d/blob/7277694fa03a7f1538bdf000b12315a2387f77fd/desktop/internal.inc#L7?

Or, DAs are reserved for the system and different apps can be implemented?

I have tried a "do-nothing" prodos app and it seems to exit the desktop and reload it at the end. I was looking to create something more integrated (if possible).

**Comment by inexorabletash** [comment]
MGTK is just a library. Full documentation from Apple is here:

[MouseGraphics ToolKit](https://drive.google.com/file/d/1EHjwyu77FJAjNhAt8DwMxBhAdUL0RKMM/view?usp=sharing)
[Graphics Primitives](https://drive.google.com/file/d/1YqdtxkMlzEebU5HxL6sOv6PhhddSLhHe/view?usp=sharing)

(I've added a few more calls to MGTK though, which are documented [here](https://github.com/a2stuff/a2d/blob/main/mgtk/MGTK.md#miscellaneous))

An "MGTK app" would just be a ProDOS (but could be DOS 3.3, really) app (binary or SYS file) that includes the MGTK library and uses it. It would call the MGTK MLI with `StartDesktop` and `InitMenu` and then `GetEvent` in a loop, processing events like clicks and keys.  The section in https://github.com/a2stuff/a2d/blob/main/mgtk/MGTK.md#creating-applications-and-desktop-desk-accessories calls out what an app needs to do as part of the lifecycle. 

Desk Accessories (DAs) are a convention within the DeskTop app itself, which uses MGTK. They can call into DeskTop's copy of MGTK (which sits at Aux $4000) and have limited memory to play in so they don't trash DeskTop. They also need to call into DeskTop's own APIs for a few things (e.g. redrawing the desktop icons when a window moves). 

Are you wanting to write a true standalone app using MGTK, or a DA that runs inside DeskTop? For the former... take a look at the documentation listed above. I don't have a `hello_world.s` for you although it would be a good idea. (It doesn't really belong in this repo though.)

If you're want to write a DA, it's best to copy one of the existing ones.

I'm happy to help answer questions here or via chat somewhere!

**Comment by audetto** [comment]
Yes, I think you have answered and cleared my biggest misunderstanding on what is an *Application*.

I will start with a DA.
By reading the memory layout https://github.com/a2stuff/a2d/blob/main/desktop/README.md#memory-map I seem to understand that the area 0x0800 till 0x2000 is available to DAs. (or possibly only till 0x1B00 when they copy themselves to Aux).

So the maximum size for a DA is 6144 (or 4864), and indeed the biggest one `CONTROL.PANEL` is only 4786.

**Comment by inexorabletash** [comment]
Yep. PRs for the docs are welcome; they were written over time as I was disassembling to understand how things worked in the original code, but may not have been updated consistently with new findings and as I've extended the API. 

Keep the questions coming!

**Comment by DocDoom99** [comment]
There are still a few who to this days try to milk a few dollars for the latest available version of the MouseDesk Toolkit. It is for both ProDOS and UCSD Apple Pascal works with text, HGR and DHGR, comes with pdf manuals. If you really need this stuff I can share it, for free!

Marco

**Comment by inexorabletash** [comment]
Thanks @DocDoom99 - we actually have the early PDF docs (linked above) and the source code is not a blocker. The OP's questions here were more theoretical. We've picked them up over on https://github.com/cc65/cc65/issues/1531 so I'll close this out.
