### ISSUE TITLE
The "M" in "AM" and in "PM" in the date and time in list views is cut off from view and cannot be scrolled into view in windows with 3 or less items in them

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#479]
**Describe the bug**
The "M" in "AM" and in "PM" in the date and time in list views is cut off from view and cannot be scrolled into view in windows with 3 or less items in them.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open a window with with exactly 3 items in it.
3. Click on the View menu and go to View > by Name.
4. The right side of the date and time in the list view is cut off from view.
5. Scroll all the way to the right end of the window using the horizontal scrollbar.
6. The "M" in "AM" and in "PM" in the date and time in the list view is cut off from view and cannot be scrolled into view.

**Expected behavior**
The "M" in "AM" and in "PM" in the date and time in list views should be able to be scrolled into view in windows with 3 or less items in them.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 30 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
The "Clock" setting in the Control Panel control panel is correctly set for "12hr".

**Comment by inexorabletash** [comment]
It's not about the number of items, it's about the width of the window:

![image](https://user-images.githubusercontent.com/771547/122502606-c831db80-cfab-11eb-8edc-530ea005d160.png)
