### ISSUE TITLE
The "About this Apple II" window title string in This Apple should be "About This Apple II" instead, because "this" is always capitalized as "This" in title case

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#480]
The "About this Apple II" window title string in This Apple should be "About This Apple II" instead, because "this" is always capitalized as "This" in title case, just like the later Mac and the later IIGS. This This Apple window title string change should be made to the English original and an equivalent change should be made, where applicable, to all translations.

**Comment by inexorabletash** [comment]
Done.

Note that none of the other languages (Spanish, Italian, French, German) are changed. This is intentional - the title casing was verified using the Apple macOS Glossaries.
