### ISSUE TITLE
System Speed DA: Screen artifacts when cursor overlaps animation

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#481]
**Describe the bug**
The running man animation covers the cursor instead of the cursor covering the running man animation and this causes screen artifacts to occur.

**To Reproduce**
1. Start Apple II DeskTop.
2. Click on the Apple menu and go to Control Panels.
3. Open the System Speed control panel.
4. Put the cursor in the path of the running man animation or attempt to cover the running man animation with the cursor.
5. The running man animation covers the cursor instead of the cursor covering the running man animation and this causes screen artifacts to occur.

**Expected behavior**
The cursor should cover the running man animation instead of the running man animation covering the cursor and screen artifacts should not occur.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 31 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment]
This issue occurs whether the System Speed control panel is in "Normal" mode or the System Speed control panel is in "Fast" mode.

**Comment by inexorabletash** [comment]
Thanks. Should be an easy fix - drawing a bitmap needs to be wrapped in hiding the cursor. Will probably result in flickering, though.

**Comment by inexorabletash** [comment]
The fix (show/hide the cursor) was worse than the problem, which only manifested if you put the cursor over the animation. Will ponder a better fix.
