### ISSUE TITLE
Holding the Apple key down while starting Apple II DeskTop should temporarily enable "Copy to RAMCard" if the "Copy to RAMCard (if present)" setting in the new Startup control panel is unchecked and disabled

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#482]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that I cannot temporarily enable "Copy to RAMCard" if the "Copy to RAMCard (if present)" setting in the new Startup control panel is unchecked and disabled.

**Describe the solution you'd like**
As referenced in issue #460 and issue #476, holding the Apple key down while starting Apple II DeskTop should temporarily enable "Copy to RAMCard" if the "Copy to RAMCard (if present)" setting in the new Startup control panel is unchecked and disabled. This proposed new feature is in addition to Apple II DeskTop's current behavior and an inversion of Apple II DeskTop's current behavior of holding the Apple key down while starting Apple II DeskTop temporarily disabling "Copy to RAMCard" if the "Copy to RAMCard (if present)" setting in the new Startup control panel is checked and enabled.

**Describe alternatives you've considered**
Just keep on checking and unchecking the "Copy to RAMCard (if present)" checkbox in the new Startup control panel.

**Additional context**
This feature request is useful for people who want to easily override their "Copy to RAMCard (if present)" setting in the new Startup control panel.

**Comment by inexorabletash** [comment]
Not interested. The use is too niche.
