### ISSUE TITLE
Laser 128: /RAM5 is erased when running This Apple DA

### ISSUE THREAD

**Issue by JavRivera** [a2stuff/a2d#483]
![4DF01F62-ECFC-43D7-BCF9-4F9B990A1970](https://user-images.githubusercontent.com/86275043/122851951-d2bae080-d2dd-11eb-83ea-0fb9f50638f5.jpeg)

https://user-images.githubusercontent.com/86275043/122851965-d8182b00-d2dd-11eb-87e7-5401739e971a.MOV

**Comment by inexorabletash** [comment]
@JavRivera Can you confirm:

* You downloaded the disk image from https://github.com/a2stuff/a2d/releases/tag/v1.2-alpha31 ?
* You downloaded the 800k image?
* You're testing on a Laser 128, I'm guessing? What are you using for the drive?
* You let it copy itself to RAMCard on start?

I can't repro here under emulation. The error you're seeing could happen if the CONTROL.PANELS or SCREEN.SAVERS folders were not present or were not copied.

* Can you attach a photo of the contents of the two drives? The A2.Desktop 800k floppy and Ram5 ?
* Can you try opening the A2.Desktop drive, and open those folders manually?

**Comment by inexorabletash** [comment]
The reporter mentioned on chat that this only occurs after the This Apple DA is run. 

Obvious possibilities are (1) memory corruption or (2) the slot probing causes issues with the RAMCard.

**Comment by inexorabletash** [comment]
Yay, I can repro on my Laser 128. 

After launching This Apple, Ram5 is empty!

**Comment by inexorabletash** [comment]
Repro:

* Launch DeskTop on a Laser 128
* Copy a file to the Ram5 volume. You can open/close the volume to confirm the file is present.
* Run the This Apple DA 
* Close the DA window
* Open the Ram5 volume. 

Expect: The file is still present.
Actual: The file is gone!

**Comment by inexorabletash** [comment]
Okay, it's not memory corruption, and not the slot scan.

It's the SmartPort calls. Both the slinky card RAM check and the device count/name lookups are causing the ramdisk to get reformatted; commenting out one or the other isn't enough. If I comment out both, Ram5 remains intact.

* https://github.com/a2stuff/a2d/blob/main/desk.acc/this.apple.s#L1632
* https://github.com/a2stuff/a2d/blob/main/desk.acc/this.apple.s#L1746

**Comment by inexorabletash** [comment]
Reading through the code for the slinky card ram check, nothing leaps out to me as wrong. When I have time, I'll try having the code run from Main rather than Aux, in case bank switching and the Laser firmware are at odds somehow. Strange that I'm getting the correct result from the memory size query if the call is wrong, though!

**Comment by inexorabletash** [comment]
I might have to invoke @mgcaret for another look at the code here.

**Comment by mgcaret** [comment]
I don’t see anything that jumps out at me with a quick once-over.  I don’t have any experience with the ‘128 so I am not sure how the RAM disk is implemented in hardware.  

The main possibilities seem to be:
  - hardware probing messes up the actual data
  - Smartport probing has unexpected consequences on the 128.

I think that isolating the various chunks of code until it stops happening will be necessary to identify the ‘what’ and then we can figure out the ‘why’ from there.

**Comment by mgcaret** [comment]
As far as hardware probes go, I tend to wonder about possible side effects of non-passive probes like the Z80 and Uthernet code do.

**Comment by inexorabletash** [comment]
In theory, I've isolated it down to just the SmartPort STATUS calls. Nerf just those in the DA and everything is fine. But that doesn't mean that e.g. the non-passive probes don't "prime" the SP calls to have bad side effects (although I don't think they'll get hit on the Laser)

I'll try implementing a stand-alone binary that does the SP calls. If that doesn't manifest the problem, start slimming down the DA.

**Comment by inexorabletash** [comment]
>  I'll try having the code run from Main rather than Aux, in case bank switching and the Laser firmware are at odds somehow

Boom, this was it. Probably doesn't like having the screen holes yoinked away from underneath it.

Making sure all SmartPort calls come from Main solved the problem.

**Comment by JavRivera** [comment]
Where's Alpha 32 to test??!!
;D

**Comment by mgcaret** [comment]
Oh yeah, waaaay too much stuff in Apple II Land depend on the integrity of the screen holes, and they are easy to mess up.  

Funny thing is I almost mentioned them, but I figured the firmware ought to know which bank is in play.
