### ISSUE TITLE
Holding the Shift key down while starting Apple II DeskTop should temporarily disable "Copying Apple II DeskTop into RAMCard"

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#484]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that I cannot hold the Shift key down while starting Apple II DeskTop to temporarily disable "Copying Apple II DeskTop into RAMCard" like I can do while starting the Mac and the IIGS to temporarily disable INITs / Extensions. 

**Describe the solution you'd like**
Holding the Shift key down while starting Apple II DeskTop should temporarily disable "Copying Apple II DeskTop into RAMCard", just like holding down the Apple key while starting Apple II DeskTop already does, just like the Mac and the IIGS.

**Describe alternatives you've considered**
Just keep on holding down the Apple key while starting Apple II DeskTop in order to temporarily disable "Copying Apple II DeskTop into RAMCard".

**Additional context**
This feature request is useful for people who are already used to and have it in their muscle memory to hold down the Shift key while starting the computer to temporarily disable INITs / Extensions on the Mac and on the IIGS.

**Comment by inexorabletash** [comment]
There's already a shortcut for this. Adding another one is not worthwhile.

**Comment by c0mmander8** [comment]
Just like Apple-` and Apple-Tab to switch windows, and Apple-clicking and Shift-clicking to select multiple icons, it is extremely useful to accommodate multiple and various muscle memories. I think this feature request is worthwhile.

**Comment by c0mmander8** [comment]
In light of you already implementing Apple-\` and Apple-Tab to cycle windows forwards in issue #143, commit 6800e00, you already implementing Shift-Apple-\` to cycle windows backwards in issue #230, commit 1c4acb2, you already implementing Shift-Apple-Tab to cycle windows backwards in issue #230, commit 62dae54, and you already implementing Shift-clicking to select multiple contiguous and/or noncontiguous icons in issue #340, commit 68835d6, please reconsider your decision and please reopen this issue. Holding the Shift key down while starting Apple II DeskTop should temporarily disable "Copying Apple II DeskTop into RAMCard...", just like holding down the Apple key while starting Apple II DeskTop already does, just like the Mac and the IIGS. This feature request is useful for people who are already used to and have it in their muscle memory to hold down the Shift key while starting the computer to temporarily disable INITs / Extensions on the Mac and on the IIGS. Just like Apple-\` and Apple-Tab to cycle windows forwards, Shift-Apple-\` and Shift-Apple-Tab to cycle windows backwards, and Apple-clicking and Shift-clicking to select multiple contiguous and/or noncontiguous icons, it is extremely useful to accommodate multiple and various muscle memories. I think this feature request is indeed worthwhile.
