### ISSUE TITLE
The background of an error dialog box becomes transparent instead of remaining an opaque white the second time and subsequent times that the same error dialog box appears in relation to the same file

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#486]
**Describe the bug**
The background of an error dialog box becomes transparent instead of remaining an opaque white the second time and subsequent times that the same error dialog box appears in relation to the same file.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open a window.
3. Double-click on a file that Apple II DeskTop cannot open.
4. A dialog box appears stating "This file cannot be opened.".
5. The background of the error dialog box is correctly an opaque white.
6. Click OK.
7. Double-click on that same file that Apple II DeskTop cannot open a second time.
8. A dialog box appears a second time stating "This file cannot be opened.".
9. This time though, the background of the error dialog box has become transparent.
10. Click OK.
11. Double-click on that same file that Apple II DeskTop cannot open a third time.
12. A dialog box appears a third time stating "This file cannot be opened.".
13. The background of the error dialog box has become transparent again.
14. Click OK.

**Expected behavior**
The background of an error dialog boxes should remain an opaque white instead of becoming transparent the second time and subsequent times that the same error dialog box appears in relation to the same file.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 31 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
This bug does not occur if you keep on double-clicking on different files that Apple II DeskTop cannot open instead of double-clicking on the same file that Apple II DeskTop cannot open repeatedly.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/123351334-ba330c00-d511-11eb-8504-3b98c7c441d5.png)
