### ISSUE TITLE
SYSTEM.SPEED alters video setting

### ISSUE THREAD

**Issue by GG-62321** [a2stuff/a2d#488]
Suggest viewing attached video:
https://user-images.githubusercontent.com/86381664/123167805-ab2e5a00-d43c-11eb-913c-b80a2b3e9001.mov

**Describe the bug**
Using SYSTEM.SPEED control panel, clicking either choice Normal or Fast changes video from monochrome to color (or worse).

**To Reproduce**
1. Start DeskTop
2. Click on Apple menu
3. Click Control Panels
4. Click SYSTEM.SPEED
5. click Fast twice or click Normal

**Expected behavior**
No change - the IIC does not include any speed up hardware - it is stock.

**Screenshots**
See attached video

**System Details (please complete the following information):**
 - System Apple IIc (ROM 4)
 - ProDOS version 2.4.1
 - DeskTop version 1.2-alpha31 June 19, 2021
 - Other Floppy EMU SmartPort w/2 32MB drives
 - Video is Apple RBG w/Video-7

**Additional context**
This is my first time playing with Apple Desktop

**Comment by inexorabletash** [comment]
Heh, I have the Video-7 adapter for the IIc but no TTL monitor or adapter to use it with.

The NORMFAST code is kinda hinkey.... I'll see if anyone has fixed this with other forks.

**Comment by GG-62321** [comment]
I retested using an Apple Color monitor.

Clicking Fast does not produce any obvious problems but clicking Normal seems (to me) to switch to 40-col mode.  Clicking Fast restores the display mode.

https://user-images.githubusercontent.com/86381664/123487999-ad2b2100-d5d4-11eb-9b56-2ad2a66a2320.mov
