### ISSUE TITLE
Files that are invisible in other operating systems should not appear in the Apple menu in Apple II DeskTop

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#490]
Files that are invisible in other operating systems, such as "Finder.Data" - GS/OS Finder window data files from GS/OS for users of the Apple IIGS - and "Icon" - Macintosh Finder custom icon files from the Classic Mac OS for users of the Macintosh LC PDS Apple IIe Option Card, should not appear in the Apple menu in Apple II DeskTop.

**Comment by c0mmander8** [comment]
As referenced in issue #491, other files that cannot be opened by Apple II DeskTop should also not appear in the Apple menu in Apple II DeskTop.

**Comment by inexorabletash** [comment]
This is redundant with #491
