### ISSUE TITLE
Don't include files that cannot be opened in the Apple menu

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#491]
Files that cannot be opened by Apple II DeskTop should not appear in the Apple menu in Apple II DeskTop.

**Comment by c0mmander8** [comment]
As referenced in issue #490, this includes files that are invisible in other operating systems, such as "Finder.Data" - Apple IIGS Finder window data files from GS/OS for users of the Apple IIGS - and such as "Icon" - Macintosh Finder custom icon files from the Classic Mac OS for users of the Macintosh LC PDS Apple IIe Option Card.

**Comment by inexorabletash** [comment]
This sounds a bit like "if it hurts, then don't do it", but the duplicate bug indicates the use case: files may be added by the OS, not the user.
