### ISSUE TITLE
Regression: Disk Copy is broken in Apple II DeskTop 1.2 Alpha 31

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#492]
**Describe the bug**
Disk Copy is broken in Apple II DeskTop 1.2 Alpha 31. This is a regression in Apple II DeskTop 1.2 Alpha 31. Disk Copy was not broken in Apple II DeskTop 1.2 Alpha 28.

**To Reproduce**
1. Start Apple II DeskTop.
2. Click on the Special menu and go to Special > Disk Copy....
3. The "Quick Copy" window appears in Disk Copy stating "Select source disk".
4. Click on the Options menu and go to Options > Disk Copy.
5. The "Disk Copy" window appears in Disk Copy stating "Select source disk".
6. Select a volume and click OK.
7. The "Disk Copy" window appears in Disk Copy stating "Select destination disk".
8. Select another volume and click OK.
9. A dialog box appears stating "Insert source disk and click OK.".
10. Click OK or Cancel by using the mouse and not by pressing Return or Esc on the keyboard.
11. The "Insert source disk and click OK." dialog box disappears and the "Quick Copy" window appears in Disk Copy stating "Select source disk" with its window borders missing.
12. Click on the Options menu and see that there is a check mark next to both Options > Quick Copy and Options > Disk Copy.
13. If you use the keyboard instead of the mouse in step 10 and eventually go on to actually start the copy, clicking on any resulting dialog box with the mouse will crash Disk Copy instead.

**Expected behavior**
Disk Copy should work properly, like it did in Apple II DeskTop 1.2 Alpha 28.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 31 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
Disk Copy crashes after step 10 instead of step 11 occurring in Apple II DeskTop 1.2 Alpha 29 and in Apple II DeskTop 1.2 Alpha 30.

**Comment by inexorabletash** [comment]
Thanks for identifying the regression range. The cause is b748c7bb7b596fe053284925e2c271ad1627b241 - the Disk Copy code was switched to use the common alert button lib, but the MGTK relay call mechanism wasn't hooked up so the OK/Cancel etc buttons would hang/crash on mouse click.
