### ISSUE TITLE
Eliminate the empty space between the word "available" and the vertical scrollbar up arrow on the right side of the volume info header

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#493]
Eliminate the empty space between the word "available" and the vertical scrollbar up arrow on the right side of the volume info header, just like the early Mac and the IIGS.

**Comment by inexorabletash** [comment]
Right-aligned strings are more complex than it would assume. Left aligned-strings can be drawn by moving the current position to a fixed start location, and drawing each substring (e.g. label, number), and drawing spaces to erase a previous shorter string. Drawing right-aligned strings requires composing all of the substrings into a buffer, shifting the string to have spaces as a prefix, computing the length, offsetting the current position, and drawing the string.

It's not worth my time or the code complexity for this, although I wouldn't object if someone submitted a good patch.

**Comment by c0mmander8** [comment]
Can't you eliminate the empty space between the word "available" and the vertical scrollbar up arrow on the right side of the volume info header while still using left-aligned strings?

**Comment by c0mmander8** [comment]
**Describe the bug**
Please reopen this issue. Even with the right side of the volume info header displaying the maximum number of digits possible for a ProDOS volume, there is still some empty space between the word "available" and the vertical scrollbar up arrow on the right side of the volume info header. I think this bug is from when you briefly changed changed the size displayed in the volume info header from "K" to "KB" and back again.

**To Reproduce**
Steps to reproduce the behavior:
1. Start Apple II DeskTop with a fresh copy of "Live.Install" mounted, which is a fresh copy of the "Live.Install.po" disk image from ftp://ftp.apple.asimov.net/pub/apple_II/images/gs/os/gsos/Apple_IIGS_System_6.0.4/.
2. Open "Live.Install".
3. The right side of the volume info header says "27,422K available".
4. Even with the right side of the volume info header displaying the maximum number of digits possible for a ProDOS volume, there is still some empty space between the word "available" and the vertical scrollbar up arrow on the right side of the volume info header.
5. I think this bug is from when you briefly changed changed the size displayed in the volume info header from "K" to "KB" and back again.

**Expected behavior**
With the right side of the volume info header displaying the maximum number of digits possible for a ProDOS volume, there should be no empty space between the word "available" and the vertical scrollbar up arrow on the right side of the volume info header.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 33 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
I think this bug is from when you briefly changed changed the size displayed in the volume info header from "K" to "KB" and back again.

**Comment by c0mmander8** [comment]
This is now a bug that can be fixed while still using left-aligned strings.

**Comment by c0mmander8** [comment]
This bug is definitely from when you briefly changed changed the size displayed in the volume info header from "K" to "KB" and back again.

**Comment by c0mmander8** [comment]
I have confirmed that this bug is definitely from when you briefly changed changed the size displayed in the volume info header from "K" to "KB" and back again.

**Comment by c0mmander8** [comment]
I am sorry and I apologize for the repeated posts in this issue and in issue #523. Please do not suspend or ban me. Thank you for your trouble.
