### ISSUE TITLE
Apple II DeskTop makes multiple copies of a folder you are copying within itself, one inside another, like a nesting doll instead of making just 1 copy of the folder

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#495]
**Describe the bug**
Apple II DeskTop makes multiple copies of a folder you are copying within itself, one inside another, like a nesting doll instead of making just 1 copy of the folder.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open a window.
3. Click on the File menu and go to File > New Folder....
4. Enter a name for the new folder.
5. Click OK.
6. Click on the File menu and go to File > Copy a File....
7. Select the folder you have just created.
8. Click OK.
9. Select the folder you have just created again.
10. Click OK.
11. Apple II DeskTop makes multiple copies of the folder you are copying within itself, one inside another, like a nesting doll instead of making just 1 copy of the folder.
12. Microscopic black dots appear on the top of the menu bar above the Apple menu.
13. A dialog box appears stating, "The syntax of the pathname is invalid.".

**Expected behavior**
Apple II DeskTop should make 1 copy of a folder you care copying within itself instead of making multiple copies of the folder, one inside another, like a nesting doll.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 32 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
"Files remaining to copy:" in the "Copy..." dialog box starts decreasing from "0", then going to "65,535" and decreasing from that.

**Comment by c0mmander8** [comment]
Why did you have to disable copying a folder within itself in order to fix this bug?

**Comment by inexorabletash** [comment]
This was the easiest change to define and implement. It's also what macOS does, with a similar error alert (in System 6) or just ignoring the drag/drop (in macOS 10)

**Comment by c0mmander8** [comment]
Apple IIGS GS/OS System 6.0.1 and later allow you to copy, but not move, a folder, but not a volume, within itself though.
