### ISSUE TITLE
Enable highlighting of multiple characters with the insertion point to delete or replace them throughout Apple II DeskTop, Disk Copy, the Selector and desk accessories

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#496]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that I cannot highlight characters with the insertion point to delete or replace them in Apple II DeskTop, Disk Copy, the Selector and desk accessories.

**Describe the solution you'd like**
As referenced in issue #203, enable highlighting of multiple characters with the insertion point to delete or replace them throughout Apple II DeskTop, Disk Copy, the Selector and desk accessories, just like the Mac and the IIGS.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
There is no other context or screenshots about this feature request here.

**Comment by inexorabletash** [comment]
Too complex
