### ISSUE TITLE
When running from RAMCard, Control panel settings are not saved to the startup disk if Desktop.Config does not exist

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#498]
**Describe the bug**
Selector entries and control panel settings are not saved to the startup disk while booted from a RAMCard if the Selector.List and Desktop.Config files are missing from the startup disk. This issue is the root cause of issue #497.

**To Reproduce**
1. Start Apple II DeskTop from "A2.Desktop", which is the "A2DeskTop-1.2-alpha32-en_800k.2mg" disk image, while booted from a RAMCard.
2. Click on the Apple menu and go to Control Panels.
3. Open the Control.Panel control panel.
4. Change the desktop pattern and check and enable "RGB Color" setting.
5. Set the "Clock" setting to "24hr".
6. Close the Control.Panel control panel.
7. Click on the File menu and go to File > Quit.
8. Turn off the computer.
9. Turn on the computer.
10. Restart Apple II DeskTop from the same "A2.Desktop" disk image as in step 1, which is the "A2DeskTop-1.2-alpha32-en_800k.2mg" disk image, while either booted from a RAMCard or not booted from a RAMCard.
11. The desktop pattern is back to the default desktop pattern and "RGB Color" is disabled.
12. The "Clock" setting is back to "12hr".

**Expected behavior**
Selector entries and control panel settings should be saved to the startup disk while booted from a RAMCard if the Selector.List and Desktop.Config files are missing from the startup disk, and either one or both of the Selector.List and Desktop.Config files, as the case may be, should be automatically created by Apple II DeskTop on the startup disk in this scenario.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 32 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
The RAMCard I am booting from is the Apple IIGS Control Panel RAM5 RAM disk.

**Comment by inexorabletash** [comment]
Not the same root cause as #497; it's better to avoid speculating and filing bugs that are too general.

**Comment by inexorabletash** [comment]
The causes were similar, but "root cause" has a special meaning.
