### ISSUE TITLE
Create a new Apple II DeskTop numbered error message dialog box string stating, "A volume can't be moved or copied into itself.", and, if you have not done so already in issue #495, commit ce36a0a, prevent a volume from being moved or copied within itself, within its own folders or within its own subfolders

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#499]
Create a new Apple II DeskTop numbered error message dialog box string stating, "A volume can't be moved or copied into itself.", and, if you have not done so already in issue #495, commit ce36a0a, prevent a volume from being moved or copied within itself, within its own folders or within its own subfolders.

**Comment by inexorabletash** [comment]
Another warning: please do not make issue titles entire paragraphs. 

The change probably applies to volumes as well. Adding a separate string for that issue is not worth the size impact.

**Comment by inexorabletash** [comment]
The message could be made more generic ("item" instead of "folder"). Please don't file a bug about that, though.

**Comment by c0mmander8** [comment]
What about stating "A folder or volume can't be moved or copied into itself." instead of stating "An item can't be moved or copied into itself."?

**Comment by c0mmander8** [comment]
I prefer stating "A folder or volume can't be moved or copied into itself." instead of stating "An item can't be moved or copied into itself.".

**Comment by c0mmander8** [comment]
As referenced in commit 2b9292b and issue #502, the Apple II DeskTop numbered error message dialog box string stating "An item can't be moved or copied into itself." should state "A folder or volume can't be moved or copied into itself." instead.
