### ISSUE TITLE
Eliminate the empty space on the left side of the menu bar located to the left of the "Disk Copy Version 1.2" menu bar splash screen when launching Disk Copy

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#500]
Eliminate the empty space on the left side of the menu bar located to the left of the "Disk Copy Version 1.2" menu bar splash screen when launching Disk Copy.

**Comment by c0mmander8** [comment]
Can't you still use left-aligned strings to eliminate the empty space I requested in issue #493 and issue #494?

**Comment by inexorabletash** [comment]
Not worth the effort. 

Also, I don't think you understand what "right aligned" means. Please stop repeating yourself about issues. If you're so passionate about little things like this, learn to code and try fixing them yourself.
