### ISSUE TITLE
Reenable making a copy, but please do not reenable moving, of a folder or a volume within itself

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#503]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that I cannot make a copy of a folder or a volume within itself.

**Describe the solution you'd like**
Reenable making a copy, but please do not reenable moving, of a folder or a volume within itself, just like Apple IIGS GS/OS System 6.0.1 and later allow with folders.

**Describe alternatives you've considered**
Make a copy of the folder that I want to be copied within itself to another folder first and then move that copy to its final location.

**Additional context**
There is no other context or screenshots about this feature request here.

**Comment by inexorabletash** [comment]
Not interested. Niche use case in complex code and easy work-around.
