### ISSUE TITLE
Additional RELEASE-NOTES.md string changes

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#504]
Additional RELEASE-NOTES.md string changes:

"* Localizations into these languages: ([#327](https://github.com/a2stuff/a2d/issues/327))
    * English
    * French
    * Italian
    * Spanish
    * German" should be 
"* Localizations into these additional languages: ([#327](https://github.com/a2stuff/a2d/issues/327))
    * French
    * Italian
    * Spanish
    * German" because Apple II DeskTop 1.1 was already available in English.

"* Windows restored when DeskTop is relaunched. ([#210](https://github.com/a2stuff/a2d/issues/210))" should be 
"* Windows restored when DeskTop is relaunched. ([#210](https://github.com/a2stuff/a2d/issues/210), [#213](https://github.com/a2stuff/a2d/issues/213))".

"* Show Text File DA: Keyboard support. **Esc** quits, arrows scroll. ([#4](https://github.com/a2stuff/a2d/issues/4))" should be 
"* Show Text File DA: Keyboard support. **Esc** quits, arrow keys scroll, and **Space bar** toggles between Proportional mode and Fixed mode. ([#4](https://github.com/a2stuff/a2d/issues/4), [#403](https://github.com/a2stuff/a2d/issues/403))".

 "* **Startup**
    * Toggle startup options. ([#476](https://github.com/a2stuff/a2d/issues/476))" should be 
" * **Startup**
    * Toggle startup options. ([#460](https://github.com/a2stuff/a2d/issues/460), [#476](https://github.com/a2stuff/a2d/issues/476))".

Add an entry stating "* Desk accessories, directories, and previewable files can be launched from the Selector menu and **Selector > Run an Entry...**" while making a note that these file types still cannot be launched when booted from the Selector directly at startup. 

Also, add an entry to the Release Notes referencing issue #190.

**Comment by c0mmander8** [comment]
Corrections for Additional RELEASE-NOTES.md string changes:

"* **Startup**
    * Toggle startup options. ([#476](https://github.com/a2stuff/a2d/issues/476))" should be 
"* **Startup**
    * Toggle startup options. ([#460](https://github.com/a2stuff/a2d/issues/460), [#476](https://github.com/a2stuff/a2d/issues/476))".

**Comment by inexorabletash** [comment]
> because Apple II DeskTop 1.1 was already available in English.

The notes intentionally contain all localizations, for completeness.

> "* Windows restored when DeskTop is relaunched. ([#210](https://github.com/a2stuff/a2d/issues/210), [#213](https://github.com/a2stuff/a2d/issues/213))".

Context like this is not necessary. 

> "* Show Text File DA: Keyboard support. **Esc** quits, arrow keys scroll, and **Space bar** toggles between Proportional mode and Fixed mode. ([#4](https://github.com/a2stuff/a2d/issues/4), [#403](https://github.com/a2stuff/a2d/issues/403))".

Added, thanks.

>    * Toggle startup options. ([#460](https://github.com/a2stuff/a2d/issues/460), [#476](https://github.com/a2stuff/a2d/issues/476))".

This level of detail is not necessary.

> Add an entry stating...

Not important enough.

> Also, add an entry to the Release Notes referencing issue #190.

Not important enough.

> Corrections for Additional RELEASE-NOTES.md string changes:

Please don't add noise to issues by adding additional comments just to correct whitespace in your text.

**Comment by c0mmander8** [comment]
Now that you are extensively revising a2d/RELEASE-NOTES.md, please reopen this issue and please reconsider the string changes and string additions I have proposed to a2d/RELEASE-NOTES.md in this issue.
