### ISSUE TITLE
The size of a volume stated in File > Get Info and stated in the volume info header does not match the size of a volume stated in Special > Get Size

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#506]
**Describe the bug**
The size of a volume stated in File > Get Info and stated in the volume info header does not match the size of a volume stated in Special > Get Size.

**To Reproduce**

1. Start Apple II DeskTop while booted from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha32-en_800k.2mg" disk image,
2. Select the "A2.Desktop" volume.
3. Click on the File menu and go to File > Get Info.
4. "Size used/total:" is "243K / 800K".
5. Click OK.
6. Click on the Special menu and go to File > Get Size.
7. "Space used on disk:" is "239K".
8. Click OK.
9. Open the "A2.Desktop" volume.
10. The volume info header states "243K in disk".
11. Click on the File menu and go to File > Select All.
12. Click on the Special menu and go to File > Get Size.
13. "Space used on disk:" is "239K".
14. I do not know which stated size, if either of them, is the true size.

**Expected behavior**
The size of a volume stated in File > Get Info and stated in the volume info header should match the size of a volume stated in Special > Get Size.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 32 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
I do not know which stated size, if either of them, is the true size.

**Comment by inexorabletash** [comment]
Special > Get Size counts the size of selected or contained files. File > Get Info on a volume looks at the actual used/free block count. These differ in some cases. For volumes, there is the overhead of the volume bitmap, and potentially bad blocks.

**Comment by inexorabletash** [comment]
I'm going to close this out since it doesn't seem like a big deal that the two are different, as long as Get Size is consistently reporting a the number. 

A plausible change would be to short-circuit the size calc if the target is a volume, but since that logic is re-used as part of the pass to compute the number of files before other file operations it would be risky and low benefit.
