### ISSUE TITLE
Enable opening binary (BIN) files without first having to hold the Apple key down in Apple II DeskTop?

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#508]
Why do you first have to hold the Apple key down to open binary (BIN) files in Apple II DeskTop? If that reason no longer makes sense, if it ever did in the first place, enable opening binary (BIN) files without first having to hold the Apple key down in Apple II DeskTop. Please do not implement this feature request if first having to hold the Apple key down to open binary (BIN) files in Apple II DeskTop still makes sense.

**Comment by inexorabletash** [comment]
I suspect this was because binary files could be executable or could be data files like images, and the authored wanted to protect users from that. 

I think the current scheme works fine since it prevents accidental opening but if you know what you're doing you can still run them.

**Comment by c0mmander8** [comment]
What would be the downside to implementing this feature request?

**Comment by ph0enix-c0der** [comment]
The "Won't Fix" label should be removed from this issue and this issue should be added to the Apple II DeskTop 1.2 milestone.
