### ISSUE TITLE
Adding a single item to the "Desk.Acc" folder on the startup disk will result in that item not copying itself to the RAMCard and that item not being listed in the Apple menu

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#509]
**Describe the bug**
Adding a single item to the "Desk.Acc" folder on the startup disk will result in that item not copying itself to the RAMCard and that item not being listed in the Apple menu.

**To Reproduce**
1. Start Apple II DeskTop while booted from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha32-en_800k.2mg" disk image, while booted from a RAMCard or while not booted from a RAMCard.
2. Open the "Desk.Acc" folder on the "A2.Desktop" volume.
3. Open the "Control.Panels" folder on the "A2.Desktop" volume.
4. Move the "Date" control panel from the "Control.Panels" folder on the "A2.Desktop" volume to the "Desk.Acc" folder on the "A2.Desktop" volume.
5. Quit Apple II DeskTop.
6. Shut down the computer.
7. Turn on the computer.
8. Restart Apple II DeskTop while booted from "A2.Desktop", while booted from a RAMCard this time.
9. Click on the Apple menu and see that the "Date" control panel is not listed there.
10. Open the "Desk.Acc" folder on the RAMCard and see that the "Date" control panel is not located inside that folder.
11. Open the "Desk.Acc" folder on the "A2.Desktop" volume.
12. Open the "Control.Panels" folder on the "A2.Desktop" volume.
13. Move the "Control.Panel" control panel from the "Control.Panels" folder on the "A2.Desktop" volume to the "Desk.Acc" folder on the "A2.Desktop" volume.
14. Quit Apple II DeskTop.
15. Shut down the computer.
16. Turn on the computer.
17. Restart Apple II DeskTop while booted from "A2.Desktop", while booted from a RAMCard.
18. Click on the Apple menu and see that the "Date" control panel is now listed there, but that the "Control.Panel" control panel is not listed there, because there is only enough room in the Apple menu for 12 items.
19. Open the "Desk.Acc" folder on the RAMCard and see that both the "Date" control panel and the "Control.Panel" control panel are now located inside that folder.

**Expected behavior**
Adding a single item to the "Desk.Acc" folder on the startup disk should result in that item copying itself to the RAMCard and that item being listed in the Apple menu.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 32 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
The RAMCard I am booting from is the Apple IIGS Control Panel RAM5 RAM disk. This bug occurs whether the additional item added to the "Desk.Acc" folder is a desk accessory, a folder, an executable file or a previewable file. This bug does not occur when removing an item or multiple items from the "Desk.Acc" folder.

**Comment by c0mmander8** [comment]
I meant to say, "Adding a single item to the "Desk.Acc" folder on the startup disk will result in that item not copying itself to the RAMCard and that item not being listed in the Apple menu while booted from the RAMCard.". The single item is still listed in the Apple menu while not booted from a RAMCard.

**Comment by inexorabletash** [comment]
Weird! Thanks for such a detailed set of repro steps. I was able to duplicate it. Not sure what's going on yet.

One note though: when you write _"while booted from a RAMCard"_ it is confusing; that implies you are copying PRODOS to a ramdisk and booting (starting the operating system) from the RAMDisk. You should say "when copied to a RAMCard" or "when running from a RAMCard" instead.

**Comment by inexorabletash** [comment]
The logic in `desktop.system.s`'s `read_file_entry` proc has a bug. If the last file entry in a block is at the end of the directory, the dir pointer attempts to advance by 5 bytes, but only 1 byte is read, and a non-zero result is returned, so the entry is skipped.
