### ISSUE TITLE
Apply all the changes you have made in window positioning and window size in the main Apple II DeskTop app to the Disk Copy app and the Selector app

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#510]
**Is your feature request related to a problem? Please describe.**
You have clearly made some window position and window size changes to the main Apple II DeskTop app in Apple II DeskTop 1.2 compared with Apple II DeskTop 1.1. The main about box, the regular dialog boxes, the alert dialog boxes and the error dialog boxes of the main Apple II DeskTop app are more centered and, in some cases, a different size than in Apple II DeskTop 1.1. These changes have not yet been applied to the different elements of the Disk Copy app and the different elements of the Selector app. The main window, the regular dialog boxes, the alert dialog boxes and the error dialog boxes of the Disk Copy app and the main window, the regular dialog boxes, the alert dialog boxes and the error dialog boxes of the Selector app are still off-center when compared with the main Apple II DeskTop app. This should change for greater user interface consistency.

**Describe the solution you'd like**
Apply all the changes you have made in window positioning and window size in the main Apple II DeskTop app to the Disk Copy app and the Selector app. This includes changes to the main window, the regular dialog boxes, the alert dialog boxes and the error dialog boxes of the Disk Copy app and changes to the main window, the regular dialog boxes, the alert dialog boxes and the error dialog boxes of the Selector app so that they are consistent with those of the main Apple II DeskTop app.

**Describe alternatives you've considered**
Just keep on using the Disk Copy app and the Selector app in Apple II DeskTop 1.2 the way it currently is.

**Additional context**
This would be a good time to implement issue #411, if you decide to reconsider your position on that issue.

**Comment by inexorabletash** [comment]
Thank you for pointing out the inconsistencies. 

I tidied up what I could find.

**Comment by c0mmander8** [comment]
What about the File > Run a Program... dialog box in the Selector app and its alert dialog boxes and its error dialog boxes?

**Comment by inexorabletash** [comment]
Yes, all of the file pickers (Selector, DeskTop) and alerts (DeskTop, Selector, Disk Copy) have the same coordinates.

Again, **PLEASE STOP MAKING REDUNDANT COMMENTS.**
