### ISSUE TITLE
The trailing "A" in the "Try Again A" dialog box button string should be more flush right in the main Apple II DeskTop app, the Disk Copy app and the Selector app

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#512]
The trailing "A" in the "Try Again A" dialog box button string should be more flush right in the main Apple II DeskTop app, the Disk Copy app and the Selector app.

**Comment by c0mmander8** [comment]
**Describe the bug**
Please reopen this issue. This bug still occurs in Apple II DeskTop 1.2 Alpha 33. The trailing "A" in the "Try Again A" dialog box button string should be flush right in the main Apple II DeskTop app, the Disk Copy app and the Selector app.

**To Reproduce**
Steps to reproduce the behavior:
1. Start Apple II DeskTop from "A2.Desktop", which is the "A2DeskTop-1.2-alpha33-en_800k.2mg" disk image, with at least two volumes mounted.
2. Open the "A2.Desktop" volume.
3. Open the "Optional" folder.
4. Move the "Selector" file from the "Optional" folder to the "A2.Desktop" volume.
5. Click on the Selector menu and go to Selector > Add an Entry....
6. Click on "Change Drive".
7. Select a file or a folder to add to the Selector from the second volume.
8. Click OK.
9. Click on the File menu and go to File > Quit.
10. Unmount the second volume.
11. Turn off the computer.
12. Turn on the computer.
13. Launch the Selector.
14. Select the file or the folder you added to the Selector from the second volume in step 7.
15. Click OK.
16. A dialog box appears stating, "Please insert source disk.".
17. The trailing "A" in the "Try Again A" dialog box button string is not flush right.

**Expected behavior**
The trailing "A" in the "Try Again A" dialog box button string should be flush right in the main Apple II DeskTop app, the Disk Copy app and the Selector app.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 33 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There may be other instances of this bug or similar bugs outstanding in the main Apple II DeskTop app, the Disk Copy app and the Selector app. Please try hard to spot them all. Thank you.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/126906785-52c485b6-cd15-43cc-bb92-3f284727cb1e.png)

It's fine in tip-of-tree.

**Comment by c0mmander8** [comment]
What does tip-of-tree mean?

**Comment by inexorabletash** [comment]
The latest (tip) revision in the source code (a tree of files)
