### ISSUE TITLE
Inconsistent default window sizing for nested folder structure

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#514]
**Describe the bug**
Each successive window that opens in a nesting doll of folders is wider than the previous one, when all of the windows contain just 1 folder and nothing else inside of them.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open a window.
3. Create an 8-level nesting doll of folders, with each folder containing just 1 item-the folder for the next level.
4. Close all open windows.
5. Open the window opened in step 2.
6. Open each folder in the nesting doll of folders, one level at a time.
7. Each successive window that opens is wider than the previous one, even though all of the windows contain just 1 folder and nothing else inside of them.

**Expected behavior**
Each successive window that opens in a nesting doll of folders should be the same size as the previous one, when all of the windows contain just 1 folder and nothing else inside of them.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 33 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/126907207-e2adcd4b-ca79-4534-9073-687fb5871c4c.png)

The description is close but not correct. The first few windows have the same width, then the 4th through final window have a different length.

**Comment by inexorabletash** [comment]
Nice one.
