### ISSUE TITLE
The respective menu title does not remain highlighted the entire time Screen Dump is running

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#515]
**Describe the bug**
The respective menu title does not remain highlighted the entire time Screen Dump is running.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open the "Desk.Acc" folder.
3. Select "Screen.Dump".
4. Press Apple-O.
5. The File menu title briefly highlights when Screen Dump starts to run.
6. The File menu title remains unhighlighted while Screen Dump runs.
7. The File menu title is highlighted for a longer period of time than in step 5 when Screen Dump is finished running.

**Expected behavior**
The respective menu title should remain highlighted the entire time Screen Dump is running.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 33 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
This bug occurs whether Screen Dump is run from the Apple menu, from File > Open, from pressing the Apple-O keyboard shortcut, from the Selector > Run an Entry... dialog box or from the Selector menu.

**Comment by inexorabletash** [comment]
That's intentional. 

Please write shorter issue titles.

**Comment by inexorabletash** [comment]
To clarify more: the window title is intentionally not highlighted so that the screenshot doesn't always show a highlighted menu, e.g. when using the screenshots to craft documentation.
