### ISSUE TITLE
An item is copied instead of moved when a move is attempted from a folder opened from the Apple menu to another window on the same volume

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#517]
**Describe the bug**
An item is copied instead of moved when a move is attempted from a folder opened from the Apple menu to another window on the same volume.

**To Reproduce**
1. Start Apple II DeskTop, when not running Apple II DeskTop from a RAMCard.
2. Open a window on the startup disk.
3. Click on the Apple menu and select the Control Panels folder.
4. Attempt to move the Date control panel to the window you opened in step 2.
5. The Date control panel is copied to that window instead of being moved there.

**Expected behavior**
An item should be moved instead of copied when a move is attempted from a folder opened from the Apple menu to another window on the same volume.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 33 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
I think this bug is related to issue #466, because the name of the startup disk is shown all in capital letters in the "from:" line of the "Copy..." dialog box that results from the move attempt while the name of the startup disk is shown with normal casing in the "to:" line of the "Copy..." dialog box that results from the move attempt.

**Comment by c0mmander8** [comment]
I think this bug and issue #466 share the same underlying cause.

**Comment by inexorabletash** [comment]
The comparison is not case sensitive. 

https://github.com/a2stuff/a2d/blob/main/desktop/main.s#L13365
