### ISSUE TITLE
There is no space immediately between a long, 14-character Selector menu entry and the Apple-Number key keyboard shortcut; there is ample space only after you restart Apple II DeskTop

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#518]
**Describe the bug**
There is no space immediately between a long, 14-character Selector menu entry and the Apple-Number key keyboard shortcut. There is ample space only after you restart Apple II DeskTop.

**To Reproduce**
1. Start Apple II DeskTop from "A2.Desktop", which is the "A2DeskTop-1.2-alpha33-en_800k.2mg" disk image, while not running Apple II DeskTop from a RAMCard.
2. Open the "A2.Desktop" volume.
3. Click on the File menu and go to File > New Folder....
4. Type the 15-letter "Mmmmmmmmmmmmmmm" as the filename of the new folder in the "Enter the folder name:" text field.
5. Click OK.
6. Click on the Selector Menu and go to Selector > Add an Entry....
7. Select the folder you have just created in steps 3-5.
8. Click OK.
9. Delete a letter from the "Enter the name (14 characters max.):" text field since that text field only supports 14-character filenames.
10. Click OK.
11. Click on the Selector menu again.
12. There is no space between the "Mmmmmmmmmmmmmm" Selector menu entry and the Apple-1 keyboard shortcut.
13. Click on the File menu and go to File > Quit.
14. Turn off the computer.
15. Turn on the computer.
16. Restart Apple II DeskTop from "A2.Desktop", still while not running Apple II DeskTop from a RAMCard.
17. Click on the Selector menu.
18. There is ample space between the "Mmmmmmmmmmmmmm" Selector menu entry and the Apple-1 keyboard shortcut.

**Expected behavior**
There should be ample space immediately between a long, 14-character Selector menu entry and the Apple-Number key keyboard shortcut.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 33 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment]
The Selector menu should widen itself immediately when being it being wide is necessary and the Selector menu should narrow itself immediately when it being wide is no longer necessary. The Selector menu should do both.

**Comment by inexorabletash** [comment]
Not worth it to fix.

**Comment by inexorabletash** [comment]
Actually, I came up with a trivial fix.
