### ISSUE TITLE
Selector's DeskTop button doesn't flash when activated with keyboard

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#519]
**Describe the bug**
The "DeskTop Q" dialog box button or the "OK" dialog box button in the main Selector window either do not flash at all or flash way too briefly when using the keyboard compared to other dialog box button flashes throughout Apple II DeskTop, Disk Copy, the Selector and desk accessories.

**To Reproduce**
1. Launch the Selector.
2. Press Return from the keyboard before selecting an item from the Selector, press Return from the keyboard after selecting an item from the Selector, press Q from the keyboard before selecting an item from the Selector or press Q from the keyboard after selecting an item from the Selector.
3. The "DeskTop Q" dialog box button or the "OK" dialog box button either do not flash at all or flash way too briefly when compared to other dialog box button flashes throughout Apple II DeskTop, Disk Copy, the Selector and desk accessories.

**Expected behavior**
The "DeskTop Q" dialog box button or the "OK" dialog box button in the main Selector window should flash the same way when using the keyboard as other dialog box button flashes throughout Apple II DeskTop, Disk Copy, the Selector and desk accessories.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 33 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment]
By "flash", I mean a dialog box button being highlighted.

**Comment by inexorabletash** [comment]
Yeah, there's no code to flash those buttons. Trivial to add.

**Comment by c0mmander8** [comment]
Please reopen this issue. As referenced above, this bug also applies to the "OK" dialog box button in the main Selector window. It flashes way too briefly when using the keyboard compared to other dialog box button flashes throughout Apple II DeskTop, Disk Copy, the Selector and desk accessories.

**Comment by inexorabletash** [comment]
The OK button *does* flash; at 1MHz it may flash for less than 1/60th of a second and miss a screen refresh. This is more likely when running at higher speed. But if you throttle down to 1MHz and hold the Return key down, you can see OK flash most of the time.

In general, further work here is not worthwhile. The flash is "as fast as it can be" in all instances (literally, PaintRect calls right after one another); in some cases the call is microseconds slower than others due to bank switching. Adding an artificial delay would require pausing the system for some time. I'm usually running my emulator unthrottled, so almost never see the flashes anyway.

**Comment by c0mmander8** [comment]
I never said that the "OK" dialog box button in the main Selector window did not flash at all when using the keyboard. That was the "DeskTop Q" dialog box button in the main Selector window that did not flash at all when using the keyboard. I said that the "OK" dialog box button in the main Selector window flashes way too briefly when using the keyboard compared to other dialog box button flashes throughout Apple II DeskTop, Disk Copy, the Selector and desk accessories.
