### ISSUE TITLE
There is a subtle highlighting bug when selecting a long, 14-character Selector Other Run List entry from the Selector > Edit an Entry..., Selector > Delete an Entry... and Selector > Run an Entry... dialog boxes

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#520]
**Describe the bug**
There is a subtle highlighting bug when selecting a long, 14-character Selector Other Run List entry from the Selector > Edit an Entry..., Selector > Delete an Entry... and Selector > Run an Entry... dialog boxes. This subtle highlighting bug does not apply to Selector Run List entries in these dialog boxes and this subtle highlighting bug does not apply to both Selector Run List entries and Selector Other Run List entries when booted into the Selector directly at startup.

**To Reproduce**
1. Start Apple II DeskTop from "A2.Desktop", which is the "A2DeskTop-1.2-alpha33-en_800k.2mg" disk image, while not running Apple II DeskTop from a RAMCard.
2. Open the "A2.Desktop" volume.
3. Click on the File menu and go to File > New Folder....
4. Type the 15-letter "Mmmmmmmmmmmmmmm" as the filename of the new folder in the "Enter the folder name:" text field.
5. Click OK.
6. Click on the Selector Menu and go to Selector > Add an Entry....
7. Select the folder you have just created in steps 3-5.
8. Click OK.
9. Delete a letter from the "Enter the name (14 characters max.):" text field since that text field only supports 14-character filenames.
10. Select "Other Run list" from the "Add an entry to the:" list.
11. Click OK.
12. Repeat steps 6-11 15 more times until the Selector Other Run List is full.
13. Click on the Selector menu and go to Selector > Run an Entry....
14. Scroll back and forth and up and down through the 16 14-letter "Mmmmmmmmmmmmmm" entries you have just created in the Selector Other Run List with the arrow keys multiple times.
15. Notice the subtle highlighting bug.
16. This subtle highlighting bug only applies to selecting a long, 14-character Selector Other Run List entry from the Selector > Edit an Entry..., Selector > Delete an Entry... and Selector > Run an Entry... dialog boxes. This subtle highlighting bug does not apply to Selector Run List entries in these dialog boxes and this subtle highlighting bug does not apply to both Selector Run List entries and Selector Other Run List entries when booted into the Selector directly at startup.

**Expected behavior**
There should not be a subtle highlighting bug when selecting a long, 14-character Selector Other Run List entry from the Selector > Edit an Entry..., Selector > Delete an Entry... and Selector > Run an Entry... dialog boxes.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 33 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment]
By "subtle highlighting bug", I mean that the entire "Mmmmmmmmmmmmmm" is not entirely highlighted in both columns of the Other Run List in the Selector > Edit an Entry..., Selector > Delete an Entry... and Selector > Run an Entry... dialog boxes. Also, the portion of "Mmmmmmmmmmmmmm" that is not highlighted in the left column of the Other Run List (the middle column of the dialog box) is highlighted in the right column of the Other Run List (the right column of the dialog box) in the Selector > Edit an Entry..., Selector > Delete an Entry... and Selector > Run an Entry... dialog boxes.

**Comment by inexorabletash** [comment]
Please spent less time writing overly verbose descriptions, and figure out how to post screenshots instead.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/127258655-34207e85-5dff-494f-8d59-6ba3b4a94172.png)

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/127259296-b8839913-61ca-45fc-bfe5-267920448bd1.png)
![image](https://user-images.githubusercontent.com/771547/127259304-39e478bb-c910-4669-95f6-1e981ffb33aa.png)
