### ISSUE TITLE
Run Basic Here should simply fail to run without a dialog box appearing when Run Basic Here is run without any windows open

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#521]
**Is your feature request related to a problem? Please describe.**
Run Basic Here fails to run with a dialog box stating "This file cannot be opened." when Run Basic Here is run without any windows open. Sort Directory, Find Files, Show Text File, Show Image File and Show Font File simply fail to run without a dialog box appearing when they are run without any windows open.

**Describe the solution you'd like**
Run Basic Here should also simply fail to run without a dialog box appearing when Run Basic Here is run without any windows open, just like Sort Directory, Find Files, Show Text File, Show Image File and Show Font File already do. This feature request is for greater user interface consistency.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
This feature request is for greater user interface consistency.

**Comment by inexorabletash** [comment]
I added a message instead, here and Find Files.

The Preview DAs could be improved to show an error, but they aren't invokable without a selection by default, so I don't think that's worth the effort.

**Comment by c0mmander8** [comment]
What about when Sort Directory is run without any windows open?

**Comment by inexorabletash** [comment]
Good call. Fixed.

**Comment by c0mmander8** [comment]
I see that this issue was fixed in commit 4c80bc8 and in commit e58e634.
