### ISSUE TITLE
Should an error dialog box be shown when binary (BIN) files are attempted to be opened in Apple II DeskTop without the Apple key being held down?

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#522]
Binary (BIN) files currently simply fail to open in Apple II DeskTop without an error dialog box appearing if they are attempted to be opened without the Apple key being held down. Should an error dialog box be shown in this scenario? An error dialog box would provide information to the unknowing user why the binary (BIN) file is not being opened in this scenario. Although, if someone accidentally forgets to hold the Apple key down while attempting to open a binary (BIN) file in Apple II DeskTop and realizes it on their own, a superfluous dialog box would just waste extra time.

**Comment by inexorabletash** [comment]
If I get multiple reports that users are confused, I'll consider it. Preemptively addressing this is not worth it.

**Comment by inexorabletash** [comment]
Ended up doing this in d5ec3b6ef35c8cc2f17b685312b066486d31921d
