### ISSUE TITLE
The "N" in the "Normal N" dialog box button string and the "F" in the "Fast F" dialog box button string in the System Speed control panel should be more flush right

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#525]
The "N" in the "Normal N" dialog box button string and the "F" in the "Fast F" dialog box button string in the System Speed control panel should be more flush right.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/127584665-fc856a69-fb0b-4db5-9f79-d045bc54423f.png)
