### ISSUE TITLE
Selector menu repaints incorrectly if SELECTOR.LIST is modified while DeskTop is running and an entry is added

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#526]
**Describe the bug**
The Selector menu and the desktop are garbled and screen artifacts are left behind in 1 of the instances of GSplus when there are 2 instances of GSplus running and an entry is added to the Selector menu in each of the instances.

**To Reproduce**
1. Open 2 instances of GSplus.
2. In both instances of GSplus, start Apple II DeskTop from the same and shared startup disk file - "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha33-en_800k.2mg" disk image, while not running Apple II DeskTop from a RAMCard in both instances.
3. In instance 1, click on the Selector menu and go to Selector > Add an Entry....
4. In instance 1, select an entry to add to the Selector menu.
5. In instance 1, click OK.
6. In instance 1, click OK again.
7. In instance 1, click on the Selector menu and see that the entry you have added to the Selector menu has been correctly added.
8. In instance 2, click on the Selector menu and go to Selector > Add an Entry....
9. In instance 2, select an entry to add to the Selector menu.
10. In instance 2, click OK. 
11. In instance 2, click OK again.
12. In instance 2, click on the Selector menu and see that the Selector menu and the desktop are garbled and screen artifacts are left behind.

**Expected behavior**
The Selector menu should be reset each time an entry is added to the Selector menu in each GSplus instance and the Selector menu and the desktop should not be garbled and screen artifacts should not be left behind in both of the instances of GSplus when there are 2 instances of GSplus running and an entry is added to the Selector menu in each of the instances.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 33 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
Was this bug also fixed in issue #518, commit e585977 when you fixed issue #518?

**Comment by inexorabletash** [comment]
Sounds like the file or entire disk image is getting corrupted by having it open in two emulators at the same time. That's not really supportable. 

Are you able to repro without two instances?

Does the problem persist after restarting a single emulator? If so, can you attach the corrupted Selector.List file?

**Comment by c0mmander8** [comment]
Selector.List and the entire disk image are not getting corrupted by having them open in two emulators at the same time. In fact, Selector > Run an Entry... keeps track of all of the changes just fine. It is the Selector menu that is getting corrupted. I am not able to reproduce this bug without two instances of GSplus running. The problem does not persist after restarting the affected emulator(s). This bug might have also been fixed in the meantime in issue #518, commit e585977 when you fixed issue #518.

**Comment by inexorabletash** [comment]
Nifty!

![image](https://user-images.githubusercontent.com/771547/128107614-ac894f16-e02b-4db5-a876-31162896db09.png)

**Comment by inexorabletash** [comment]
Nothing to do with the root cause or fix for #518.

**Comment by inexorabletash** [comment]
In general, having two emulators using the same disk image simultaneously will not be supported by most programs.

I'll leave this open because I'm curious what exactly is going on - I wouldn't expect the menu records to be corrupted this way!

**Comment by inexorabletash** [comment]
Repro that doesn't require two emulators. All file references are into the A2.DESKTOP directory.

1. Launch DeskTop
2. Delete SELECTOR.LIST
3. Quit DeskTop
4. Launch DeskTop
5. Add a selector entry
6. Rename SELECTOR.LIST to SELECTOR.LIST2
7. Quit DeskTop
8. Launch DeskTop
9. Delete SELECTOR.LIST
10. Rename SELECTOR.LIST2 to SELECTOR.LIST
11. Add a selector entry
12. Look at the Selector menu

**Comment by inexorabletash** [comment]
Interesting... the new entry is added in memory in `run_list_entries` and `run_list_paths` (and on disk) as entry 2, which makes sense for the file. But in memory, entry 1 in `run_list_entries` is left blank. The menu length is increased by one. But since the first selector entry menu item points at the first entry in `run_list_entries` and that's null data, you get garbage.

In `selector_overlay2` the `assign_entry_data` and `remove_entry` procs only updates the specified entry in the menu.

Since the whole selector list file is loaded anyway, rebuilding the menu from the disk data would fix this. Should be pretty easy. Low priority, though, since modifying DeskTop's files when it is running is a bad idea.
