### ISSUE TITLE
Crash/corruption if File > New Folder pushes icon count past the maximum

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#527]
**Describe the bug**
Screen artifacts appear on the menu bar and Apple II DeskTop freezes after the "Warning! A window must be closed before opening this new catalog." error dialog box appears after creating a new folder even though there are only 124 items / icons in Apple II DeskTop.

**To Reproduce**
1. Start Apple II DeskTop with just the startup disk mounted, and no other volumes, RAMCards or RAM disks mounted.
2. Open a window of the root directory of the startup disk.
3. Click on the File menu and go to File > New Folder....
4. Name the folder "A".
5. Click OK.
6. Open the window of the folder "A" you have just created.
7. Click on the File menu and go to File > New Folder....
8. Name the folder "B".
9. Click OK.
10. Open the window of the folder "B" you have just created.
11. Move or copy files and folders or create new folders until the contents of "B" totals 115 items.
12. Close all windows except "B".
13. Create new folders until the contents of "B" totals 121 items.
14. Click on the File menu and go to File > New Folder....
15. Give the new folder a name.
16. Click OK.
17. A dialog box appears stating, "Warning! A window must be closed before opening this new catalog.".
18. Click OK or click Cancel.
19. Screen artifacts appear on the menu bar and Apple II DeskTop freezes.
20. The "Warning! A window must be closed before opening this new catalog." error dialog box appears even though there are now only 122 items in "B", which is the only open window, and only 2 icons on the desktop - the startup disk and the trash can, totaling 124 items / icons.
21. The Apple II DeskTop documentation located at "https://www.a2desktop.com/docs#h.p_d6jyIELgS1YY" states, "ℹ️ NOTE: DeskTop is limited to displaying up to 127 icons at once. If there are not enough icons available to display a directory's files, DeskTop will ask you to close a window and try again.".
22. 124 items / icons is less than 127 icons.

**Expected behavior**
Screen artifacts should not appear on the menu bar and Apple II DeskTop should not freeze after the "Warning! A window must be closed before opening this new catalog." error dialog box appears after creating a new folder even though there are only 124 items / icons in Apple II DeskTop.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 33 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
If you simply try to open a folder that has already has 122 items or more in it, the "Warning! A window must be closed before opening this new catalog." error dialog box appears but no screen artifacts appear on the menu bar and Apple II DeskTop does not freeze after clicking OK or clicking Cancel.

**Comment by inexorabletash** [comment]
FWIW, the code had a limit of 123 for some reason, rather than 126. And I checked the code and the limit is 126 not 127, so I fixed the docs.

Anyway, yeah, if **File > New Folder** leads to a case where the window can't be refreshed, badness happens.

**Comment by inexorabletash** [comment]
This was a fun one. Fix was a bit involved but worthwhile.
