### ISSUE TITLE
The "Warning! A window must be closed before opening this new catalog." error dialog box has a superfluous Cancel button

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#528]
The "Warning! A window must be closed before opening this new catalog." error dialog box has a superfluous Cancel button.

**Comment by inexorabletash** [comment]
Fixed.

**Comment by c0mmander8** [comment]
Please reopen this issue. As referenced in commit 10f02a8, what about the superfluous Cancel button in the other warning message identifier with the same message? Please have that superfluous Cancel button also removed.
