### ISSUE TITLE
Fix the off-by-one bug so that the 127th icon can be shown in Apple II DeskTop

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#529]
As referenced in issue #528, commit 10f02a8, fix the off-by-one bug so that the 127th icon can be shown in Apple II DeskTop. After you fix this bug, update the Apple II DeskTop documentation located at "https://www.a2desktop.com/docs#h.p_d6jyIELgS1YY" to state, "ℹ️ NOTE: DeskTop is limited to displaying up to 127 icons at once. If there are not enough icons available to display a directory's files, DeskTop will ask you to close a window and try again.".

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/128272973-21e21b31-3951-463d-8b8d-271a8c68e2a3.png)

Note that there's some subtlety - DeskTop reserves some of the icon pool for ProDOS devices even if they aren't online. So you may find that ejecting disks doesn't let you add more file icons.

**Comment by inexorabletash** [comment]
And no, I won't add details about the exact icon count formula to the documentation; it's too esoteric for most users.
