### ISSUE TITLE
You have to hold down the Apple key in order to open a binary (BIN) file from the Apple menu, the Selector menu or the Selector > Run an Entry... dialog box

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#530]
**Describe the bug**
You have to hold down the Apple key in order to open a binary (BIN) file from the Apple menu, the Selector menu or the Selector > Run an Entry... dialog box.

**To Reproduce**
1. Start Apple II DeskTop.
2. Add a binary (BIN) file to the Desk.Acc folder or to the Selector.
3. Click on the File menu and go to File > Quit.
4. Turn off the computer.
5. Turn on the computer.
6. Restart Apple II DeskTop.
7. Attempt to open a binary (BIN) file from the Apple menu, the Selector menu or the Selector > Run an Entry... dialog box.
8. The binary (BIN) file does not open unless you hold down the Apple key while performing step 7.

**Expected behavior**
You should not have to hold down the Apple key in order to open a binary (BIN) file from the Apple menu, the Selector menu or the Selector > Run an Entry... dialog box.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 33 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
This bug does not occur when opening a binary (BIN) file from the main Selector app window or when opening a binary (BIN) file from the File > Run a Program... dialog box in the Selector app.

**Comment by inexorabletash** [comment]
Thank you for advocating for consistency.

Simplified to only require an Apple key when double clicking.
