### ISSUE TITLE
You have to hold down the Apple key in order to open a binary (BIN) file from File > Open

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#531]
**Describe the bug**
You have to hold down the Apple key in order to open a binary (BIN) file from File > Open.

**To Reproduce**
1. Start Apple II DeskTop.
2. Select a binary (BIN) file.
3. Click on the File menu and go to File > Open.
4. The binary (BIN) file does not open unless you hold down the Apple key while performing step 3.

**Expected behavior**
You should not have to hold down the Apple key in order to open a binary (BIN) file from File > Open.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 33 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment]
This bug does not apply to double-clicking the file icon to open a binary (BIN) file. This bug only applies to opening a binary (BIN) file by first selecting the file icon and then clicking on the File menu and going to File > Open.

**Comment by c0mmander8** [comment]
The following statement from the Apple II DeskTop documentation located at "https://www.a2desktop.com/docs#h.p_d6jyIELgS1YY" is wrong. You can run a binary (BIN) file by double-clicking it if you hold the Apple key down while doing so.

ℹ️ NOTE: You can't run a Binary file by double-clicking, but you can run it with the △-O shortcut or by holding down △ (or ▲) while selecting File > Open.

**Comment by c0mmander8** [comment]
Do you think this issue will enable accidental openings of binary (BIN) files? I still want to prevent those from occurring.

**Comment by c0mmander8** [comment]
Maybe this issue is not a good idea. What do you think?

**Comment by c0mmander8** [comment]
What is your opinion on this issue?

**Comment by inexorabletash** [comment]
**STOP REPEATING YOURSELF**

**Comment by inexorabletash** [comment]
Thank you for advocating for consistency.

Simplified to only require an Apple key when double clicking.
