### ISSUE TITLE
The position of the scrollbar thumbs on both of the scrollbars are reset whenever a source window or a destination window is redrawn after a file or a folder is moved or copied

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#532]
**Describe the bug**
The position of the scrollbar thumbs on both of the scrollbars are reset whenever a source window or a destination window is redrawn after a file or a folder is moved or copied.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open a window with at least 20 items.
3. Resize the window so that it is small as possible.
4. Scroll the window all the way right to the right end of the window.
5. Scroll the window all the way down to the bottom of the window.
6. Move or copy a file or a folder to or from another window.
7. The position of the scrollbar thumbs on both of the scrollbars are reset in both the source window and the destination window when the windows are redrawn.

**Expected behavior**
The position of the scrollbar thumbs on both of the scrollbars should stay the same and not be reset whenever a source window or a destination window is redrawn after a file or a folder is moved or copied.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 33 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment]
The "Expected behavior" is the behavior of the Mac and the IIGS.

**Comment by inexorabletash** [comment]
Not worth fixing, since all of the icons are repositioned as well.

**Comment by c0mmander8** [comment]
Please reopen this issue. I still think that this issue is an important issue to be implemented because this would greatly increase the usability of Apple II DeskTop.
