### ISSUE TITLE
The "Files remaining to copy:" or "Files remaining to move:" number remains the same and does not decrease when clicking No in the "Copy..." or "Move..." dialog boxes

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#534]
**Describe the bug**
The "Files remaining to copy:" or "Files remaining to move:" number remains the same and does not decrease when clicking No in the "Copy..." or "Move..." dialog boxes.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open a window.
3. Select at least 5 items.
4. Copy these items to another folder or volume.
5. Attempt to copy these items to the same folder or volume as in step 4 a second time or attempt to move these items to the same folder or volume as in step 4.
6. The "Copy..." or "Move..." dialog box appears stating, "That file already exists. Do you want to write over it?".
7. Click No.
8. The "Files remaining to copy:" or "Files remaining to move:" number remains the same and does not decrease.
9. Keep on clicking No.
10. The "Files remaining to copy:" or "Files remaining to move:" number keeps on remaining the same and keeps on not decreasing.

**Expected behavior**
The "Files remaining to copy:" or "Files remaining to move:" number should decrease and not remain the same when clicking No in the "Copy..." or "Move..." dialog boxes.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 34 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Thanks, good catch.

**Comment by inexorabletash** [comment]
After this fix it would be good to test that the numbers don't drop below zero in odd cases. I ran a handful of tests and it seemed to work.

Also, if you are copying a directory structure and say "No" to e.g. a directory with 5 files, the count won't drop by 5. Fixing that would be an extreme amount of work for little benefit, so it's not worth pursuing.
