### ISSUE TITLE
DeskTop freezes when copying items that result in the maximum icon limit being exceeded

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#538]
**Describe the bug**
Apple II DeskTop freezes when copying items that result in the maximum icon limit being exceeded.

**To Reproduce**
1. Start Apple II DeskTop with just the startup disk mounted at s7d1, and no other volumes, RAMCards or RAM disks mounted.
2. Open a window of the root directory of the startup disk.
3. Click on the File menu and go to File > New Folder....
4. Name the folder "A".
5. Click OK.
6. Open the window of the folder "A" you have just created.
7. Click on the File menu and go to File > New Folder....
8. Name the folder "B".
9. Click OK.
10. Open the window of the folder "B" you have just created.
11. Move or copy files and folders or create new folders until the contents of "B" totals 115 items.
12. Close all windows except "A" and "B".
13. Move 15 items from "B" to "A".
14. Copy the 15 items you just moved in step 13 from "A" to "B".
15. A dialog box appears stating, "Warning! A window must be closed before opening this new catalog.".
16. Click OK.
17. Apple II DeskTop freezes.

**Expected behavior**
Apple II DeskTop should not freeze when copying items that result in the maximum icon limit being exceeded.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 34 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Thanks. I think I caught all of the cases where this can occur.
