### ISSUE TITLE
Volumes that are ejected and then remounted are not remounted in reverse DEVLST order

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#540]
**Describe the bug**
Volumes that are ejected and then remounted are not remounted in reverse DEVLST order.

**To Reproduce**
1. Start Apple II DeskTop in GSplus with four volumes mounted at s7d1, s7d2, s5d1 and s5d2, and no other volumes, RAMCards or RAM disks mounted.
2. All four volumes located at s7d1, s7d2, s5d1, and s5d2 are mounted in reverse DEVLST order.
3. In the "Disk Configuration" section of "GSplus Configuration", eject all four volumes located at s7d1, s7d2, s5d1, and s5d2 at the same time.
4. All four volumes located at s7d1, s7d2, s5d1, and s5d2 are ejected.
5. In the "Disk Configuration" section of "GSplus Configuration", remount all four volumes located at s7d1, s7d2, s5d1, and s5d2 at the same time.
6. All four volumes located at s7d1, s7d2, s5d1, and s5d2 are not remounted in reverse DEVLST order.

**Expected behavior**
Volumes that are ejected and then remounted should be remounted in reverse DEVLST order to the maximum extent possible.

**Screenshots**
 I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 34 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
It seems that, currently, volumes that are ejected and then remounted are remounted in DEVLST order instead.

**Comment by inexorabletash** [comment]
Obscure, and emulator-only, but easy.
