### ISSUE TITLE
Enable successful mounting, ejecting and remounting of all volumes while already booted using the Apple II DeskTop GUI in all slots and drives to the maximum extent possible, including slot remapped drives

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#541]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that, currently, you are only able to successfully mount, eject and remount volumes while already booted using the Apple II DeskTop GUI in s5d1 and s5d2.

**Describe the solution you'd like**
Enable successful mounting, ejecting and remounting of all volumes while already booted using the Apple II DeskTop GUI in all slots and drives to the maximum extent possible, including slot remapped drives.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
There is no other context or screenshots about this feature request here.

**Comment by inexorabletash** [comment]
This works fine in the Virtual II emulator. It seems that it's a limitation of your emulator, which doesn't implement the SmartPort protocol correctly and does not report some devices as removable.
