### ISSUE TITLE
Apple II DeskTop is currently broken when there are two or more volumes mounted with the identical volume name

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#542]
**Describe the bug**
Apple II DeskTop is currently broken when there are two or more volumes mounted with the identical volume name.

**To Reproduce**
1. Start Apple II DeskTop with the startup disk and another volume with different contents mounted with the identical volume name.
2. Double-click on the icon of the startup disk on the desktop.
3. Look at the contents of the window.
4. Click on the View menu and go to View > by Name, View > by Date, View > by Size, or View > by Type.
5. The window is now empty.
6.  Click on the View menu and go to View > as Icons.
7. The contents of the window are now restored.
8. Close the window.
9. Double-click on the other volume mounted with the identical volume name as the startup disk on the desktop.
10. Look at the contents of the window.
11. See that the contents of the window match the contents of the window in step 3 and step 7.
12. Click on the View menu and go to View > by Name, View > by Date, View > by Size, or View > by Type.
13. The window is now empty.
14.  Click on the View menu and go to View > as Icons.
15. The contents of the window are now restored.
16. Close the window.
17. Click on the File menu and go to File > Copy a File... or File > Delete a File..., click on the Special menu and go to Special > Format a Disk..., Special > Erase a Disk... or Special > Disk Copy..., or click on the Selector menu and go to Selector > Add an Entry..., Selector > Edit an Entry..., Selector > Delete an Entry... or Selector > Run an Entry....
18. Apple II DeskTop freezes.

**Expected behavior**
Apple II DeskTop should not be broken when there are two or more volumes mounted with the identical volume name.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 34 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment]
This bug seems related to issue #310, but I no longer remember anything about issue #310.

**Comment by c0mmander8** [comment]
I take back my last comment. Reading the comments in issue #310, I am sure that this bug is not related to issue #310.

**Comment by inexorabletash** [comment]
As mentioned over in #310:

> FWIW, DeskTop is supposed to report an error on startup if there are duplicate volume names, I'm not sure why that's not happening. Having duplicate volume names is going to make ProDOS very confused, so that needs to be avoided. 

Contrary to the ProDOS documentation, the ON_LINE call is not returning an error when there are duplicate volume names. DeskTop is coded to detect this error and not create a volume icon with the same name, but since that's not happening, ProDOS gets confused.

**Comment by inexorabletash** [comment]
Alerts will be shown now.

ProDOS may still get confused and tell DeskTop the wrong details about a volume, which is why duplicate volume names aren't really supported.
