### ISSUE TITLE
A volume icon or a folder icon should no longer be highlighted after you open it by double-clicking on it

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#544]
**Is your feature request related to a problem? Please describe.**
In Apple II DeskTop 1.1, a volume icon or a folder icon is still highlighted after you open it by double-clicking on it, by clicking on the File menu and going to File > Open, or by using the Apple-O keypress shortcut, just like the Mac and the early IIGS. In Apple II DeskTop 1.2 Alpha 34, a volume icon or a folder icon is no longer highlighted after you open it by clicking on the File menu and going to File > Open, or by using the Apple-O or the Apple-Down Arrow keypress shortcuts, just like the later IIGS. In Apple II DeskTop 1.2 Alpha 34, a volume icon or a folder icon is still highlighted only after you open it by double-clicking on it, just like the Mac and the early IIGS.

**Describe the solution you'd like**
A volume icon or a folder icon should no longer be highlighted after you open it by double-clicking on it, just like the later IIGS. This feature request is for greater user interface consistency throughout Apple II DeskTop.

**Describe alternatives you've considered**
A volume icon or a folder icon could be made to be still highlighted after you open it by clicking on the File menu and going to File > Open, or by using the Apple-O or the Apple-Down Arrow keypress shortcuts, instead, just like the Mac and the early IIGS.

**Additional context**
This feature request is for greater user interface consistency throughout Apple II DeskTop.

**Comment by inexorabletash** [comment]
Yeah, the behavior here is weird and inconsistent, and needs to be cleaned up. 

The situation is slightly more complicated than on the Mac/IIgs in that MGTK can't paint icons in inactive windows, whereas that's possible with QuickDraw. That's indirectly the source of some bugs now, where a folder icon being opened is left highlighted and it can't be correctly unhighlighted when selection shifts to something in the active window.

I tried to make some fixes here earlier, but my understanding of the code was more limited then.

**Comment by inexorabletash** [comment]
A comprehensive fix should cover #415 too.
