### ISSUE TITLE
The drag-select selection rectangle should have 90 degree square edges instead of having rounded corners

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#550]
**Is your feature request related to a problem? Please describe.**
The drag-select selection rectangle has rounded corners instead of having 90 degree square edges like the Mac and the IIGS.

**Describe the solution you'd like**
The drag-select selection rectangle should have 90 degree square edges instead of having rounded corners, just like the Mac and the IIGS.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
Add an entry to the release notes referencing that the drag-select selection rectangle now has square edges.

**Comment by inexorabletash** [comment]
This is a result of using the xor operation for drawing. Not worth extra code for such a change.
