### ISSUE TITLE
The drag-select selection rectangle on the desktop should also be made up of dotted lines like the drag-select selection rectangle in a window already is

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#552]
**Is your feature request related to a problem? Please describe.**
The drag-select selection rectangle on the desktop is still made up of solid lines like the IIGS instead of the drag-select selection rectangle on the desktop also being made up of dotted lines like the the drag-select selection rectangle in a window already is.

**Describe the solution you'd like**
The drag-select selection rectangle on the desktop should also be made up of dotted lines like the drag-select selection rectangle in a window already is, just like the Mac.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
Add an entry to the release notes referencing that the drag-select selection rectangle is now made up of dotted lines.

**Comment by inexorabletash** [comment]
It already is, it's just hard to tell since the background is a checkboard by default.

![image](https://user-images.githubusercontent.com/771547/132074271-740f1731-874d-44d1-85ee-5036efaaffde.png)
