### ISSUE TITLE
Format Disk: Bitmap set up incorrectly

### ISSUE THREAD

**Issue by inexorabletash** [a2stuff/a2d#557]
**To Reproduce**
1. In Virtual II, create a new 32MB Omnidisk image: `Untitled.2mg`
2. Use DeskTop to format the disk.
3. At a shell prompt, run
`$ cadius CHECKVOLUME ~/Untitled.2mg`

``` 
cadius v 1.4.5 (c) Brutal Deluxe 2011-2013.
  - Check volume '/Users/josh/Untitled.2mg'
    => Block 0010 is declared FREE in the Bitmap, but used by Bitmap
    => Block 0011 is declared FREE in the Bitmap, but used by Bitmap
    => Block 0012 is declared FREE in the Bitmap, but used by Bitmap
    => Block 0013 is declared FREE in the Bitmap, but used by Bitmap
    => Block 0014 is declared FREE in the Bitmap, but used by Bitmap
    => Block 0015 is declared FREE in the Bitmap, but used by Bitmap
    => Block FFF8 is declared IN USE in the Bitmap, but it not referenced by any object
    => Block FFF9 is declared IN USE in the Bitmap, but it not referenced by any object
    => Block FFFA is declared IN USE in the Bitmap, but it not referenced by any object
    => Block FFFB is declared IN USE in the Bitmap, but it not referenced by any object
    => Block FFFC is declared IN USE in the Bitmap, but it not referenced by any object
    => Block FFFD is declared IN USE in the Bitmap, but it not referenced by any object
    => Block FFFE is declared IN USE in the Bitmap, but it not referenced by any object
```

This doesn't occur when the image is formatted with Copy II Plus.

**Comment by inexorabletash** [comment]
As a side effect of the above, the first file is copied to the volume overwrites the bitmap table and marks a random assortment of blocks $A000 onward as used, rendering large portions of the disk unusable.

The code is likely in `desktop/ovl_format_erase.s` circa the "Subsequent blocks..." comment.

**Comment by apple2geek** [comment]
The existing code that created the volume bitmap during a format made several erroneous assumptions including:
- That the block size of the volume would be an even multiple of 8
- That the maximum volume bitmap size would be 10 blocks (maximum volume size of 49,960 blocks)
Violating these assumptions would generate a volume bitmap that was, in a word, wrong.
I'm working on a replacement that will eliminate these assumptions and hopefully produce correct volume bitmaps for all volumes up to the maximum supported volume size of 65,535 blocks.

**Comment by apple2geek** [comment]
I believe I have a valid replacement for the VBM creation code that should solve this issue.  Pending review and approval.
