### ISSUE TITLE
Long file paths are not clipped in the "Copying to RAMCard..." dialog box in the Selector causing screen painting errors

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#558]
**Describe the bug**
Long file paths are not clipped in the "Copying to RAMCard..." dialog box in the Selector causing screen painting errors, just like in issue #465.

**To Reproduce**
1. Start Apple II DeskTop from "A2.Desktop", which is the "A2DeskTop-1.2-alpha35-en_800k.2mg" disk image, while not running Apple II DeskTop from a RAMCard.
2. Open the "A2.Desktop" volume.
3. Click on the File menu and go to File > New Folder....
4. Type the 15-letter "Mmmmmmmmmmmmmmm" as the filename of the new folder in the "Enter the folder name:" text field.
5. Click OK.
6. Open the "Mmmmmmmmmmmmmmm" folder you have just created in steps 3-5.
7. Click on the File menu and go to File > New Folder....
8. Type the 15-letter "Mmmmmmmmmmmmmmm" as the filename of the new folder in the "Enter the folder name:" text field.
9. Click OK.
10. Open the "Mmmmmmmmmmmmmmm" folder you have just created in steps 7-9.
11. Click on the File menu and go to File > New Folder....
12. Type the 15-letter "Mmmmmmmmmmmmmmm" as the filename of the new folder in the "Enter the folder name:" text field.
13. Click OK.
14. Open the "Mmmmmmmmmmmmmmm" folder you have just created in steps 11-13.
15. Click on the File menu and go to File > New Folder....
16. Type the 4-letter "Mmmm" as the filename of the new folder in the "Enter the folder name:" text field.
17. Click OK.
18. Click on the Selector Menu and go to Selector > Add an Entry....
19. Select the parent "Mmmmmmmmmmmmmmm" folder you created in steps 3-5.
20. Click OK.
21. Delete a letter from the "Enter the name (14 characters max.):" text field since that text field only supports 14-character filenames.
22. Select "at first use" from the "Copy to RAMCard:" list.
23. Click OK.
24. Click on the File menu and go to File > Quit.
25. Turn off the computer.
26. Turn on the computer.
27. Launch the Selector from "A2.Desktop", which is the "A2DeskTop-1.2-alpha35-en_800k.2mg" disk image, now while running Apple II DeskTop from a RAMCard.
28. Select the "Mmmmmmmmmmmmmm" entry you added to the Selector in steps 18-23.
29. Click OK.
30. The long file paths are not clipped in the "Copying to RAMCard..." dialog box in the Selector causing screen painting errors instead of the long file paths being clipped in the "Copying to RAMCard..." dialog box in the Selector and not causing screen painting errors, just like in issue #465.
31. The "Copying to RAMCard..." dialog box in the Selector states, "An error occurred during the download. The copy wasn't completed, click OK to continue."
32. The "Copying to RAMCard..." dialog box in the Selector has the OK button in the lower left corner of the dialog box instead of having the OK button in the lower right corner of the dialog box, just like in issue #411. This bug is being tracked as issue #559.

**Expected behavior**
Long file paths should be clipped in the "Copying to RAMCard..." dialog box in the Selector and should not cause screen painting errors.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 35 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
The "Copying to RAMCard..." dialog box in the Selector has the OK button in the lower left corner of the dialog box instead of having the OK button in the lower right corner of the dialog box, just like in issue #411. This bug is being tracked as issue #559.

**Comment by c0mmander8** [comment]
Here is a link to issue #559.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/133941453-87cc2cbb-60a2-447c-aaee-9be3173f11a6.png)

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/133941614-a66e17f1-523b-4a44-9c06-bb104c6016b7.png)
