### ISSUE TITLE
The "Copying to RAMCard..." dialog box in the Selector has the OK button in the lower left corner of the dialog box

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#559]
As referenced in issue #558, the "Copying to RAMCard..." dialog box in the Selector has the OK button in the lower left corner of the dialog box, just like in issue #411. The "Copying to RAMCard..." dialog box in the Selector should instead have the OK button in the lower right corner of the dialog box, just like the rest of Apple II DeskTop, the Selector, Disk Copy and the desk accessories.

**Comment by c0mmander8** [comment]
Here is a link to issue #558.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/133937366-c32e2c13-85d7-4afd-bdef-1da767f81147.png)

Repro: 
1. Create a selector entry set to copy to RAMCard on first use
2. Launch selector
3. Invoke the item
4. While the copy is proceeding, eject the disk.

**Comment by inexorabletash** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/771547/133937549-15ba8dc8-7385-4b20-b215-176e5d3cd81d.png)
