### ISSUE TITLE
"Copy to RAMCard..." in Apple II DeskTop erases files and folders after the "Selector" file is moved from the "Optional" folder to the "A2.Desktop" volume

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#562]
**Describe the bug**
"Copy to RAMCard..." in Apple II DeskTop erases files and folders after the "Selector" file is moved from the "Optional" folder to the "A2.Desktop" volume.

**To Reproduce**
1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha36-en_800k.2mg" disk image, while running Apple II DeskTop from a RAMCard.
2. Open the "A2.Desktop" volume.
3. Open the "Optional" folder.
4. Move the "Selector" file from the "Optional" window to the "A2.Desktop" window.
5. Close all windows.
6. Click on the Selector menu and go to Selector > Add an Entry....
7. Open the "Desk.Acc" folder in the Selector > Add an Entry... dialog box and select the "Control.Panels" folder.
8. Click OK.
9. Select "at first use" from the "Copy to RAMCard:" list.
10. Click OK.
11. A dialog box appears stating, "Do you want to save the new list on the system disk?".
12. Click OK.
13. Click on the Selector menu and go to Selector > Add an Entry....
14. Select the "Desk.Acc" folder in the Selector > Add an Entry... dialog box.
15. Click OK.
16. Select "at first use" from the "Copy to RAMCard:" list.
17. Click OK.
18. A dialog box appears stating, "Do you want to save the new list on the system disk?".
19. Click OK.
20. Open the "A2.Desktop" volume.
21. The volume info header states "11 Items" and all the files and folders in the "A2.Desktop" volume are intact.
22. Close the window.
23. Click on the Selector menu and select the "Control.Panels" folder.
24. "Copy to RAMCard..." copies the contents of the parent "Desk.Acc" folder to the RAMCard.
25. The "Control Panels" folder in the RAMCard opens.
26. Close the window.
27. Open the "A2.Desktop" volume.
28. The volume info header states "10 Items" and the "Desk.Acc" folder in the "A2.Desktop" volume is now gone.
29. Close the window.
30. Click on the Selector menu and select the "Desk.Acc" folder.
31. "Copy to RAMCard..." copies the contents of the parent "A2.Desktop" volume to the RAMCard.
32. A dialog box appears stating, "The syntax of the pathname is invalid.".
33. Click OK.
34. Open the "A2.Desktop" volume.
35. The volume info header states "0 Items" and the "A2.Desktop" volume is now empty.

**Expected behavior**
"Copy to RAMCard..." in Apple II DeskTop should not erase files and folders after the "Selector" file is moved from the "Optional" folder to the "A2.Desktop" volume.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 36 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
My guess is that this has nothing to do with the Selector file and that the copy is accidentally being turned into a move since it's same-volume.

**Comment by inexorabletash** [comment]
Nice find. A couple of simpler repros are in the release notes.
