### ISSUE TITLE
Please eliminate the Selector menu flash caused after adding an entry to the Selector in Selector > Add an Entry..., after editing an entry in the Selector in Selector > Edit an Entry... and after deleting an entry in the Selector in Selector > Delete an Entry...

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#563]
Please eliminate the Selector menu flash caused after adding an entry to the Selector in Selector > Add an Entry..., after editing an entry in the Selector in Selector > Edit an Entry... and after deleting an entry in the Selector in Selector > Delete an Entry.... The Selector menu flash is annoying. This bug was caused by the fix to issue #518 in issue #518, commit e585977. Please do not revert and / or unfix issue #518. Please find a way to have both this issue and issue #518 fixed at the same time.

**Comment by inexorabletash** [comment]
This is due to resetting the menu.

In normal operations, users won't be changing Selector items frequently, so this isn't worth the effort to fix.
