### ISSUE TITLE
"Files remaining to copy:" in the "Copying to RAMCard..." dialog box briefly blanks out after briefly saying "0" when the copy of files and folders is completed when the target is in the volume directory

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#564]
**Describe the bug**
"Files remaining to copy:" in the "Copying to RAMCard..." dialog box briefly blanks out after briefly saying "0" when the copy of files and folders is completed when the target is in the volume directory. I think that this issue is an off-by-one bug, just like issue #462. I think that this issue is related to issue #462 and that this issue has the same root cause as issue #462, but this time in the Selector app instead of in the Apple II DeskTop app.

**To Reproduce**
1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha36-en_800k.2mg" disk image, while running Apple II DeskTop from a RAMCard.
2. Click on the Selector menu and go to Selector > Add an Entry....
3. Open the "Desk.Acc" folder in the Selector > Add an Entry... dialog box and select the "Control.Panels" folder.
4. Click OK.
5. Select "at first use" from the "Copy to RAMCard:" list.
6. Click OK.
7. A dialog box appears stating, "Do you want to save the new list on the system disk?".
8. Click OK.
9. Click on the Selector menu and go to Selector > Add an Entry....
10. Select the "Desk.Acc" folder in the Selector > Add an Entry... dialog box.
11. Click OK.
12. Select "at first use" from the "Copy to RAMCard:" list.
13. Click OK.
14. A dialog box appears stating, "Do you want to save the new list on the system disk?".
15. Click OK.
16. Click on the File menu and go to File > Quit.
17. Turn off the computer.
18. Turn on the computer.
19. Launch the Selector from "A2.Desktop", while running Apple II DeskTop from a RAMCard.
20. Select the "Control.Panels" folder from the Selector window.
21. "Files remaining to copy:" in the "Copying to RAMCard..." dialog box correctly briefly says "0" when the copy of files and folders is completed.
22. A dialog box appears stating, "Unable to run the program.".
23. Click OK.
24. Select the "Desk.Acc" folder from the Selector window.
25. "Files remaining to copy:" in the "Copying to RAMCard..." dialog box briefly blanks out after briefly saying "0" when the copy of files and folders is completed.

**Expected behavior**
"Files remaining to copy:" in the "Copying to RAMCard..." dialog box should not briefly blank out after briefly saying "0" when the copy of files and folders is completed when the target is in the volume directory.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 36 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
I think that this issue is an off-by-one bug, just like issue #462. I think that this issue is related to issue #462 and that this issue has the same root cause as issue #462, but this time in the Selector app instead of in the Apple II DeskTop app.

**Comment by inexorabletash** [comment]
That's super obscure, but yeah, weird:

![image](https://user-images.githubusercontent.com/771547/134612818-8b97de17-49b0-430d-a61f-47e37a6e5529.png)

**Comment by inexorabletash** [comment]
Simpler repro:

1. Create a disk image with a single executable file at the root, e.g. BASIC.SYSTEM
2. Configure a system with a RAMCard
3. Launch DeskTop.
4. Configure a Selector entry for the executable file, set to Copy to RAMCard... at first use
5. Quit
6. Launch Selector
7. Invoke the selector entry
