### ISSUE TITLE
The "New name:" dialog box text string in the File > Duplicate... dialog box should be replaced with a new dialog box text string

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#565]
The "New name:" dialog box text string in the File > Duplicate... dialog box should be replaced with a new dialog box text string. The identical "New name:" dialog box text string is used in the File > Rename... dialog box. The "New name:" dialog box text string's use in the File > Rename... dialog box makes sense. The "New name:" dialog box text string's use in the File > Duplicate... dialog box does not make sense.

**Comment by inexorabletash** [comment]
If it's good enough for GS/OS Finder it's good enough for me:

![image](https://user-images.githubusercontent.com/771547/134610255-b2e07581-4756-468a-9036-ecd265f454ef.png)
