### ISSUE TITLE
Remove "Do you want to save the new list on the system disk?" prompt

### ISSUE THREAD

**Issue by inexorabletash** [a2stuff/a2d#567]
When DeskTop is copied to RAMCard, and you modify Selector entries, DeskTop writes the updated `SELECTOR.LIST` to the copy on the ramdisk, but then prompts "Do you want to save the new list on the system disk?" and only if you select OK does it try to write to the original fdir. This is original MouseDesk behavior, and makes sense if you are likely to have swapped out your system disk. If you have swapped out the original disk you'll get a retry prompt.

The Control Panel DAs I wrote always try to write `DESKTOP.CONFIG` back to both RAM and original paths, without prompting. If the original is not found, it silently fails rather than prompting.

In a fixed-disk scenario where you are unlikely to have removed the original and running from RAM is just a speed optimization, prompting is annoying. But on the other hand, if you have removed the disk, having the changes be silently lost is also annoying.

Two options:

* Eliminate the prompt, and have DeskTop to always try writing to both locations, silently failing if the system disk is absent.
* Have DeskTop prompt only if the original location isn't online. If it is online, just write.

If the latter is chosen, maybe the same logic should be applied to the Control Panel DAs.

**Comment by apple2geek** [comment]
Just an opinion on this one.  It seems that the logic of "Try to write the configs, and if you can't write the config safely such that you won't lose changes (or the whole config), prompt the user for a decision or action" would be the most user-friendly.  For the prompting, basically ask them to re-insert the missing/removed disk and click "OK" try again, or choose "Cancel" to abandon saving the config changes with an explanation of the consequences of that choice.

**Comment by inexorabletash** [comment]
This turned out to be super easy. For now I haven't updated the Control Panel DAs to prompt as well.
