### ISSUE TITLE
When two folders are selected, and then opened at the same time, the second selected folder icon appears in the other newly opened window

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#568]
**Describe the bug**
When two folders are selected, and then opened at the same time, the second selected folder icon appears in the other newly opened window.

**To Reproduce**
Example 1:

1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha36-en_800k.2mg" disk image.
2. Open the "A2.Desktop" volume.
3. First click on the "Optional" folder and then click on the "Desk.Acc" folder while holding down a modifier key, in that order.
4. Double-click on the "Optional" folder, double click on the "Desk.Acc" folder or click on the File menu and go to File > Open.
5. The "Desk.Acc" folder icon appears briefly in the newly opened "Optional" window before being partially covered over by the newly opened "Desk.Acc" window.
6. Close the "Desk.Acc" window.
7. The "Desk.Acc" folder icon is still partially visible in the "Optional" window and the "Desk.Acc" folder icon is now partially repainted over.

Example 1 and Example 4 have identical results.

Example 2:

1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha36-en_800k.2mg" disk image.
2. Open the "A2.Desktop" volume.
3. First click on the "Desk.Acc" folder and then click on the "Optional" folder while holding down a modifier key, in that order.
4. Double-click on the "Desk.Acc" folder, double click on the "Optional" folder or click on the File menu and go to File > Open.
5. The "Optional" folder icon appears in the newly opened "Desk.Acc" window.

Example 3:

1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha36-en_800k.2mg" disk image.
2. Open the "A2.Desktop" volume.
3. First click on the "Desk.Acc" folder and then click on the "Preview" folder while holding down a modifier key, in that order, or drag-select the "Desk.Acc" folder and the "Preview" folder at the same time.
4. Double-click on the "Desk.Acc" folder, double click on the "Preview" folder or click on the File menu and go to File > Open.
5. The "Preview" folder icon appears briefly in the newly opened "Desk.Acc" window before being covered over by the newly opened "Preview" window.

Example 4:

1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha36-en_800k.2mg" disk image.
2. Open the "A2.Desktop" volume.
3. First click on the "Preview" folder and then click on the "Desk.Acc" folder while holding down a modifier key, in that order.
4. Double-click on the "Preview" folder, double click on the "Desk.Acc" folder or click on the File menu and go to File > Open.
5. The "Desk.Acc" folder icon appears briefly in the newly opened "Preview" window before being partially covered over by the newly opened "Desk.Acc" window.
6. Close the "Desk.Acc" window.
7. The "Desk.Acc" folder icon is still partially visible in the "Preview" window and the "Desk.Acc" folder icon is now partially repainted over.

Example 1 and Example 4 have identical results.

**Expected behavior**
When two folders are selected, and then opened at the same time, the second selected folder icon should not appear in the other newly opened window.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 36 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment]
GitHub incorrectly and involuntarily renumbered my short groups of steps for each example and synthesized them as part of one long sequence of steps. What is supposed to be "Example 1: Steps 1-7" is correctly stated as "Example 1: Steps 1-7". What is supposed to be "Example 2: Steps 1-5" is incorrectly stated as "Example 2: Steps 8-12". What is supposed to be "Example 3: Steps 1-5" is incorrectly stated as "Example 3: Steps 13-17". What is supposed to be "Example 4: Steps 1-7" is incorrectly stated as "Example 4: Steps 18-24". Please edit the step numbers so that they appear correctly.

**Comment by c0mmander8** [comment]
This issue also applies to three folders being first selected, and then opened at the same time. Please try first selecting, and then opening the "Optional" folder, the "Desk.Acc" folder and the "Preview" folder at the same time in the different orders given in the list in issue #363. Treat the "Optional" folder as folder A, the "Desk.Acc" folder as folder B and the "Preview" folder as folder C.

**Comment by inexorabletash** [comment]
A couple of screenshots to help explain this better:

![image](https://user-images.githubusercontent.com/771547/134777128-a991682c-cfa3-48a8-8ec3-ed18a397a3ff.png)

![image](https://user-images.githubusercontent.com/771547/134777161-6ff58774-8bbf-4f34-9b16-5ce8c7c839ac.png)

@c0mmander8 : You really need to learn how to use a web browser so you can edit your posts. 

The renumbering is because markdown is sensitive to whitespace and indenting. If you leave blank lines between numbered lists they won't renumber.
