### ISSUE TITLE
When two volumes with the same name are mounted at s7d1 and s7d2 in GSplus, the volume at s7d2 is mounted in Apple II DeskTop instead of the startup disk at s7d1

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#571]
**Describe the bug**
When two volumes with the same name are mounted at s7d1 and s7d2 in GSplus, the volume at s7d2 is mounted in Apple II DeskTop instead of the startup disk at s7d1.

**To Reproduce**
1. Start Apple II DeskTop in GSplus from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha36-en_800k.2mg" disk image, mounted at s7d1, while not running Apple II DeskTop from a RAMCard, with a blank volume also named "A2.Desktop" mounted at s7d2.
2. An error dialog box appears stating, "There are 2 volumes with the same name.".
3. Click OK.
4. There is only 1 "A2.Desktop" volume icon on the desktop.
5. Open the "A2.Desktop" volume icon.
6. The blank volume's blank contents appear in the "A2.Desktop" volume window.
7. Click on the Apple menu and select a desk accessory or a folder.
8. An error dialog box appears stating, "Part of the pathname doesn't exist.".
9. The startup disk at s7d1 should have been mounted in Apple II DeskTop instead of the blank volume at s7d2.

**Expected behavior**
When two volumes with the same name are mounted at s7d1 and s7d2 in GSplus, the startup disk at s7d1 should be mounted in Apple II DeskTop instead of the volume at s7d2.

**Screenshots**
 I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 36 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment]
I am starting to think Apple II DeskTop is working as intended in this scenario and that this is a feature, not a bug.

**Comment by c0mmander8** [comment]
If I understand this correctly, the last volume in reverse DEVLST order with the same name is the volume that is mounted in Apple II DeskTop. And if the last volume in reverse DEVLST order with the same name is unmounted, the previous volume in reverse DEVLST order with the same name is then subsequently mounted in Apple II DeskTop.

**Comment by c0mmander8** [comment]
Ignore my last 2 comments. I am still confused how this works or how this is supposed to work.

**Comment by inexorabletash** [comment]
ProDOS itself is confused. ProDOS can really only talk to files on disk by path. If you have two volumes named `DISK` and reference a file named `/DISK/FILE`, ProDOS doesn't know which volume you're talking about. That's probably why you're seeing unpredictable behavior - it's just not supported.

DeskTop warns you about this and will only show one, but operations on the disk can basically randomly go to one disk or another. Another option would be to refuse to start in this case. Or crash. Or try to eject the disk. Or remove the volume from the device list.

Anyway, don't do that, it's not supported.
