### ISSUE TITLE
Please eliminate the redrawing of the entire desktop when adjusting a window title after a window has been renamed

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#573]
Please eliminate the redrawing of the entire desktop when adjusting a window title after a window has been renamed. The redrawing of the entire desktop is annoying. This bug was caused by the fix to issue #469 in issue #469, commit 35b5bf0. Please do not revert and / or unfix issue #469. Please find a way to have both this issue and issue #469 fixed at the same time.

Here is what you said in issue #469 for reference:

Window title updates could be done with a full repaint at worst. Probably the best thing would be a way to invalidate a window's title area; MGTK doesn't have an "invalidate rectangle" but it really should.

Here is what you said in issue #469, commit 35b5bf0 for reference:

* Since windows can't be arbitrarily repainted, if any window titles
  are affected the entire desktop is redrawn. That's slow-ish, but
  still a vast improvement over closing/reloading windows.

**Comment by inexorabletash** [comment]
After thinking about this for a while, it's just too obscure to justify the time and code complexity impact to improve here.

A handful of plausible approach:
* Add a new MGTK call to update a rect. This would be based on `erase_window` logic, that draws the rect and then posts update events. The rename code would determine the rect for the affected window's title area and force an update.
* Add a new MGTK call to set the name of a window. This could be somewhat more scoped in that only the affected window's title area needs to redraw, followed by updates for any overlapping windows. 

Unless there is significant demand, this isn't worth the code complexity or risk to improve here.
