### ISSUE TITLE
Please eliminate the reloading from disk of the entire window with selection when any of the renamed icons are SYS files

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#574]
Please eliminate the reloading from disk of the entire window with selection when any of the renamed icons are SYS files. The reloading of the entire window with selection is annoying. This bug was caused by the fix to issue #469 in issue #469, commit 35b5bf0. Please do not revert and / or unfix issue #469. Please find a way to have both this issue and issue #469 fixed at the same time.

Here is what you said in issue #469 for reference:

SYS files could be handled by setting a flag and forcing a window reload. Actually swapping in an icon without it moving would be tricky. We could also punt on that case.

Here is what you said in issue #469, commit 35b5bf0 for reference:

* If any of the renamed icons are SYS files, the window with selection
  is reloaded from disk. This is necessary since SYS file icons change
  based on the name (.SYSTEM suffix or not). That's no worse than the
  previous behavior.

**Comment by inexorabletash** [comment]
Not worth the code complexity.
