### ISSUE TITLE
The "Disk II", "RAMCard", and "AppleShare" strings should be all correctly capitalized for all slots and all drives in the Special > Format a Disk... and Special > Erase a Disk... dialog boxes and in the This.Apple desk accessory

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#578]
**Describe the bug**
The Apple IIGS Control Panel RAM5 RAM disk located at s5d2 is incorrectly displayed as "Ramcard" instead of being correctly capitalized as "RAMCard" in the Special > Format a Disk... and Special > Erase a Disk... dialog boxes and in the This.Apple desk accessory. The screenshot posted at the bottom of issue #325 shows a RAMCard located at s3d1 correctly capitalized as "RAMCard" in the Format a Disk... dialog box after the changes to Apple II DeskTop in issue #325, commit f181310 were made. The notes to issue #325, commit f181310 state that there are hardcoded strings for "Disk II", "RAMCard", and "AppleShare". Make sure that these three strings are all correctly capitalized for all slots and all drives in the Special > Format a Disk... and Special > Erase a Disk... dialog boxes and in the This.Apple desk accessory.

**To Reproduce**
1. Start Apple II DeskTop in GSplus from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha37-en_800k.2mg" disk image, with an Apple IIGS Control Panel RAM5 RAM disk enabled in the Apple IIGS Control Panel.
2. Click on the Special menu and go to Special > Format a Disk... or Special > Erase a Disk....
3. The entry next to "S5,D2:" is incorrectly displayed as "Ramcard" instead of being correctly capitalized as "RAMCard".
4. Click Cancel.
5. Click on the Apple menu and select the This.Apple desk accessory.
6. The entry next to "Slot 5:" is incorrectly displayed as "SmartPort: Disk 3.5, Ramcard, Disk 3.5" instead of being correctly capitalized as "SmartPort: Disk 3.5, RAMCard, Disk 3.5".

**Expected behavior**
The Apple IIGS Control Panel RAM5 RAM disk located at s5d2 should be correctly displayed as "RAMCard" instead of being incorrectly capitalized as "Ramcard" in the Special > Format a Disk... and Special > Erase a Disk... dialog boxes and in the This.Apple desk accessory. The "Disk II", "RAMCard", and "AppleShare" strings should be all correctly capitalized for all slots and all drives in the Special > Format a Disk... and Special > Erase a Disk... dialog boxes and in the This.Apple desk accessory.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 37 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Case adjusting is done for SmartPort protocol devices. The options are leaving it as reported by the device, e.g. "RAMCARD", "OMNIDISK", etc. or case-adjusting to "Ramcard", "Omnidisk", etc. That applies to the GS RAMDisk. 

Non-SmartPort devices have hard coded strings including "Disk II" and "AppleShare", or "RAMCard" for RAMDisks with software drivers. If you see those appear, that's a bug. 

I'm not going to introduce a lookup table for device names.
