### ISSUE TITLE
Enable pressing any key at all to dismiss the Apple > About Apple II DeskTop about box

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#579]
Enable pressing any key at all to dismiss the Apple > About Apple II DeskTop about box, just like the middle IIGS.

**Comment by inexorabletash** [comment]
Not interested.

**Comment by c0mmander8** [comment]
Please reopen this issue and issue #580. This issue and issue #580 are for greater user interface consistency. Pressing any key at all in the Flying Toasters, Invert or Melt screen savers or pressing any key at all in the Show Duet File preview handler dismisses the respective screen saver or the Show Duet File preview handler.
