### ISSUE TITLE
Enable pressing any key at all, other than the space bar, to dismiss the Show Image File preview handler

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#580]
Enable pressing any key at all, other than the space bar, to dismiss the Show Image File preview handler. Pressing the space bar should still toggle between color mode and monochrome mode.

**Comment by c0mmander8** [comment]
I accidentally marked this issue with the "DeskTop" label instead of the "Desk Accessories" label. Please remove the "DeskTop" label from this issue and add the "Desk Accessories" label to this issue.

**Comment by inexorabletash** [comment]
Not interested. I want to reserve other keys for future operations.

**Comment by c0mmander8** [comment]
Please reopen this issue and issue #579. This issue and issue #579 are for greater user interface consistency. Pressing any key at all in the Flying Toasters, Invert or Melt screen savers or pressing any key at all in the Show Duet File preview handler dismisses the respective screen saver or the Show Duet File preview handler.
