### ISSUE TITLE
Pressing any key while the Show Duet File preview handler is running does not affect it

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#581]
**Describe the bug**
Pressing any key while the Show Duet File preview handler is running does not affect it.

**To Reproduce**
1. Start Apple II DeskTop in GSplus from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha37-en_800k.2mg" disk image.
2. Double-click and open the "A2.Desktop" volume.
3. Double click and open the "Preview" folder.
4. Double-click and open the "Show.Duet.File" preview handler.
5. The Show Duet File about box goes away and Show Duet File closes after a few seconds.
6. Double-click and open the "Show.Duet.File" preview handler again.
7. This time, keep pressing any key repeatedly while the Show Duet File about box is present.
8. Step 7 has no effect and Show Duet File still closes after a few seconds, just like in step 5.

**Expected behavior**
Pressing any key while the Show Duet File preview handler is running shout cause the Show Duet File about box to go away immediately and Show Duet File to close immediately.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 37 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
I actually have no music files to play with Show Duet File. My test simply consisted of first double-clicking and opening Show Duet File and waiting for it to close by itself. It did so after a few seconds. Then I double-clicked and opened Show Duet File a second time while pressing any key I could repeatedly. This had no effect. This did not affect Show Duet File at all. It still closed by itself after a few seconds instead of closing immediately.

**Comment by inexorabletash** [comment]
It's probably crashing or stuck in a tight loop if you don't have an appropriate file. Reopen if you can reproduce the behavior with an actual ED file.
