### ISSUE TITLE
Please make the menu bar clock in both the Apple II DeskTop app and the Selector app fully accurate by updating it continuously instead of updating it every 3-5 seconds

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#589]
As referenced in issue #7, currently, the menu bar clock is not fully accurate. The menu bar clock is currently updated on the same polling interval as disks are scanned for - every 3-5 seconds. Please make the menu bar clock in both the Apple II DeskTop app and the Selector app fully accurate by updating it continuously instead of updating it every 3-5 seconds.

**Comment by inexorabletash** [comment]
While some of the bugs you file are worthwhile, you file multiple bugs per day which are about trivial issues, and you repeatedly fail to follow guidance on how to write concise issue reports. Banning for a month.

**Comment by inexorabletash** [comment]
Polling more frequently would make the mouse less responsive.

If you're relying on your Apple for that amount of precision in your clock, you're doing something wrong.

Please don't file such low value bugs. It takes time away from being able to make meaningful improvements just to read them. Also, adhere to short bug titles and short descriptions. Other people who watch this repo are complaining about the noise that such length issue titles generate. Out of respect for others, please take the extra time to edit bug reports to be as concise as possible.

**Comment by c0mmander8** [comment]
I am sorry. I apologize for any offense I caused. I meant no harm. I will try to file less bugs and I will try to file the bugs I do file less often. I am trying to squash every bug I can find in order to make Apple II DeskTop more consistent and more reliable in its looks and its actions. I am a perfectionist. But it is extremely hard, if not impossible, for me to make my bug titles, bug descriptions and bug reports any shorter and more concise than they already are, although I will still try to do so. I am already keeping my bug titles, bug descriptions and bug reports as short and concise as possible with the way I write.

**Comment by c0mmander8** [comment]
Is there an alternative way to fix this bug than by polling more frequently?
