### ISSUE TITLE
Screensaver with digital/analog clock

### ISSUE THREAD

**Issue by mikgigs** [a2stuff/a2d#590]
A clock screensaver. Similar to the one in Windows 3.x - digital clock, e.g. 20:00 at random position, changed e.g. every 2 minutes

**Comment by inexorabletash** [comment]
Digital:

![image](https://user-images.githubusercontent.com/771547/200132970-323b17e7-4542-43bc-8fca-2712948a0daf.png)

Doesn't move, though.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/200147776-ffcea09b-5a06-4965-a517-e8aadc66a24b.png)

**Comment by mikgigs** [comment]
Thank you, Sir!
Now, my apple ii clone is 10 times more useful! Cheers!
