### ISSUE TITLE
Apple II DeskTop, Disk Copy, the Selector or desk accessories take between a few and numerous seconds to return back to black and white mode upon exiting the Apple IIGS Control Panel instead of it occurring instantaneously

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#595]
**Describe the bug**
Apple II DeskTop, Disk Copy, the Selector or desk accessories take between a few and numerous seconds to return back to black and white mode upon exiting the Apple IIGS Control Panel instead of it occurring instantaneously.

**To Reproduce**
1. Start Apple II DeskTop or launch the Selector on an Apple IIGS with the "RGB Color" setting in the Apple II DeskTop Control.Panel control panel disabled.
2. Only if you want to, launch Disk Copy or open a desk accessory if Apple II DeskTop has been started instead of the Selector being launched. This step is completely optional.
3. Enter the Apple IIGS Control Panel.
4. Exit the Apple IIGS Control Panel.
5. The Apple IIGS remains in color mode and its video is messed up for between a few and numerous seconds before the Apple IIGS returns to black and white mode and its video returns to normal.

**Expected behavior**
Apple II DeskTop, Disk Copy, the Selector or desk accessories should return back to black and white mode instantaneously upon exiting the Apple IIGS Control Panel if the the "RGB Color" setting in the Apple II DeskTop Control.Panel control panel is disabled instead of taking between a few and numerous seconds to do so.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 39 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
This issue is for greater user interface consistency.

**Comment by inexorabletash** [comment]
This would require more frequent polling, which would make mouse movement more janky. 

For an infrequent action by users, the current polling frequency is acceptable.

**Comment by c0mmander8** [comment]
Is there an alternative way to fix this bug than more frequent polling?
