### ISSUE TITLE
Respect 12/24hr setting in Date.And.Time control panel

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#596]
The time display and input in the Date.And.Time control panel should be a 12-hour clock, with "AM" and "PM" shown, if the "12hr" "Clock" setting is selected in the Control.Panel control panel and a 24-hour clock, with "AM" and "PM" not shown, if the "24hr" "Clock" setting is selected in the Control.Panel control panel instead of the time display and input in the Date.And.Time control panel currently always being a 24-hour clock, with "AM" and "PM" not shown, no matter which "Clock" setting is selected in the Control.Panel control panel.

**Comment by c0mmander8** [comment]
This feature request was referenced in issue #11, commit a6a89e7.

**Comment by inexorabletash** [comment]
I think you may have failed to read the commit comment, which reads: "Please don't file a bug about that, although
PRs welcome."

**Comment by c0mmander8** [comment]
Indeed, I did read the part of the commit comment in issue #11, commit a6a89e7 which states "(Please don't file a bug about that, although
PRs welcome.)" before creating this feature request. I still think this feature request is advisable and necessary, though.
