### ISSUE TITLE
Implement automatic window navigation after clicking and holding down the mouse button while opening a folder or a volume, and then automatically open and close windows while navigating subfolders while the mouse button is still held down

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#597]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that I have to tunnel folders to get where I want to go in order to leave behind no open windows in my wake.

**Describe the solution you'd like**
As referenced in issue #371, implement automatic window navigation after clicking and holding down the mouse button while opening a folder or a volume, and then automatically open and close windows while navigating subfolders while the mouse button is still held down, just like in the Classic Mac OS 8.0-9.2.2 Finder. This is an alternative to and a variation on tunneling folders. I am not talking about implementing automatic window navigation while dragging a file or a folder or while dragging multiple files or multiple folders, although that would be an even better feature to add.

**Describe alternatives you've considered**
Keep on tunneling folders, just as I have always done.

**Additional context**
This is an alternative to and a variation on tunneling folders. I am not talking about implementing automatic window navigation while dragging a file or a folder or while dragging multiple files or multiple folders, although that would be an even better feature to add.

**Comment by inexorabletash** [comment]
Interesting - I was unaware of this feature. I downloaded https://github.com/felixrieseberg/macintosh.js to try it out. For those who haven't seen it:

* Double-click on a volume or folder, but keep holding the mouse button (so down/up/down-hold)
* After a second or so, the mouse pointer turns into a magnifying glass, and stays in this mode until you let go.
* If you hover the mouse over a volume or folder icon for about a second its window will open, near the mouse. The window has an inset highlight, indicating its transient state.
* If you move the mouse out of a transient window, it will close.
* If you release the mouse button while in a transient window, it will stay open.
* 
By combining these actions, you can somewhat more easily explore the file system without double-clicking icons and closing windows.

However... given that it's an incredibly obscure feature that wasn't present in very old macOS and not in modern OSes either. I don't think it's worth trying to support relative to the cost/risk.
