### ISSUE TITLE
Keyboard shortcut suggestions for file pickers

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#598]
New keyboard shortcuts for the file picker dialog boxes in the Apple II DeskTop app and in the Selector app for keyboard shortcut consistency with the main Apple II DeskTop app:

* Control-\`: Cycle mounted drives in reverse DEVLST order. Same as Tab. (In addition to keyboard shortcut consistency with the main Apple II DeskTop app, this proposed keyboard shortcut and the proposed Shift-Control-\` keyboard shortcut are necessary because the proposed Shift-Tab keyboard shortcut will not work on a non-Apple IIGS without the Shift key mod installed.)
* Shift-Control-\`: Cycle mounted drives in DEVLST order. Same as proposed Shift-Tab. (In addition to keyboard shortcut consistency with the main Apple II DeskTop app, this proposed keyboard shortcut and the proposed Control-\` keyboard shortcut are necessary because the proposed Shift-Tab keyboard shortcut will not work on a non-Apple IIGS without the Shift key mod installed.)
* Shift-Tab: Cycle mounted drives in DEVLST order. Same as proposed Shift-Control-\`.
* Control-W: Open enclosing folder or, if none, enclosing volume of the current folder. Same as Control-C or proposed Control-Up Arrow.
* Control-Down Arrow: Open selected folder. Same as Control-O.
* Control-Up Arrow: Open enclosing folder or, if none, enclosing volume of the current folder. Same as Control-C or proposed Control-W.
* Holding Shift key down while clicking "Change Drive": Cycle mounted drives in DEVLST order. Same as proposed Shift-Control-\` or proposed Shift-Tab.

New keyboard shortcut for the main Apple II DeskTop app for keyboard shortcut consistency with the file picker dialog boxes in the Apple II DeskTop app and in the Selector app:

* Apple-C: Close selected window. Same as Apple-W.

**Comment by c0mmander8** [comment]
Please edit my above post. "Control-`" should be "Control-\`" wherever it appears in my above post and "Shift-Control-`" should be "Shift-Control-\`" wherever it appears in my above post. Thank you.

**Comment by c0mmander8** [comment]
Should the behavior of the Apple modifier key and the Control modifier key in the file picker dialog boxes in the Apple II DeskTop app and in the Selector app be reversed? In the in the "Open...", "Save" and "Save As..." dialog boxes on the Mac, the Command modifier key, the Mac equivalent of the Apple modifier key, is used instead of the Control modifier key for keyboard shortcuts. In the in the "Open...", "Save", "Save as..." and "Save Copy as..." dialog boxes on the IIGS, the Open-Apple modifier key, is used instead of the Control modifier key for keyboard shortcuts. What do you think? Please tell me your opinion.

**Comment by c0mmander8** [comment]
This would also unify the behavior of the keyboard shortcuts in the file picker dialog boxes in the Apple II DeskTop app and in the Selector app with the behavior of the keyboard shortcuts in the rest of the Apple II DeskTop app, in the rest of the Selector app, in Disk Copy and in Key Caps.

**Comment by inexorabletash** [comment]
I added support for holding Apple to switch the direction when clicking Change Drive or pressing Tab. The rest is not worthwhile.

**Comment by c0mmander8** [comment]
The Apple modifier key would be used for keyboard shortcuts and the Control modifier key would be used for keyboard navigation in the file picker dialog boxes in the Apple II DeskTop app and in the Selector app.

**Comment by c0mmander8** [comment]
As referenced in issue #604, I especially think that making Control-Arrow keypresses do something in all of the file picker dialog boxes, both in the Apple II DeskTop app and in the Selector app, is worthwhile, since these ideas were the main purpose behind me filing this issue in the first place.

**Comment by c0mmander8** [comment]
I have a question for you. Could you please answer it for me? Can Control-Tab be detected by 8-bit Apple IIs and 8-bit Apple II clones?

**Comment by c0mmander8** [comment]
When I said, "Can Control-Tab be detected by 8-bit Apple IIs and 8-bit Apple II clones?", I meant to instead say, "Can Control-Tab be detected by 8-bit Apple IIs that are compatible with Apple II DeskTop and 8-bit Apple II clones that are compatible with Apple II DeskTop?". I am excluding from my question the original 1977 Apple II, the 1979 Apple II Plus (Apple II+) and the original 1983 Apple IIe with the Revision A motherboard without Double Low Resolution Graphics (DLGR) and Double High Resolution Graphics (DHGR) support and clones based on the original 1977 Apple II, the 1979 Apple II Plus (Apple II+) and the original 1983 Apple IIe with the Revision A motherboard without Double Low Resolution Graphics (DLGR) and Double High Resolution Graphics (DHGR) support.

**Comment by c0mmander8** [comment]
I would appreciate it very much if you answer the question mentioned above and I thank you in advance for doing so.

**Comment by c0mmander8** [comment]
I think that I have answered my own question. I think that Control-Tab cannot be detected by 8-bit Apple IIs that are compatible with Apple II DeskTop and 8-bit Apple II clones that are compatible with Apple II DeskTop because there is no basic ASCII C0 control code that corresponds to Control-Tab.

**Comment by c0mmander8** [comment]
I know for certain that I have answered my own question. I know for certain that Control-Tab cannot be detected by all 8-bit Apple IIs, including all 8-bit Apple IIs that are compatible with Apple II DeskTop, and all 8-bit Apple II clones, including all 8-bit Apple II clones that are compatible with Apple II DeskTop, because Control-Tab does not correspond with any basic ASCII C0 control code.
