### ISSUE TITLE
Change the "Change Drive" button to a "Desktop" button and list volumes

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#599]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that I have to cycle through lots of volumes in the file picker dialog boxes, both in the Apple II DeskTop app and in the Selector app, in order to reach the volume I am searching for when I have 13 volumes mounted.

**Describe the solution you'd like**
Clicking on the "Change Drive" button in any of the file picker dialog boxes, either in the Apple II DeskTop app or in the Selector app, should present a list of all mounted volumes so that you can choose the volume you want, just like clicking on the "Desktop" button in the "Open...", "Save" and "Save As..." dialog boxes in Classic Mac OS System 7.0 - Mac OS 8.1.

**Describe alternatives you've considered**
Keep on cycling through lots of volumes in the file picker dialog boxes in order to reach the volume I am searching for, just as I have always done.

**Additional context**
There is no other context or screenshots about this feature request here.

**Comment by c0mmander8** [comment]
If you decide you want to keep the current behavior of the "Change Drive" button, you can instead, in addition to the "Change Drive" button, add a "Desktop" button with a Control-D keypress keyboard shortcut for the proposed new behavior.

**Comment by c0mmander8** [comment]
A Control-D keypress should be the keyboard shortcut for the proposed new behavior whether it is using the existing "Change Drive" button, a renamed "Desktop" button or an additional "Desktop" button in addition to the existing "Change Drive" button.

**Comment by inexorabletash** [comment]
This would be equivalent to the "Desktop" button introduced in Mac OS System 7:

![image](https://user-images.githubusercontent.com/771547/145321449-ef00331e-d630-47a2-8f9a-e006239ca498.png)

I haven't thought through all of the challenges here, but this doesn't seem to be totally infeasible to try and tackle this. "Change Drive" would change to "DeskTop" (as suggested above), and either hitting that or "Close" enough times would take you to the list of volumes.

Not something I'm going to work on, but someone else might be interested.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/199872787-f427417f-4901-46c7-a966-818848b276e1.png)

![image](https://user-images.githubusercontent.com/771547/199872794-8cfcece8-a63b-4721-a665-6021ebc2ba49.png)

![image](https://user-images.githubusercontent.com/771547/199872812-2426ae03-0651-4f80-981d-c2e525fbe5d7.png)
