### ISSUE TITLE
Add a "New Folder" button to all of the file picker dialog boxes

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#601]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that I cannot directly create a new folder in the File > Copy a File... file picker dialog box to contain a file that I am duplicating.

**Describe the solution you'd like**
For greater user convenience, add a "New Folder" button to all of the file picker dialog boxes, both in the Apple II DeskTop app and in the Selector app, just like in the "Save" and "Save As..." dialog boxes on the Mac and in the "Save", "Save as..." and "Save Copy as..." dialog boxes on the IIGS.

**Describe alternatives you've considered**
Keep on, first, creating a new folder at the destination site and then using the File > Copy a File... file picker dialog box to duplicate the file.

**Additional context**
It would also be useful to be able to directly create a folder in the Shortcuts > Add a Shortcut... or the Shortcuts > Edit a Shortcut... file picker dialog box and then be able to immediately add the folder to the Selector.

**Comment by inexorabletash** [comment]
Interesting idea. For the record, it looks like this first showed up in macOS System 7. System 6 doesn't have this. This is from TeachText, I assume the dialogs are pretty standard, apart from the "what type to save as" radio buttons in System 7.

System 6:
![image](https://user-images.githubusercontent.com/771547/145320538-56302e84-6f8b-4524-a0a8-66d97b4ad591.png)

System 7:
![image](https://user-images.githubusercontent.com/771547/145320856-b04bdce8-6dac-4040-b7a4-b4a0482a3b1c.png)

The challenge is running the code for a nested dialog for the name prompt and the folder creation code/error handling within the already complex file picker. It would be a substantial amount of work.

**Comment by c0mmander8** [comment]
A Control-N keypress should be the keyboard shortcut for the proposed new "New Folder" button.

**Comment by inexorabletash** [comment]
Due to how crowded the dialog is, and how complicated this would be to implement, I'm going to close this out. It's not a bad idea, it's just unlikely to happen without significantly rethinking the UI.
