### ISSUE TITLE
Should the behavior of the Apple modifier key and the Control modifier key in the file picker dialog boxes in the Apple II DeskTop app and in the Selector app be reversed?

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#602]
As referenced in issue #598, should the behavior of the Apple modifier key and the Control modifier key in the file picker dialog boxes in the Apple II DeskTop app and in the Selector app be reversed? The Apple modifier key would be used for keyboard shortcuts and the Control modifier key would be used for keyboard navigation in the file picker dialog boxes in the Apple II DeskTop app and in the Selector app. This would unify the behavior of the keyboard shortcuts in the file picker dialog boxes in the Apple II DeskTop app and in the Selector app, which currently use the Control modifier key, with the behavior of the keyboard shortcuts in the rest of the Apple II DeskTop app, in the rest of the Selector app, in Disk Copy and in Key Caps, which use the Apple modifier key. In the in the "Open...", "Save" and "Save As..." dialog boxes on the Mac, the Command modifier key, the Mac equivalent of the Apple modifier key, is used instead of the Control modifier key for keyboard shortcuts. In the in the "Open...", "Save", "Save as..." and "Save Copy as..." dialog boxes on the IIGS, the Open-Apple modifier key, is used instead of the Control modifier key for keyboard shortcuts. What do you think? Please tell me your opinion.

**Comment by inexorabletash** [comment]
No. 

(Not something I'm interested in pursuing.)
