### ISSUE TITLE
Refresh file list in file pickers when disks are swapped

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#603]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that I have to keep on clicking on "Change Drive" after I insert a 3.5-inch floppy disk in order to reach the contents of the 3.5-inch floppy disk that I have just inserted.

**Describe the solution you'd like**
All of the file picker dialog boxes, both in the Apple II DeskTop app and in the Selector app, should automatically update their contents to the contents of a just inserted 3.5-inch floppy disk.

**Describe alternatives you've considered**
Just keep on clicking on "Change Drive" after I insert a 3.5-inch floppy disk in order to reach the contents of the 3.5-inch floppy disk that I have just inserted.

**Additional context**
After this feature request is implemented, make sure that clicking on "Change Drive" goes to the volume immediately following the just inserted 3.5-inch floppy disk in reverse DEVLST order and make sure that clicking on "Change Drive" with the Apple modifier key held down goes to the volume immediately following the just inserted 3.5-inch floppy disk in DEVLST order.

**Comment by c0mmander8** [comment]
The "Additional context" I gave up above in this feature request also applies to the Tab and Apple-Tab keyboard shortcuts.

**Comment by c0mmander8** [comment]
After this feature request is implemented, make sure that pressing the Tab keyboard shortcut goes to the volume immediately following the just inserted 3.5-inch floppy disk in reverse DEVLST order and make sure that pressing the Apple-Tab keyboard shortcut goes to the volume immediately following the just inserted 3.5-inch floppy disk in DEVLST order.

**Comment by c0mmander8** [comment]
This feature request aims to copy the behavior from the "Open...", "Save" and "Save As..." dialog boxes on the Mac Classic Mac OS and this feature request aims to copy the behavior from the "Open...", "Save", "Save as..." and "Save Copy as..." dialog boxes on the IIGS GS/OS.

**Comment by inexorabletash** [comment]
This would require polling, which is error prone and requires filtering out certain drive types (e.g. IIc+'s internal drive, since it keeps the drive motor spinning endlessly). DeskTop itself does that.

I'm not going to implement this, but it's a plausible project for someone else to pick up so I'm not going to close it for now.

**Comment by c0mmander8** [comment]
After issue #605 is implemented, the "Additional context" I gave up above in this feature request also applies to clicking on "Change Drive" with the Shift modifier key held down on an Apple IIGS, on a Platinum Apple IIe or on a Apple II or a Apple II clone that has had the Shift key mod installed. Furthermore, after issue #605 is implemented, the "Additional context" I gave up above in this feature request also applies to the Shift-Tab keyboard shortcut on an Apple IIGS, on a Platinum Apple IIe or on a Apple II or a Apple II clone that has had the Shift key mod installed.

**Comment by c0mmander8** [comment]
After this feature request and issue #605 are both implemented, make sure that clicking on "Change Drive" with the Shift modifier key held down also goes to the volume immediately following the just inserted 3.5-inch floppy disk in DEVLST order on an Apple IIGS, on a Platinum Apple IIe or on a Apple II or a Apple II clone that has had the Shift key mod installed. Furthermore, after this feature request and issue #605 are both implemented, make sure that pressing the Shift-Tab keyboard shortcut also goes to the volume immediately following the just inserted 3.5-inch floppy disk in DEVLST order on an Apple IIGS, on a Platinum Apple IIe or on a Apple II or a Apple II clone that has had the Shift key mod installed.

**Comment by inexorabletash** [comment]
Not worth implementing, given the complexity/cost.
