### ISSUE TITLE
Make Control-Arrow keypresses do something in all of the file picker dialog boxes

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#604]
As referenced in issue #598, make Control-Arrow keypresses do something in all of the file picker dialog boxes, both in the Apple II DeskTop app and in the Selector app. I especially think that these ideas are worthwhile, since these ideas were the main purpose behind me filing issue #598 in the first place. The following are my ideas:

* Control-Left Arrow: Cycle mounted drives in DEVLST order. Same as Apple-Tab. (The equivalent Command-Left Arrow command is implemented in Mac Classic Mac OS System 7.0-Mac OS 8.1 and the equivalent Open Apple-Left Arrow is implemented in IIGS GS/OS System 6.0.1 and later.)
* Control-Right Arrow: Cycle mounted drives in reverse DEVLST order. Same as Tab. (The equivalent Command-Right Arrow command is implemented in Mac Classic Mac OS System 7.0-Mac OS 8.1 and the equivalent Open Apple-Right Arrow is implemented in IIGS GS/OS System 6.0.1 and later.)
* Control-Down Arrow: Open selected folder. Same as Control-O. (The equivalent Command-Down Arrow command is implemented in Mac Classic Mac OS System 3.0-Mac OS 9.2.2 and the equivalent Open Apple-Down Arrow is implemented in IIGS GS/OS System 3.1 and later.)
* Control-Up Arrow: Open enclosing folder or, if none, enclosing volume of the current folder. Same as Control-C. (The equivalent Command-Up Arrow command is implemented in Mac Classic Mac OS System 3.0-Mac OS 9.2.2 and the equivalent Open Apple-Up Arrow is implemented in IIGS GS/OS System 3.1 and later.)

**Comment by c0mmander8** [comment]
Please implement these ideas. Thank you.

**Comment by c0mmander8** [comment]
The Mac Classic Mac OS examples I gave up above in this feature request were from the "Open...", "Save" and "Save As..." dialog boxes on the Mac Classic Mac OS and the IIGS GS/OS examples I gave up above in this feature request were from the "Open...", "Save", "Save as..." and "Save Copy as..." dialog boxes on the IIGS GS/OS.

**Comment by inexorabletash** [comment]
* The Control key can only be detected on IIgs systems. Control+Arrow on an 8-bit machine generates the same input as the arrow on its own.
* There are already keyboard options for these actions, as you point out.
* The Command/Apple+Arrow modifiers you cite from other OSes are already used for actions in this dialog (up/down are home/end in the file list, left/right are home/end in the text field), so this wouldn't be improving "muscle memory" from other OSes

So, unless I was going to completely redo the input for file dialogs (and I already solved that issue), I'm not going to make these changes.

*Do not file duplicate issues* just because you disagree with a previous resolution.

**Comment by c0mmander8** [comment]
I am sorry to hear that Control-Arrow keypresses cannot be detected on 8-bit Apple IIs and on 8-bit Apple II clones. I did not know of that fact. Even if reduced in scope to just the Apple IIGS, I think that this feature request is still extremely useful and worthwhile. The muscle memory from other operating systems analogy here is maybe imprecise and imperfect here because it is the Control key and not the Apple key, because as you have already stated above, the Apple key is already used for other actions in all of the file picker dialog boxes, both in the Apple II DeskTop app and in the Selector app. The muscle memory from other operating systems analogy works though for the Control-O keypress keyboard shortcut even though it is maybe imprecise and imperfect because it is Control-O and not Apple-O. Even though there are alternative keyboard shortcuts for each of these actions, adding these keyboard shortcuts to the Apple IIGS would be greatly helpful. Sometimes opening and closing folders and cycling mounted drives with the Arrow keys is something that is greatly wanted and is something that is sorely missed. So, please reconsider your decision and please reopen this issue. Then, as referenced above and in issue #598, please implement the Control-Arrow keypress keyboard shortcuts mentioned above and in issue #598 for the Apple IIGS.

**Comment by c0mmander8** [comment]
I know that you are hesitant about adding Apple IIGS-only features, but I sincerely think that this feature request is a good one to implement.

**Comment by c0mmander8** [comment]
Please implement this feature request. Thank you.
