### ISSUE TITLE
Allow shift as modifier for "Change Drive" in file pickers

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#605]
As referenced in issue #598, allow the use of Shift-Tab as an additional keyboard shortcut to cycle mounted drives in DEVLST order in addition to the already existing Apple-Tab keyboard shortcut to cycle mounted drives in DEVLST order in all of the file picker dialog boxes, both in the Apple II DeskTop app and in the Selector app. Further, allow holding the Shift key down while clicking "Change Drive" to cycle mounted drives in DEVLST order in addition to the already existing holding the Apple key down while clicking "Change Drive" to cycle mounted drives in DEVLST order. This simple feature request is useful for Apple IIGS users, Platinum Apple IIe users and users of Apple IIs and Apple II clones that have had the Shift key mod installed to use their muscle memory from using other operating systems in order to cycle mounted drives in reverse. You have already traveled down this same path and used the same logic when you allowed the Shift-Apple-Tab keyboard shortcut to cycle backwards through open windows in the Apple II DeskTop app in issue #230, commit 62dae54.

**Comment by c0mmander8** [comment]
Please implement this feature request. Thank you.

**Comment by inexorabletash** [comment]
Please keep your issue titles short. I've been editing them to provide examples of appropriate titles. Please use these to learn how to write more concise titles.
