### ISSUE TITLE
File picker scrollbar not positioned proportional to number of entries

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#607]
**Describe the bug**
Pressing Apple-Down Arrow or scrolling down to the last entry in the scrollbar in a volume or a folder that has 9 or more files and / or folders in any of the file picker dialog boxes, both in the Apple II DeskTop app and in the Selector app, leaves a lot of empty space in the scrollbar below the scrollbar thumb even though the last entry in the scrollbar is highlighted.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open a file picker dialog box.
3. Select a volume or open a folder that has 9 or more files and / or folders.
4. Press Apple-Down Arrow.
5. There is a lot of empty space in the scrollbar below the scrollbar thumb even though the last entry in the scrollbar is highlighted.

**Expected behavior**
There should be no empty space in the scrollbar below the scrollbar thumb when the last entry in the scrollbar in a volume or a folder that has 9 or more files and / or folders in any of the file picker dialog boxes, both in the Apple II DeskTop app and in the Selector app, is highlighted.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 39 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment]
The "Expected behavior" section of this bug report should instead read as, "Pressing Apple-Down Arrow or scrolling down to the last entry in the scrollbar in a volume or a folder that has 9 or more files and / or folders in any of the file picker dialog boxes, both in the Apple II DeskTop app and in the Selector app, should leave no empty space in the scrollbar below the scrollbar thumb."

**Comment by inexorabletash** [comment]
Please keep your issue titles short.
