### ISSUE TITLE
Include ellipsis (...) in progress bar text strings

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#611]
Should all of the startup screen progress bar text strings, both in the English original and in all translations, have an ellipsis (...) at the end of them because an ellipsis (...) indicates an ongoing operation? This means the following:

1. Should the "Copying Apple II DeskTop into RAMCard" startup screen progress bar text string instead be "Copying Apple II DeskTop into RAMCard..."?
2. Should the "Loading Selector" startup screen progress bar text string instead be "Loading Selector..."?
3. Should the "Loading Apple II DeskTop" startup screen progress bar text string instead be "Loading Apple II DeskTop..."?

**Comment by inexorabletash** [comment]
Eh, maybe. Ideally this would be done using the ellipsis character `…` rather than 3 periods `...`, taking advantage of the [MouseText](https://en.wikipedia.org/wiki/MouseText) character if mousetext is available.
