### ISSUE TITLE
Mouse cursor flashes on left edge of screen when the Fast Mouse Tracking is clicked

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#612]
**Describe the bug**
The mouse cursor briefly appears for an instant on the left edge of the center of the screen before disappearing again when the "Fast" radio button in the "Mouse Tracking" section of the Control.Panel control panel is selected.

**To Reproduce**
1. Start Apple II DeskTop.
2. Click on the Apple menu and select the Control.Panels folder.
3. Double-click on and open the Control.Panel control panel.
4. Select the "Fast" radio button in the "Mouse Tracking" section of the Control.Panel control panel.
5. The mouse cursor briefly appears for an instant on the left edge of the center of the screen before disappearing again.
6. If step 5 does not occur, rapidly and repeatedly alternate between selecting the "Slow" radio button and the "Fast" radio button in the "Mouse Tracking" section of the Control.Panel control panel.
7. Eventually, the mouse cursor briefly appears for an instant on the left edge of the center of the screen before disappearing again.
8. Step 5 / step 7 keeps on occurring the more you repeat and keep on performing step 6.

**Expected behavior**
The mouse cursor should not appear at all on the left edge of the center of the screen when the "Fast" radio button in the "Mouse Tracking" section of the Control.Panel control panel is selected.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 40 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Please keep your issue titles short. You have been asked repeatedly. Failure to follow instructions will result in banning. Don't make excuses, just follow instructions.

**Comment by inexorabletash** [comment]
The DA avoids mouse warping after calling `ScaleMouse` by posting a `no_event` with the same coords. This works just fine.

Following the scaling, the input loop calls `GetEvent`; this MGTK routine calls `MoveCursor` which compares internal `mouse_state` (last reading of actual mouse coords - which are incorrect) against `set_pos_params` (last known coords - which are correct here); since they differ, this results in a cursor redraw.

**Comment by c0mmander8** [comment]
Please do not ban me. I am trying to be helpful. I find it extremely hard to shorten my issue titles. Perhaps it would be better if you shorten my issue titles for me after I post my issues?
