### ISSUE TITLE
The right one-third of a folder is still shaded in after opening and then closing multiple folders, including the affected folder itself

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#613]
**Describe the bug**
The right one-third of a folder is still shaded in after opening and then closing multiple folders, including the affected folder itself.

**To Reproduce**
1. Start Apple II DeskTop in GSplus from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha40-en_800k.2mg" disk image.
2. Open the "A2.Desktop" volume.
3. Create a new folder named "A" inside the "A2.Desktop" volume window.
4. Open the "A" folder that you have just created in step 3.
5. Create 5 new folders named "A", "B", "C", "D" and "E" inside the "A" folder window.
6. Close all windows.
7. Open the "A2.Desktop" volume.
8. Open the parent "A" folder that you created in step 3.
9. Click on the File menu and go to File > Select All and select the five folders named "A", "B", "C", "D" and "E" simultaneously.
10. Click on the File menu and go to File > Open and open the five folders named "A", "B", "C", "D" and "E" simultaneously.
11. Close the "E" folder window.
12. Close the "D" folder window.
13. Close the "C" folder window.
14. Close the "B" folder window.
15. Close the "A" folder window.
16. The right one-third of the "C" folder is still shaded in inside the parent "A" folder window.

**Expected behavior**
A folder should not be shaded in at all after opening and then closing multiple folders, including the affected folder itself.

**Screenshots**
 I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 40 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
As referenced in issue #612, please do not ban me for my long issue title for this issue. I am trying to be helpful. I find it extremely hard to shorten my long issue titles. Could you please shorten my long issue title for this issue for me after I post this issue?

**Comment by c0mmander8** [comment]
Instead of reading as "15. Close the "A" folder window.", step 15 should instead read as "15. Close the child "A" folder window."

**Comment by inexorabletash** [comment]
This is a known issue and too difficult to fix (i.e. would likely require a complete redo of MGTK).

MGTK doesn't support painting into irregular regions, so background windows can only be painted when partially revealed by a closing/moving window on top. So anything which causes a folder state to change in a background window can result in this. This is why selection in background windows is not supported in A2D, as it's much more obvious. The effect on shading is unfortunate, but relatively minor. Here's an easier repro:

1. Open a volume window A, containing folder B.
2. Open folder window B
3. Open a second volume window C.
4. Position window B so it does not obscure A.
5. Position window C so it partially overlaps the icon A.
6. Close window B
7. Close or move window C.

**Comment by c0mmander8** [comment]
Your easier reproduction of this bug does not work as written. First, for the sake of clarity, instead of reading as "4. Position window B so it does not obscure A.", step 4 in your easier reproduction of this bug should instead read as "4. Position window B so it does not obscure the folder icon of itself, folder icon B, in window A.". Second, to get to the main point of this comment, instead of reading as "5. Position window C so it partially overlaps the icon A.", step 5 in your easier reproduction of this bug should instead read as "5. Position window C so it partially overlaps the folder icon B in window A.". This way your easier reproduction of this bug actually works.

**Comment by c0mmander8** [comment]
Your easier reproduction of this bug should instead read as:


1. Open a first volume window A, containing a folder icon B.
2. Open the folder icon B to create a folder window B.
3. Open a second volume window C.
4. Position window B so it does not obscure the folder icon of itself, folder icon B, in window A.
5. Position window C so it partially overlaps the folder icon B in window A.
6. Close window B.
7. Close or move off of the folder icon B in window A, window C.
