### ISSUE TITLE
A mouse click does not currently dismiss the Matrix screen saver

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#618]
A mouse click does not currently dismiss the Matrix screen saver. A mouse click should dismiss the Matrix screen saver.

**Comment by inexorabletash** [comment]
MGTK is not active while this screen saver is running, so the mouse is not polled. Won't fix.

**Comment by c0mmander8** [comment]
Please reconsider your decision and please reopen this issue. Then, as referenced above, please implement that a mouse click should dismiss the Matrix screen saver as a feature request instead.
