### ISSUE TITLE
Launching an application program or quitting Apple II DeskTop on an unenhanced Apple IIe causes screen artifacts to appear on the screen for a second before going away

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#621]
**Describe the bug**
Launching an application program or quitting Apple II DeskTop on an unenhanced Apple IIe in AppleWin 1.30.7.0 causes screen artifacts, including the "Loading Apple II DeskTop" splash screen complete with the progress bar, to appear on the screen for a second before going away.

**To Reproduce**
1. Start Apple II DeskTop on an unenhanced Apple IIe in AppleWin 1.30.7.0.
2. Click on the File menu and go to File > Quit.
3. Screen artifacts, including the "Loading Apple II DeskTop" splash screen complete with the progress bar, appear on the screen for a second before going away.

**Expected behavior**
Launching an application program or quitting Apple II DeskTop on an unenhanced Apple IIe should not cause screen artifacts, including the "Loading Apple II DeskTop" splash screen complete with the progress bar, to appear on the screen at all.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Unenhanced Apple IIe
 - Emulator? [e.g. real hardware, or emulator name] AppleWin 1.30.7.0 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 40 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
This bug does not occur on an Enhanced Apple IIe in AppleWin 1.30.7.0 or on a ROM 01 Apple IIGS in GSplus 0.14.

**Comment by inexorabletash** [comment]
Interesting. I think I fixed this, but I'm not entirely sure I understand the root cause.

**Comment by c0mmander8** [comment]
I made an error in this reporting this issue. This issue actually takes place on an unenhanced Apple IIe in AppleWin 1.30.3.0, NOT on an unenhanced Apple IIe in AppleWin 1.30.7.0. I actually cannot get AppleWin 1.30.7.0 to open on my computer. When I try to open AppleWin 1.30.7.0 on my computer, I get a "Runtime Exception" alert dialog box with an error message stating "Card: wrong slot". I apologize sincerely for my error.

**Comment by c0mmander8** [comment]
This bug does occurs sporadically on an enhanced Apple IIe in AppleWin 1.30.3.0 or on a ROM 01 Apple IIGS in GSplus 0.14.

**Comment by c0mmander8** [comment]
"Additional context" should instead read as follows:


This bug does occurs sporadically on an enhanced Apple IIe in AppleWin 1.30.3.0 or on a ROM 01 Apple IIGS in GSplus 0.14.

**Comment by c0mmander8** [comment]
This issue is updated in issue #639.

**Comment by c0mmander8** [comment]
This issue continues to occur in Apple II DeskTop 1.2 Alpha 41. This issue is updated in issue #639.

**Comment by c0mmander8** [comment]
This issue was not fixed by commit 4af1b77.
