### ISSUE TITLE
After implementing issue #626, show Open Apple-Solid Apple-W or Solid Apple-Open Apple-W, whichever order of the Apple glyphs you prefer, next to "Close All" in the File menu as a keyboard shortcut for that item

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#627]
After implementing issue #626, show Open Apple-Solid Apple-W or Solid Apple-Open Apple-W, whichever order of the Apple glyphs you prefer, next to "Close All" in the File menu as a keyboard shortcut for that item.

**Comment by inexorabletash** [comment]
This isn't worth tracking as a separate issue. It can be handled as part of the implementation of #626 if that gets tackled. 

(As an aside, MGTK doesn't support double-modifiers in menu items, so ultimately this is likely to be Won't Fix, but it's too soon to say.)

**Comment by c0mmander8** [comment]
I know you said that "it's not worth it to add it" in issue #626, commit a31b727, but please reconsider your decision, please reopen this issue and please update MGTK to support double-modifiers and other multi-character shortcuts in menu items. Then, as referenced above, please show Open Apple-Solid Apple-W or Solid Apple-Open Apple-W, whichever order of the Apple glyphs you prefer, next to "Close All" in the File menu as a keyboard shortcut for that menu item. It is very handy to have a keyboard shortcut, when there is one, displayed next to a menu item. The implementation of issue #302, where the return glyph is now shown next to "Rename..." in the File menu as a keyboard shortcut for that menu item, was very handy in this regard.
