### ISSUE TITLE
Create a new icon type for forked files

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#632]
**Is your feature request related to a problem? Please describe.**
I am always frustrated that I cannot tell whether a file is a forked file that Apple II DeskTop cannot move or copy.

**Describe the solution you'd like**
If issue #288 is not implemented, create a new icon type for forked files so that you can tell whether a file is a forked file that Apple II DeskTop cannot move or copy.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
There is no other context or screenshots about this feature request here.

**Comment by c0mmander8** [comment]
Please create separate icon types for forked files and forked applications.

**Comment by c0mmander8** [comment]
Please create separate icon types for forked files and for forked applications, though.

**Comment by inexorabletash** [comment]
I investigated; this is possible - forked files simply have a different storage type. But the memory cost for multiple icons for this is too high. It would also require logic for changing how file records are structured, just for an edge case. If you're using GS/OS content regularly, I recommend just using the GS/OS Finder. I want DeskTop to be robust (so it shouldn't crash), but I don't want to expend energy or memory on niche usage.

(Most GS/OS-specific file types already have a special IIgs icon.)
