### ISSUE TITLE
The "Screen.Savers" folder is unable to be moved or copied into the "Control.Panels" folder

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#633]
**Describe the bug**
The "Screen.Savers" folder is unable to be moved or copied into the "Control.Panels" folder.

**To Reproduce**
1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha40-en_800k.2mg" disk image.
2. Double click and open the "A2.Desktop" volume.
3. Double-click and open the "Desk.Acc" folder.
4. Drag the "Screen.Savers" folder into the "Control.Panels" folder.
5. The "Move..." dialog box appears and the move starts.
6. An error message dialog box appears stating, "The syntax of the pathname is invalid.".
7. Click OK.
8. The move is cancelled.

**Expected behavior**
The "Screen.Savers" folder should be able to be moved or copied into the "Control.Panels" folder.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 40 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
The "Control.Panels" folder is able to be moved or copied into the "Screen.Savers" folder.

**Comment by inexorabletash** [comment]
The path `"/A2.DeskTop/Desk.Acc/Control.Panels/Screen.Savers/Flying.Toasters"` is too long for ProDOS to handle, hence the path is invalid.

**Comment by inexorabletash** [comment]
I improved the error message to indicate the path may be too long.
