### ISSUE TITLE
Apple II DeskTop allows the user to replace a folder with an item it contains in the File > Copy a File... dialog box

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#635]
**Describe the bug**
Apple II DeskTop allows the user to replace a folder with an item it contains in the File > Copy a File... dialog box.

**To Reproduce**
1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha40-en_800k.2mg" disk image.
2. Double-click and open the "A2.Desktop" volume.
3. Double-click and open the "Desk.Acc" folder.
4. Rename the "Calculator" desk accessory file to "Desk.Acc".
5. Close the "Desk.Acc" window.
6. Close the "A2.Desktop" window.
7. Click on the File menu and go to File > Copy a File....
8. Select the "Desk.Acc" folder.
9. Click Open.
10. Select the "Desk.Acc" desk accessory file.
11. Click OK.
12. Click OK again without doing anything else.
13. A "Copy..." dialog box appears stating, "That file already exists. Do you want to write over it?".
14. Click Yes.
15. An error message alert dialog box appears stating, "The file is locked."
16. Click OK.
17. Double-click and open the "A2.Desktop" volume.
18. The "Desk.Acc" folder has been replaced with the "Desk.Acc" desk accesory file.
19. Double-click and attempt to open the "Desk.Acc" desk accessory file.
20. Apple II DeskTop freezes.

**Expected behavior**
Apple II DeskTop should not allow the user to replace a folder with an item it contains in the File > Copy a File... dialog box and Apple II DeskTop should instead give an error message. The File > Copy a File... dialog box should not be dismissed so that the user can either choose another filename for the item, choose another location to copy the item or choose a different item to copy.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 40 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment]
"Expected behavior" should instead read as follows:


The "That name already exists. Please use another name." error message alert dialog box should appear instead when the user attempts to replace a file or folder with itself in the File > Copy a File... dialog box. The File > Copy a File... dialog box should not be dismissed so that the user can either choose another filename for the file or folder, choose another location to copy the file or folder or choose a different file or folder to copy.

**Comment by c0mmander8** [comment]
Please delete my previous comment and please delete this comment, too.

**Comment by c0mmander8** [comment]
"Expected behavior" should instead read as follows:


The "That name already exists. Please use another name." error message alert dialog box should appear instead when the user attempts to replace a folder with an item it contains in the File > Copy a File... dialog box. The File > Copy a File... dialog box should not be dismissed so that the user can either choose another filename for the item, choose another location to copy the item or choose a different item to copy.

**Comment by inexorabletash** [comment]
Fixed by f4254f7

**Comment by c0mmander8** [comment]
Please reopen this issue. This issue was not fixed by commit f4254f7. This issue still occurs in Apple II DeskTop 1.2 Alpha 41.

**Comment by c0mmander8** [comment]
"Expected behavior" should instead read as follows:

The new "An item cannot be replaced by itself or an item it contains." error message alert dialog box should appear instead when the user attempts to replace a folder with an item it contains in the File > Copy a File... dialog box. The File > Copy a File... dialog box should not be dismissed so that the user can either choose another filename for the item, choose another location to copy the item or choose a different item to copy.

**Comment by inexorabletash** [comment]
Thanks for verifying that the fix regressed.

But please try to restrain yourself from commenting repeatedly on issues. I've told you many times before, it's detrimental rather than helpful.

**Comment by c0mmander8** [comment]
This issue is updated in issue #643.
