### ISSUE TITLE
Apple II DeskTop allows the user to replace a folder with an item it contains by dropping the item into the parent window or onto the parent volume icon

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#636]
**Describe the bug**
Apple II DeskTop allows the user to replace a folder with an item it contains by dropping the item into the parent window or onto the parent volume icon, unlike the Mac and the IIGS.

**To Reproduce**
1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha40-en_800k.2mg" disk image.
2. Double-click and open the "A2.Desktop" volume.
3. Double-click and open the "Desk.Acc" folder.
4. Rename the "Calculator" desk accessory file to "Desk.Acc".
5. Drag the "Desk.Acc" desk accessory file into the "A2.Desktop" window or onto the "A2.Desktop" volume icon on the desktop.
6. A "Move..." dialog box appears stating, "That file already exists. Do you want to write over it?".
7. Click Yes.
8. An error message alert dialog box appears stating, "The file is locked.".
9. Click OK.
10. Close the "Desk.Acc" window.
11. Close the "A2.Desktop" window.
12. Double-click and open the "A2.Desktop" volume.
13. The "Desk.Acc" folder has been replaced with the "Desk.Acc" desk accesory file.
14. Double-click and attempt to open the "Desk.Acc" desk accessory file.
15. Apple II DeskTop freezes.

**Expected behavior**
Apple II DeskTop should not allow the user to replace a folder with an item it contains by dropping the item into the parent window or onto the parent volume icon and Apple II DeskTop should instead give an error message instead, just like the Mac and the IIGS.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 40 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment]
The title of this issue and "Describe the bug" should instead read as follows:


Apple II DeskTop allows the user to replace a folder with an item it contains by dropping the item into the parent window or, if the folder is located in the root directory of the volume, onto the parent volume icon, unlike the Mac and the IIGS.


"Expected behavior" should instead read as follows:


Apple II DeskTop should not allow the user to replace a folder with an item it contains by dropping the item into the parent window or, if the folder is located in the root directory of the volume, onto the parent volume icon and Apple II DeskTop should instead give an error message instead, just like the Mac and the IIGS.

**Comment by inexorabletash** [comment]
Fixed by f4254f7
