### ISSUE TITLE
Mouse Keys do not work in Apple II DeskTop 1.2 Alpha 41, both on an unenhanced Apple IIe and on an enhanced Apple IIe, in AppleWin 1.30.3.0

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#640]
Mouse Keys do not work in Apple II DeskTop 1.2 Alpha 41, both on an unenhanced Apple IIe and on an enhanced Apple IIe, in AppleWin 1.30.3.0. Mouse Keys work perfectly fine in Apple II DeskTop 1.2 Alpha 41 on a ROM 01 Apple IIGS in GSplus 0.14. Yes, I do know that the Apple II modifier keys are different in AppleWin 1.30.3.0 and GSplus 0.14.

**Comment by inexorabletash** [comment]
Works fine for me in 1.30.7.0. Try using the Joystick control panel to make sure you are correctly triggering button 0 and 1 (OA and SA).
