### ISSUE TITLE
Double modifiers, such as Open Apple-Solid Apple-O and Open Apple-Solid Apple-W, do not work in Apple II DeskTop 1.2 Alpha 41 on a ROM 01 Apple IIGS in GSplus 0.14

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#641]
Double modifiers, such as Open Apple-Solid Apple-O and Open Apple-Solid Apple-W, do not work in Apple II DeskTop 1.2 Alpha 41 on a ROM 01 Apple IIGS in GSplus 0.14. Double modifiers, such as Open Apple-Solid Apple-O and Open Apple-Solid Apple-W, work perfectly fine in Apple II DeskTop 1.2 Alpha 41, both on an unenhanced Apple IIe and on an enhanced Apple IIe, in AppleWin 1.30.3.0. Yes, I do know that the Apple II modifier keys are different in GSplus 0.14 and AppleWin 1.30.3.0.

**Comment by inexorabletash** [comment]
I can repro in GSplus 0.14 on Windows. Looks like an issue with that emulator, though - double-command keys may be getting used to control the emulator. MAME does something similar.

I'll verify on real hardware.

**Comment by inexorabletash** [comment]
It's fine on a real ROM 01 Apple IIgs, so likely an emulator issue.
