### ISSUE TITLE
The new "An item cannot be replaced by itself or an item it contains." error message alert dialog box should appear instead and stop you from proceeding further when you attempt to replace an item with itself or an item it contains in the File > Copy a File... dialog box

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#643]
**Describe the bug**
The "That name already exists. Please use another name." error message alert dialog box appears when you attempt to replace an item with itself and nothing stops you from replacing an item with an item it contains in the File > Copy a File... dialog box.

**To Reproduce**
1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha41-en_800k.2mg" disk image.
2. Click on the File menu and go to File > Copy a File....
3. Click and select the "Basic.System" application program file in the root directory of the "A2.Desktop" volume.
4. Click OK.
5. Click OK again without doing anything else.
6. An error message alert dialog box appears stating, "That name already exists. Please use another name.".
7. The new error message alert dialog box stating "An item cannot be replaced by itself or an item it contains." should appear instead in step 6.
8. Click OK.
9. Click Cancel.
10. Click Cancel again and exit the File > Copy a File... dialog box.
11. Click on the File menu and go to File > Copy a File....
12. Click and select the "Desk.Acc" folder in the root directory of the "A2.Desktop" volume.
13. Click Open.
14. Click and select the "Calculator" desk accessory file in the "Desk.Acc" folder of the "A2.Desktop" volume.
15. Click OK.
16. The "Destination filename:" text field should read "/A2.Desktop/Desk.Acc/".
17. Click OK.
18. The new error message alert dialog box stating "An item cannot be replaced by itself or an item it contains." should appear instead after step 17.
19. A "Copy..." dialog box appears stating, "That file already exists. Do you want to write over it?".
20. Click Yes.
21. An error message alert dialog box appears stating, "The file is locked."
22. Click OK.
23. Double-click and open the "A2.Desktop" volume.
24. The "Desk.Acc" folder has been replaced with the "Desk.Acc" desk accessory file.
25. Double-click and attempt to open the "Desk.Acc" desk accessory file.
26. Apple II DeskTop freezes.

**Expected behavior**
The new "An item cannot be replaced by itself or an item it contains." error message alert dialog box should appear instead and stop you from proceeding further when you attempt to replace an item with itself or an item it contains in the File > Copy a File... dialog box.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 41 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment]
This issue is an update of issue #635.

**Comment by inexorabletash** [comment]
I'm not sure the new message is better, but ¯\_(ツ)_/¯. 

I think before step 16 you're missing a "Click on Desk.Acc in the list" step

**Comment by c0mmander8** [comment]
Before step 16, I am not missing a "Click on Desk.Acc in the list" step. I instead manually renamed the "Destination filename:" text field to read "/A2.Desktop/Desk.Acc/" in step 16.

**Comment by inexorabletash** [comment]
Thanks for clarifying. In the future, I would phrase that as "Edit the destination filename to be..." instead.

In this case, the error shown is "The pathname is too long or not valid." which is accurate and has not changed. A valid pathname can't end in `/` which is why that error is shown.

**Comment by c0mmander8** [comment]
What about when the "Destination filename:" text field is instead manually renamed to read "/A2.Desktop/Desk.Acc", without the ending slash (/), in step 16? The ending slash (/) in step 16 was a typographical error on my part while originally typing up this bug report. I later copied-and-pasted that ending slash (/) typographical error from step 16 into my previous comment on February 1, 2022. As mentioned in step 18, does the new error message alert dialog box stating "An item cannot be replaced by itself or an item it contains." now appear after step 17 in the latest build of Apple II DeskTop 1.2? As mentioned in step 18, the new error message alert dialog box stating "An item cannot be replaced by itself or an item it contains." does not appear after step 17 in Apple II DeskTop 1.2 Alpha 41.

**Comment by inexorabletash** [comment]
Without the ending slash, you do get the "An item cannot be replaced by itself or an item it contains." error now. I just wanted to be very clear.

**Comment by inexorabletash** [comment]
Thanks for verifying!
