### ISSUE TITLE
Run Basic Here does not work while booted from a RAMCard

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#645]
**Describe the bug**
Run Basic Here does not work while booted from a RAMCard.

**To Reproduce**
1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha41-en_800k.2mg" disk image, with an Apple IIGS Control Panel RAM5 RAM disk enabled in the Apple IIGS Control Panel.
2. Double-click and open the "A2.Desktop" volume icon.
3. Click on the Apple menu and select "Run Basic Here".
4. An error message alert dialog box appears stating, "BASIC.SYSTEM not found.".
5. Click OK.
6. Drag the "Basic.System" application program file from the "A2.Desktop" volume window to the "Ram5" volume icon in order to copy it there.
7. Double-click and open the "Ram5" volume icon.
8. Click on the Apple menu and select "Run Basic Here".
9. An error message alert dialog box appears stating, "BASIC.SYSTEM not found.".
10. Click OK.
11. Drag the "Basic.System" application program file you copied over in step 5 from the "Ram5" volume window to the "Desktop" folder icon located in the "Ram5" volume window in order to move it there.
12. Double-click and open the "Desktop" folder icon located in the "Ram5" volume window.
13. Click on the Apple menu and select "Run Basic Here".
14. An error message alert dialog box appears stating, "BASIC.SYSTEM not found.".

**Expected behavior**
Run Basic Here should work while booted from a RAMCard.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 41 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
 There is no other context about the problem here.

**Comment by c0mmander8** [comment]
"1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha41-en_800k.2mg" disk image, with an Apple IIGS Control Panel RAM5 RAM disk enabled in the Apple IIGS Control Panel." should instead be 
"1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha41-en_800k.2mg" disk image, while running Apple II DeskTop from an Apple IIGS Control Panel RAM5 RAM disk enabled in the Apple IIGS Control Panel."

**Comment by c0mmander8** [comment]
**Describe the bug**
Run Basic Here does not work while running Apple II DeskTop from a RAMCard.

**To Reproduce**
Steps to reproduce the behavior:
1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha41-en_800k.2mg" disk image, while running Apple II DeskTop from an Apple IIGS Control Panel RAM5 RAM disk enabled in the Apple IIGS Control Panel.
2. Double-click and open the "A2.Desktop" volume icon.
3. Click on the Apple menu and select "Run Basic Here".
4. An error message alert dialog box appears stating, "BASIC.SYSTEM not found.".
5. Click OK.
6. Drag the "Basic.System" application program file from the "A2.Desktop" volume window to the "Ram5" volume icon in order to copy it there.
7. Double-click and open the "Ram5" volume icon.
8. Click on the Apple menu and select "Run Basic Here".
9. An error message alert dialog box appears stating, "BASIC.SYSTEM not found.".
10. Click OK.
11. Drag the "Basic.System" application program file you copied over in step 5 from the "Ram5" volume window to the "Desktop" folder icon located in the "Ram5" volume window in order to move it there.
12. Double-click and open the "Desktop" folder icon located in the "Ram5" volume window.
13. Click on the Apple menu and select "Run Basic Here".
14. An error message alert dialog box appears stating, "BASIC.SYSTEM not found.".

**Expected behavior**
Run Basic Here should work while running Apple II DeskTop from a RAMCard.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 41 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
This bug does not occur while not running Apple II DeskTop from a RAMCard.

**Comment by inexorabletash** [comment]
Can you please explain why you are unable to edit your issues?

**Comment by c0mmander8** [comment]
As referenced in issue #291, I am unable to edit the titles of my issues / pull requests, edit my issues / pull requests / comments themselves, delete my comments, commit changes to my fork of this repository or create a new pull request because the computer I use to do all my work is running Windows Vista and the latest web browsers available for Windows Vista are extremely outdated, many years old, versions of Mozilla Firefox and Google Chrome. When I first started contributing, just over a year and a half ago, the web browsers available for Windows Vista were not as extremely outdated as they are today and I was able to, for only just a few months, edit the titles of my issues / pull requests, edit my issues / pull requests / comments themselves, delete my comments, commit changes to my fork of this repository or create a new pull request before that functionality was broken.

**Comment by inexorabletash** [comment]
That's unfortunate. I needed a low-end Windows machine for development recently, and was able to purchase a "mini-PC" from Amazon that shipped with Windows 10 for under USD$150. It isn't good for games, but is perfectly adequate for light computing needs. I realize that may not be affordable for everyone, but if you started a Gofundme (etc) I would contribute to allow you to be more effective.

**Comment by inexorabletash** [comment]
Someone suggested trying out https://portableapps.com/news/2022-01-27--firefox-portable-96.0.3-released which might work on your machine.
