### ISSUE TITLE
No keyboard shortcuts at all work while in Mouse Keys mode throughout Apple II DeskTop, Disk Copy, the Selector and the desk accessories

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#647]
**Describe the bug**
No keyboard shortcuts at all work while in Mouse Keys mode throughout Apple II DeskTop, Disk Copy, the Selector and the desk accessories.

**To Reproduce**
1. Start Apple II DeskTop.
2. Press Open Apple-Solid Apple-Space to enter Mouse Keys mode.
3. While in Mouse Keys mode, find and click and select an icon by using the Arrow keys and the Solid Apple key.
4. While in Mouse Keys mode, nothing happens when you attempt to open the icon selected in step 3 by pressing Open Apple-O.
5. Press Esc to exit Mouse Keys mode.
6. The icon selected in step 3 now opens by pressing Open Apple-O.

**Expected behavior**
Keyboard shortcuts that do not interfere with the operation of Mouse Keys mode should work while in Mouse Keys mode throughout Apple II DeskTop, Disk Copy, the Selector and the desk accessories. Keyboard shortcuts that do interfere with the operation of Mouse Keys mode should still not work while in Mouse Keys mode throughout Apple II DeskTop, Disk Copy, the Selector and the desk accessories.

**Screenshots**
 I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 41 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
Keyboard shortcuts that do not interfere with the operation of Mouse Keys mode should work while in Mouse Keys mode throughout Apple II DeskTop, Disk Copy, the Selector and the desk accessories. Keyboard shortcuts that do interfere with the operation of Mouse Keys mode should still not work while in Mouse Keys mode throughout Apple II DeskTop, Disk Copy, the Selector and the desk accessories.

**Comment by inexorabletash** [comment]
Yes, this is correct. Exit MouseKeys mode to use shortcuts.

I'll update the docs to make that clearer.

**Comment by c0mmander8** [comment]
This issue is updated as a feature request in issue #648.

**Comment by c0mmander8** [comment]
"To exit Mouse Keys mode, press **Space**. A confirmation sound will play." under the subheading "**Mouse Keys**" under the heading "**Keyboard Control**" in the Apple II DeskTop "**Docs**" at https://www.a2desktop.com/docs#h.p_fthAmDxtEOQ9 should instead be 
"To exit Mouse Keys mode, press **Esc**. A confirmation sound will play.", with the word "**Esc**" replacing the word "**Space**".

**Comment by c0mmander8** [comment]
"ℹ️ NOTE: Keyboard shortcuts (e.g. **△-O**) do not work while in MouseKeys mode." under the subheading "**Mouse Keys**" under the heading "**Keyboard Control**" in the Apple II DeskTop "**Docs**" at https://www.a2desktop.com/docs#h.p_fthAmDxtEOQ9 should instead be 
"ℹ️ NOTE: Keyboard shortcuts (e.g. **△-O**) do not work while in Mouse Keys mode.", with the words "Mouse Keys", with a space between "Mouse" and "Keys", replacing the word "MouseKeys", with no space between "Mouse" and "Keys", for greater consistency in the Apple II DeskTop "**Docs**" at https://www.a2desktop.com/docs#h.p_fthAmDxtEOQ9.
