### ISSUE TITLE
Keyboard shortcuts that do not interfere with the operation of Mouse Keys mode should work while in Mouse Keys mode throughout Apple II DeskTop, Disk Copy, the Selector and the desk accessories

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#648]
**Is your feature request related to a problem? Please describe.**
As referenced in issue #647, I am frustrated that no keyboard shortcuts at all work while in Mouse Keys mode throughout Apple II DeskTop, Disk Copy, the Selector and the desk accessories.

**Describe the solution you'd like**
As referenced in issue #647, keyboard shortcuts that do not interfere with the operation of Mouse Keys mode should work while in Mouse Keys mode throughout Apple II DeskTop, Disk Copy, the Selector and the desk accessories. As referenced in issue #647, keyboard shortcuts that do interfere with the operation of Mouse Keys mode should still not work while in Mouse Keys mode throughout Apple II DeskTop, Disk Copy, the Selector and the desk accessories.

**Describe alternatives you've considered**
Just keep on exiting and then reentering Mouse Keys mode in order to just use keyboard shortcuts.

**Additional context**
As referenced in issue #647, keyboard shortcuts that do not interfere with the operation of Mouse Keys mode should work while in Mouse Keys mode throughout Apple II DeskTop, Disk Copy, the Selector and the desk accessories. As referenced in issue #647, keyboard shortcuts that do interfere with the operation of Mouse Keys mode should still not work while in Mouse Keys mode throughout Apple II DeskTop, Disk Copy, the Selector and the desk accessories.

**Comment by c0mmander8** [comment]
This issue is an update of issue #647 as a feature request.

**Comment by c0mmander8** [comment]
"To exit Mouse Keys mode, press **Space**. A confirmation sound will play." under the subheading "**Mouse Keys**" under the heading "**Keyboard Control**" in the Apple II DeskTop "**Docs**" at https://www.a2desktop.com/docs#h.p_fthAmDxtEOQ9 should instead be 
"To exit Mouse Keys mode, press **Esc**. A confirmation sound will play.", with the word "**Esc**" replacing the word "**Space**".

**Comment by c0mmander8** [comment]
"ℹ️ NOTE: Keyboard shortcuts (e.g. **△-O**) do not work while in MouseKeys mode." under the subheading "**Mouse Keys**" under the heading "**Keyboard Control**" in the Apple II DeskTop "**Docs**" at https://www.a2desktop.com/docs#h.p_fthAmDxtEOQ9 should instead be 
"ℹ️ NOTE: Keyboard shortcuts (e.g. **△-O**) do not work while in Mouse Keys mode.", with the words "Mouse Keys", with a space between "Mouse" and "Keys", replacing the word "MouseKeys", with no space between "Mouse" and "Keys", for greater consistency in the Apple II DeskTop "**Docs**" at https://www.a2desktop.com/docs#h.p_fthAmDxtEOQ9.

**Comment by inexorabletash** [comment]
Not interested. Mouse Keys is already niche functionality, it's not worth the risk or code size to improve it further. Using shortcuts, nearly everything can be done without Mouse Keys anyway.
