### ISSUE TITLE
An error message loop appears when Run.Basic.Here or Basic.System is opened when Control.Panels is the active window

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#649]
**Describe the bug**
An error message loop appears when Run.Basic.Here or Basic.System is opened when Control.Panels is the active window.

**To Reproduce**
1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha41-en_800k.2mg" disk image, while not running Apple II DeskTop from a RAMCard.
2. Click on the Apple menu and select "Control Panels".
3. Click on the Apple menu and select "Run Basic Here".
4. An error message appears stating, "FILE TYPE MISMATCH".
5. An error message appears stating, "SYNTAX ERROR".
6. An error message appears stating, "PATH NOT FOUND".
7. Step 5 and step 6 keep repeating in a loop.
8. An error message appears stating, "SYNTAX ERROR".
9. An error message appears stating, "?SYNTAX ERROR".
10. Step 4 - step 9 do not occur if "Screen Savers" is selected in step 2 instead of "Control Panels".

**Expected behavior**
An error message loop should not appear when Run.Basic.Here or Basic.System is opened when Control.Panels is the active window.

**Screenshots**
 I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 41 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
An error message loop does not appear when Run.Basic.Here or Basic.System is opened when Desk.Acc or Screen.Savers is the active window instead of Control.Panels.

**Comment by inexorabletash** [comment]
Hah, this is because BASIC.SYSTEM tries to `RUN` the control panel `STARTUP`... which is obviously not a BASIC file, so things go off the rails.

Two possible fixes:
* Treat `STARTUP` as a reserved name, and rename the `STARTUP` DA to ....?
* Change the RBH DA to blank out the starting filename buffer at $2006, but then a BASIC `STARTUP` file would not be run.
