### ISSUE TITLE
Add option to allow making the startup RAMCard not the default volume

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#658]
**Is your feature request related to a problem? Please describe.**
I am having serious second thoughts about startup RAMCards and startup RAM disks being the default volume, as referenced in issue #468 and just implemented in issue #468, commit f3dba83. RAMCards and RAM disks are not persistent forms of storage. Therefore, though the user can add or enable an application program shortcut, a file shortcut or a folder shortcut to "Copy to RAMCard:" "at boot" or "at first use", the user is most likely want to open or manipulate an application program, a file or a folder from the actual startup disk itself, not from the startup RAMCard or the startup RAM disk Apple II DeskTop is copied into. Although if the user does take advantage of the "Copy to RAMCard:" feature, especially the "Copy to RAMCard:" "at boot" option, the new startup RAMCard and startup RAM disk behavior you just implemented in issue #468, commit f3dba83 can be a godsend.

**Describe the solution you'd like**
Add a suboption to the Startup Options control panel under the "Copy to RAMCard (if present)" option, just like how suboptions are implemented in the Classic Mac OS, to "Make startup RAMCard the default volume". When this proposed new suboption is enabled, the startup RAMCard or the startup RAM disk Apple II DeskTop is copied into, if a startup RAMCard or a startup RAM disk exists, is the default volume in the upper right corner of the Apple II DeskTop app desktop, in the File > Copy a File..., File > Delete a File... and Shortcuts > Add a Shortcut... file picker dialog boxes in the Apple II DeskTop app, in Disk Copy, and in the File > Run a Program... file picker dialog box in the Selector app. When this proposed new suboption is disabled or a startup RAMCard or a startup RAM disk does not exist, the actual startup disk itself, not the startup RAMCard or the startup RAM disk Apple II DeskTop is copied into, is the default volume in the upper right corner of the Apple II DeskTop app desktop, in the File > Copy a File..., File > Delete a File... and Shortcuts > Add a Shortcut... file picker dialog boxes in the Apple II DeskTop app, in Disk Copy, and in the File > Run a Program... file picker dialog box in the Selector app. This issue and issue #468 do not apply to the Special > Format a Disk... and Special > Erase a Disk... dialog boxes in the Apple II DeskTop app and the Shortcuts > Edit a Shortcut... file picker dialog box in the Apple II DeskTop app.

**Describe alternatives you've considered**
There are no alternative solutions or features that I can think of for this scenario.

**Additional context**
This issue and issue #468 do not apply to the Special > Format a Disk... and Special > Erase a Disk... dialog boxes in the Apple II DeskTop app and the Shortcuts > Edit a Shortcut... file picker dialog box in the Apple II DeskTop app.

**Comment by c0mmander8** [comment]
This issue is an update of issue #468.

**Comment by inexorabletash** [comment]
Please don't leave comments like that. If you are viewing this page in a web browser, you'll see that GitHub automatically creates links between issues when mentioned. If you add them manually, it generates email and notifications, which are annoying.

**Comment by inexorabletash** [comment]
Thank you for thinking through the poor usability of leaving the RAMCard volume first in the list. Rather than an option, I just made this happen unconditionally.

Change is in ff2d615dbae77df8d8b7a5ec95a2ca2c08366adf
