### ISSUE TITLE
The "Clock" "12hr" / "24hr" setting in the Control Panel control panel should instead be "Time" "12hr" / "24hr" because this setting also controls how time is displayed in File > Get Info and in list views

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#659]
The "Clock" "12hr" / "24hr" setting in the Control Panel control panel should instead be "Time" "12hr" / "24hr" because this setting also controls how time is displayed in File > Get Info and in list views. In fact, this is all this setting does in systems without a real-time clock.

**Comment by inexorabletash** [comment]
While your observation is true that this applies to all time formats, not just the real-time clock, in English the common phrase is "12-hour clock" or "24-hour clock". You can think of this setting as "which form of clock do you normally use?"

So I'm going to leave this alone for now.

I am likely to move this setting into the Date and Time DA when #596 is tackled, at which point the label can be removed entirely.
