### ISSUE TITLE
Apple II DeskTop should also have a prompt to save changes if the write fails in the Shortcuts > Add a Shortcut..., Shortcuts > Edit a Shortcut... and Shortcuts > Delete a Shortcut... dialog boxes, even if not running from RAMCard

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#665]
In commit 5292168, you added a prompt to save changes if the write fails in the Control Panel, Date And Time and Startup Options control panels, even if not running from RAMCard. Apple II DeskTop should also have a prompt to save changes if the write fails in the Shortcuts > Add a Shortcut..., Shortcuts > Edit a Shortcut... and Shortcuts > Delete a Shortcut... dialog boxes, even if not running from RAMCard. This issue is for greater user interface consistency throughout the Apple II DeskTop app and the desk accessories.

**Comment by inexorabletash** [comment]
This is already the case. Please make sure to test before filing bugs.
