### ISSUE TITLE
The changes you made in issue #468, commit f3dba83 and issue #658, commit ff2d615 should also be applied to the device order seen in the file picker dialog boxes in the Apple II DeskTop app and the Special > Format a Disk... and Special > Erase a Disk... dialog boxes in the Apple II DeskTop app

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#667]
The changes you made in issue #468, commit f3dba83 and issue #658, commit ff2d615 should also be applied to the device order seen in the file picker dialog boxes in the Apple II DeskTop app and the Special > Format a Disk... and Special > Erase a Disk... dialog boxes in the Apple II DeskTop app. This issue is for greater user interface consistency throughout the Apple II DeskTop app, Disk Copy and the Selector app.

**Comment by inexorabletash** [comment]
This is already the case.
