### ISSUE TITLE
Please reenable the use of control characters in the "Enter the name (14 characters max.):" shortcut name field in Shortcuts > Add a Shortcut... and in Shortcuts > Edit a Shortcut...

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#668]
As referenced in commit 12493fb, users of the Apple II DeskTop app and the Selector app should be able to continue to use control characters to embellish their shortcut names. It is not nice to take away features that already exist for no good reason. Please reenable the use of control characters in the "Enter the name (14 characters max.):" shortcut name field in Shortcuts > Add a Shortcut... and in Shortcuts > Edit a Shortcut.... Also, as a consequence, please delete the following lines of text in a2d/res/notes/testplan.md:

1. Please delete "* In each field, type a control character that is not an alias for an arrow/Tab/Return/Escape, e.g. Control+D. Verify that it is ignored.".
2. Please delete "* In the Shortcuts > Add/Edit a Shortcut... name field, type a non-path, non-control character. Verify that it is accepted.".

**Comment by inexorabletash** [comment]
The glyphs used for control characters are not guaranteed to be stable, and so must not be relied on by users.
