### ISSUE TITLE
In accordance with issue #491, after implementing issue #669, all of the archive types supported by AUTO UnShrinkIt, which are listed in issue #669, should be able to be added to the Apple menu for opening and extracting

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#670]
In accordance with issue #491, after implementing issue #669, all of the archive types supported by AUTO UnShrinkIt, which are listed in issue #669, should be able to be added to the Apple menu for opening and extracting. This issue does sound a bit silly but this issue is for greater user interface consistency in the Apple II DeskTop app in that any file, application program or folder the Apple II DeskTop app can open can also be placed in the Apple menu.

**Comment by inexorabletash** [comment]
This is already supported for types identified as archives. No additional work is needed.
