### ISSUE TITLE
Add an entry to a2d/docs/Building_And_Running.md relating to "DISK.COPY"

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#676]
Add an entry to a2d/docs/Building_And_Running.md, under the heading "Install Instructions", relating to "DISK.COPY".

**Comment by inexorabletash** [comment]
Creating issues like this for documentation nitpicks is extremely disruptive. I'm receiving complaints from other contributors that this is very annoying.

I've created https://github.com/a2stuff/a2d/issues/681 as a single issue to contain feedback on documentation. Please do not file new issues, and instead leave comments on that issue.

**Comment by inexorabletash** [comment]
This was done in d7af32b441d00340e9e93ad7709ac00158e9614a
