### ISSUE TITLE
Add two entries to the read me located at a2d/res/README.txt relating to "DISK.COPY" and "UNSHRINK"

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#677]
Add two entries to the read me located at a2d/res/README.txt, under the heading "Apple II DeskTop", under the subheading "Installation", relating to "DISK.COPY" and "UNSHRINK".

**Comment by inexorabletash** [comment]
Creating issues like this for documentation nitpicks is extremely disruptive. I'm receiving complaints from other contributors that this is very annoying.

I've created https://github.com/a2stuff/a2d/issues/681 as a single issue to contain feedback on documentation. Please do not file new issues, and instead leave comments on that issue.

**Comment by inexorabletash** [comment]
DISK.COPY added since it's required, UNSHRINK is just one of several "extras" and the list is not comprehensive, e.g. not all DAs are listed.

**Comment by inexorabletash** [comment]
d7af32b441d00340e9e93ad7709ac00158e9614a
