### ISSUE TITLE
Apple II DeskTop "History" located at https://www.a2desktop.com/history updates

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#678]
In the Apple II DeskTop "History" located at https://www.a2desktop.com/history, under the heading "2018", 
"New DAs: Eyes, This Apple, Screen Dump, Run Basic Here, Key Caps" should instead be 
"New DAs: Eyes, This Apple, Screen Dump, Run Basic Here, Key Caps.", with a period (.) at the end of the sentence for consistency with the other Apple II DeskTop "History" timeline entries.

In the Apple II DeskTop "History" located at https://www.a2desktop.com/history, under the heading "2020", 
"New DAs: System Speed, Joystick Calibration, Find Files, Melt, Invert." should instead be 
"New DAs: System Speed, Joystick, Find Files, Melt, Invert.", with the word "Joystick" replacing the words "Joystick Calibration", because the name of Joystick control panel is simply just "Joystick" without the word "Calibration" included in its name.

In the Apple II DeskTop "History" located at https://www.a2desktop.com/history, under the heading "2021", 
"New DAs: Startup, Show Duet File, Matrix" should instead be 
"New DAs: Startup Options, Show Duet File, Matrix.", with the words "Startup Options" replacing the word "Startup", because the name of the Startup Options control panel is now "Startup Options" and no longer simply just "Startup" without the word "Options" included in its name, and with a period (.) at the end of the sentence for consistency with the other Apple II DeskTop "History" timeline entries.

**Comment by inexorabletash** [comment]
Creating issues like this for documentation nitpicks is extremely disruptive. I'm receiving complaints from other contributors that this is very annoying.

I've created https://github.com/a2stuff/a2d/issues/681 as a single issue to contain feedback on documentation. Please do not file new issues, and instead leave comments on that issue.

**Comment by inexorabletash** [comment]
Leaving "Joystick Calibration" because the DA's name is the full phrase, and "Joystick" doesn't explain the purpose. There's just not enough space in the filename to say the whole thing.
