### ISSUE TITLE
In the Apple II DeskTop documentation, "Click the Proportional button in the top right to toggle to Fixed mode, or vice versa." should instead be "Tap the spacebar or click the Proportional button in the top right to toggle to Fixed mode, or vice versa." or "Click the Proportional button in the top right or tap the spacebar to toggle to Fixed mode, or vice versa."

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#679]
In the Apple II DeskTop documentation, under the heading "Working With Files", located at https://www.a2desktop.com/docs#h.p_d6jyIELgS1YY, under the subheading "Text — TXT", 
"Click the Proportional button in the top right to toggle to Fixed mode, or vice versa." should instead be 
"Tap the spacebar or click the Proportional button in the top right to toggle to Fixed mode, or vice versa." or 
"Click the Proportional button in the top right or tap the spacebar to toggle to Fixed mode, or vice versa.".

**Comment by inexorabletash** [comment]
Creating issues like this for documentation nitpicks is extremely disruptive. I'm receiving complaints from other contributors that this is very annoying.

I've created https://github.com/a2stuff/a2d/issues/681 as a single issue to contain feedback on documentation. Please do not file new issues, and instead leave comments on that issue.
