### ISSUE TITLE
The Open Apple-Solid Apple-Down Arrow and Open Apple-Solid Apple-Up Arrow keyboard shortcuts do not work in Apple II DeskTop 1.2 Alpha 43

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#683]
**Describe the bug**

The Open Apple-Solid Apple-Down Arrow and Open Apple-Solid Apple-Up Arrow keyboard shortcuts do not work in Apple II DeskTop 1.2 Alpha 43, even though the Open Apple-Solid Apple-O and Open Apple-Solid Apple-W keyboard shortcuts do work in Apple II DeskTop 1.2 Alpha 43.

**To Reproduce**
1. Start Apple II DeskTop.
2. Double-click a volume icon and open its volume window.
3. Select a folder icon located in the volume window opened in step 2.
4. Press Open Apple-Solid Apple-Down Arrow.
5. Nothing happens at all.
6. Press Open Apple-Solid Apple-O.
7. The folder icon opens its folder window and then the volume window opened in step 2 closes.
8. Press Open Apple-Solid Apple-Up Arrow.
9. Nothing happens at all.
10. Double-click the volume icon mentioned in step 2 and reopen its volume window.
11. Press Open Apple-Solid Apple-W.
12. All open windows close.

**Expected behavior**
The Open Apple-Solid Apple-Down Arrow and Open Apple-Solid Apple-Up Arrow keyboard shortcuts should work in Apple II DeskTop 1.2, just like the Open Apple-Solid Apple-O and Open Apple-Solid Apple-W keyboard shortcuts do work in Apple II DeskTop 1.2.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Both an Unenhanced Apple IIe and an Enhanced Apple IIe
 - Emulator? [e.g. real hardware, or emulator name] AppleWin 1.30.9.0 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 43 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment]
Works fine for me in Virtual ][ on the Mac and AppleWin on Windows 10. You should make sure it's not an emulation issue or your operating system eating the keys. Try running BASIC.SYSTEM and typing in this program:

```
10 GET A$
20 PRINT ASC(A$), PEEK(49249)>127, PEEK(49250)>127
30 GOTO 10
```

Then try pressing combinations of <kbd>Open Apple</kbd>, <kbd>Solid Apple</kbd>, and keys like <kbd>O</kbd> or <kbd>Up Arrow</kdb>. If there's a combination that doesn't cause any output (like OA+SA+Up or OA+SA+Down) then it's your emulator and/or your OS that's preventing A2D from receiving the keypress.

Interestingly for me, with AppleWin, typing with a directly connected USB keyboard, it ignored OA+SA+O (as well as OA+SA+C and several other letters). But when I connected to the Windows machine via Remote Desktop, OA+SA+O was fine! Weird. But not A2D's fault.
