### ISSUE TITLE
When you move a window or, especially, when you close a window, you briefly, for between a second and a few seconds, see beneath the current window.

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#684]
**Describe the bug**
When you move a window or, especially, when you close a window, you briefly, for between a second and a few seconds, see part of a window or a whole window located directly beneath the current window, part of a window or a whole window located multiple layers beneath the current window and/or part of the desktop or the whole desktop located beneath the current window.

**To Reproduce**

Example 1:

1. Start Apple II DeskTop.
2. Close all open windows.
3. Double-click on a volume icon and open its volume window.
4. Click on the File menu and go to File > New Folder....
5. Type "A" in the "Enter the folder name:" text field.
6. Click OK.
7. Double-click on the "A" folder icon and open its folder window.
8. Select the volume window you opened in step 3.
9. Close the volume window you opened in step 3.
10. Select the "A" folder window.
11. Click on the File menu and go to File > New Folder....
12. Type "B" in the "Enter the folder name:" text field.
13. Click OK.
14. Double-click on the "B" folder icon and open its folder window.
15. Move and stretch the "B" folder window so that the "A" folder window is completely covered and hidden by the "B" folder window.
16. Move the "B" folder window so that part of the "A" folder window is uncovered and visible.
17. There is briefly, for between a second and a few seconds, no windows visible at all where the "B" folder window was previously located and only the desktop is shown before the uncovered part of the "A" folder window is finally shown.
18. Move the "B" folder window so that the "A" folder window is completely covered and hidden by the "B" folder window again.
19. Close the "B" folder window.
20. There is briefly, for between a second and a few seconds, no windows visible at all and only the desktop is shown before the "A" folder window is finally shown.

Example 2:

1. Start Apple II DeskTop.
2. Close all open windows.
3. Double-click on a volume icon and open its volume window.
4. Move the volume window you opened in step 3 around the screen.
5. There is briefly, for between a second and a few seconds, no windows visible at all and only the desktop is shown before the volume window is finally shown again.

**Expected behavior**
When you move a window or when you close a window, you should not see anything located beneath the current window-that is you should not see part of a window or a whole window located directly beneath the current window, part of a window or a whole window located multiple layers beneath the current window and/or part of the desktop or the whole desktop located beneath the current window.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 43 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment]
The period (.) at the end of the issue title of this issue should be deleted.

**Comment by c0mmander8** [comment]
The period (.) at the end of the issue title of this issue should be deleted. Please delete the period (.) at the end of the issue title of this issue.

**Comment by c0mmander8** [comment]
Please do not suspend me or ban me for my repeated comments in this issue. I am sincerely sorry and I sincerely apologize for my repeated comments in this issue. Thank you for your trouble.

**Comment by inexorabletash** [comment]
Because MGTK does not support regions like QuickDraw, repaints are only done for full rectangles when windows are moved, resized, or closed, and are done using the painter's algorithm (repainting the dirty rectangle from back to front). Using QuickDraw regions on the Mac and IIgs, the effect can be done seamlessly by not doing a full painters algorithm but by handling it via subset regions for the desktop and each revealed window. Note that even as far as System 7 on the Mac, though, this was only done for the window frames themselves; the window contents only painted at the end of an update cycle.

This is way beyond the possibilities for this project to improve.
