### ISSUE TITLE
Add support for the forward delete key on extended ADB keyboards on the Apple IIGS for the new forward delete function in text input fields in addition to the already existing Control-F keyboard shortcut

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#688]
Add support for the forward delete key on extended ADB keyboards on the Apple IIGS for the new forward delete function in text input fields in addition to the already existing Control-F keyboard shortcut.

**Comment by inexorabletash** [comment]
I don't have access to such a keyboard. Run this at the BASIC prompt and report back what it says when you press the key:
```
10 POKE 49168,0
20 IF PEEK(49152) < 128 THEN 20
30 PRINT PEEK(49152) - 128
40 GOTO 10
```

**Comment by c0mmander8** [comment]
I do not have access to such an extended Apple Desktop Bus (ADB) keyboard either. I just, logically, think that adding support for the forward delete key on extended Apple Desktop Bus (ADB) keyboards on the Apple IIGS makes sense as a feature request to complement the new forward delete function in text input fields with its already existing Control-F keypress keyboard shortcut.

**Comment by inexorabletash** [comment]
Closing until someone can supply an answer to this then.

**Comment by inexorabletash** [comment]
$C000 will report $75, which is the same as 'u'. It can be further distinguished by looking at bit 4 of $C025 which will be set.

However, this a lot of code for something very obscure, for an issue which no-one has actually complained about running into, so it's not worth pursuing further.

**Comment by c0mmander8** [comment]
Please reopen this issue and please implement this issue. Pressing the forward delete key on a real extended Universal Serial Bus (USB) keyboard on an emulated ROM 01 Apple IIGS in GSplus 0.14 (the latest version of the program) on a computer running Windows Vista also produces a lowercase "u". I did not mention this earlier in this issue because I thought that this behavior might just be an emulator bug. But since this behavior is the correct and intended behavior, implementing this issue would be useful to users running an Apple IIGS emulator on a computer with a real extended keyboard in addition to users running a real Apple IIGS with a real extended Apple Desktop Bus (ADB) keyboard.

**Comment by c0mmander8** [comment]
Please reopen this issue and please implement this issue. Add support for the forward delete key on extended Apple Desktop Bus (ADB) keyboards on the Apple IIGS for the new forward delete function in text input fields in addition to the already existing Control-F keyboard shortcut. Pressing the forward delete key on a real extended Universal Serial Bus (USB) keyboard on an emulated ROM 01 Apple IIGS in GSplus 0.14 (the latest version of the program) on a computer running Windows Vista also produces a lowercase "u". I did not mention this earlier in this issue because I thought that this behavior might just be an emulator bug. But since this behavior is the correct and intended behavior, implementing this issue would be useful to users running an Apple IIGS emulator on a computer with a real extended keyboard in addition to users running a real Apple IIGS with a real extended Apple Desktop Bus (ADB) keyboard.
