### ISSUE TITLE
Apple II DeskTop app window improvements, both in icon view and in list views, while holding the Apple key down, regardless of whether you are in Apple-X scroll contents mode or not

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#689]
Apple II DeskTop app window improvements, both in icon view and in list views, while holding the Apple key down, regardless of whether you are in Apple-X scroll contents mode or not:

Current behavior:

1. Holding either Apple key while clicking on the Up Arrow on the screen: scrolls up one line at a time
2. Holding either Apple key while clicking on the Down Arrow on the screen: scrolls down one line at a time
3. Holding either Apple key while clicking on the Left Arrow on the screen: scrolls left one line at a time
4. Holding either Apple key while clicking on the Right Arrow on the screen: scrolls right one line at a time
5. Holding both the Open Apple key and the Solid Apple key while clicking on the Up Arrow on the screen: scrolls up one line at a time
6. Holding both the Open Apple key and the Solid Apple key while clicking on the Down Arrow on the screen: scrolls down one line at a time
7. Holding both the Open Apple key and the Solid Apple key while clicking on the Left Arrow on the screen: scrolls left one line at a time
8. Holding both the Open Apple key and the Solid Apple key while clicking on the Right Arrow on the screen: scrolls right one line at a time

Proposed new behavior:

1. Holding either Apple key while clicking on the Up Arrow on the screen: Page Up
2. Holding either Apple key while clicking on the Down Arrow on the screen: Page Down
3. Holding either Apple key while clicking on the Left Arrow on the screen: Page Left
4. Holding either Apple key while clicking on the Right Arrow on the screen: Page Right
5. Holding both the Open Apple key and the Solid Apple key while clicking on the Up Arrow on the screen: scrolls up all the way to the top of the window
6. Holding both the Open Apple key and the Solid Apple key while clicking on the Down Arrow on the screen: scrolls down all the way to the bottom of the window
7. Holding both the Open Apple key and the Solid Apple key while clicking on the Left Arrow on the screen: scrolls left all the way to the left side of the window
8. Holding both the Open Apple key and the Solid Apple key while clicking on the Right Arrow on the screen: scrolls right all the way to the right side of the window

**Comment by inexorabletash** [comment]
Modified-scrollbar clicks are too obscure to consider. I'm unaware of any OS that has these.
