### ISSUE TITLE
Apple II DeskTop app Apple-X scroll contents mode, both in icon view and in list views, Apple-Arrow keypress keyboard shortcut window improvements

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#690]
Apple II DeskTop app Apple-X scroll contents mode, both in icon view and in list views, Apple-Arrow keypress keyboard shortcut window improvements:

Current behavior:

1. Apple-Up Arrow; scrolls up one line at a time
2. Apple-Down Arrow: scrolls down one line at a time
3. Apple-Left Arrow: scrolls left one line at a time
4. Apple-Right Arrow: scrolls right one line at a time
5. Open Apple-Solid Apple-Up Arrow: scrolls up one line at a time or does nothing
6. Open Apple-Solid Apple-Down Arrow: scrolls down one line at a time or does nothing
7. Open Apple-Solid Apple-Left Arrow: scrolls left one line at a time or does nothing
8. Open Apple-Solid Apple-Right Arrow: scrolls right one line at a time or does nothing

Proposed new behavior:

1. Apple-Up Arrow; Page Up
2. Apple-Down Arrow: Page Down
3. Apple-Left Arrow: Page Left
4. Apple-Right Arrow: Page Right
5. Open Apple-Solid Apple-Up Arrow: scrolls up all the way to the top of the window
6. Open Apple-Solid Apple-Down Arrow: scrolls down all the way to the bottom of the window
7. Open Apple-Solid Apple-Left Arrow: scrolls left all the way to the left side of the window
8. Open Apple-Solid Apple-Right Arrow: scrolls right all the way to the right side of the window

**Comment by inexorabletash** [comment]
Reasonable, but it turns into a lot of code and this is pretty obscure functionality, so not going to do it for now.

**Comment by c0mmander8** [comment]
Look over this issue, issue #691, issue #692, issue #693, issue #694, issue #695, issue #696 and issue #697 and also add support for the "Page Up", "Page Down", "Home" and "End" keys on extended Apple Desktop Bus (ADB) keyboards on the Apple IIGS:

"Page Up" key: Implement support for this key wherever Apple-Up Arrow is currently implemented or proposed to be implemented.
"Page Down" key: Implement support for this key wherever Apple-Down Arrow is currently implemented or proposed to be implemented.
"Home" key: Implement support for this key wherever Open Apple-Solid Apple-Up Arrow is currently implemented or proposed to be implemented.
"End" key: Implement support for this key wherever Open Apple-Solid Apple-Down Arrow is currently implemented or proposed to be implemented.
