### ISSUE TITLE
File picker dialog boxes, both in the Apple II DeskTop app and in the Selector app, Apple-Arrow keypress keyboard shortcut improvements

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#691]
File picker dialog boxes, both in the Apple II DeskTop app and in the Selector app, Apple-Arrow keypress keyboard shortcut improvements:

Current behavior:

1. Apple-Up Arrow; Home
2. Apple-Down Arrow: End
3. Open Apple-Solid Apple-Up Arrow: does nothing
4. Open Apple-Solid Apple-Down Arrow: does nothing
5. Holding either Apple key while clicking on the Up Arrow on the screen: moves up one list entry
6. Holding either Apple key while clicking on the Down Arrow on the screen: moves down one list entry
7. Holding both the Open Apple key and the Solid Apple key while clicking on the Up Arrow on the screen: moves up one list entry
8. Holding both the Open Apple key and the Solid Apple key while clicking on the Down Arrow on the screen: moves down one list entry

Proposed new behavior:

1. Apple-Up Arrow; Page Up
2. Apple-Down Arrow: Page Down
3. Open Apple-Solid Apple-Up Arrow: Home
4. Open Apple-Solid Apple-Down Arrow: End
5. Holding either Apple key while clicking on the Up Arrow on the screen: Page Up
6. Holding either Apple key while clicking on the Down Arrow on the screen: Page Down
7. Holding both the Open Apple key and the Solid Apple key while clicking on the Up Arrow on the screen: Home
8. Holding both the Open Apple key and the Solid Apple key while clicking on the Down Arrow on the screen: End

**Comment by inexorabletash** [comment]
In the future, please refrain from filing so many issues at once. 

* Standardized on Apple-Up/Down for Page Up/Down. Does not change selection.
* Standardized on OA+SA+Up/Down for Home/End. Does change selection.
* Modified clicks don't change. (That they do anything in file picker is weirdness from supporting Apple+Click on Change Drive)

**Comment by c0mmander8** [comment]
Please disregard and please delete my last comment. My last comment was a mistake.

**Comment by c0mmander8** [comment]
Look over this issue, issue #690, issue #692, issue #693, issue #694, issue #695, issue #696 and issue #697 and also add support for the "Page Up", "Page Down", "Home" and "End" keys on extended Apple Desktop Bus (ADB) keyboards on the Apple IIGS:

"Page Up" key: Implement support for this key wherever Apple-Up Arrow is currently implemented or proposed to be implemented.
"Page Down" key: Implement support for this key wherever Apple-Down Arrow is currently implemented or proposed to be implemented.
"Home" key: Implement support for this key wherever Open Apple-Solid Apple-Up Arrow is currently implemented or proposed to be implemented.
"End" key: Implement support for this key wherever Open Apple-Solid Apple-Down Arrow is currently implemented or proposed to be implemented.
