### ISSUE TITLE
Disk Copy app main dialog box Apple-Arrow keypress keyboard shortcut improvements

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#692]
Disk Copy app main dialog box Apple-Arrow keypress keyboard shortcut improvements:

Current behavior:

1. Apple-Up Arrow; does nothing
2. Apple-Down Arrow: does nothing
3. Holding either Apple key while clicking on the Up Arrow on the screen: does nothing
4. Holding either Apple key while clicking on the Down Arrow on the screen: does nothing

Proposed new behavior:

1. Apple-Up Arrow; Home
2. Apple-Down Arrow: End
3. Holding either Apple key while clicking on the Up Arrow on the screen: Home
4. Holding either Apple key while clicking on the Down Arrow on the screen: End

**Comment by inexorabletash** [comment]
* Standardized on Apple-Up/Down for Page Up/Down. Does not change selection.
* Standardized on OA+SA+Up/Down for Home/End. Does change selection.
* Modified clicks are ignored.
