### ISSUE TITLE
Calendar desk accessory Apple-Arrow keypress keyboard shortcut improvements

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#693]
Calendar desk accessory Apple-Arrow keypress keyboard shortcut improvements:

Current behavior:

1. Left Arrow: goes backward one month
2. Right Arrow: goes forward one month
3. Up Arrow: goes backward one month
4. Down Arrow: goes forward one month
5. Apple-Left Arrow; goes backward one year
6. Apple-Right Arrow: goes forward one year
7. Apple-Up Arrow: goes backward one year
8. Apple-Down Arrow: goes forward one year
9. Open Apple-Solid Apple-Left Arrow: does nothing
10. Open Apple-Solid Apple-Right Arrow: does nothing
11. Open Apple-Solid Apple-Up Arrow: does nothing
12. Open Apple-Solid Apple-Down Arrow: does nothing
13. Clicking on the Left Arrow on the screen: goes backward one month
14. Clicking on the Right Arrow on the screen: goes forward one month
15. Holding either Apple key while clicking on the Left Arrow on the screen: does nothing
16. Holding either Apple key while clicking on the Right Arrow on the screen: does nothing
17. Holding both the Open Apple key and the Solid Apple key while clicking on the Left Arrow on the screen: does nothing
18. Holding both the Open Apple key and the Solid Apple key while clicking on the Right Arrow on the screen: does nothing

Proposed new behavior:

1. Left Arrow: goes backward one month
2. Right Arrow: goes forward one month
3. Up Arrow: goes backward one month
4. Down Arrow: goes forward one month
5. Apple-Left Arrow; goes backward one year
6. Apple-Right Arrow: goes forward one year
7. Apple-Up Arrow: goes backward one year
8. Apple-Down Arrow: goes forward one year
9. Open Apple-Solid Apple-Left Arrow: goes backward 10 years
10. Open Apple-Solid Apple-Right Arrow: goes forward 10 years
11. Open Apple-Solid Apple-Up Arrow: goes backward 10 years
12. Open Apple-Solid Apple-Down Arrow: goes forward 10 years
13. Clicking on the Left Arrow on the screen: goes backward one month
14. Clicking on the Right Arrow on the screen: goes forward one month
15. Holding either Apple key while clicking on the Left Arrow on the screen: goes backward one year
16. Holding either Apple key while clicking on the Right Arrow on the screen: goes forward one year
17. Holding both the Open Apple key and the Solid Apple key while clicking on the Left Arrow on the screen: goes backward 10 years
18. Holding both the Open Apple key and the Solid Apple key while clicking on the Right Arrow on the screen: goes forward 10 years

**Comment by inexorabletash** [comment]
Too obscure to worry about.

**Comment by c0mmander8** [comment]
Please reopen this issue and please implement this issue. Since the Calendar desk accessory supports years ranging from 1901 to 2155, the Open Apple-Solid Apple keyboard shortcuts I have proposed in this issue would be useful to users to cut down significantly on the number of clicks needed to reach distant years.

**Comment by c0mmander8** [comment]
Look over this issue, issue #690, issue #691, issue #692, issue #694, issue #695, issue #696 and issue #697 and also add support for the "Page Up", "Page Down", "Home" and "End" keys on extended Apple Desktop Bus (ADB) keyboards on the Apple IIGS:

"Page Up" key: Implement support for this key wherever Apple-Up Arrow is currently implemented or proposed to be implemented.
"Page Down" key: Implement support for this key wherever Apple-Down Arrow is currently implemented or proposed to be implemented.
"Home" key: Implement support for this key wherever Open Apple-Solid Apple-Up Arrow is currently implemented or proposed to be implemented.
"End" key: Implement support for this key wherever Open Apple-Solid Apple-Down Arrow is currently implemented or proposed to be implemented.

**Comment by c0mmander8** [comment]
Please reopen this issue and please implement this issue. Since the Calendar desk accessory supports years ranging from 1901 to 2155, the Open Apple-Solid Apple keyboard shortcuts I have proposed in this issue would be useful to users to cut down significantly on the number of clicks needed to reach distant years.
