### ISSUE TITLE
Date and Time control panel Apple-Arrow keypress keyboard shortcut improvements

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#694]
Date and Time control panel Apple-Arrow keypress keyboard shortcut improvements:

Current behavior:

1. Apple-Up Arrow; does nothing
2. Apple-Down Arrow: does nothing
3. Holding either Apple key while clicking on the Up Arrow on the screen: does nothing
4. Holding either Apple key while clicking on the Down Arrow on the screen: does nothing

Proposed new behavior:

1. Apple-Up Arrow; goes forward 10 days / goes forward 10 months / goes forward 10 years / goes forward 10 hours / goes forward 10 minutes / toggle AM / PM
2. Apple-Down Arrow: goes backward 10 days / goes backward 10 months / goes backward 10 years / goes backward 10 hours / goes backward 10 minutes / toggle AM / PM
3. Holding either Apple key while clicking on the Up Arrow on the screen: goes forward 10 days / goes forward 10 months / goes forward 10 years / goes forward 10 hours / goes forward 10 minutes / toggle AM / PM
4. Holding either Apple key while clicking on the Down Arrow on the screen: goes backward 10 days / goes backward 10 months / goes backward 10 years / goes backward 10 hours / goes backward 10 minutes / toggle AM / PM

**Comment by inexorabletash** [comment]
Too obscure to worry about.

**Comment by c0mmander8** [comment]
Please reopen this issue and please implement this issue. Since the Date and Time control panel supports up to 31 days / 12 months / 100 years / up to 24 hours / 60 minutes / sometimes toggling AM / PM, the Open Apple-Solid Apple keyboard shortcuts I have proposed in this issue would be useful to users to cut down significantly on the number of clicks needed to reach distant days / months / years / hours / minutes.

**Comment by c0mmander8** [comment]
Please disregard and please delete my last comment. My last comment was a mistake.

**Comment by c0mmander8** [comment]
Please reopen this issue and please implement this issue. Since the Date and Time control panel supports up to 31 days / 12 months / 100 years / up to 24 hours / 60 minutes / sometimes toggling AM / PM, the Apple key keyboard shortcuts I have proposed in this issue would be useful to users to cut down significantly on the number of clicks needed to reach distant days / months / years / hours / minutes.

**Comment by c0mmander8** [comment]
Look over this issue, issue #690, issue #691, issue #692, issue #693, issue #695, issue #696 and issue #697 and also add support for the "Page Up", "Page Down", "Home" and "End" keys on extended Apple Desktop Bus (ADB) keyboards on the Apple IIGS:

"Page Up" key: Implement support for this key wherever Apple-Up Arrow is currently implemented or proposed to be implemented.
"Page Down" key: Implement support for this key wherever Apple-Down Arrow is currently implemented or proposed to be implemented.
"Home" key: Implement support for this key wherever Open Apple-Solid Apple-Up Arrow is currently implemented or proposed to be implemented.
"End" key: Implement support for this key wherever Open Apple-Solid Apple-Down Arrow is currently implemented or proposed to be implemented.

**Comment by c0mmander8** [comment]
Please reopen this issue and please implement this issue. Since the Date and Time control panel supports up to 31 days / 12 months / 100 years / up to 24 hours / 60 minutes / sometimes toggling AM / PM, the Apple key keyboard shortcuts I have proposed in this issue would be useful to users to cut down significantly on the number of clicks needed to reach distant days / months / years / hours / minutes.
