### ISSUE TITLE
Find Files desk accessory Apple-Arrow keypress keyboard shortcut improvements

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#695]
Find Files desk accessory Apple-Arrow keypress keyboard shortcut improvements:

Current behavior:

1. Apple-Up Arrow; Page Up
2. Apple-Down Arrow: Page Down
3. Open Apple-Solid Apple-Up Arrow: does nothing
4. Open Apple-Solid Apple-Down Arrow: does nothing
5. Holding either Apple key while clicking on the Up Arrow on the screen: does nothing
6. Holding either Apple key while clicking on the Down Arrow on the screen: does nothing
7. Holding both the Open Apple key and the Solid Apple key while clicking on the Up Arrow on the screen: does nothing
8. Holding both the Open Apple key and the Solid Apple key while clicking on the Down Arrow on the screen: does nothing

Proposed new behavior:

1. Apple-Up Arrow; Page Up
2. Apple-Down Arrow: Page Down
3. Open Apple-Solid Apple-Up Arrow: Home
4. Open Apple-Solid Apple-Down Arrow: End
5. Holding either Apple key while clicking on the Up Arrow on the screen: Page Up
6. Holding either Apple key while clicking on the Down Arrow on the screen: Page Down
7. Holding both the Open Apple key and the Solid Apple key while clicking on the Up Arrow on the screen: Home
8. Holding both the Open Apple key and the Solid Apple key while clicking on the Down Arrow on the screen: End

**Comment by inexorabletash** [comment]
In the future, please refrain from filing so many issues at once.

* Standardized on Apple-Up/Down for Page Up/Down. Does not change selection.
* Standardized on OA+SA+Up/Down for Home/End. Does change selection.
* Modified clicks are ignored.
