### ISSUE TITLE
Show Text File preview handler Apple-Arrow keypress keyboard shortcut improvements

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#696]
Show Text File preview handler Apple-Arrow keypress keyboard shortcut improvements:

Current behavior:

1. Apple-Up Arrow; Page Up
2. Apple-Down Arrow: Page Down
3. Apple-Left Arrow: Home
4. Apple-Right Arrow: End
5. Open Apple-Solid Apple-Up Arrow: does nothing
6. Open Apple-Solid Apple-Down Arrow: does nothing
7. Holding either Apple key while clicking on the Up Arrow on the screen: does nothing
8. Holding either Apple key while clicking on the Down Arrow on the screen: does nothing
9. Holding both the Open Apple key and the Solid Apple key while clicking on the Up Arrow on the screen: does nothing
10. Holding both the Open Apple key and the Solid Apple key while clicking on the Down Arrow on the screen: does nothing

Proposed new behavior:

1. Apple-Up Arrow; Page Up
2. Apple-Down Arrow: Page Down
3. Apple-Left Arrow: Home
4. Apple-Right Arrow: End
5. Open Apple-Solid Apple-Up Arrow: Home
6. Open Apple-Solid Apple-Down Arrow: End
7. Holding either Apple key while clicking on the Up Arrow on the screen: Page Up
8. Holding either Apple key while clicking on the Down Arrow on the screen: Page Down
9. Holding both the Open Apple key and the Solid Apple key while clicking on the Up Arrow on the screen: Home
10. Holding both the Open Apple key and the Solid Apple key while clicking on the Down Arrow on the screen: End

**Comment by inexorabletash** [comment]
I'm going to merge this into #422 because it turns out that until that is addressed, this doesn't behave very sensibly.

**Comment by c0mmander8** [comment]
Look over this issue, issue #690, issue #691, issue #692, issue #693, issue #694, issue #695 and issue #697 and also add support for the "Page Up", "Page Down", "Home" and "End" keys on extended Apple Desktop Bus (ADB) keyboards on the Apple IIGS:

"Page Up" key: Implement support for this key wherever Apple-Up Arrow is currently implemented or proposed to be implemented.
"Page Down" key: Implement support for this key wherever Apple-Down Arrow is currently implemented or proposed to be implemented.
"Home" key: Implement support for this key wherever Open Apple-Solid Apple-Up Arrow is currently implemented or proposed to be implemented.
"End" key: Implement support for this key wherever Open Apple-Solid Apple-Down Arrow is currently implemented or proposed to be implemented.

**Comment by ph0enix-c0der** [comment]
This issue should be added to the Apple II DeskTop 1.2 milestone.

**Comment by inexorabletash** [comment]
Please don't waste my time (or yours) on this sort of bookkeeping. Release notes capture the important things; no-one should be looking through old bugs.

If you want to be productive, try running through the test plan and ensure there haven't been regressions.
