### ISSUE TITLE
Sounds control panel Apple-Arrow keypress keyboard shortcut improvements

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#697]
Sounds control panel Apple-Arrow keypress keyboard shortcut improvements:

Current behavior:

1. Apple-Up Arrow; Page Up or Home?
2. Apple-Down Arrow: Page Down or End?
3. Apple-Left Arrow: does nothing
4. Apple-Right Arrow: does nothing
5. Open Apple-Solid Apple-Up Arrow: does nothing
6. Open Apple-Solid Apple-Down Arrow: does nothing
7. Holding either Apple key while clicking on the Up Arrow on the screen: does nothing
8. Holding either Apple key while clicking on the Down Arrow on the screen: does nothing
9. Holding both the Open Apple key and the Solid Apple key while clicking on the Up Arrow on the screen: does nothing
10. Holding both the Open Apple key and the Solid Apple key while clicking on the Down Arrow on the screen: does nothing

Proposed new behavior:

1. Apple-Up Arrow; Page Up
2. Apple-Down Arrow: Page Down
3. Apple-Left Arrow: Home
4. Apple-Right Arrow: End
5. Open Apple-Solid Apple-Up Arrow: Home
6. Open Apple-Solid Apple-Down Arrow: End
7. Holding either Apple key while clicking on the Up Arrow on the screen: Page Up
8. Holding either Apple key while clicking on the Down Arrow on the screen: Page Down
9. Holding both the Open Apple key and the Solid Apple key while clicking on the Up Arrow on the screen: Home
10. Holding both the Open Apple key and the Solid Apple key while clicking on the Down Arrow on the screen: End

**Comment by inexorabletash** [comment]
In the future, please refrain from filing so many issues at once.

* Standardized on Apple-Up/Down for Page Up/Down. Does not change selection.
* Standardized on OA+SA+Up/Down for Home/End. Does change selection.
* Modified clicks are ignored.

**Comment by c0mmander8** [comment]
Look over this issue, issue #690, issue #691, issue #692, issue #693, issue #694, issue #695 and issue #696 and also add support for the "Page Up", "Page Down", "Home" and "End" keys on extended Apple Desktop Bus (ADB) keyboards on the Apple IIGS:

"Page Up" key: Implement support for this key wherever Apple-Up Arrow is currently implemented or proposed to be implemented.
"Page Down" key: Implement support for this key wherever Apple-Down Arrow is currently implemented or proposed to be implemented.
"Home" key: Implement support for this key wherever Open Apple-Solid Apple-Up Arrow is currently implemented or proposed to be implemented.
"End" key: Implement support for this key wherever Open Apple-Solid Apple-Down Arrow is currently implemented or proposed to be implemented.
