### ISSUE TITLE
Clipped descenders occur in the Disk Copy list box entries

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#698]
As referenced in issue #126, clipped descenders still occur in the Disk Copy app main dialog box list entries.

**Comment by inexorabletash** [comment]
Yep. Needs to switch from 8px/line to actually using the text height. This requires pulling in multiply/divide logic (since /8 is easy but /9 is not) for highlighting/hit testing, and probably some layout tweaks.
