### ISSUE TITLE
Simplify file picker dialogs

### ISSUE THREAD

**Issue by inexorabletash** [a2stuff/a2d#699]
## Background

There are several confusing things about how A2D (c/o MouseDesk) uses file dialogs:

* The file picker dialogs c/o MouseDesk allow the user to either select files (using the list box/open/close/drive buttons) or type a path. The path is considered the canonical "result" of the dialog; the other UI is just to set it. This can be confusing if the user edits the path. The path also takes up substantial screen space, and very long paths don't even fit.
* DeskTop's File > Copy a File... and File > Delete a File... commands confuse users - they expect these commands to operate on the selected files. In reality, these are an alternative to selection. The IIgs and macOS never had these - you just drag the files to the destination or trash instead. 
* DeskTop's File > Copy a File... and Shortcuts > Add/Edit a Shortcut... are two-stage dialogs, where you pick a source, then click OK, then (in the same dialog) start modifying the second field (destination or name). You can even hit Cancel (or click) to go back to the first field. This is rather esoteric UI. It works... but does anyone but me really understand it?

## Proposal

Here's a proposal to simplify the UI dramatically here, but it's a big change so I wanted to get feedback. Overall, it assumes that the user of DeskTop is more comfortable with a GUI than with ProDOS pathnames, which seems reasonable. But maybe the functionality being altered is for power users anyway, and the loss of the pathnames is too detrimental?

### Selector > File > Run a Program...
* Drop the path field
* Shorten & narrow the dialog

Mockup:

![image](https://user-images.githubusercontent.com/771547/165653764-a3bcad6f-8011-4155-9d2f-46f1170ce81a.png)

### DeskTop > File > Copy a File...
* Require file selection(s) for the menu item to be active
* Rename command to: Copy...
* Retitle dialog to: "Select copy destination:"
* Drop source/destination path fields
* Shorten & narrow the dialog
* Functionality loss: Can no longer specify a different destination _filename_. (You need to copy, then rename.)

This would look similar to the "Run a Program..." dialog, just with a different title.

### DeskTop > File > Delete a File...
* Require file selection(s) for the menu item to be active
* Rename menu command to: Delete
* Dialog goes away; this would operate on the selection, and jump immediately to the confirmation dialog.

### DeskTop > Shortcuts > Add/Edit a Shortcut...
* Single field for shortcut name
* Shorten the dialog
* Functionality loss: Specifying shortcuts for disks is less obvious (would still work, though)

Mockup:

![image](https://user-images.githubusercontent.com/771547/165653746-072fc16c-1195-4848-a57e-39eb6d020eae.png)

## Potential follow-ups
* Move the current disk name centered above the Change Drive button
* Add the current folder name centered above list box control, given that this context is lost without the path.
* Have the File > Copy... dialog start in the selection's directory, rather than the first drive.
* Have Shortcuts > Add a Shortcut... init to the current selection, if any.

**Comment by c0mmander8** [comment]
I vote against all of these proposed changes. I like all of the file picker dialog boxes, both in the Apple II DeskTop app and in the Selector app, the way they currently are. Also, the current File > Copy a File... / File > Delete a File... file picker dialog boxes in the Apple II DeskTop app lets users copy items or delete items from folders with more than 127 items inside of them. That functionality would also be lost with these proposed changes.

**Comment by c0mmander8** [comment]
I vote against all of these proposed changes due to my extreme and heavy opposition to all of them. I like all of the file picker dialog boxes, both in the Apple II DeskTop app and in the Selector app, the way they currently are. Also, the current File > Copy a File... / File > Delete a File... file picker dialog boxes in the Apple II DeskTop app let users copy items or delete items from folders with more than 127 items inside of them. That functionality would also be lost with these proposed changes.
