### ISSUE TITLE
Also add support for the "Page Up", "Page Down", "Home" and "End" keys on extended Apple Desktop Bus (ADB) keyboards on the Apple IIGS

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#702]
Look over issue #690, issue #691, issue #692, issue #693, issue #694, issue #695, issue #696 and issue #697 and also add support for the "Page Up", "Page Down", "Home" and "End" keys on extended Apple Desktop Bus (ADB) keyboards on the Apple IIGS:

"Page Up" key: Implement support for this key wherever Apple-Up Arrow is currently implemented or proposed to be implemented.
"Page Down" key: Implement support for this key wherever Apple-Down Arrow is currently implemented or proposed to be implemented.
"Home" key: Implement support for this key wherever Open Apple-Solid Apple-Up Arrow is currently implemented or proposed to be implemented.
"End" key: Implement support for this key wherever Open Apple-Solid Apple-Down Arrow is currently implemented or proposed to be implemented.

**Comment by inexorabletash** [comment]
Too niche to worry about. It would be nice to have the codes documented for posterity, though.
