### ISSUE TITLE
Matrix causes LCM Eve to lock up system 

### ISSUE THREAD

**Issue by inexorabletash** [a2stuff/a2d#703]
Reported by an LCM Eve user: 

After running Matrix, when the screen returns to graphics mode, the mouse cursor is responsive but clicking doesn't do anything and the system only responds to a power cycle, not even control-OA-reset.

**Comment by inexorabletash** [comment]
3dd3f7e1 may solve this, but need confirmation

**Comment by inexorabletash** [comment]
Nope. Still trying to iterate on this.

**Comment by inexorabletash** [comment]
@fenarinarsa - FYI; this is a particularly odd EVE issue. Note that the latest releases are still buggy and EVE-specific fixes have gone in, but they don't appear to have solved this problem. 

At the point where this code runs, the EVE's HR1/2/3 should have been twiddled (to enable mono DHR) but none of TXT16 or the other registers should be on. This code "backs up" main and aux text page (since the graphics library uses them as scratch space; the screen holes are not touched), switches to text mode, runs an animation effect, then switches back to graphics mode, "restores" the main and aux text pages, and exits.

I don't have a good theory for the weird behavior the reporter is seeing (e.g. mouse cursor moves but no clicks?!?). Bad theories include that aux shadowing kicks on so the GUI library malfunctions, or that screen holes stop responding properly (talking to the mouse with aux memory active is a bit strange), or that one of the other EVE registers kicks in (ENHRCPREG?) and mucks up everything.

**Comment by fenarinarsa** [comment]
Interesting. Thank you for mentioning me, even if I'm not really an EVE specialist so far - I haven't had much time to play with extended modes.
Clicking not working seem strange. I don't really know how a2d works though. The most obvious candidate is of course the TXT16 features that writes in AUX for each write in MAIN that may be enabled in some way?
Without any live debugger or logic analyzer, hard to tell what happens.

**Comment by inexorabletash** [comment]
Yeah. I have made some test builds that progressive turn off more and more of the code to try and narrow down the cause, but it is slow going with about one change per week to test.

If there are any other EVE users out there interested I helping to debug I can send them builds.

**Comment by inexorabletash** [comment]
Confirmed fixed by 1c3ff822
