### ISSUE TITLE
DA windows closed by OA-W in addition to Esc

### ISSUE THREAD

**Issue by xandark** [a2stuff/a2d#743]
I was closing the file desktop windows with OA-W and then I noticed that it doesn't work on DA's. I found by accident that Esc closes DA's. 

Is there a reason why OA-W couldn't also close DA's?

v1.3-alpha4

**Comment by inexorabletash** [comment]
The mechanical answer is: because OA-W is a menu shortcut and menus are not operational during DAs.

It would be possible to add code to windowed DAs to close on OA-W. PRs welcome!

**Comment by xandark** [comment]
I understand. Well, my 6502 assembly skills are no good, so I guess I'll just wait to see if anyone else takes this up, but thanks.

**Comment by inexorabletash** [comment]
In case anyone wants to tackle this:

* 'W' shouldn't be hardcoded, as it could be changed c/o localization. DeskTop gets it via the `res_char_menu_item_close_shortcut` definition.
* Both upper and lowercase should be supported, so case folding of the key would be necessary.
* Each DA has its own logic for exiting, so the same code can't be copy-pasted everywhere.
