### ISSUE TITLE
Calculator DA has some unusual glyphs in v1.3-alpha4

### ISSUE THREAD

**Issue by xandark** [a2stuff/a2d#745]
![Screenshot 2023-03-04 (18∶39∶26)](https://user-images.githubusercontent.com/5048913/222938749-06ab4d17-2c14-4a59-91bb-21ae47fdae05.png)

In the title bar, there is something at the right that I do not know what it is. Clicking on it doesn't do anything.

On the key to the right of the 0 it looks like a £ symbol. Is that supposed to be there?

**Comment by inexorabletash** [comment]
Thank you for pointing this out! 

Glitched caused by an earlier refactor.

(Also... you've filed four bugs in just a handful minutes. I appreciate your enthusiasm, but consider throttling your activity to avoid irritating other participants.)
