### ISSUE TITLE
Clicking in Calculator title bar causes an unconditional window repaint

### ISSUE THREAD

**Issue by xandark** [a2stuff/a2d#746]
If I click in the Calculator window title bar, do not move the mouse, let go of the button, the window unconditionally repaints itself. I notice that other windows do not have this behavior, both file windows and Eyes, for example.

Seems clunky from a user perspective, and especially since drawing is so slow to watch all the buttons repaint themselves.

**Comment by inexorabletash** [comment]
Also affected Sci Calc and Puzzle.

**Comment by inexorabletash** [comment]
Good catch!
