### ISSUE TITLE
Karateka.Yell does not auto-play on double-click in v1.3-alpha4

### ISSUE THREAD

**Issue by xandark** [a2stuff/a2d#747]
Karateka.Yell in Sample.Media used to auto-play when you double-clicked the file. 

Now A2D reports this:

![Screenshot 2023-03-04 (18∶50∶42)](https://user-images.githubusercontent.com/5048913/222939080-31422fa7-5e7d-44d9-8db9-42e669f313e5.png)

However, if I select the file and do an OA-O, the file will open and auto-play without displaying the message.

**Comment by inexorabletash** [comment]
Yes, that's working as intended. It's a safety net since it's so easy to double-click. If you use a keyboard shortcut it's assumed you know what you're doing.

**Comment by xandark** [comment]
How does A2D determine that that BIN file is actually an audio clip?

**Comment by inexorabletash** [comment]
It doesn't - KARATEKA.YELL is a program.

**Comment by xandark** [comment]
Oohhhhh! Got it.
