### ISSUE TITLE
Unify keyboard and mouse menu navigation

### ISSUE THREAD

**Issue by frankmilliron** [a2stuff/a2d#754]
If "File" menu is actively being displayed, the keystroke for "Quit" is not launched when hitting OA-Q. Only clicking on the menu entry will launch the item, once the window is open. Would be nice if you could launch the item using keystrokes.

**Comment by frankmilliron** [comment]
"ESC" should also close the menu if the menu entry was clicked to open. Arrow keys should traverse the menus. They do not currently. Only another mouse click will launch or close the menu.

**Comment by inexorabletash** [comment]
After some initial exploration, it seems like it'll be necessary to do an overhaul of the keyboard menu system to integrate it better into the mouse menu system, to remove special cases and provide all of the above.

There's also a bug where certain presses get interpreted as mouse coords while the menu is showing.
