### ISSUE TITLE
Menu closes immediately on opening with "ESC"

### ISSUE THREAD

**Issue by frankmilliron** [a2stuff/a2d#756]
To replicate:
place arrow pointer in farthest upper-left corner, hit "ESC" to open menus.
Menu closes immediately upon opening.

**Comment by inexorabletash** [comment]
Proximal cause is that in `MenuSelectImpl` when `lda     #find_mode_by_coord` / `jsr     find_menu` runs, the `set_pos_params` are not the correct mouse coords, so menu is dismissed.

**Comment by inexorabletash** [comment]
This is weird - once mouse mode is entered, the mouse should be moved to the keyboard mouse position (aligned with the relevant menu item) via PositionKbdMouse, but if the mouse is at x=0 the wrong coordinates are returned via the GetAndReturnEvent call, for some iteration of the event loop inside MenuSelectImpl.

**Comment by inexorabletash** [comment]
I still haven't spotted it, but there's some subtlety where `mouse_state` (where we think the mouse is) and `set_pos_params` (where we try and `SETMOUSE`) get out of sync, so `set_pos_params` gets overwritten with real (?) values instead of keyboard values during the `GetEvent` call.

**Comment by inexorabletash** [comment]
Hey @frankmilliron - was this in Virtual ][ ? I can repro in Virtual ][ but not in MAME (via Ample) so I'm wondering if this is actually an emulation issue.

**Comment by frankmilliron** [comment]
Indeed this is an emulation issue with Virtual ][. MAME correctly moves the mouse pointer to the active menu window as well, which V2 does not. I need to set up my //c so I can finally test this on real hardware.

**Comment by inexorabletash** [comment]
New keyboard menu logic works around this.
