### ISSUE TITLE
Display corrupted when returning from //GS Apps

### ISSUE THREAD

**Issue by banksr1979** [a2stuff/a2d#764]
When Returning to Desktop after quitting various //GS Applications, the display is corrupted. Desktop seem to otherwise be running normally, but the display is 'fragmented', rendering it unusable

**To Reproduce**
On Apple //GS Rom 03:

1. Boot to DeskTop
2. Launch GS Application, for example NoiseTracker https://archive.org/details/a2gs_NoiseTracker_1992_FTW_FW
3. Quit GS Application, returning to Desktop
4. Desktop display is corrupt - clicking around, moving mouse, using keyboard shortcuts all seem to work, but you're working blind

**Expected behavior**
Desktop starts normally

**Screenshots**
![fail](https://github.com/a2stuff/a2d/assets/99176911/4b4af7da-94a1-4aad-a5fc-a614a4d233c5)

 - System Apple IIgs, Rom3, 
 - Emulator? Nope, real hardware.
 - DeskTop version 1.3 Final
 - Other Fully populated apple memory expansion, 2 and a bit meg of ram, no other cards, booting the 32 Meg Hard drive image hosted on a SmartportSD, https://gitlab.com/nyankat/smartportsd. No other disk drives, standard GS ADB keyboard and mouse, GS RGB Monitor running at 60Hz

**Additional context**

Happens with a few GS Apps I've tried so far, SHR viewer and NoiseTracker. Resetting to bitsy-bye and then launching Desktop again fixes it. It looks like perhaps the apps mess with some video mode registers, and don't put them back where the found them, and Desktop assumes they're set to default when booting. maybe. idk, i'm no expert.

Will try on an emulator as soon as I get one set up, there's a small but non-zero chance its a fault in my hardware, although it seems to be ok - will find some diagnostic tools!

**Comment by banksr1979** [comment]
Behaviour _not_ seen in KEGS emulator on Windows or android (although going to 'about this Apple II' locks the emulator up, but that's a different issue!

**Comment by inexorabletash** [comment]
Repros for me in MAME via Ample, ROM 01 IIgs.

**Comment by inexorabletash** [comment]
Thanks for the report! This was fun. The issue was caused by not resetting a bit in `NEWVIDEO`. Apparently all three of `SHADOW`, `SPEED` and `NEWVIDEO` can affect shadowing on the IIgs.
