### ISSUE TITLE
Disk Copy causes A2Stream not to work

### ISSUE THREAD

**Issue by cskare** [a2stuff/a2d#766]
After launching Disk Copy from Desktop and then quitting Disk Copy, Desktop causes A2Stream not to work.  A2Stream errors with "/RAM not present".

1. Start DeskTop
2. Launch Disk Copy
3. Quit Disk Copy
4. Launch A2Stream using A2Stream.System
5. A2Stream errors with "/RAM not present"

A2Stream when working will ask for URL to stream.

AppleWin 1.30.15.0 Enhanced Apple //e, Uthernet II enabled
Apple II Desktop 1.3
A2Stream 1.3

**Comment by inexorabletash** [comment]
Another good bug. Thanks!
