### ISSUE TITLE
CD Remote shouldn't play on track up/down unless it's already playing

### ISSUE THREAD

**Issue by rb6502** [a2stuff/a2d#768]
**Describe the bug**
CD Remote currently starts playing each track when you press track forward/backward.  This should only occur if the CD is currently playing, like real CD players and Apple's CD Player apps on the IIgs and classic Mac.

Moreover, if you press track up/down when the drive is stopped (for instance, after clicking the Stop button) playback starts but the playback position doesn't update and you can't click the stop button.

**To Reproduce**
1. Start DeskTop with an Apple CD-ROM drive and SCSI card or the upcoming MAME emulation and a CD with at least one audio track in the drive
2. Open the Extras folder and double-click "CD Remote"
3. Click Track Up, CD Remote will try to play the first track (even if it's a data track, but that's a separate issue).
4. Playback will continue, but you will be unable to click Stop and the time display won't update unless you then click Play.

**Expected behavior**

**Screenshots**

**System Details (please complete the following information):**
 - System Apple IIe Enhanced
 - Emulator? MAME 0.258 work-in-progress (this can't yet be tested in a public MAME tree, but it should show on real hardware)
 - ProDOS version 2.4.2
 - DeskTop version 1.3 Release
 - Other Mouse in slot 4, SCSI card in slot 7, using the A2DeskTop-1.3-en_32MB.hdv image

**Additional context**

**Comment by inexorabletash** [comment]
None of the 3 SCSI CD-ROM drives I've purchased are functional, so I'm looking forward to the MAME release!

**Comment by inexorabletash** [comment]
Interesting... the code seems to be doing the same thing as the GS/OS 6.0.1 source when sending the AudioSearch command, i.e. setting the first byte of the buffer to signal whether to play or hold.

https://github.com/a2stuff/a2d/blob/5ea833706e7bc24a389a0a266257926cfa79314a/desk.acc/cd.remote.s#L1715

Possibilities are:
* We broke something when disassembling/adapting the code from the original CD player IIe app, and the code is buggy in a subtle way - either near the AudioSearch call or farther upstream. 
* It was buggy in the IIe app and no one noticed back in the day. Maybe it got the protocol subtly wrong?
* The MAME emulation is buggy. Listing for completeness. :)

I'll be able to diagnose further once that release of MAME is out, but if you want to see if we're sending AudioSearch with the correct or incorrect params that'd help.

**Comment by rb6502** [comment]
I don't actually handle the search command right now because it's the least understandable one :-)  There's an explicit Play being sent somewhere down the line when you click the Track up/down buttons, is all I know.  It'd be great if someone had a working drive and could try some things.

**Comment by inexorabletash** [comment]
Heh, okay. That helps, I'll stare at the code some more.

**Comment by inexorabletash** [comment]
Does the same thing happen when the <kbd>N</kbd> key is pressed? Under the hood, the GUI maps button presses to key presses, and dispatches into the key handling logic. I'm not spotting an issue yet but if the same thing happens with the <kbd>N</kbd> key then it at least slightly narrows things down.

**Comment by apple2geek** [comment]
I'd be most interested to know if the "original" full-screen P8 CD Remote starts playing if you choose "track up"/"next" from a stopped state.  If it does, then the behavior lies in the original code to begin with.  I would hope it does not, but I don't recall ever specifically seeing that behavior tested or demonstrated, one way or the other.

My suspicion is that if the playback is being erroneously started, it's probably happening somewhere in the "C20AudioSearch" (line 1690). I have to confess, that was one of the subroutines that I had the most trouble wrapping my head around.  I thought I eventually had a pretty good handle on it, but even then I wasn't 100% sure of _exactly_ how it behaves, or is intended to behave, and I never got enough of a compatible system set up to do the deep dive I needed to figure it out fully.  The documentation that I was able to find for the AudioSearch SP Control call is _absolutely_ inadequate at best.

That routine (C20AudioSearch) and some of the "Random" play behavior routines near the end were the ones that I ultimately had to just ... assume they worked as-is, and leave them exactly as they were (please note my blunt comments on lines 2308/2396/2399).

**Comment by inexorabletash** [comment]
Non-update: inspection of the IIgs 6.0.1 source calling #$20 and the original CDREMOTE and our new DA all seem to call it with the same buffer, so it does seem like it's some higher level flow control issue in the code, but I still haven't spotted it yet.

Now that we understand the calls and responses a bit better expanding the FAKE_HARDWARE mode to return dummy data is a possibility, but if we get the emulator soon that'll be easier. :)

**Comment by inexorabletash** [comment]
Playing with this now. The issue reproduces in the original code https://github.com/a2stuff/cdremote too.

The CD Remote (DA here and original) just send #$20 (AudioSearch) when next/prev track is selected, whether playing or not. They don't send a subsequent AudioPlay command - I can BRK right after the Nth search and the playing starts up in MAME. If I explicitly send an AudioStop (assuming we're not playing) then it behaves.

When you mention _"I don't actually handle the search command right now because it's the least understandable one"_ is the code just falling through to an AudioPlay or something? The parameters (looking at ASeekTrack in the IIgs code spdriver.aii) seem to be:

* buffer+0: $00 = hold, $01 = play
* buffer+1: play mode, $09 = stereo
* buffer+2: track (BCD)
* buffer+3: zero
* buffer+4: zero
* buffer+5: zero
* buffer+6: $02 (address type - track number)

It seems like the first byte (buffer+0) is being ignored and play is initiated regardless.

If it helps here are videos of someone using the original remote on real hardware:

https://www.youtube.com/watch?v=loXFF4MgP24

And here's our CD Remote. You can see the scenario here being exercised - with playback stopped, the Next Track button is hit and playback doesn't start automatically.

https://www.youtube.com/watch?v=m8VFkwpGVOM

**Comment by inexorabletash** [comment]
Also, it seems on startup that the remote is detecting (via a status query) that the CD is actively playing. This can be worked around by sending an explicit stop but this is not necessary on real hardware, so far as I can tell.

**Comment by inexorabletash** [comment]
FYI the original CD Remote which gets more video air time: https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/hardware/storage/disk/misc/Apple%20II%20CD%20Setup.dsk

**Comment by inexorabletash** [comment]
Hmmm, and confusingly - if CD audio is currently playing then $20 AudioSearch *stops* audio, regardless of the state of the first buffer byte.

**Comment by inexorabletash** [comment]
Oh hey @rb6502 - hopefully you're typing an update somewhere. :) I was starting to look into the MAME code but if you've got an update coming let me know!

**Comment by inexorabletash** [comment]
Checking in @rb6502 - I'm assuming you closed this because you agree this is an emulation issue, but if I'm wrong please let me know. If it is an emulation issue, is there a pending fix for MAME? Or do we need to do research, and if so how can we help?

**Comment by inexorabletash** [comment]
One more for @rb6502 - does this line mean `APPLE_AUDIO_STATUS` will never return anything but "PLAYING" ? https://github.com/mamedev/mame/blob/f290e3bae9e89d858e0f7a8ddfc5c3fbe82dd121/src/devices/bus/nscsi/cd.cpp#L1154 

Accidentally left in, perhaps?

**Comment by inexorabletash** [comment]
Reported issue in https://github.com/mamedev/mame/issues/12925
