### ISSUE TITLE
Previous lines of text disappears while scrolling down a text file in "Fixed" font

### ISSUE THREAD

**Issue by cskare** [a2stuff/a2d#770]
**Describe the bug**
While scrolling down text file Sudoku.Story, in "Fixed" font mode, previous lines of text disappear when a new line is displayed.  Scrolling up through text file has similar issue.  Does not appear to be an issue with "Proportional" font mode.

**To Reproduce**
1. Download SUDOKU.dsk from www.michaeljmahon.com/Sudoku.html
2. Start DeskTop
3. Open Sudoku disk
4. Open Sudoku.Story text file
5. Click on "Proportional" to change to "Fixed" font
6. Scroll down using down arrow key until bottom line reads "with"
7. Scroll down again using down arrow key
8. Bottom line now reads "permitted adding ..." and previous 2 lines disappeared

**Expected behavior**
Previous lines of text should not disappear while scrolling down through a text file.

**Screenshots**

**System Details (please complete the following information):**
 - AppleWin 1.30.15.0 & Apple //jse
 - DeskTop version 1.4-alpha1

**Additional context**

**Comment by inexorabletash** [comment]
Thanks for the detailed repro instructions. I'm able to repro the issue. I'll look into it.

**Comment by inexorabletash** [comment]
Give this a whirl - drop the file from this disk into MODULES/ (in 1.4) or PREVIEW/ (in 1.3)
[show_text_file.dsk.zip](https://github.com/a2stuff/a2d/files/12811451/show_text_file.dsk.zip)

**Comment by cskare** [comment]
The fix works great!  Thanks for your great work!
________________________________
