### ISSUE TITLE
Monochrome mode broken on IIe Card

### ISSUE THREAD

**Issue by tweedyf** [a2stuff/a2d#771]
a2d works great (albeit with the expected fuzzy text) in color mode on my Color Classic II with IIe Card.

However, when I switch to monochrome mode, the desktop doesn't render properly, and moving the mouse creates odd diagonal artifacts. This is from starting a2d in color mode, switching to monochrome, then moving the mouse a bit.

![A2D bw](https://github.com/a2stuff/a2d/assets/18741473/0205673a-e385-4dd8-a2c2-4549642f2c54)

More screen artifacts are created the more the mouse moves, so it quickly becomes unusable:

![Picture 01](https://github.com/a2stuff/a2d/assets/18741473/433ee18b-2326-4690-86b4-67295b758e12)

If I start a2d in monochrome mode, the entire screen is garbled:

![Picture 00](https://github.com/a2stuff/a2d/assets/18741473/b758bb60-fff9-490f-ae64-14c047e9c248)

System:

* a2d 1.3
* Color Classic II
* Mac OS 7.1.1
* Apple IIe Card

**Comment by inexorabletash** [comment]
What version of the IIe card software is on your Mac?

**Comment by tweedyf** [comment]
2.2.2d1

**Comment by inexorabletash** [comment]
Can you try 2.2.1? While 2.2.2d1 fixes some bugs it's known to introduce other bugs since it wasn't an official release. 

2.2.1 doesn't exhibit the problems for me:
![image](https://github.com/a2stuff/a2d/assets/771547/e0c3adff-6f57-46a3-b91e-24a069d42933)

(I suspect an emulation issue as the color/mono difference is completely invisible to the emulated machine.)

**Comment by frankmilliron** [comment]
In my notes about the IIe card I have "v2.2.2d1 - buggy developer preview version, VBL signal reversed accidentally (don't use)".

Use 2.2.1 instead.

**Comment by tweedyf** [comment]
Thanks, I should have thought of that. Unfortunately though, downgrading to 2.2.1 doesn't seems to have resolved the issue.

I'll do a bit more troubleshooting when I'm back at home tonight. I have a CC board I can swap in, and I can also try the IIe Card in an LC 475, to try to isolate this a bit more.

@inexorabletash what are the details of the system you have this working on?

**Comment by tweedyf** [comment]
Happy to report that A2D works as expected on the LC475 and with the 16MHZ CC board installed. Weirdly though, the behavior above persists when I have the 33MHZ CCII board installed. Unfortunately I don't have another, so I can't say whether the issue is with this CCII logic board in particular or with something about that board type in general.

**Comment by inexorabletash** [comment]
I finally had a chance to get my LC set up again. Here's my working config:

Macintosh LC 475 820-0364-A board (in Performa 400 case)
System 7.5.3 Revision 2
IIe Card: 670-4444-A
IIe Startup version: 2.2.1

No issues with monochrome mode, either switching while already running or starting in monochrome mode.

Closing this out as it doesn't seem like something that can be handled by DeskTop itself.
