### ISSUE TITLE
Options control panel causes basic.system to crash

### ISSUE THREAD

**Issue by cskare** [a2stuff/a2d#784]
**Describe the bug**
Clicking on 'Run Basic Here' from Apple Menu after running 'Options' control panel desk accessory causes crash to monitor.

**To Reproduce**
1. Start DeskTop
2. From the Apple menu, select 'Control Panel'
3. Open 'Options' desk accessory
4. Close 'Options' desk accessory
5. From the Apple menu, select 'Run Basic Here'
6. Crashes to monitor

**Expected behavior**
Basic system should load and prompt should appear.

**System Details**
 - AppleWin 1.30.17,0 & //jse emulators
 - DeskTop version 1.4-alpha4

**Comment by inexorabletash** [comment]
Thanks for the report! I can repro back to 1.4-alpha3. Should be easy to bisect when I'm back at home.
