### ISSUE TITLE
Selector crash when loading with ProDos 2.4.3

### ISSUE THREAD

**Issue by samccormack** [a2stuff/a2d#789]
**Describe the bug**
With Prodos 2.4.3 trying to load a program or going to the full desktop crashes into the monitor. Oddly I only see this bug on my //c + my Apple //gs works fine with the same configuration. Launching selector shortcuts from the full desktop does not crash system.

**To Reproduce**
1. Launch the selector
2. Pick a program to run or D to launch the desktop
3. Program starts to load then crashes to the monitor

**Expected behavior**
program loads with no crashing

**System Details (please complete the following information):**
 - System Apple //c +
 - Emulator? real hardware
 - ProDOS version 2.4.3
 - DeskTop version 1.3
 - Other: mouse, a2heaven 1mb ram expansion

**Additional context**
I have a //c plus and a //gs and the problem only appears on the //c plus using the same disk with both.

**Comment by inexorabletash** [comment]
Have you tried a 1.4 build?

**Comment by samccormack** [comment]
I have not. I will try oneOn Jan 24, 2024, at 8:36 PM, Joshua Bell ***@***.***> wrote:﻿
Have you tried a 1.4 build?

**Comment by inexorabletash** [comment]
Other useful questions: 

* is Desktop copying itself to the RAMdisk on startup?
* You mention ProDOS 2.4.3; does it repro with 2.4.2?

**Comment by samccormack** [comment]
Yes things are copied to the ramdisk. Also this doesn’t happen with 2.4.2On Jan 24, 2024, at 8:52 PM, Joshua Bell ***@***.***> wrote:﻿
Other useful questions:

is Desktop copying itself to the RAMdisk on startup?
You mention ProDOS 2.4.3; does it repro with 2.4.2?

**Comment by inexorabletash** [comment]
I can repro in MAME (via Ample) using //c Plus and 1.4. I'll figure it out - thanks for the report!

**Comment by samccormack** [comment]
Yeah just reproduced the issue in 1.4On Jan 24, 2024, at 9:37 PM, Joshua Bell ***@***.***> wrote:﻿
I can repro in MAME (via Ample) using //c Plus and 1.4. I'll figure it out - thanks for the report!

**Comment by samccormack** [comment]
The run basic from here option crashes like the selector does under 2.4.3On Jan 24, 2024, at 9:37 PM, Joshua Bell ***@***.***> wrote:﻿
I can repro in MAME (via Ample) using //c Plus and 1.4. I'll figure it out - thanks for the report!

**Comment by inexorabletash** [comment]
At least for the shortcut case, the MLI `OPEN` call in `lib/invoker.s` circa line 99 is failing with $56 Bad Buffer Address. The buffer is at $800, and the system bitmap at $BF58 is $CF $00 $00 ... $00 $00 $01 which should indicate page 8 is free. This is... weird.

**Comment by inexorabletash** [comment]
Okay wow, this was quite the journey. The bug requires exactly this to happen:

* An Apple IIc+ which has unique mouse firmware and what I'd consider a bug
* MGTK being used with ROM banked in, which is only true in the Selector (Shortcuts) module, which has fragile code
* ProDOS 2.4.3 which apparently has critical code at just the right spot at $FBB3. 2.4.2 is apparently immune; some memory corruption must be happening but it doesn't cause a problem.

This was a bug in the original MGTK (although 6f08ef65 replicated the code).

**Comment by inexorabletash** [comment]
The fix will be in the next 1.4 alpha build (end of January).

**Comment by inexorabletash** [comment]
@samccormack https://github.com/a2stuff/a2d/releases/tag/v1.4-alpha5 has the fix if you want to try it out

**Comment by samccormack** [comment]
Awesome it looks like the selector is working now. I do have a new issue in that I get a crash when it attempts to copy itself to the RAM disk. See attached picture. If you would like I can submit a new issue for this. It copies desktop.system and makes the modules directory before crashing.On Feb 3, 2024, at 12:17 PM, Joshua Bell ***@***.***> wrote:﻿
@samccormack https://github.com/a2stuff/a2d/releases/tag/v1.4-alpha5 has the fix if you want to try it out

**Comment by inexorabletash** [comment]
@samccormack thanks for letting me know about the "copy itself to the RAM disk" issue. Big mistake on my part. I'm pushing out an alpha6 with the fix because it was new in alpha5 and really bad. https://github.com/a2stuff/a2d/releases/tag/v1.4-alpha6
