### ISSUE TITLE
Break out MGTK into a library

### ISSUE THREAD

**Issue by eschaton** [a2stuff/a2d#798]
It's been awesome to see all the work done on MGTK as part of understanding, documenting, and enhancing Apple II Desktop!

It'd be really cool to have it as a separate library for use by other applications—potentially even as some sort of "shared library" such that it could be shared between applications, whether just on disk or in memory, though that seems like a stretch goal.

One reason for this is that I've been wondering what a "MousePaint 2" that uses MGTK and supports DHR would take.

**Comment by inexorabletash** [comment]
It really is broken out as a library... just not as a separate Github project.

To avoid premature work, I'd encourage you (or anyone else) to make a copy of the file(s) for now. If you get to the state where this becomes a problem we can look at separating it (and other toolkits/libs) into a separate repo.

"MousePaint 2" sounds like an awesome project!

**Comment by inexorabletash** [comment]
Closing as non-actionable for now.
