### ISSUE TITLE
WozBrickOut does not function!

### ISSUE THREAD

**Issue by jewettg** [a2stuff/a2d#801]
**Describe the bug**
The included WozBrickOut program does not function.   

**To Reproduce**
1. Start DeskTop
2. Double-Click on WozBrickOut.
3. Screen blanks and then Apple // Desktop reappears.

**Expected behavior**
Be able to run the program.

**Screenshots**
(none)

**System Details (please complete the following information):**
 - System: Apple //c w/ 1mb expansion card and ROM 5x installed.
 - - [Rom 5x Info](https://github.com/mgcaret/rom4x)
 - - [Apple IIc RamExpress II+](https://www.a2heaven.com/webshop/index.php?rt=product/product&product_id=144)
 - Emulator? Real Hardware
 - ProDOS 2.4.3
 - DeskTop version: 1.3
 - Other: [Apple //c USB to //c mouse converter](https://www.applefritter.com/content/usb-apple-c-c-and-apple-bus-mouse-card-adapter)

**Additional context**
Just wanted to report this.  Have not done extensive testing.

**Comment by inexorabletash** [comment]
Are you able to launch INTBASIC.SYSTEM from the EXTRAS/ folder?

**Comment by inexorabletash** [comment]
I'm unable to repro on my IIc Plus with ROM 5X; using ProDOS 2.4.3 and DeskTop 1.4 beta. 

As mentioned in #800 it may be that something is missing from your repro steps that's critical. Are you running directly off one of the distribution images, or are you copying the files to another disk first? Is that a necessary part of the repro?

**Comment by jewettg** [comment]
OK, so I finally have my //c up and running again with v1.4.    You asked if I could launch the INTBASIC.SYSTEM, and the answer is yes -- and it gives me a integer basic prompt ">", which I then did a "CATALOG" and then did a "RUN WOZBRICKOUT" and it worked.  Terribly I add.. since I have no paddles.  

However, I thought the experience would be like I saw with AppleVision, which when I double-clicked it the icon, it automatically launched the appropriate "intbasic.system" and then the integer basic program, of course in a 40-cal mode, which is fine.  I know it did this in v1.3, but it does not work in v1.4, and now attempting to use "AppleVision" from v1.4, that no longer works.

When I double-click the "AppleVision" or "WozBrickout" programs, you see a slight flicker, but nothing.  I tried to highlight the icon and choose △-O or choose "Open" from the File menu, and same result, a slight "flicker" and nothing.  

I swear this worked in v1.3, so I do not want to close this.   Please let me know how I can help debug this!

**Comment by inexorabletash** [comment]
Thanks. Okay, I need to gather some data:

* Does launching an AppleSoft BASIC program (like the Hello World example) via File > Open work?
* When you start DESKTOP.SYSTEM, does it indicate it is copying to RAMCard or not?
* Can you confirm it is working on your system using A2D 1.3?

**Comment by inexorabletash** [comment]
My hypothesis is that you let DeskTop start to copy itself to RAMCard but canceled the operation before DESKTOP/EXTRAS/INTBASIC.SYSTEM was copied. Then on reboot DeskTop thinks it is on the RAMDisk and uses that copy, but it's incomplete. Can you check if there is a DESKTOP directory on your RAMdisk which is a partial copy of A2D that you didn't create? If so, delete it, and restart, holding down Apple to stop A2D copying itself to RAMCard

**Comment by inexorabletash** [comment]
If this checks out... I have a fix but since it's not a regression from v1.3 I won't fix it this late in v1.4. It'll be fixed in v1.5.

Since you have a battery-backed RAMDisk, you probably want to disable this functionality anyway. Apple > Control Panels > Options and uncheck "Copy to RAMCard (if present)"

**Comment by jewettg** [comment]
> Thanks. Okay, I need to gather some data:
> 
>     * Does launching an AppleSoft BASIC program (like the Hello World example) via File > Open work?
So, "HelloWorld" launches just fine, however the IntegerBasic programs "AppleVision" and "WozBrickout" will not launch.
Other programs that are NOT integerbasic or applesoft basic also work just fine.  All the A2D components launch just fine.  It seems this is isolated to just integerbasic programs.

>     * When you start DESKTOP.SYSTEM, does it indicate it is copying to RAMCard or not?
So, I have a 1MB RAM disk, provided by the RAMExpress II+ addition to the //c+.
Yes, it copies to the //c+ RAM disk, not the RAMExpress II+.
 
>     * Can you confirm it is working on your system using A2D 1.3?
Well, I swear it worked last time, maybe I am imagining things!  I remember double-clicking "AppleVision" and watching it launch and I smiled, as it was one of the first programs I also ran on my Apple //e when I got it working!  
HOWEVER -- NO, I reloaded v1.3 and tried-double-clicking AppleVision = no.  Running it manually (after launching integerbasic.system" -- works).

**Comment by jewettg** [comment]
> My hypothesis is that you let DeskTop start to copy itself to RAMCard but canceled the operation before DESKTOP/EXTRAS/INTBASIC.SYSTEM was copied. Then on reboot DeskTop thinks it is on the RAMDisk and uses that copy, but it's incomplete. Can you check if there is a DESKTOP directory on your RAMdisk which is a partial copy of A2D that you didn't create? If so, delete it, and restart, holding down Apple to stop A2D copying itself to RAMCard

I have always let it load into the RAM Disk, and usually -- everytime I turn on the computer.. it launch Apple II Desktop from the RAMDisk and it comes up very quickly.  

However, I have ordered an "SPIISD MINI for IIc" and plan on using that for the foreseable future.  I might let it start from the RAM disk, unless you tell me that is not recommended.

**Comment by jewettg** [comment]
> If this checks out... I have a fix but since it's not a regression from v1.3 I won't fix it this late in v1.4. It'll be fixed in v1.5.
> 
> Since you have a battery-backed RAMDisk, you probably want to disable this functionality anyway. Apple > Control Panels > Options and uncheck "Copy to RAMCard (if present)"

So, it is blank again, and so I am putting anymore testing on hold until I get my "SPIISD", and will resume testing.

BTW -- you are doing a great job with this!  Fantastic work.  I look forward to a stable v1.4, and what you bring to the table in v1.5.   It has been a blast!

**Comment by jewettg** [comment]
This is now going to get closed.   It must have been something to do with the dual RAM Disks and such.  I now have an SP2SD device that holds 32MB SmartPort images.  I have 1.4b2 installed there, and it works fantastic.  WOZBrickOut works, AppleVision works, BASIC programs launch, etc..   

If you want me to help you resolve this - if any interest, let me know, but I am now very happy.
